import { resolveAudioNarrationMode, type AudioSegment, type MediaScene, type RenderManifest } from '@/core/media';
import { stableId } from '@/core/editing';
import { AUDIO_PROFILES } from './config';
import type { AudioPlatformProfile, AudioQualityScore, AudioRecommendation, DuckingPlan, LoudnessPlan, MusicProductionPlan, SfxProductionPlan, SilenceRegion, SpeechPacingAnalysis, VoiceSegmentAnalysis } from './types';
import { clamp, round, tokenize } from './utils';

export function analyzeVoiceTiming(manifest: RenderManifest): VoiceSegmentAnalysis[] {
  return manifest.timeline.scenes.map((scene) => {
    const voice = intersections(manifest.audio.voice, scene); const starts = voice.map((item) => Math.max(scene.startMs, item.startMs)); const ends = voice.map((item) => Math.min(scene.endMs, item.endMs));
    const first = starts.length ? Math.min(...starts) - scene.startMs : null; const last = ends.length ? Math.max(...ends) - scene.startMs : null;
    const leading = first ?? scene.durationMs; const trailing = last === null ? scene.durationMs : Math.max(0, scene.durationMs - last); const covered = unionDuration(voice.map((item) => [Math.max(scene.startMs, item.startMs), Math.min(scene.endMs, item.endMs)]));
    const overlap = overlapDuration(voice); const issues = [...(leading > (scene.role === 'hook' ? 350 : 700) ? ['Voice starts late.'] : []), ...(trailing > 900 ? ['Voice leaves a long scene tail.'] : []), ...(overlap > 0 ? ['Voice segments overlap.'] : []), ...(voice.length === 0 ? ['Voice segment is missing.'] : [])];
    const recommendations = issues.map((description, index) => recommendation(scene.id, 'voice', index ? 'medium' : 'high', description, 5, 85));
    return { sceneId: scene.id, firstVoiceCueMs: first, lastVoiceCueMs: last, leadingSilenceMs: leading, trailingSilenceMs: trailing, voiceCoverage: round(covered / Math.max(1, scene.durationMs), 3), alignmentScore: Math.round(clamp(100 - leading / 20 - trailing / 30 - overlap / 10)), overlapRisk: Math.round(clamp(overlap / 10)), timingIssues: issues, recommendations };
  });
}

export function analyzeSilence(manifest: RenderManifest, voices = analyzeVoiceTiming(manifest)): SilenceRegion[] {
  const regions: SilenceRegion[] = [];
  for (const analysis of voices) { const scene = manifest.timeline.scenes.find((item) => item.id === analysis.sceneId); if (!scene) continue;
    if (analysis.leadingSilenceMs > 250) regions.push(region(scene.startMs, scene.startMs + analysis.leadingSilenceMs, scene, scene.role === 'hook' && analysis.leadingSilenceMs > 700 ? 'dead-air' : 'leading', scene.role === 'payoff' ? 70 : 20, hasMusic(manifest, scene.startMs, scene.startMs + analysis.leadingSilenceMs)));
    if (analysis.trailingSilenceMs > 500) regions.push(region(scene.endMs - analysis.trailingSilenceMs, scene.endMs, scene, 'trailing', scene.role === 'payoff' ? 65 : 25, hasMusic(manifest, scene.endMs - analysis.trailingSilenceMs, scene.endMs)));
    const sorted = intersections(manifest.audio.voice, scene).sort((a, b) => a.startMs - b.startMs); for (let index = 1; index < sorted.length; index += 1) { const start = sorted[index - 1].endMs; const end = sorted[index].startMs; if (end - start > 650) regions.push(region(start, end, scene, 'gap', /[.!?]$/u.test(String(sorted[index - 1].metadata.text ?? '')) ? 55 : 20, hasMusic(manifest, start, end))); }
  }
  return regions.sort((a, b) => a.startMs - b.startMs || (a.sceneId ?? '').localeCompare(b.sceneId ?? ''));
}

export function analyzeSpeechPacing(manifest: RenderManifest): SpeechPacingAnalysis {
  const scenePacing = manifest.timeline.scenes.map((scene) => { const words = tokenize(scene.text).length; const voiceMs = Math.max(1, unionDuration(intersections(manifest.audio.voice, scene).map((item) => [Math.max(scene.startMs, item.startMs), Math.min(scene.endMs, item.endMs)])) || scene.durationMs); const wpm = words * 60_000 / voiceMs; const cps = scene.text.length / (voiceMs / 1000); return { sceneId: scene.id, estimatedWpm: Math.round(wpm), charactersPerSecond: round(cps), paceScore: Math.round(clamp(100 - Math.abs(wpm - targetWpm(scene)) * 0.7)) }; });
  const wpm = scenePacing.length ? scenePacing.reduce((sum, item) => sum + item.estimatedWpm, 0) / scenePacing.length : 0; const score = scenePacing.length ? scenePacing.reduce((sum, item) => sum + item.paceScore, 0) / scenePacing.length : 0;
  const recommendations: AudioRecommendation[] = []; if (wpm > 210) recommendations.push(recommendation(null, 'pacing', 'high', 'Reduce speech density or extend voice timing.', 7, 86)); if (wpm < 90) recommendations.push(recommendation(null, 'pacing', 'medium', 'Tighten slow delivery while keeping natural pauses.', 5, 78));
  return { estimatedWpm: Math.round(wpm), paceScore: Math.round(score), readabilityScore: Math.round(clamp(110 - Math.max(0, wpm - 180) * 0.7)), overloadRisk: Math.round(clamp((wpm - 170) * 1.5)), slowSpeechRisk: Math.round(clamp((110 - wpm) * 1.5)), scenePacing, recommendedRateAdjustment: round(clamp(150 / Math.max(1, wpm), 0.8, 1.2), 2), recommendations };
}

export function analyzeVoiceQuality(manifest: RenderManifest): AudioQualityScore {
  const missing = manifest.audio.voice.filter((item) => !item.assetId && item.metadata.source !== 'tts-placeholder').length; const gains = manifest.audio.voice.map((item) => item.gain); const clipping = gains.filter((gain) => gain > 1.2).length; const low = gains.filter((gain) => gain < 0.35).length; const spread = gains.length ? Math.max(...gains) - Math.min(...gains) : 1;
  const evidence = [`${manifest.audio.voice.length} voice segments inspected.`, `${missing} segments have no usable source metadata.`, `Gain spread is ${round(spread)}.`]; const recommendations: AudioRecommendation[] = [];
  if (clipping) recommendations.push(recommendation(null, 'loudness', 'high', 'Reduce hot voice gain before limiting.', 8, 88)); if (low) recommendations.push(recommendation(null, 'voice', 'medium', 'Normalize low voice segments.', 6, 82));
  const technical = clamp(100 - missing * 30); const consistency = clamp(100 - spread * 80); return { technicalScore: Math.round(technical), intelligibilityRisk: Math.round(clamp(low * 25 + spread * 20)), clippingRisk: Math.round(clamp(clipping * 35)), lowLevelRisk: Math.round(clamp(low * 30)), consistencyScore: Math.round(consistency), overallVoiceScore: Math.round((technical + consistency + clamp(100 - clipping * 35) + clamp(100 - low * 30)) / 4), evidence, recommendations };
}

export function planMusic(manifest: RenderManifest): MusicProductionPlan { const intensity = manifest.timeline.scenes.reduce((sum, item) => sum + item.intensity, 0) / Math.max(1, manifest.timeline.scenes.length); const energy = Math.round(clamp(intensity * 100)); const mood = energy > 70 ? 'energetic' : energy < 35 ? 'calm' : 'uplifting'; const silent = resolveAudioNarrationMode(manifest.audio) === 'silent'; return { intent: silent ? 'support the video pacing and visual rhythm' : 'support narration without masking voice', mood, energy, tempoRange: energy > 70 ? [110, 140] : energy < 35 ? [65, 90] : [85, 115], entryMs: 0, exitMs: manifest.durationMs, loopRequired: manifest.audio.music.some((item) => Boolean(item.metadata.loop)), fadeInMs: manifest.audio.settings.musicFadeInMs, fadeOutMs: manifest.audio.settings.musicFadeOutMs, searchQuery: `${mood} instrumental short video background`, preferredGenres: energy > 70 ? ['electronic', 'modern percussion'] : ['ambient', 'light cinematic'], instrumentation: silent ? ['instrumental', 'rhythmic'] : ['instrumental', 'voice-friendly'], vocals: 'instrumental', avoidTerms: ['dominant vocals', 'harsh lead'], maskingRisk: silent ? 0 : Math.round(clamp((manifest.audio.settings.musicGain - 0.3) * 200)) }; }

export function planSfx(manifest: RenderManifest): SfxProductionPlan[] { const plans: SfxProductionPlan[] = []; const silent = resolveAudioNarrationMode(manifest.audio) === 'silent'; let last = -2000; for (const scene of manifest.timeline.scenes) { if (!['hook', 'payoff'].includes(scene.role) && scene.intensity < 0.78) continue; const startMs = scene.startMs + Math.min(300, scene.durationMs * 0.15); if (startMs - last < 800) continue; const intent = scene.role === 'payoff' ? 'success' : 'impact'; plans.push({ sceneId: scene.id, startMs, durationMs: 180, intent, searchQuery: `${intent} short clean sound effect`, gainDb: scene.role === 'hook' ? -9 : -12, fadeMs: 35, priority: scene.role === 'hook' ? 'high' : 'medium', reason: `${scene.role} emphasis`, avoidOverlapWithVoice: !silent, confidence: 82 }); last = startMs; } return plans; }

export function planDucking(manifest: RenderManifest): DuckingPlan[] { const attack = Math.min(250, Math.max(40, manifest.audio.settings.duckingAttackMs)); const release = Math.min(600, Math.max(100, manifest.audio.settings.duckingReleaseMs)); return mergeVoiceRanges(manifest.audio.voice).map(([startMs, endMs]) => ({ triggerTrack: 'voice', targetTrack: 'music', startMs: Math.max(0, startMs - attack), endMs: Math.min(manifest.durationMs, endMs + release), reductionDb: round(20 * Math.log10(Math.max(0.05, manifest.audio.settings.duckingGain)), 1), attackMs: attack, releaseMs: release, threshold: -28, reason: 'Keep narration intelligible over music.', confidence: 92 })); }
export function planLoudness(manifest: RenderManifest, platform: AudioPlatformProfile): LoudnessPlan { const base = AUDIO_PROFILES[platform]; const narrationRequired = resolveAudioNarrationMode(manifest.audio) === 'required'; const risks = [...(narrationRequired && manifest.audio.voice.some((item) => item.gain > 1.2) ? ['voice-clipping-risk'] : []), ...(narrationRequired && manifest.audio.settings.musicGain > 0.45 ? ['voice-masking-risk'] : []), ...(manifest.audio.sfx.some((item) => item.gain > 1.1) ? ['sfx-spike-risk'] : [])]; return { ...base, risks }; }

function recommendation(sceneId: string | null, category: AudioRecommendation['category'], priority: AudioRecommendation['priority'], description: string, expectedImpact: number, confidence: number): AudioRecommendation { return { id: stableId('audio-rec', `${sceneId}|${category}|${description}`), sceneId, category, priority, title: description, description, expectedImpact, confidence }; }
function intersections(segments: readonly AudioSegment[], scene: MediaScene): AudioSegment[] { return segments.filter((item) => item.endMs > scene.startMs && item.startMs < scene.endMs && (!item.sceneId || item.sceneId === scene.id)); }
function region(startMs: number, endMs: number, scene: MediaScene, type: SilenceRegion['type'], intentionalProbability: number, music: boolean): SilenceRegion { const durationMs = Math.max(0, endMs - startMs); return { startMs, endMs, durationMs, sceneId: scene.id, type, severity: durationMs > 1500 && type === 'dead-air' ? 'critical' : durationMs > 1000 ? 'high' : durationMs > 600 ? 'medium' : 'low', intentionalProbability, evidence: [`${durationMs} ms ${type} silence.`, music ? 'Background music fills the region.' : 'No voice or music activity detected.'], recommendedAction: intentionalProbability > 60 ? 'Review and preserve if dramatic.' : 'Trim while retaining a natural breath.' }; }
function hasMusic(manifest: RenderManifest, startMs: number, endMs: number): boolean { return manifest.audio.music.some((item) => item.endMs > startMs && item.startMs < endMs); }
function targetWpm(scene: MediaScene): number { return scene.role === 'hook' ? 175 : scene.role === 'cta' ? 145 : 155; }
function unionDuration(ranges: readonly (readonly [number, number])[]): number { const sorted = ranges.filter(([a, b]) => b > a).sort((a, b) => a[0] - b[0]); let total = 0; let start = -1; let end = -1; for (const range of sorted) { if (range[0] > end) { total += Math.max(0, end - start); [start, end] = range; } else end = Math.max(end, range[1]); } return total + Math.max(0, end - start); }
function overlapDuration(items: readonly AudioSegment[]): number { const sorted = [...items].sort((a, b) => a.startMs - b.startMs); return sorted.slice(1).reduce((sum, item, index) => sum + Math.max(0, sorted[index].endMs - item.startMs), 0); }
function mergeVoiceRanges(items: readonly AudioSegment[]): Array<[number, number]> { const sorted = items.map((item) => [item.startMs, item.endMs] as [number, number]).sort((a, b) => a[0] - b[0]); const result: Array<[number, number]> = []; for (const range of sorted) { const last = result.at(-1); if (last && range[0] <= last[1] + 250) last[1] = Math.max(last[1], range[1]); else result.push([...range]); } return result; }
