import { createManifestRevisionId, MANIFEST_FINGERPRINT_VERSION, stableId } from '@/core/editing';
import type { AudioConflict, AudioOperation, AudioProductionInput, AudioProductionOptions, AudioProductionPlan, AudioRecommendation } from './types';
import { AUDIO_PLAN_VERSION } from './config';
import { analyzeSilence, analyzeSpeechPacing, analyzeVoiceQuality, analyzeVoiceTiming, planDucking, planLoudness, planMusic, planSfx } from './analyzers';
import { assertActive, clamp } from './utils';

export function compileAudioProductionPlan(input: AudioProductionInput, options: AudioProductionOptions = {}, signal?: AbortSignal): AudioProductionPlan {
  assertActive(signal); if (input.projectId !== input.manifest.projectId || input.projectId !== input.directorReport.projectId) throw new Error('Audio project, manifest and Director report identities must match.');
  const fingerprint = createManifestRevisionId(input.manifest); if (input.directorReport.analyzedManifestFingerprint !== fingerprint || input.directorReport.manifestFingerprintVersion !== MANIFEST_FINGERPRINT_VERSION) throw new Error('Manifest changed; run AI Director analysis again before audio production.');
  const voice = analyzeVoiceTiming(input.manifest); const silence = analyzeSilence(input.manifest, voice); const pacing = analyzeSpeechPacing(input.manifest); const quality = analyzeVoiceQuality(input.manifest); const music = planMusic(input.manifest); const sfx = planSfx(input.manifest); const ducking = planDucking(input.manifest); const loudness = planLoudness(input.manifest, options.platformProfile ?? 'generic-short-video');
  const recommendations = dedupeRecommendations([...voice.flatMap((item) => item.recommendations), ...pacing.recommendations, ...quality.recommendations]); const operations = buildOperations(input, recommendations, silence, sfx, ducking, loudness); const conflicts = detectAudioConflicts(operations, input.manifest.durationMs); const linked = operations.map((operation) => ({ ...operation, conflicts: conflicts.filter((item) => item.operationIds.includes(operation.id)).map((item) => item.id) }));
  const affectedScenes = [...new Set(linked.flatMap((item) => item.sceneId ? [item.sceneId] : []))].sort(); const automatic = linked.filter((item) => item.automaticallyApplicable).map((item) => item.id); return { id: stableId('audio-plan', `${input.projectId}|${fingerprint}`), projectId: input.projectId, planVersion: AUDIO_PLAN_VERSION, sourceManifestFingerprint: fingerprint, sourceManifestFingerprintVersion: MANIFEST_FINGERPRINT_VERSION, sourceDirectorReportFingerprint: input.directorReport.analyzedManifestFingerprint, createdAt: input.directorReport.generatedAt, voiceAnalysis: voice, silenceRegions: silence, pacing, quality, music, sfx, ducking, loudness, operations: linked, conflicts, recommendations, expectedQualityImpact: Math.round(clamp(linked.reduce((sum, item) => sum + item.expectedImpact, 0), 0, 30)), expectedDurationDeltaMs: -silence.filter((item) => item.intentionalProbability < 50).reduce((sum, item) => sum + Math.min(item.durationMs - 180, 700), 0), affectedScenes, automaticOperations: automatic, manualOperations: linked.filter((item) => !item.automaticallyApplicable).map((item) => item.id), diagnostics: { warnings: conflicts.filter((item) => item.severity === 'critical').map((item) => item.reason), analyzerNotes: ['Metadata-based deterministic analysis; no waveform ML or TTS call was used.'] } };
}

export function deriveEffectiveAudioPlan(plan: AudioProductionPlan): AudioProductionPlan { const enabled = plan.operations.filter((item) => item.status !== 'disabled'); const conflicts = detectAudioConflicts(enabled, plan.music.exitMs); const operations = plan.operations.map((item) => ({ ...item, conflicts: conflicts.filter((conflict) => conflict.operationIds.includes(item.id)).map((conflict) => conflict.id) })); const affectedScenes = [...new Set(enabled.flatMap((item) => item.sceneId ? [item.sceneId] : []))].sort(); return { ...plan, operations, conflicts, affectedScenes, expectedQualityImpact: Math.round(clamp(enabled.reduce((sum, item) => sum + item.expectedImpact, 0), 0, 30)), automaticOperations: enabled.filter((item) => item.automaticallyApplicable).map((item) => item.id), manualOperations: enabled.filter((item) => !item.automaticallyApplicable).map((item) => item.id), diagnostics: { ...plan.diagnostics, warnings: conflicts.filter((item) => item.severity === 'critical').map((item) => item.reason) } }; }
export function resolveAudioConflict(plan: AudioProductionPlan, conflictId: string, selectedId: string): AudioProductionPlan { const conflict = deriveEffectiveAudioPlan(plan).conflicts.find((item) => item.id === conflictId); if (!conflict?.operationIds.includes(selectedId)) throw new Error('Select an operation from the active audio conflict.'); return deriveEffectiveAudioPlan({ ...plan, operations: plan.operations.map((item) => conflict.operationIds.includes(item.id) && item.id !== selectedId ? { ...item, status: 'disabled' as const } : item) }); }
export function detectAudioConflicts(operations: readonly AudioOperation[], durationMs: number): AudioConflict[] { const result: AudioConflict[] = []; const pairs: Array<[AudioOperation['type'], AudioOperation['type'], AudioConflict['type']]> = [['trim-silence', 'extend-silence', 'silence-removal-conflict'], ['add-fade-in', 'change-music-entry', 'fade-conflict'], ['normalize-music-gain', 'reduce-masking', 'gain-conflict']]; for (const [left, right, type] of pairs) for (const a of operations.filter((item) => item.type === left)) for (const b of operations.filter((item) => item.type === right && item.sceneId === a.sceneId)) result.push(conflict(type, [a.id, b.id], a.sceneId, 'critical', `${left} conflicts with ${right}.`)); const trims = operations.filter((item) => item.type === 'trim-silence'); for (let index = 0; index < trims.length; index += 1) for (const other of trims.slice(index + 1)) { const item = trims[index]; if (item.sceneId === other.sceneId && number(item.parameters.startMs) < number(other.parameters.endMs) && number(other.parameters.startMs) < number(item.parameters.endMs)) result.push(conflict('silence-removal-conflict', [item.id, other.id], item.sceneId, 'critical', 'Overlapping silence trims must be resolved before apply.')); } for (const item of operations) { const start = number(item.parameters.startMs); const end = number(item.parameters.endMs); if (start < 0 || start > durationMs || (item.type === 'trim-silence' && (end <= start || end > durationMs))) result.push(conflict('segment-out-of-bounds', [item.id], item.sceneId, 'critical', 'Audio operation is outside the timeline.')); } return result.sort((a, b) => a.id.localeCompare(b.id)); }

function buildOperations(input: AudioProductionInput, recommendations: readonly AudioRecommendation[], silence: AudioProductionPlan['silenceRegions'], sfx: AudioProductionPlan['sfx'], ducking: AudioProductionPlan['ducking'], loudness: AudioProductionPlan['loudness']): AudioOperation[] { const items: AudioOperation[] = [];
  silence.filter((item) => item.durationMs > 500 && item.intentionalProbability < 50).forEach((item) => items.push(operation(input, item.sceneId, 'trim-silence', `Trim ${item.type} silence.`, { startMs: item.startMs, endMs: item.endMs, preserveMs: 180 }, 4, 84, true)));
  if (ducking.length) items.push(operation(input, null, input.manifest.audio.automation.length ? 'adjust-ducking' : 'add-ducking', 'Regenerate voice-aware music ducking.', {}, 7, 93, true));
  if (loudness.risks.includes('voice-clipping-risk')) items.push(operation(input, null, 'reduce-clipping-risk', 'Reduce clipping risk in voice segments.', { maxGain: 1.1 }, 8, 90, true));
  if (loudness.risks.includes('voice-masking-risk')) items.push(operation(input, null, 'reduce-masking', 'Lower music under narration.', { gain: 0.22 }, 8, 91, true));
  sfx.forEach((item) => items.push(operation(input, item.sceneId, 'insert-sfx', item.reason, { startMs: item.startMs, durationMs: item.durationMs, intent: item.intent, gainDb: item.gainDb }, 5, item.confidence, false)));
  recommendations.filter((item) => item.category === 'voice').forEach((item) => { if (item.description.includes('late')) items.push(operation(input, item.sceneId, 'shift-voice', item.description, { targetOffsetMs: 120 }, item.expectedImpact, item.confidence, true, item.id)); });
  return [...new Map(items.map((item) => [`${item.sceneId}|${item.type}|${item.type === 'trim-silence' ? `${item.parameters.startMs}|${item.parameters.endMs}` : ''}`, item])).values()].sort((a, b) => priority(b.priority) - priority(a.priority) || (a.sceneId ?? '').localeCompare(b.sceneId ?? '') || number(a.parameters.startMs) - number(b.parameters.startMs) || a.type.localeCompare(b.type)); }
function operation(input: AudioProductionInput, sceneId: string | null, type: AudioOperation['type'], reason: string, parameters: AudioOperation['parameters'], expectedImpact: number, confidence: number, automaticallyApplicable: boolean, sourceRecommendationId: string | null = null): AudioOperation { const region = type === 'trim-silence' ? `|${parameters.startMs}|${parameters.endMs}` : ''; return { id: stableId('audio-op', `${input.projectId}|${sceneId}|${type}${region}`), projectId: input.projectId, sceneId, sourceRecommendationId, type, priority: expectedImpact >= 8 ? 'high' : 'medium', reason, evidence: [reason], parameters, expectedImpact, confidence, automaticallyApplicable, dependencies: [], conflicts: [], status: 'proposed', createdAt: input.directorReport.generatedAt }; }
function dedupeRecommendations(items: readonly AudioRecommendation[]): AudioRecommendation[] { return [...new Map(items.map((item) => [`${item.sceneId}|${item.category}|${item.description}`, item])).values()].sort((a, b) => b.expectedImpact - a.expectedImpact || a.id.localeCompare(b.id)); }
function conflict(type: AudioConflict['type'], operationIds: string[], sceneId: string | null, severity: AudioConflict['severity'], reason: string): AudioConflict { return { id: stableId('audio-conflict', `${type}|${operationIds.sort().join('|')}`), type, operationIds: operationIds.sort(), sceneId, severity, reason, resolved: false }; }
function priority(value: AudioOperation['priority']): number { return { critical: 4, high: 3, medium: 2, low: 1 }[value]; }
function number(value: unknown): number { return typeof value === 'number' && Number.isFinite(value) ? value : 0; }
