import { calculateAudioMetrics, type AudioAutomationPoint, type AudioSegment, type MediaClip, type RenderManifest } from '@/core/media';
import { createManifestRevisionId, createTimelineSnapshot, deepClone, retimeManifest, stableId, type TimelineSnapshot } from '@/core/editing';
import { deriveEffectiveAudioPlan } from './compiler';
import type { AudioInvalidationScope, AudioOperation, AudioOperationType, AudioProductionPlan, AudioProductionPreview } from './types';
import { assertActive, clamp } from './utils';

export function transformAudio(snapshot: TimelineSnapshot, plan: AudioProductionPlan, enabledIds?: readonly string[], signal?: AbortSignal) { assertActive(signal); if (snapshot.projectId !== plan.projectId || snapshot.manifestFingerprint !== plan.sourceManifestFingerprint || createManifestRevisionId(snapshot.manifest) !== plan.sourceManifestFingerprint) throw new Error('Stale audio plan; create a new preview from the current manifest.'); const manifest = deepClone(snapshot.manifest); const applied: string[] = []; const skipped: string[] = []; let removedSilenceMs = 0; const affectedScenes = new Set<string>(); const allowed = new Set(enabledIds ?? plan.operations.filter((item) => item.status !== 'disabled').map((item) => item.id));
  const operations = [...plan.operations].sort(operationOrder);
  const conflicted = new Set(plan.conflicts.filter((item) => item.severity === 'critical' && !item.resolved).flatMap((item) => item.operationIds));
  for (const operation of operations) { assertActive(signal); if (!allowed.has(operation.id) || operation.status === 'disabled' || conflicted.has(operation.id) || operation.dependencies.some((id) => !applied.includes(id))) { skipped.push(operation.id); continue; } const result = applyAudioOperation(manifest, operation, plan); if (result.applied) { applied.push(operation.id); removedSilenceMs += result.removedSilenceMs; invalidatedSceneIds(manifest, operation).forEach((id) => affectedScenes.add(id)); } else skipped.push(operation.id); }
  normalizeManifestAudio(manifest); validateAudioManifest(manifest); manifest.validation = null; const fingerprint = createManifestRevisionId(manifest); const revisionId = stableId('audio-revision', `${snapshot.revisionId}|${applied.join('|')}|${fingerprint}`); return { snapshot: createTimelineSnapshot(manifest, revisionId, snapshot.revisionId, plan.createdAt), applied, skipped, removedSilenceMs, affectedScenes: [...affectedScenes].sort() };
}
export function createAudioPreview(plan: AudioProductionPlan, snapshot: TimelineSnapshot, approvedManualIds: readonly string[] = [], signal?: AbortSignal): AudioProductionPreview {
  const effective = deriveEffectiveAudioPlan(plan);
  const requested = [...new Set(approvedManualIds)].sort();
  const manual = effective.operations.filter((item) => !item.automaticallyApplicable);
  const critical = new Set(effective.conflicts.filter((item) => item.severity === 'critical' && !item.resolved).flatMap((item) => item.operationIds));
  const eligible = new Set(manual.filter((item) => item.status !== 'disabled' && !critical.has(item.id)).map((item) => item.id));
  const approvedManualOperationIds = requested.filter((id) => eligible.has(id));
  const ignored = requested.filter((id) => !eligible.has(id));
  const selected = [...effective.automaticOperations, ...approvedManualOperationIds];
  const transformed = transformAudio(snapshot, effective, selected, signal);
  const conflicts = effective.conflicts;
  const applied = new Set(transformed.applied);
  const quality = effective.operations.filter((item) => applied.has(item.id)).reduce((sum, item) => sum + item.expectedImpact, 0);
  const reusableSceneIds = snapshot.manifest.timeline.scenes.map((item) => item.id).filter((id) => !transformed.affectedScenes.includes(id));
  return { id: stableId('audio-preview', `${effective.id}|${transformed.snapshot.revisionId}|${effective.operations.map((item) => `${item.id}:${item.status}`).join('|')}|manual:${requested.join('|')}`), projectId: effective.projectId, planId: effective.id, sourceRevisionId: snapshot.revisionId, createdAt: effective.createdAt, approvedManualOperationIds, unapprovedManualOperationIds: manual.filter((item) => item.status !== 'disabled' && !approvedManualOperationIds.includes(item.id)).map((item) => item.id).sort(), beforeVoice: deepClone(snapshot.manifest.audio.voice), afterVoice: deepClone(transformed.snapshot.manifest.audio.voice), removedSilenceMs: transformed.removedSilenceMs, automation: transformed.snapshot.manifest.audio.automation, sfx: transformed.snapshot.manifest.audio.sfx, loudness: effective.loudness, durationDeltaMs: transformed.snapshot.manifest.durationMs - snapshot.manifest.durationMs, affectedScenes: transformed.affectedScenes, operationCount: transformed.applied.length, conflicts, estimatedQualityImprovement: Math.round(clamp(quality, 0, 30)), rerenderSceneIds: transformed.affectedScenes, reusableSceneIds, cacheReuseEstimate: reusableSceneIds.length, validationImpact: 'requires-validation', warnings: [...effective.diagnostics.warnings, ...ignored.map((id) => `Ignored invalid manual operation approval: ${id}.`), ...(conflicts.some((item) => item.severity === 'critical') ? ['Critical audio conflicts must be resolved before apply.'] : [])], proposedSnapshot: transformed.snapshot };
}

type OperationResult = { applied: boolean; removedSilenceMs: number };
const unchanged = { applied: false, removedSilenceMs: 0 } as const;
function applyAudioOperation(manifest: RenderManifest, operation: AudioOperation, plan: AudioProductionPlan): OperationResult { if (operation.type === 'keep') return { applied: true, removedSilenceMs: 0 };
  if (operation.type === 'trim-silence' && operation.sceneId) return trimSilence(manifest, operation);
  if (operation.type === 'shift-voice' && operation.sceneId) { const scene = manifest.timeline.scenes.find((item) => item.id === operation.sceneId); if (!scene) return unchanged; const voice = manifest.audio.voice.filter((item) => item.sceneId === operation.sceneId); if (!voice.length) return unchanged; const target = Number(operation.parameters.targetOffsetMs ?? 120); const shift = Math.min(...voice.map((item) => item.startMs)) - (scene.startMs + target); manifest.audio.voice = manifest.audio.voice.map((item) => item.sceneId === operation.sceneId ? shiftSegment(item, -shift) : item); return { applied: true, removedSilenceMs: 0 }; }
  if (operation.type === 'add-ducking' || operation.type === 'adjust-ducking') { mergeDuckingAutomation(manifest, operation, plan); return { applied: true, removedSilenceMs: 0 }; }
  if (operation.type === 'reduce-clipping-risk' || operation.type === 'normalize-voice-gain') { const max = Number(operation.parameters.maxGain ?? 1.1); manifest.audio.voice = manifest.audio.voice.map((item) => ({ ...item, gain: Math.min(item.gain, max) })); manifest.audio.settings.voiceGain = Math.min(manifest.audio.settings.voiceGain, max); return { applied: true, removedSilenceMs: 0 }; }
  if (operation.type === 'reduce-masking' || operation.type === 'normalize-music-gain') { const gain = Number(operation.parameters.gain ?? 0.22); manifest.audio.music = manifest.audio.music.map((item) => ({ ...item, gain })); manifest.audio.settings.musicGain = gain; return { applied: true, removedSilenceMs: 0 }; }
  if (operation.type === 'insert-sfx' && operation.sceneId) { const scene = manifest.timeline.scenes.find((item) => item.id === operation.sceneId); if (!scene) return unchanged; const startMs = clamp(Number(operation.parameters.startMs), scene.startMs, scene.endMs); const durationMs = Math.min(Number(operation.parameters.durationMs ?? 180), scene.endMs - startMs); if (durationMs <= 0) return unchanged; const id = stableId('audio-sfx', operation.id); if (manifest.audio.sfx.some((item) => item.id === id)) return unchanged; manifest.audio.sfx.push({ id, type: 'sfx', sceneId: scene.id, startMs, endMs: startMs + durationMs, durationMs, gain: dbToGain(Number(operation.parameters.gainDb ?? -12)), fadeInMs: 15, fadeOutMs: Math.min(60, durationMs / 2), metadata: { role: 'audio-production', intent: operation.parameters.intent, source: 'sfx-placeholder' } }); return { applied: true, removedSilenceMs: 0 }; }
  if (operation.type === 'remove-sfx') { const before = manifest.audio.sfx.length; manifest.audio.sfx = manifest.audio.sfx.filter((item) => item.id !== operation.parameters.segmentId); return { applied: manifest.audio.sfx.length !== before, removedSilenceMs: 0 }; }
  return unchanged; }

function trimSilence(manifest: RenderManifest, operation: AudioOperation): OperationResult {
  const scene = manifest.timeline.scenes.find((item) => item.id === operation.sceneId); if (!scene) return unchanged;
  let startMs = Number(operation.parameters.startMs); let endMs = Number(operation.parameters.endMs); const preserveMs = Math.max(0, Number(operation.parameters.preserveMs ?? 180));
  if (!Number.isFinite(startMs) || !Number.isFinite(endMs)) return unchanged;
  if (operation.parameters.coordinateSpace === 'scene-relative' || (scene.startMs > 0 && startMs < scene.startMs && endMs <= scene.durationMs)) { startMs += scene.startMs; endMs += scene.startMs; }
  startMs = clamp(startMs, scene.startMs, scene.endMs); endMs = clamp(endMs, scene.startMs, scene.endMs); const regionMs = endMs - startMs; const delta = Math.max(0, regionMs - preserveMs); if (!delta) return unchanged;
  const leading = startMs === scene.startMs; const trailing = endMs === scene.endMs;
  if (leading) { const first = Math.min(...manifest.audio.voice.filter((item) => item.sceneId === scene.id && item.startMs >= endMs).map((item) => item.startMs)); const shift = Math.min(delta, first - scene.startMs); if (!Number.isFinite(shift) || shift <= 0) return unchanged; shiftLinkedAfter(manifest, scene.id, endMs, -shift); return { applied: true, removedSilenceMs: shift }; }
  if (trailing) { const minimum = Math.max(1, scene.transition.durationMs, scene.overlapBeforeMs, scene.overlapAfterMs); const removable = Math.min(delta, Math.max(0, scene.durationMs - minimum)); if (!removable) return unchanged; const candidate = deepClone(manifest); const candidateScene = candidate.timeline.scenes.find((item) => item.id === scene.id); if (!candidateScene) return unchanged; candidateScene.durationMs -= removable; candidateScene.endMs = candidateScene.startMs + candidateScene.durationMs; try { retimeManifest(candidate); validateAudioManifest(candidate); } catch { return unchanged; } Object.assign(manifest, candidate); return { applied: true, removedSilenceMs: removable }; }
  shiftLinkedAfter(manifest, scene.id, endMs, -delta); return { applied: true, removedSilenceMs: delta };
}
function shiftLinkedAfter(manifest: RenderManifest, sceneId: string, boundary: number, delta: number): void {
  manifest.audio.voice = manifest.audio.voice.map((item) => item.sceneId === sceneId && item.startMs >= boundary ? shiftSegment(item, delta) : item);
  manifest.audio.sfx = manifest.audio.sfx.map((item) => item.sceneId === sceneId && item.startMs >= boundary && item.metadata.voiceLinked === true ? shiftSegment(item, delta) : item);
  manifest.subtitles.words = manifest.subtitles.words.map((item) => item.sceneId === sceneId && item.startMs >= boundary ? shiftTimed(item, delta) : item);
  manifest.subtitles.cues = manifest.subtitles.cues.map((item) => item.sceneId === sceneId && item.startMs >= boundary ? shiftTimed(item, delta) : item);
  manifest.timeline.tracks = manifest.timeline.tracks.map((track) => track.type === 'subtitle' || track.type === 'voice' ? { ...track, clips: track.clips.map((clip) => clip.sceneId === sceneId && clip.startMs >= boundary ? shiftTimed(clip, delta) : clip) } : track);
}
function shiftSegment<T extends AudioSegment>(item: T, delta: number): T { return { ...item, startMs: item.startMs + delta, endMs: item.endMs + delta } as T; }
function shiftTimed<T extends { startMs: number; endMs: number; durationMs: number }>(item: T, delta: number): T { return { ...item, startMs: item.startMs + delta, endMs: item.endMs + delta } as T; }
function operationOrder(a: AudioOperation, b: AudioOperation): number { const aStart = Number(a.parameters.startMs); const bStart = Number(b.parameters.startMs); return (Number.isFinite(aStart) ? aStart : Number.MAX_SAFE_INTEGER) - (Number.isFinite(bStart) ? bStart : Number.MAX_SAFE_INTEGER) || a.id.localeCompare(b.id); }

type InvalidationPolicy = { scope: AudioInvalidationScope; track?: 'voice' | 'music' | 'sfx' };
const INVALIDATION_POLICY: Readonly<Partial<Record<AudioOperationType, InvalidationPolicy>>> = {
  'trim-silence': { scope: 'scene-range' }, 'shift-voice': { scope: 'scene' }, 'insert-sfx': { scope: 'scene' }, 'remove-sfx': { scope: 'scene' }, 'move-sfx': { scope: 'scene-range' }, 'add-emphasis': { scope: 'scene' },
  'normalize-voice-gain': { scope: 'track', track: 'voice' }, 'reduce-clipping-risk': { scope: 'track', track: 'voice' }, 'normalize-music-gain': { scope: 'track', track: 'music' }, 'reduce-masking': { scope: 'track', track: 'music' }, 'normalize-sfx-gain': { scope: 'track', track: 'sfx' },
  'add-ducking': { scope: 'global-timeline' }, 'adjust-ducking': { scope: 'global-timeline' }, 'add-fade-in': { scope: 'global-timeline' }, 'add-fade-out': { scope: 'global-timeline' }, 'shorten-music': { scope: 'global-timeline' }, 'extend-music': { scope: 'global-timeline' }, 'loop-music': { scope: 'global-timeline' }, 'change-music-entry': { scope: 'global-timeline' }, 'change-music-exit': { scope: 'global-timeline' }, 'align-beat-plan': { scope: 'global-timeline' },
};
export function audioInvalidationScope(operation: AudioOperation): AudioInvalidationScope { return INVALIDATION_POLICY[operation.type]?.scope ?? (operation.sceneId ? 'scene' : 'final-mix-only'); }
function invalidatedSceneIds(manifest: RenderManifest, operation: AudioOperation): string[] { const policy = INVALIDATION_POLICY[operation.type] ?? { scope: operation.sceneId ? 'scene' as const : 'final-mix-only' as const }; if (policy.scope === 'global-timeline' || policy.scope === 'final-mix-only') return manifest.timeline.scenes.map((item) => item.id); if (policy.scope === 'track' && policy.track) { const segments = policy.track === 'sfx' ? manifest.audio.sfx : manifest.audio[policy.track]; return manifest.timeline.scenes.filter((scene) => segments.some((item) => item.endMs > scene.startMs && item.startMs < scene.endMs)).map((item) => item.id); } if (!operation.sceneId) return []; const index = manifest.timeline.scenes.findIndex((item) => item.id === operation.sceneId); if (index < 0) return []; const scene = manifest.timeline.scenes[index]; if (policy.scope !== 'scene-range') return [scene.id]; if (operation.type === 'trim-silence') return manifest.timeline.scenes.filter((item) => item.index >= scene.index || (item.index === scene.index - 1 && scene.overlapBeforeMs > 0)).map((item) => item.id); return manifest.timeline.scenes.filter((item) => item.id === scene.id || ((scene.overlapBeforeMs > 0 || item.overlapAfterMs > 0) && item.index === scene.index - 1) || ((scene.overlapAfterMs > 0 || item.overlapBeforeMs > 0) && item.index === scene.index + 1)).map((item) => item.id); }

function mergeDuckingAutomation(manifest: RenderManifest, operation: AudioOperation, plan: AudioProductionPlan): void { const retained = manifest.audio.automation.filter((item) => !isGeneratedDuckingOwnedBy(item, operation.id)); const generated = plan.ducking.flatMap((item, index) => duckingPoints(item.startMs, item.endMs, manifest.audio.settings.musicGain, item.reductionDb, index, operation, plan)); manifest.audio.automation = [...retained, ...generated].sort(automationOrder); }
function isGeneratedDuckingOwnedBy(point: AudioAutomationPoint, operationId: string): boolean { if (point.metadata.sourceOperationId !== operationId || point.metadata.source === 'manual') return false; return point.metadata.source === 'audio-production' || (point.type === 'ducking' && point.metadata.kind === 'ducking'); }
function automationOrder(a: AudioAutomationPoint, b: AudioAutomationPoint): number { return Number(a.metadata.startMs ?? a.timeMs) - Number(b.metadata.startMs ?? b.timeMs) || Number(a.metadata.endMs ?? a.timeMs) - Number(b.metadata.endMs ?? b.timeMs) || a.trackType.localeCompare(b.trackType) || a.id.localeCompare(b.id); }

function normalizeManifestAudio(manifest: RenderManifest): void { const duration = manifest.durationMs; for (const key of ['voice', 'music', 'sfx'] as const) manifest.audio[key] = manifest.audio[key].flatMap((item) => clampSegment(item, duration)); manifest.audio.automation = manifest.audio.automation.filter((item) => Number.isFinite(item.timeMs)).map((item) => ({ ...item, timeMs: clamp(item.timeMs, 0, duration), gain: clamp(item.gain, 0, 1.5) })).sort(automationOrder); syncAudioTracks(manifest); manifest.audio.metrics = calculateAudioMetrics(duration, manifest.audio.voice, manifest.audio.music, manifest.audio.sfx, manifest.audio.automation, manifest.audio.settings); }
function syncAudioTracks(manifest: RenderManifest): void { const typeMap = { voice: manifest.audio.voice, music: manifest.audio.music, effects: manifest.audio.sfx } as const; manifest.timeline.tracks = manifest.timeline.tracks.map((track) => { if (!(track.type in typeMap)) return track; const segments = typeMap[track.type as keyof typeof typeMap]; const remaining = [...track.clips]; const clips = segments.map((segment) => { const index = remaining.findIndex((clip) => clip.sceneId === (segment.sceneId ?? 'global') && clip.assetId === segment.assetId && clip.metadata.audioType === segment.type); const existing = index >= 0 ? remaining.splice(index, 1)[0] : undefined; return segmentClip(segment, existing); }); return { ...track, volume: track.type === 'voice' ? manifest.audio.settings.voiceGain : track.type === 'music' ? manifest.audio.settings.musicGain : manifest.audio.settings.sfxGain, clips }; }); }
function segmentClip(segment: AudioSegment, existing?: MediaClip): MediaClip { return { id: existing?.id ?? stableId(`clip-${segment.type}`, segment.id), sceneId: segment.sceneId ?? 'global', assetId: segment.assetId, startMs: segment.startMs, endMs: segment.endMs, durationMs: segment.durationMs, offsetMs: existing?.offsetMs ?? 0, metadata: { ...existing?.metadata, ...segment.metadata, audioType: segment.type, gain: segment.gain, fadeInMs: segment.fadeInMs, fadeOutMs: segment.fadeOutMs } }; }
function clampSegment(item: AudioSegment, duration: number): AudioSegment[] { const startMs = clamp(item.startMs, 0, duration); const endMs = clamp(item.endMs, startMs, duration); return endMs > startMs ? [{ ...item, startMs, endMs, durationMs: endMs - startMs, gain: clamp(item.gain, 0, 1.5), fadeInMs: clamp(item.fadeInMs, 0, (endMs - startMs) / 2), fadeOutMs: clamp(item.fadeOutMs, 0, (endMs - startMs) / 2) }] : []; }
function duckingPoints(start: number, end: number, gain: number, reductionDb: number, index: number, operation: AudioOperation, plan: AudioProductionPlan): AudioAutomationPoint[] { const reduced = gain * dbToGain(reductionDb); const point = (phase: string, timeMs: number, pointGain: number): AudioAutomationPoint => ({ id: stableId('audio-ducking', `${plan.id}|${operation.id}|${index}|${phase}`), type: 'ducking', trackType: 'music', timeMs, gain: pointGain, metadata: { type: 'automation', kind: 'ducking', phase, startMs: start, endMs: end, sourceOperationId: operation.id, sourcePlanId: plan.id, source: 'audio-production' } }); return [point('attack', start, gain), point('active', start + 1, reduced), point('release', end, reduced), point('end', end + 1, gain)]; }
export function validateAudioManifest(manifest: RenderManifest): void { const ids = new Set<string>(); for (const segment of [...manifest.audio.voice, ...manifest.audio.music, ...manifest.audio.sfx]) { if (ids.has(segment.id)) throw new Error('Audio segment IDs must be unique.'); ids.add(segment.id); if (segment.startMs < 0 || segment.endMs <= segment.startMs || segment.endMs > manifest.durationMs || segment.durationMs !== segment.endMs - segment.startMs) throw new Error('Audio segment timing is invalid.'); if (segment.gain < 0 || segment.gain > 1.5) throw new Error('Audio gain is outside safe bounds.'); if (segment.sceneId && !manifest.timeline.scenes.some((scene) => scene.id === segment.sceneId)) throw new Error('Audio segment references an invalid scene.'); } for (const point of manifest.audio.automation) if (point.timeMs < 0 || point.timeMs > manifest.durationMs || point.gain < 0 || point.gain > 1.5) throw new Error('Audio automation is invalid.'); }
function dbToGain(db: number): number { return clamp(10 ** (db / 20), 0, 1.5); }
