import type { DirectorReport, DirectorRecommendationPriority } from '@/core/director';
import type { AudioSegment, MediaScene, RenderManifest } from '@/core/media';
import type { TimelineRevision, TimelineSnapshot } from '@/core/editing';

export type AudioOperationType = 'trim-silence' | 'extend-silence' | 'shift-voice' | 'normalize-voice-gain' | 'normalize-music-gain' | 'normalize-sfx-gain' | 'add-fade-in' | 'add-fade-out' | 'add-ducking' | 'adjust-ducking' | 'insert-sfx' | 'remove-sfx' | 'move-sfx' | 'shorten-music' | 'extend-music' | 'loop-music' | 'change-music-entry' | 'change-music-exit' | 'add-emphasis' | 'reduce-clipping-risk' | 'reduce-masking' | 'align-beat-plan' | 'keep';
export type AudioOperationStatus = 'proposed' | 'disabled' | 'applied' | 'skipped' | 'rejected';
export type AudioInvalidationScope = 'scene' | 'scene-range' | 'track' | 'global-timeline' | 'final-mix-only';
export type AudioConflictType = 'voice-overlap' | 'voice-music-masking' | 'voice-sfx-masking' | 'clipping-risk' | 'gain-conflict' | 'timing-conflict' | 'automation-conflict' | 'duplicate-sfx' | 'silence-removal-conflict' | 'fade-conflict' | 'segment-out-of-bounds' | 'missing-source' | 'unsupported-operation';
export interface AudioSceneInput { readonly scene: MediaScene; readonly voice: readonly AudioSegment[]; }
export interface AudioProductionInput { readonly projectId: string; readonly manifest: RenderManifest; readonly directorReport: DirectorReport; readonly scenes: readonly AudioSceneInput[]; }
export interface VoiceSegmentAnalysis { readonly sceneId: string; readonly firstVoiceCueMs: number | null; readonly lastVoiceCueMs: number | null; readonly leadingSilenceMs: number; readonly trailingSilenceMs: number; readonly voiceCoverage: number; readonly alignmentScore: number; readonly overlapRisk: number; readonly timingIssues: readonly string[]; readonly recommendations: readonly AudioRecommendation[]; }
export interface SilenceRegion { readonly startMs: number; readonly endMs: number; readonly durationMs: number; readonly sceneId: string | null; readonly type: 'leading' | 'trailing' | 'gap' | 'dead-air' | 'intentional'; readonly severity: 'low' | 'medium' | 'high' | 'critical'; readonly intentionalProbability: number; readonly evidence: readonly string[]; readonly recommendedAction: string; }
export interface SceneSpeechPacing { readonly sceneId: string; readonly estimatedWpm: number; readonly charactersPerSecond: number; readonly paceScore: number; }
export interface SpeechPacingAnalysis { readonly estimatedWpm: number; readonly paceScore: number; readonly readabilityScore: number; readonly overloadRisk: number; readonly slowSpeechRisk: number; readonly scenePacing: readonly SceneSpeechPacing[]; readonly recommendedRateAdjustment: number; readonly recommendations: readonly AudioRecommendation[]; }
export interface AudioQualityScore { readonly technicalScore: number; readonly intelligibilityRisk: number; readonly clippingRisk: number; readonly lowLevelRisk: number; readonly consistencyScore: number; readonly overallVoiceScore: number; readonly evidence: readonly string[]; readonly recommendations: readonly AudioRecommendation[]; }
export interface MusicProductionPlan { readonly intent: string; readonly mood: string; readonly energy: number; readonly tempoRange: readonly [number, number]; readonly entryMs: number; readonly exitMs: number; readonly loopRequired: boolean; readonly fadeInMs: number; readonly fadeOutMs: number; readonly searchQuery: string; readonly preferredGenres: readonly string[]; readonly instrumentation: readonly string[]; readonly vocals: 'instrumental' | 'either'; readonly avoidTerms: readonly string[]; readonly maskingRisk: number; }
export interface SfxProductionPlan { readonly sceneId: string; readonly startMs: number; readonly durationMs: number; readonly intent: 'impact' | 'whoosh' | 'riser' | 'hit' | 'click' | 'pop' | 'glitch' | 'reveal' | 'transition' | 'tension' | 'success' | 'notification' | 'ambience'; readonly searchQuery: string; readonly gainDb: number; readonly fadeMs: number; readonly priority: DirectorRecommendationPriority; readonly reason: string; readonly avoidOverlapWithVoice: boolean; readonly confidence: number; }
export interface DuckingPlan { readonly triggerTrack: 'voice' | 'sfx'; readonly targetTrack: 'music'; readonly startMs: number; readonly endMs: number; readonly reductionDb: number; readonly attackMs: number; readonly releaseMs: number; readonly threshold: number; readonly reason: string; readonly confidence: number; }
export type AudioPlatformProfile = 'generic-short-video' | 'youtube-shorts' | 'tiktok' | 'instagram-reels';
export interface LoudnessPlan { readonly profile: AudioPlatformProfile; readonly voiceTargetLufs: number; readonly musicTargetLufs: number; readonly sfxTargetLufs: number; readonly finalTargetLufs: number; readonly truePeakDb: number; readonly limiterCeilingDb: number; readonly normalizationMode: 'ebu-r128'; readonly risks: readonly string[]; }
export interface AudioConflict { readonly id: string; readonly type: AudioConflictType; readonly operationIds: readonly string[]; readonly sceneId: string | null; readonly severity: 'warning' | 'critical'; readonly reason: string; readonly resolved: boolean; }
export interface AudioRecommendation { readonly id: string; readonly sceneId: string | null; readonly category: 'voice' | 'silence' | 'pacing' | 'music' | 'sfx' | 'ducking' | 'loudness'; readonly priority: DirectorRecommendationPriority; readonly title: string; readonly description: string; readonly expectedImpact: number; readonly confidence: number; }
export interface AudioOperation { readonly id: string; readonly projectId: string; readonly sceneId: string | null; readonly sourceRecommendationId: string | null; readonly type: AudioOperationType; readonly priority: DirectorRecommendationPriority; readonly reason: string; readonly evidence: readonly string[]; readonly parameters: Readonly<Record<string, string | number | boolean | readonly string[] | null>>; readonly expectedImpact: number; readonly confidence: number; readonly automaticallyApplicable: boolean; readonly dependencies: readonly string[]; readonly conflicts: readonly string[]; readonly status: AudioOperationStatus; readonly createdAt: string; }
export interface AudioProductionDiagnostics { readonly warnings: readonly string[]; readonly analyzerNotes: readonly string[]; }
export interface AudioProductionPlan { readonly id: string; readonly projectId: string; readonly planVersion: '1.0'; readonly sourceManifestFingerprint: string; readonly sourceManifestFingerprintVersion: number; readonly sourceDirectorReportFingerprint: string; readonly createdAt: string; readonly voiceAnalysis: readonly VoiceSegmentAnalysis[]; readonly silenceRegions: readonly SilenceRegion[]; readonly pacing: SpeechPacingAnalysis; readonly quality: AudioQualityScore; readonly music: MusicProductionPlan; readonly sfx: readonly SfxProductionPlan[]; readonly ducking: readonly DuckingPlan[]; readonly loudness: LoudnessPlan; readonly operations: readonly AudioOperation[]; readonly conflicts: readonly AudioConflict[]; readonly recommendations: readonly AudioRecommendation[]; readonly expectedQualityImpact: number; readonly expectedDurationDeltaMs: number; readonly affectedScenes: readonly string[]; readonly automaticOperations: readonly string[]; readonly manualOperations: readonly string[]; readonly diagnostics: AudioProductionDiagnostics; }
export interface AudioProductionPreview { readonly id: string; readonly projectId: string; readonly planId: string; readonly sourceRevisionId: string; readonly createdAt: string; readonly approvedManualOperationIds: readonly string[]; readonly unapprovedManualOperationIds: readonly string[]; readonly beforeVoice: readonly AudioSegment[]; readonly afterVoice: readonly AudioSegment[]; readonly removedSilenceMs: number; readonly automation: readonly import('@/core/media').AudioAutomationPoint[]; readonly sfx: readonly AudioSegment[]; readonly loudness: LoudnessPlan; readonly durationDeltaMs: number; readonly affectedScenes: readonly string[]; readonly operationCount: number; readonly conflicts: readonly AudioConflict[]; readonly estimatedQualityImprovement: number; readonly rerenderSceneIds: readonly string[]; readonly reusableSceneIds: readonly string[]; readonly cacheReuseEstimate: number; readonly validationImpact: 'requires-validation'; readonly warnings: readonly string[]; readonly proposedSnapshot: TimelineSnapshot; }
export interface AudioProductionResult { readonly projectId: string; readonly appliedOperationIds: readonly string[]; readonly skippedOperationIds: readonly string[]; readonly previousRevision: TimelineRevision; readonly revision: TimelineRevision; }
export type AudioRevision = TimelineRevision;
export interface AudioProductionOptions { readonly platformProfile?: AudioPlatformProfile; readonly leadingSilenceThresholdMs?: number; readonly trailingSilenceThresholdMs?: number; readonly naturalPauseMs?: number; readonly historyLimit?: number; }
export interface AudioProductionEngine { analyze(input: AudioProductionInput, signal?: AbortSignal): AudioProductionPlan; preview(plan: AudioProductionPlan, snapshot: TimelineSnapshot, approvedManualOperationIds?: readonly string[], signal?: AbortSignal): AudioProductionPreview; apply(plan: AudioProductionPlan, preview: AudioProductionPreview, snapshot: TimelineSnapshot, approvedManualOperationIds?: readonly string[]): AudioProductionResult; }
