import { createRequire } from 'node:module';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import http from 'node:http';

const require = createRequire(import.meta.url);
const { createCredentialVault, createPkce, createState } = require('../../electron/youtube-credentials.cjs') as { createCredentialVault: (input: any) => any; createPkce: () => { verifier: string; challenge: string }; createState: () => string };
const { createYouTubeAuthService, SCOPES } = require('../../electron/youtube-auth-service.cjs') as { createYouTubeAuthService: (input: any) => any; SCOPES: string[] };
const { resolveYouTubeClientId } = require('../../electron/youtube-runtime-config.cjs') as { resolveYouTubeClientId: (input: any) => string | null };
const { generateRuntimeConfig } = require('../../scripts/generate-electron-runtime-config.cjs') as { generateRuntimeConfig: (input: any) => string };
const { loadLocalYouTubeClientId } = require('../../scripts/electron-local-config.cjs') as { loadLocalYouTubeClientId: (input: any) => string | null };
const safeStorage = { isEncryptionAvailable: () => true, encryptString: (value: string) => Buffer.from(`encrypted:${value}`), decryptString: (value: Buffer) => value.toString().replace(/^encrypted:/, '') };
const credential = { accessToken: 'access-secret', refreshToken: 'refresh-secret', expiresAt: new Date(Date.now() + 60_000).toISOString(), scopes: SCOPES, tokenType: 'Bearer', provider: 'youtube', channelId: 'UC1', displayName: 'Channel' };
let directory = '';
afterEach(async () => { if (directory) await rm(directory, { recursive: true, force: true }); directory = ''; });

async function connectWithChannels(channels: Array<{ id: string; title: string }>, selectionTimeoutMs?: number, serviceOptions: Record<string, unknown> = {}) {
  directory = await mkdtemp(join(tmpdir(), 'shortsflow-youtube-'));
  const vault = createCredentialVault({ userDataPath: directory, safeStorage });
  let authorizationUrl = '';
  const service = createYouTubeAuthService({ vault, clientId: 'test-client', selectionTimeoutMs, openExternal: (url: string) => { authorizationUrl = url; }, fetchImpl: async (url: string) => url.includes('/token') ? ({ ok: true, json: async () => ({ access_token: 'access-secret', refresh_token: 'refresh-secret', expires_in: 3600, token_type: 'Bearer', scope: SCOPES.join(' ') }) }) : ({ ok: true, json: async () => ({ items: channels.map((channel) => ({ id: channel.id, snippet: { title: channel.title } })) }) }), ...serviceOptions });
  const pending = service.connect();
  const settled = pending.then((value: unknown) => ({ value }), (error: unknown) => ({ error }));
  await vi.waitFor(() => expect(authorizationUrl).not.toBe(''));
  const redirect = new URL(new URL(authorizationUrl).searchParams.get('redirect_uri')!);
  const state = new URL(authorizationUrl).searchParams.get('state')!;
  await new Promise<void>((resolve, reject) => { http.get(`${redirect}?state=${encodeURIComponent(state)}&code=code`, (response) => { response.resume(); response.on('end', resolve); }).on('error', reject); });
  const outcome = await settled;
  if ('error' in outcome) throw outcome.error;
  return { vault, service, result: outcome.value as any };
}

async function connectWithChannelPages(pages: Record<string, Record<string, unknown>>) {
  const fetchImpl = vi.fn(async (url: string) => {
    if (url.includes('/token')) return { ok: true, json: async () => ({ access_token: 'access-secret', refresh_token: 'refresh-secret', expires_in: 3600, token_type: 'Bearer', scope: SCOPES.join(' ') }) };
    const page = pages[new URL(url).searchParams.get('pageToken') || 'first'];
    if (!page) throw new Error('unexpected page');
    return { ok: page.ok !== false, status: page.status ?? 200, json: async () => page.body ?? page };
  });
  return { ...(await connectWithChannels([], undefined, { fetchImpl })), fetchImpl };
}

describe('YouTube credential boundary', () => {
  it('creates unique PKCE and state values', () => { const first = createPkce(); const second = createPkce(); expect(first.verifier).not.toBe(second.verifier); expect(first.challenge).not.toBe(first.verifier); expect(createState()).not.toBe(createState()); });
  it('fails clearly when OAuth returns no authenticated channels', async () => { await expect(connectWithChannels([])).rejects.toMatchObject({ code: 'youtube-channel-missing' }); });
  it('automatically binds the sole authenticated channel', async () => { const { result } = await connectWithChannels([{ id: 'UC-one', title: 'One' }]); expect(result).toEqual(expect.objectContaining({ credentialRef: expect.stringMatching(/^youtube_/), channelRef: 'UC-one', displayName: 'One' })); });
  it('rejects a granular OAuth grant missing upload scope before storing a credential', async () => {
    directory = await mkdtemp(join(tmpdir(), 'shortsflow-youtube-'));
    const vault = createCredentialVault({ userDataPath: directory, safeStorage });
    let authorizationUrl = '';
    const service = createYouTubeAuthService({ vault, clientId: 'test-client', openExternal: (url: string) => { authorizationUrl = url; }, fetchImpl: async (url: string) => url.includes('/token') ? ({ ok: true, json: async () => ({ access_token: 'access-secret', refresh_token: 'refresh-secret', expires_in: 3600, token_type: 'Bearer', scope: 'https://www.googleapis.com/auth/youtube.readonly' }) }) : ({ ok: true, json: async () => ({ items: [{ id: 'UC-one', snippet: { title: 'One' } }] }) }) });
    const pending = service.connect();
    const settled = pending.then((value: unknown) => ({ value }), (error: unknown) => ({ error }));
    await vi.waitFor(() => expect(authorizationUrl).not.toBe(''));
    const redirect = new URL(new URL(authorizationUrl).searchParams.get('redirect_uri')!);
    const state = new URL(authorizationUrl).searchParams.get('state')!;
    await new Promise<void>((resolve, reject) => { http.get(`${redirect}?state=${encodeURIComponent(state)}&code=code`, (response) => { response.resume(); response.on('end', resolve); }).on('error', reject); });
    await expect(settled).resolves.toEqual({ error: expect.objectContaining({ code: 'insufficient-scope' }) });
    expect(await vault.exists('youtube_missing')).toBe(false);
    await expect(readFile(vault.filePath, 'utf8')).rejects.toMatchObject({ code: 'ENOENT' });
  });
  it('collects every channel page with the maximum page size before requiring selection', async () => { const { result, fetchImpl } = await connectWithChannelPages({ first: { items: [{ id: 'UC-A', snippet: { title: 'Channel A' } }], nextPageToken: 'second' }, second: { items: [{ id: 'UC-B', snippet: { title: 'Channel B' } }, { id: 'UC-C', snippet: { title: 'Channel C' } }] } }); expect(result).toEqual(expect.objectContaining({ status: 'selection-required', channels: [{ channelId: 'UC-A', displayName: 'Channel A' }, { channelId: 'UC-B', displayName: 'Channel B' }, { channelId: 'UC-C', displayName: 'Channel C' }] })); const channelUrls = fetchImpl.mock.calls.map(([url]: [string]) => url).filter((url: string) => url.includes('/youtube/v3/channels')); expect(channelUrls).toHaveLength(2); expect(new URL(channelUrls[0]).searchParams.get('maxResults')).toBe('50'); expect(new URL(channelUrls[1]).searchParams.get('pageToken')).toBe('second'); expect(JSON.stringify(result)).not.toContain('access-secret'); expect(JSON.stringify(result)).not.toContain('refresh-secret'); });
  it('automatically binds a sole channel found on a later page', async () => { const { result } = await connectWithChannelPages({ first: { items: [], nextPageToken: 'second' }, second: { items: [{ id: 'UC-late', snippet: { title: 'Late channel' } }] } }); expect(result).toEqual(expect.objectContaining({ channelRef: 'UC-late', displayName: 'Late channel', credentialRef: expect.stringMatching(/^youtube_/) })); });
  it('deduplicates paginated channels by first-seen YouTube channel ID', async () => { const { result } = await connectWithChannelPages({ first: { items: [{ id: 'UC-A', snippet: { title: 'First title' } }, { id: 'UC-B', snippet: { title: 'Channel B' } }], nextPageToken: 'second' }, second: { items: [{ id: 'UC-A', snippet: { title: 'Duplicate title' } }, { id: 'UC-C', snippet: { title: 'Channel C' } }] } }); expect(result).toEqual(expect.objectContaining({ channels: [{ channelId: 'UC-A', displayName: 'First title' }, { channelId: 'UC-B', displayName: 'Channel B' }, { channelId: 'UC-C', displayName: 'Channel C' }] })); });
  it('fails safely rather than looping or returning a partial selection on broken pagination', async () => { await expect(connectWithChannelPages({ first: { items: [{ id: 'UC-A', snippet: { title: 'Channel A' } }], nextPageToken: 'repeat' }, repeat: { items: [{ id: 'UC-B', snippet: { title: 'Channel B' } }], nextPageToken: 'repeat' } })).rejects.toMatchObject({ code: 'youtube-identity-failed' }); await expect(connectWithChannelPages({ first: { items: [{ id: 'UC-A', snippet: { title: 'Channel A' } }], nextPageToken: 'second' }, second: { ok: false, status: 500, body: { error: 'provider-failure' } } })).rejects.toMatchObject({ code: 'youtube-identity-failed' }); });
  it('requires safe deterministic selection for multiple authenticated channels', async () => { const { service, vault, result } = await connectWithChannels([{ id: 'UC-A', title: 'Channel A' }, { id: 'UC-B', title: 'Channel B' }]); expect(result).toEqual({ platform: 'youtube', status: 'selection-required', selectionRef: expect.any(String), channels: [{ channelId: 'UC-A', displayName: 'Channel A' }, { channelId: 'UC-B', displayName: 'Channel B' }] }); expect(JSON.stringify(result)).not.toContain('access-secret'); expect(JSON.stringify(result)).not.toContain('refresh-secret'); await expect(service.finalizeSelection(result.selectionRef, 'UC-other')).rejects.toMatchObject({ code: 'youtube-channel-selection-invalid' }); await expect(service.finalizeSelection(result.selectionRef, 'UC-A')).rejects.toMatchObject({ code: 'youtube-channel-selection-expired' }); expect(await vault.exists('youtube_missing')).toBe(false); });
  it('finalizes exactly one selected channel and safely expires or cancels selection contexts', async () => { const selected = await connectWithChannels([{ id: 'UC-A', title: 'Channel A' }, { id: 'UC-B', title: 'Channel B' }]); if (!('selectionRef' in selected.result)) throw new Error('Expected selection'); const [first, second] = await Promise.allSettled([selected.service.finalizeSelection(selected.result.selectionRef, 'UC-B'), selected.service.finalizeSelection(selected.result.selectionRef, 'UC-A')]); expect(first.status).toBe('fulfilled'); expect(second.status).toBe('rejected'); if (first.status === 'fulfilled') expect(first.value).toEqual(expect.objectContaining({ channelRef: 'UC-B', displayName: 'Channel B' })); const cancelled = await connectWithChannels([{ id: 'UC-C', title: 'Channel C' }, { id: 'UC-D', title: 'Channel D' }]); if (!('selectionRef' in cancelled.result)) throw new Error('Expected selection'); expect(cancelled.service.cancelSelection(cancelled.result.selectionRef)).toBe(true); await expect(cancelled.service.finalizeSelection(cancelled.result.selectionRef, 'UC-C')).rejects.toMatchObject({ code: 'youtube-channel-selection-expired' }); const expired = await connectWithChannels([{ id: 'UC-E', title: 'Channel E' }, { id: 'UC-F', title: 'Channel F' }], 0); if (!('selectionRef' in expired.result)) throw new Error('Expected selection'); await expect(expired.service.finalizeSelection(expired.result.selectionRef, 'UC-E')).rejects.toMatchObject({ code: 'youtube-channel-selection-expired' }); });
  it('automatically removes abandoned selection contexts and clears their timers on every removal path', async () => {
    let callback: (() => void) | undefined;
    const cleared: unknown[] = [];
    const timers = { selectionSetTimeout: (fn: () => void) => { callback = fn; return 'timer'; }, selectionClearTimeout: (timer: unknown) => { cleared.push(timer); } };
    const abandoned = await connectWithChannels([{ id: 'UC-E', title: 'Channel E' }, { id: 'UC-F', title: 'Channel F' }], 100, timers);
    if (!('selectionRef' in abandoned.result) || !callback) throw new Error('Expected selection timer');
    cleared.length = 0;
    callback();
    await expect(abandoned.service.finalizeSelection(abandoned.result.selectionRef, 'UC-E')).rejects.toMatchObject({ code: 'youtube-channel-selection-expired' });
    expect(cleared).toEqual(['timer']);
    expect(JSON.stringify(abandoned.result)).not.toContain('refresh-secret');
    const finalized = await connectWithChannels([{ id: 'UC-G', title: 'Channel G' }, { id: 'UC-H', title: 'Channel H' }], 100, timers);
    if (!('selectionRef' in finalized.result)) throw new Error('Expected selection');
    cleared.length = 0;
    await finalized.service.finalizeSelection(finalized.result.selectionRef, 'UC-G');
    expect(cleared).toEqual(['timer']);
    const raced = await connectWithChannels([{ id: 'UC-R', title: 'Channel R' }, { id: 'UC-S', title: 'Channel S' }], 100, timers);
    if (!('selectionRef' in raced.result) || !callback) throw new Error('Expected selection');
    const expireAfterFinalize = callback;
    await expect(raced.service.finalizeSelection(raced.result.selectionRef, 'UC-R')).resolves.toEqual(expect.objectContaining({ channelRef: 'UC-R' }));
    expireAfterFinalize();
    await expect(raced.service.finalizeSelection(raced.result.selectionRef, 'UC-R')).rejects.toMatchObject({ code: 'youtube-channel-selection-expired' });
    const cancelled = await connectWithChannels([{ id: 'UC-I', title: 'Channel I' }, { id: 'UC-J', title: 'Channel J' }], 100, timers);
    if (!('selectionRef' in cancelled.result)) throw new Error('Expected selection');
    cleared.length = 0;
    cancelled.service.cancelSelection(cancelled.result.selectionRef);
    expect(cleared).toEqual(['timer']);
  });
  it('stores only encrypted credential records and resolves by opaque reference after reload', async () => { directory = await mkdtemp(join(tmpdir(), 'shortsflow-youtube-')); const first = createCredentialVault({ userDataPath: directory, safeStorage }); const ref = await first.store(credential); expect(ref).toMatch(/^youtube_/); expect(await createCredentialVault({ userDataPath: directory, safeStorage }).resolve(ref)).toEqual(credential); const disk = await readFile(first.filePath, 'utf8'); expect(disk).not.toContain('access-secret'); expect(disk).not.toContain('refresh-secret'); });
  it('serializes concurrent stores so neither credential is lost', async () => { directory = await mkdtemp(join(tmpdir(), 'shortsflow-youtube-')); const vault = createCredentialVault({ userDataPath: directory, safeStorage }); const [first, second] = await Promise.all([vault.store({ ...credential, channelId: 'A' }), vault.store({ ...credential, channelId: 'B' })]); expect((await vault.resolve(first)).channelId).toBe('A'); expect((await vault.resolve(second)).channelId).toBe('B'); });
  it('fails closed when secure storage is unavailable', async () => { directory = await mkdtemp(join(tmpdir(), 'shortsflow-youtube-')); const vault = createCredentialVault({ userDataPath: directory, safeStorage: { ...safeStorage, isEncryptionAvailable: () => false } }); await expect(vault.store(credential)).rejects.toMatchObject({ code: 'secure-storage-unavailable' }); });
  it('rejects Electron basic_text and never reads or writes credential material through it', async () => { directory = await mkdtemp(join(tmpdir(), 'shortsflow-youtube-')); const vault = createCredentialVault({ userDataPath: directory, safeStorage: { ...safeStorage, getSelectedStorageBackend: () => 'basic_text' } }); await expect(vault.store(credential)).rejects.toMatchObject({ code: 'secure-storage-unavailable' }); await expect(vault.resolve('youtube_00000000-0000-0000-0000-000000000000')).rejects.toMatchObject({ code: 'secure-storage-unavailable' }); await expect(readFile(vault.filePath, 'utf8')).rejects.toMatchObject({ code: 'ENOENT' }); });
  it('refreshes expired credentials once, retains a prior refresh token, and never returns it through account status', async () => { directory = await mkdtemp(join(tmpdir(), 'shortsflow-youtube-')); const vault = createCredentialVault({ userDataPath: directory, safeStorage }); const ref = await vault.store({ ...credential, expiresAt: new Date(Date.now() - 1).toISOString() }); const fetchImpl = vi.fn(async () => ({ ok: true, json: async () => ({ access_token: 'new-access', expires_in: 3600, token_type: 'Bearer' }) })); const service = createYouTubeAuthService({ vault, fetchImpl, openExternal: vi.fn(), clientId: 'test-client' }); const [one, two] = await Promise.all([service.resolveExecutionCredential(ref), service.resolveExecutionCredential(ref)]); expect(one.accessToken).toBe('new-access'); expect(two.refreshToken).toBe('refresh-secret'); expect(fetchImpl).toHaveBeenCalledTimes(1); expect(await service.status(ref)).toEqual({ credentialRef: ref, authenticated: true }); });
  it('removes only terminally invalid credentials, reports status as disconnected, and never retries the dead refresh token', async () => { directory = await mkdtemp(join(tmpdir(), 'shortsflow-youtube-')); const vault = createCredentialVault({ userDataPath: directory, safeStorage }); const ref = await vault.store({ ...credential, expiresAt: new Date(Date.now() - 1).toISOString() }); const unaffectedRef = await vault.store({ ...credential, channelId: 'UC-other' }); const fetchImpl = vi.fn(async () => ({ ok: false, status: 400, json: async () => ({ error: 'invalid_grant' }) })); const service = createYouTubeAuthService({ vault, clientId: 'test-client', fetchImpl }); await expect(service.resolveExecutionCredential(ref)).rejects.toMatchObject({ code: 'credential-reconnect-required' }); expect(await service.status(ref)).toEqual({ credentialRef: ref, authenticated: false }); await expect(service.resolveExecutionCredential(ref)).rejects.toMatchObject({ code: 'credential-missing' }); expect(fetchImpl).toHaveBeenCalledTimes(1); expect(await vault.resolve(unaffectedRef)).toEqual(expect.objectContaining({ channelId: 'UC-other' })); });
  it('preserves a credential after a transient refresh failure without exposing token material', async () => { directory = await mkdtemp(join(tmpdir(), 'shortsflow-youtube-')); const vault = createCredentialVault({ userDataPath: directory, safeStorage }); const ref = await vault.store({ ...credential, expiresAt: new Date(Date.now() - 1).toISOString() }); const service = createYouTubeAuthService({ vault, clientId: 'test-client', fetchImpl: async () => { throw new Error('network unavailable'); } }); const failure = await service.resolveExecutionCredential(ref).catch((error: Error) => error); expect(failure).toMatchObject({ code: 'youtube-network-failure' }); expect(String(failure)).not.toContain('refresh-secret'); expect(await service.status(ref)).toEqual({ credentialRef: ref, authenticated: true }); });
  it('loads the desktop client ID from the explicit packaged runtime config without legacy storage', async () => { directory = await mkdtemp(join(tmpdir(), 'shortsflow-youtube-')); await (await import('node:fs/promises')).writeFile(join(directory, 'shortsflow.runtime.json'), JSON.stringify({ youtubeClientId: 'desktop-client' })); expect(resolveYouTubeClientId({ env: {}, userDataPath: directory, resourcesPath: join(directory, 'none') })).toBe('desktop-client'); expect(resolveYouTubeClientId({ env: {}, userDataPath: join(directory, 'missing'), resourcesPath: join(directory, 'none') })).toBeNull(); });
  it('generates an explicitly unconfigured runtime file when OAuth is absent and clears stale client IDs', async () => { directory = await mkdtemp(join(tmpdir(), 'shortsflow-youtube-')); const output = join(directory, 'shortsflow.runtime.json'); generateRuntimeConfig({ clientId: 'synthetic-release-client', outputFile: output }); expect(JSON.parse(await readFile(output, 'utf8'))).toEqual({ youtubeClientId: 'synthetic-release-client' }); generateRuntimeConfig({ outputFile: output, resolveClientId: () => null }); expect(JSON.parse(await readFile(output, 'utf8'))).toEqual({ youtubeClientId: '' }); expect(resolveYouTubeClientId({ env: {}, userDataPath: directory, resourcesPath: join(directory, 'none') })).toBeNull(); });
  it('uses the same local resolver for build generation, with explicit environment values taking precedence', async () => { directory = await mkdtemp(join(tmpdir(), 'shortsflow-youtube-')); const output = join(directory, 'shortsflow.runtime.json'); const fsApi = { readFileSync: () => 'SHORTSFLOW_YOUTUBE_CLIENT_ID=from-dotenv\n' }; const fromDotEnv = loadLocalYouTubeClientId({ env: {}, fsApi }); const fromEnvironment = loadLocalYouTubeClientId({ env: { SHORTSFLOW_YOUTUBE_CLIENT_ID: 'from-environment' }, fsApi }); generateRuntimeConfig({ outputFile: output, resolveClientId: () => fromDotEnv }); expect(JSON.parse(await readFile(output, 'utf8'))).toEqual({ youtubeClientId: 'from-dotenv' }); generateRuntimeConfig({ outputFile: output, resolveClientId: () => fromEnvironment }); expect(JSON.parse(await readFile(output, 'utf8'))).toEqual({ youtubeClientId: 'from-environment' }); });
  it('uses the same local .env configuration rule for both Electron launchers', () => { const fsApi = { readFileSync: () => 'SHORTSFLOW_YOUTUBE_CLIENT_ID=local-client\n' }; expect(loadLocalYouTubeClientId({ env: {}, fsApi })).toBe('local-client'); expect(loadLocalYouTubeClientId({ env: {}, fsApi })).toBe('local-client'); expect(loadLocalYouTubeClientId({ env: {}, fsApi: { readFileSync: () => '' } })).toBeNull(); });
  it('keeps native OAuth safely unavailable when an unconfigured runtime resolves no client ID', async () => { directory = await mkdtemp(join(tmpdir(), 'shortsflow-youtube-')); const vault = createCredentialVault({ userDataPath: directory, safeStorage }); const service = createYouTubeAuthService({ vault, clientId: () => resolveYouTubeClientId({ env: {}, userDataPath: directory, resourcesPath: join(directory, 'none') }) }); await expect(service.connect()).rejects.toMatchObject({ code: 'oauth-configuration-missing' }); });
  it('ignores mismatched callback states until the legitimate callback succeeds', async () => { directory = await mkdtemp(join(tmpdir(), 'shortsflow-youtube-')); const vault = createCredentialVault({ userDataPath: directory, safeStorage }); let authUrl = ''; const service = createYouTubeAuthService({ vault, clientId: 'test-client', openExternal: (url: string) => { authUrl = url; }, fetchImpl: async (url: string) => url.includes('/token') ? ({ ok: true, json: async () => ({ access_token: 'access-secret', refresh_token: 'refresh-secret', expires_in: 3600, token_type: 'Bearer', scope: SCOPES.join(' ') }) }) : ({ ok: true, json: async () => ({ items: [{ id: 'UC-legitimate', snippet: { title: 'Legitimate' } }] }) }) }); const pending = service.connect(); await vi.waitFor(() => expect(authUrl).not.toBe('')); const authorization = new URL(authUrl); const redirect = new URL(authorization.searchParams.get('redirect_uri')!); const request = (query: string) => new Promise<{ status: number; body: string }>((resolve, reject) => { http.get(`${redirect}?${query}`, (result) => { let body = ''; result.on('data', (chunk) => { body += chunk; }); result.on('end', () => resolve({ status: result.statusCode ?? 0, body })); }).on('error', reject); }); const first = await request('state=wrong-one&code=untrusted-code'); const second = await request('state=wrong-two'); for (const response of [first, second]) { expect(response.status).toBe(400); expect(response.body).toContain('Authorization could not be verified'); expect(response.body).not.toContain('completed'); expect(response.body).not.toContain(authorization.searchParams.get('state')!); expect(response.body).not.toContain('untrusted-code'); expect(response.body).not.toContain('access-secret'); } const success = await request(`state=${encodeURIComponent(authorization.searchParams.get('state')!)}&code=legitimate-code`); expect(success.status).toBe(200); expect(success.body).toContain('completed'); await expect(pending).resolves.toEqual(expect.objectContaining({ channelRef: 'UC-legitimate', authenticated: true })); });
  it('keeps valid-state denial as a terminal truthful callback failure', async () => { directory = await mkdtemp(join(tmpdir(), 'shortsflow-youtube-')); const vault = createCredentialVault({ userDataPath: directory, safeStorage }); let authUrl = ''; const pending = createYouTubeAuthService({ vault, clientId: 'test-client', openExternal: (url: string) => { authUrl = url; } }).connect(); const rejection = expect(pending).rejects.toMatchObject({ code: 'oauth-cancelled' }); await vi.waitFor(() => expect(authUrl).not.toBe('')); const authorization = new URL(authUrl); const redirect = new URL(authorization.searchParams.get('redirect_uri')!); const response = await new Promise<{ status: number; body: string }>((resolve, reject) => { http.get(`${redirect}?state=${encodeURIComponent(authorization.searchParams.get('state')!)}&error=access_denied`, (result) => { let body = ''; result.on('data', (chunk) => { body += chunk; }); result.on('end', () => resolve({ status: result.statusCode ?? 0, body })); }).on('error', reject); }); expect(response).toMatchObject({ status: 400 }); expect(response.body).toContain('Authorization was cancelled'); expect(response.body).not.toContain('completed'); await rejection; });
});
