import { createManifestRevisionId, createTimelineSnapshot, isTimelineSnapshotCurrent } from '@/core/editing';
import { validateMediaProject, type RenderManifest } from '@/core/media';
import { useAudioProductionStore } from '@/store/audioProductionStore';
import { useDirectorReportStore } from '@/store/directorReportStore';
import { useMediaStore } from '@/store/mediaStore';
import type { AudioProductionApplicationService } from './audioProductionApplicationService';
let service: AudioProductionApplicationService | null = null;
export function configureAudioProductionController(value: AudioProductionApplicationService | null): void { service = value; }
export async function createActiveAudioPlan(signal?: AbortSignal): Promise<void> { const active = requireService(); const report = useDirectorReportStore.getState().currentReport; const manifest = useMediaStore.getState().manifest; if (!report) throw new Error('Run AI Director analysis before creating an audio plan.'); if (!manifest) throw new Error('Build the active media manifest in Studio first.'); const store = useAudioProductionStore.getState(); const existing = store.getCurrentSnapshot(manifest.projectId); const snapshot = existing && isTimelineSnapshotCurrent(existing, manifest) ? existing : createTimelineSnapshot(manifest, createManifestRevisionId(manifest)); if (snapshot !== existing) store.replaceWithFreshSnapshot(snapshot); const result = await active.createPlan(report, manifest, snapshot, signal); useAudioProductionStore.getState().setWorkingSnapshot(result.snapshot); await active.createPreview(result.plan, result.snapshot, [], signal); }
export async function refreshActiveAudioPreview(): Promise<void> { const active = requireService(); const state = useAudioProductionStore.getState(); if (!state.currentPlan || !state.workingSnapshot) throw new Error('Create an audio plan first.'); await active.createPreview(state.currentPlan, state.workingSnapshot, state.approvedManualOperationIds); }
export async function applyActiveAudioPlan(approvedManualIds?: readonly string[]): Promise<void> { const active = requireService(); const state = useAudioProductionStore.getState(); if (!state.currentPlan || !state.currentPreview || !state.workingSnapshot) throw new Error('Create a current audio preview before apply.'); const approvals = approvedManualIds ?? state.approvedManualOperationIds; const source = state.workingSnapshot; const current = useMediaStore.getState().manifest; if (!current || !isTimelineSnapshotCurrent(source, current)) throw new Error('Stale audio revision; create a new plan.'); const result = await active.apply(state.currentPlan, state.currentPreview, source, approvals); const latest = useMediaStore.getState().manifest; if (!latest || !isTimelineSnapshotCurrent(source, latest)) { if (latest) useAudioProductionStore.getState().replaceWithFreshSnapshot(createTimelineSnapshot(latest, createManifestRevisionId(latest))); throw new Error('Stale audio revision; manifest changed during apply.'); } installAndValidate(result.revision.snapshot.manifest); }
export async function undoActiveAudio(): Promise<void> { assertHistoryCurrent(); const snapshot = useAudioProductionStore.getState().undo(); if (snapshot) { installAndValidate(snapshot.manifest); await requireService().revisionCompleted('undo', snapshot.projectId, snapshot.revisionId); } }
export async function redoActiveAudio(): Promise<void> { assertHistoryCurrent(); const snapshot = useAudioProductionStore.getState().redo(); if (snapshot) { installAndValidate(snapshot.manifest); await requireService().revisionCompleted('redo', snapshot.projectId, snapshot.revisionId); } }
function assertHistoryCurrent(): void { const manifest = useMediaStore.getState().manifest; const state = useAudioProductionStore.getState(); if (!manifest || !state.workingSnapshot) return; if (!isTimelineSnapshotCurrent(state.workingSnapshot, manifest)) { state.replaceWithFreshSnapshot(createTimelineSnapshot(manifest, createManifestRevisionId(manifest))); throw new Error('Audio revision history is stale because the manifest changed.'); } }
function installAndValidate(manifest: RenderManifest): void { const media = useMediaStore.getState(); media.replaceEditedManifest(manifest); const state = useMediaStore.getState(); if (!state.project || !state.assetResolution) { state.setBuildError('Audio edit was saved, but validation requires current asset resolution data.'); return; } const validation = validateMediaProject({ project: state.project, manifest: { ...manifest, validation: null }, assetResolution: state.assetResolution }); useMediaStore.getState().replaceValidatedManifest(manifest, validation); }
function requireService(): AudioProductionApplicationService { if (!service) throw new Error('AI Audio Production service is not ready.'); return service; }
