import { applicationContainer, dependencyTokens } from '@/core/di';
import { approvalFingerprint, type PublishAccount, type PublishJob, type PublishMetadata, type PublishSchedule, type PublishTarget } from '@/core/publishing';
import type { ExportArtifact } from '@/core/export-intelligence';
import { usePublishingStore } from '@/store/publishingStore';
import type { PublishingApplicationService } from './publishingApplicationService';
function service(): PublishingApplicationService { return applicationContainer.resolve(dependencyTokens.publishingApplicationService); }
let sharedQueue: ReturnType<PublishingApplicationService['createQueue']> | null = null;
export async function createPublishJob(input: { projectId: string; variantId?: string | null; account: PublishAccount; target: PublishTarget; artifact: ExportArtifact; sourceManifestFingerprint: string; metadata: PublishMetadata; schedule?: PublishSchedule; }): Promise<PublishJob> { const job = service().createJob(input); usePublishingStore.getState().updateJob(job); return job; }
export async function previewPublishJob(job: PublishJob): Promise<PublishJob> { const readiness = service().readiness(job); if (!readiness.ready) throw new Error(readiness.issues.join(' ')); const previewed = { ...job, readiness, approvalFingerprint: approvalFingerprint(job), approvedAt: null, updatedAt: new Date().toISOString() }; usePublishingStore.getState().updateJob(previewed); return previewed; }
export async function approveAndEnqueuePublish(job: PublishJob): Promise<PublishJob> { if (!job.approvalFingerprint) throw new Error('Publish preview required before approval.'); const freshReadiness = service().readiness(job); if (!freshReadiness.ready) throw new Error(freshReadiness.issues.join(' ')); if (!job.accountBinding.authenticated) throw new Error('Publishing account authentication is required.'); const fingerprint = approvalFingerprint(job); if (job.approvalFingerprint !== fingerprint) throw new Error('Publish preview is stale; please preview again before approval.'); const queue = await ensureQueue(); const approved = { ...job, readiness: freshReadiness, state: job.schedule.mode === 'scheduled' ? 'scheduled' as const : 'queued' as const, approvedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; queue.enqueue(approved); usePublishingStore.getState().updateJob(approved); void queue.start(); return approved; }
export async function retryPublishJob(jobId: string): Promise<PublishJob | null> { const queue = await ensureQueue(); const job = await queue.retry(jobId); return job; }
export async function reconcilePublishJob(jobId: string): Promise<PublishJob | null> { const queue = await ensureQueue(); return queue.reconcile(jobId); }
async function ensureQueue() { if (sharedQueue) return sharedQueue; await usePublishingStore.persist.rehydrate(); sharedQueue = service().createQueue(undefined, usePublishingStore.getState().updateJob); sharedQueue.hydrate(usePublishingStore.getState().queue); usePublishingStore.getState().setQueue(sharedQueue.snapshot()); return sharedQueue; }
export async function initializePublishingQueue() { const queue = await ensureQueue(); await queue.start(); return queue; }
