import { createManifestRevisionId, createTimelineSnapshot, isTimelineSnapshotCurrent, type TimelineSnapshot } from '@/core/editing';
import { validateMediaProject, type MediaValidationReport, type RenderManifest } from '@/core/media';
import type { CaptionStyleProfile } from '@/core/subtitle-intelligence';
import { useMediaStore } from '@/store/mediaStore';
import { useSubtitleIntelligenceStore, type SubtitleRequest } from '@/store/subtitleIntelligenceStore';
import { acquireVisualOperation, releaseVisualOperation } from './visualOperationCoordinator';
import type { SubtitleIntelligenceApplicationService } from './subtitleIntelligenceApplicationService';

const STALE = 'Manifest changed during the subtitle transaction; no partial revision was installed.'; let service: SubtitleIntelligenceApplicationService | null = null; let generation = 0; let previewGeneration = 0; let analysisAbort: AbortController | null = null; let previewAbort: AbortController | null = null;
export function configureSubtitleIntelligenceController(value: SubtitleIntelligenceApplicationService | null): void { analysisAbort?.abort(); previewAbort?.abort(); analysisAbort = null; previewAbort = null; service = value; }
export function cancelSubtitleIntelligenceRequests(): void { analysisAbort?.abort(); previewAbort?.abort(); analysisAbort = null; previewAbort = null; }
export async function createActiveSubtitlePlan(profile: CaptionStyleProfile = 'shorts'): Promise<boolean> { const active = requireService(); const manifest = requireManifest(); const lease = acquireVisualOperation(manifest.projectId, 'subtitle-analyzing'); try { const state = useSubtitleIntelligenceStore.getState(); const snapshot = state.snapshot && isTimelineSnapshotCurrent(state.snapshot, manifest) ? state.snapshot : createTimelineSnapshot(manifest, createManifestRevisionId(manifest)); if (snapshot !== state.snapshot) state.replace(snapshot); analysisAbort?.abort(); const abort = new AbortController(); analysisAbort = abort; const request = identity(snapshot, ++generation); useSubtitleIntelligenceStore.getState().start(request); try { const result = await active.createPlan(manifest, snapshot, profile, abort.signal, request.requestId); if (abort.signal.aborted || !bindings(request, snapshot)) { useSubtitleIntelligenceStore.getState().cancelRequest('analysis', request.requestId); return false; } return useSubtitleIntelligenceStore.getState().complete(request, result.plan, result.snapshot); } catch (error) { if (abort.signal.aborted || isAbort(error)) return false; if (useSubtitleIntelligenceStore.getState().failRequest(request, message(error))) throw error; return false; } finally { if (analysisAbort === abort) analysisAbort = null; } } finally { releaseVisualOperation(lease); } }
export async function refreshSubtitlePreview(): Promise<boolean> { const state = useSubtitleIntelligenceStore.getState(); if (!state.plan || !state.snapshot) throw new Error('Create a subtitle intelligence plan first.'); const abort = new AbortController(); const request = identity(state.snapshot, ++previewGeneration); const approvedIds = [...new Set(state.approvedIds)].sort(); const lease = acquireVisualOperation(state.snapshot.projectId, 'subtitle-previewing', () => abort.abort()); previewAbort = abort; useSubtitleIntelligenceStore.getState().previewStarted(request); try { try { const preview = await requireService().createPreview(state.plan, state.snapshot, approvedIds, abort.signal); if (abort.signal.aborted || !bindings(request, state.snapshot)) return false; return useSubtitleIntelligenceStore.getState().previewCompleted(request, preview); } catch (error) { if (abort.signal.aborted || isAbort(error)) return false; if (useSubtitleIntelligenceStore.getState().failRequest(request, message(error))) throw error; return false; } finally { if (previewAbort === abort) previewAbort = null; } } finally { releaseVisualOperation(lease); } }
export async function applyActiveSubtitlePlan(): Promise<void> {
  const state = useSubtitleIntelligenceStore.getState(); const projectId = state.activeProjectId ?? useMediaStore.getState().manifest?.projectId;
  if (!projectId) throw new Error('Build the active media manifest first.');
  const lease = acquireVisualOperation(projectId, 'subtitle-applying'); const visualBefore = useSubtitleIntelligenceStore.getState(); const mediaBefore = useMediaStore.getState();
  try {
    if (!state.plan || !state.preview || !state.snapshot || !state.isPreviewCurrent()) throw new Error('Wait for the current approved subtitle preview before applying.');
    assertCurrent(state.snapshot); state.applying();
    const result = await requireService().apply(state.plan, state.preview, state.snapshot, state.approvedIds);
    const prepared = prepareInstall(state.snapshot, result.revision.snapshot.manifest); useSubtitleIntelligenceStore.getState().applied(result);
    try { prepared.install(); } catch (error) { useSubtitleIntelligenceStore.setState(visualBefore, true); rollbackMedia(prepared.fingerprint, mediaBefore); throw error; }
  } catch (error) {
    if (useMediaStore.getState().manifest === mediaBefore.manifest) useSubtitleIntelligenceStore.setState(visualBefore, true);
    throw error;
  } finally { releaseVisualOperation(lease); }
}
export async function undoSubtitle(): Promise<void> { await move('undo'); } export async function redoSubtitle(): Promise<void> { await move('redo'); }
async function move(kind: 'undo' | 'redo'): Promise<void> { const state = useSubtitleIntelligenceStore.getState(); const source = state.snapshot; if (!source) return; assertCurrent(source); const lease = acquireVisualOperation(source.projectId, kind === 'undo' ? 'subtitle-undoing' : 'subtitle-redoing'); try { const candidate = useSubtitleIntelligenceStore.getState().prepareRevisionMove(kind); if (!candidate) return; await requireService().revisionCompleted(kind, candidate.projectId, candidate.target.id); assertCurrent(source); const prepared = prepareInstall(source, candidate.target.snapshot.manifest); const rollback = useSubtitleIntelligenceStore.getState().captureRollback(candidate.projectId); if (!rollback || rollback.snapshot?.revisionId !== candidate.sourceRevisionId || !useSubtitleIntelligenceStore.getState().commitRevisionMove(candidate)) throw new Error(STALE); const mediaBefore = useMediaStore.getState(); try { prepared.install(); } catch (error) { useSubtitleIntelligenceStore.getState().rollbackRevisionMove(candidate, rollback); rollbackMedia(prepared.fingerprint, mediaBefore); throw error; } } finally { releaseVisualOperation(lease); } }
function prepareInstall(source: TimelineSnapshot, candidate: RenderManifest) { assertCurrent(source); if (candidate.projectId !== source.projectId) throw new Error('Subtitle revision project does not match the active manifest.'); const media = useMediaStore.getState(); let validation: MediaValidationReport | null = null; if (media.project && media.assetResolution) validation = validateMediaProject({ project: media.project, manifest: { ...candidate, validation: null }, assetResolution: media.assetResolution }); return { fingerprint: createManifestRevisionId(candidate), install: () => { const current = useMediaStore.getState(); if (!current.manifest || !isTimelineSnapshotCurrent(source, current.manifest)) throw new Error(STALE); if (validation) current.replaceValidatedManifest(candidate, validation); else current.replaceEditedManifest(candidate); } }; }
function assertCurrent(snapshot: TimelineSnapshot): void { const manifest = useMediaStore.getState().manifest; if (!manifest || !isTimelineSnapshotCurrent(snapshot, manifest)) throw new Error(STALE); } function rollbackMedia(fingerprint: string, before: ReturnType<typeof useMediaStore.getState>): void { const manifest = useMediaStore.getState().manifest; if (manifest && createManifestRevisionId(manifest) === fingerprint) useMediaStore.setState(before, true); }
function identity(snapshot: TimelineSnapshot, requestId: number): SubtitleRequest { return { requestId, projectId: snapshot.projectId, revisionId: snapshot.revisionId, fingerprint: snapshot.manifestFingerprint }; } function bindings(request: SubtitleRequest, snapshot: TimelineSnapshot): boolean { const manifest = useMediaStore.getState().manifest; const state = useSubtitleIntelligenceStore.getState(); return Boolean(manifest && isTimelineSnapshotCurrent(snapshot, manifest) && state.activeProjectId === request.projectId); }
function requireService(): SubtitleIntelligenceApplicationService { if (!service) throw new Error('Subtitle Intelligence service is not ready.'); return service; } function requireManifest(): RenderManifest { const manifest = useMediaStore.getState().manifest; if (!manifest) throw new Error('Build the active media manifest first.'); return manifest; } function isAbort(error: unknown): boolean { return error instanceof Error && error.name === 'AbortError'; } function message(error: unknown): string { return error instanceof Error ? error.message : 'Subtitle intelligence failed.'; }
