import { createManifestRevisionId, createTimelineSnapshot, isTimelineSnapshotCurrent, type TimelineSnapshot } from '@/core/editing';
import type { ApplicationEventMap, EventBus } from '@/core/events';
import type { RenderManifest } from '@/core/media';
import type { CaptionStyleProfile, SubtitleIntelligenceEngine, SubtitleIntelligencePlan, SubtitleIntelligencePreview, SubtitleIntelligenceResult } from '@/core/subtitle-intelligence';

export interface SubtitleIntelligenceApplicationService { createPlan(manifest: RenderManifest, snapshot?: TimelineSnapshot, profile?: CaptionStyleProfile, signal?: AbortSignal, requestId?: number): Promise<{ plan: SubtitleIntelligencePlan; snapshot: TimelineSnapshot }>; createPreview(plan: SubtitleIntelligencePlan, snapshot: TimelineSnapshot, approvedIds: readonly string[], signal?: AbortSignal): Promise<SubtitleIntelligencePreview>; apply(plan: SubtitleIntelligencePlan, preview: SubtitleIntelligencePreview, snapshot: TimelineSnapshot, approvedIds: readonly string[]): Promise<SubtitleIntelligenceResult>; revisionCompleted(kind: 'undo' | 'redo', projectId: string, revisionId: string): Promise<void>; }
export function createSubtitleIntelligenceApplicationService(engine: SubtitleIntelligenceEngine, bus: EventBus<ApplicationEventMap>): SubtitleIntelligenceApplicationService { return {
  async createPlan(manifest, snapshot, profile, signal, requestId = 0) { const current = snapshot && isTimelineSnapshotCurrent(snapshot, manifest) ? snapshot : createTimelineSnapshot(manifest, createManifestRevisionId(manifest)); await bus.emit('subtitle-intelligence:analysis-started', { projectId: manifest.projectId, revisionId: current.revisionId, requestId, startedAt: new Date().toISOString() }); try { const plan = engine.analyze({ manifest, snapshot: current, profile }, signal); await bus.emit('subtitle-intelligence:plan-completed', { projectId: manifest.projectId, plan, requestId, completedAt: new Date().toISOString() }); return { plan, snapshot: current }; } catch (error) { await bus.emit('subtitle-intelligence:failed', { projectId: manifest.projectId, stage: 'analysis', requestId, message: message(error), failedAt: new Date().toISOString() }); throw error; } },
  async createPreview(plan, snapshot, approvedIds, signal) { const value = engine.preview(plan, snapshot, approvedIds, signal); await bus.emit('subtitle-intelligence:preview-created', { projectId: plan.projectId, preview: value, createdAt: new Date().toISOString() }); return value; },
  async apply(plan, preview, snapshot, approvedIds) { try { const result = engine.apply(plan, preview, snapshot, approvedIds); await bus.emit('subtitle-intelligence:apply-completed', { projectId: plan.projectId, result, completedAt: new Date().toISOString() }); return result; } catch (error) { await bus.emit('subtitle-intelligence:failed', { projectId: plan.projectId, stage: 'apply', message: message(error), failedAt: new Date().toISOString() }); throw error; } },
  async revisionCompleted(kind, projectId, revisionId) { await bus.emit(kind === 'undo' ? 'subtitle-intelligence:undo-completed' : 'subtitle-intelligence:redo-completed', { projectId, revisionId, completedAt: new Date().toISOString() }); },
}; }
function message(error: unknown): string { return error instanceof Error ? error.message : 'Subtitle intelligence failed.'; }
