import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { createAudioPreview, deriveEffectiveAudioPlan, resolveAudioConflict, type AudioConflict, type AudioOperation, type AudioProductionPlan, type AudioProductionPreview, type AudioProductionResult } from '@/core/audio-production';
import { isTimelineSnapshotInternallyValid, MANIFEST_FINGERPRINT_VERSION, type TimelineRevision, type TimelineSnapshot } from '@/core/editing';
import { createPersistentStorage } from '@/persistence/storeStorage';

type Status = 'idle' | 'analyzing' | 'ready' | 'applying' | 'completed' | 'failed';
interface PersistedAudioState { revisionsByProject: Record<string, TimelineRevision[]>; staleRevisionsByProject: Record<string, TimelineRevision[]>; activeProjectId: string | null; }
interface AudioState extends PersistedAudioState { currentPlan: AudioProductionPlan | null; currentPreview: AudioProductionPreview | null; workingSnapshot: TimelineSnapshot | null; analysisStatus: Status; applyStatus: Status; conflicts: readonly AudioConflict[]; operations: readonly AudioOperation[]; approvedManualOperationIds: readonly string[]; currentRevisionId: string | null; undoAvailable: boolean; redoAvailable: boolean; redoByProject: Record<string, TimelineRevision[]>; lastError: string | null; lastAnalyzedAt: string | null; lastAppliedAt: string | null;
  analysisStarted(projectId: string): void; planCompleted(plan: AudioProductionPlan, at: string): void; previewCreated(preview: AudioProductionPreview): void; analysisFailed(message: string): void; operationEnabled(id: string, enabled: boolean): void; approveManualOperation(id: string): void; revokeManualOperationApproval(id: string): void; approveAllManualOperations(): void; clearManualApprovals(): void; conflictResolved(id: string, selectedId: string): void; applyStarted(): void; applyCompleted(result: AudioProductionResult, at: string): void; applyFailed(message: string): void; setWorkingSnapshot(snapshot: TimelineSnapshot): void; replaceWithFreshSnapshot(snapshot: TimelineSnapshot): void; getCurrentSnapshot(projectId: string): TimelineSnapshot | null; undo(): TimelineSnapshot | null; redo(): TimelineSnapshot | null; resetProject(projectId: string): void; }
const LIMIT = 10; const base = { activeProjectId: null, currentPlan: null, currentPreview: null, workingSnapshot: null, analysisStatus: 'idle' as Status, applyStatus: 'idle' as Status, conflicts: [], operations: [], approvedManualOperationIds: [], currentRevisionId: null, revisionsByProject: {}, staleRevisionsByProject: {}, redoByProject: {}, undoAvailable: false, redoAvailable: false, lastError: null, lastAnalyzedAt: null, lastAppliedAt: null };
export const useAudioProductionStore = create<AudioState>()(persist((set, get) => ({ ...base,
  analysisStarted: (activeProjectId) => set({ activeProjectId, analysisStatus: 'analyzing', currentPlan: null, currentPreview: null, conflicts: [], operations: [], approvedManualOperationIds: [], lastError: null }),
  planCompleted: (plan, lastAnalyzedAt) => set(() => { const currentPlan = deriveEffectiveAudioPlan(plan); return { currentPlan, operations: currentPlan.operations, conflicts: currentPlan.conflicts, approvedManualOperationIds: [], currentPreview: null, analysisStatus: 'ready', lastAnalyzedAt }; }), previewCreated: (currentPreview) => set((state) => { if (!state.currentPlan || !state.workingSnapshot) return { currentPreview: null }; const expected = createAudioPreview(state.currentPlan, state.workingSnapshot, state.approvedManualOperationIds); return { currentPreview: expected.id === currentPreview.id && expected.sourceRevisionId === currentPreview.sourceRevisionId ? currentPreview : null }; }), analysisFailed: (lastError) => set({ analysisStatus: 'failed', lastError }),
  operationEnabled: (id, enabled) => set((state) => { if (!state.currentPlan) return state; const currentPlan = deriveEffectiveAudioPlan({ ...state.currentPlan, operations: state.currentPlan.operations.map((item) => item.id === id ? { ...item, status: enabled ? 'proposed' as const : 'disabled' as const } : item) }); return { currentPlan, operations: currentPlan.operations, conflicts: currentPlan.conflicts, approvedManualOperationIds: state.approvedManualOperationIds.filter((item) => item !== id), currentPreview: null }; }),
  approveManualOperation: (id) => set((state) => { const operation = state.currentPlan?.operations.find((item) => item.id === id); const critical = state.conflicts.some((item) => item.severity === 'critical' && item.operationIds.includes(id)); if (!operation || operation.automaticallyApplicable || operation.status === 'disabled' || critical) return state; return { approvedManualOperationIds: [...new Set([...state.approvedManualOperationIds, id])].sort(), currentPreview: null }; }),
  revokeManualOperationApproval: (id) => set((state) => ({ approvedManualOperationIds: state.approvedManualOperationIds.filter((item) => item !== id), currentPreview: null })),
  approveAllManualOperations: () => set((state) => ({ approvedManualOperationIds: state.operations.filter((item) => !item.automaticallyApplicable && item.status !== 'disabled' && !state.conflicts.some((conflict) => conflict.severity === 'critical' && conflict.operationIds.includes(item.id))).map((item) => item.id).sort(), currentPreview: null })),
  clearManualApprovals: () => set({ approvedManualOperationIds: [], currentPreview: null }),
  conflictResolved: (id, selectedId) => set((state) => { if (!state.currentPlan) return state; const currentPlan = resolveAudioConflict(state.currentPlan, id, selectedId); const eligible = new Set(currentPlan.operations.filter((item) => !item.automaticallyApplicable && item.status !== 'disabled').map((item) => item.id)); return { currentPlan, operations: currentPlan.operations, conflicts: currentPlan.conflicts, approvedManualOperationIds: state.approvedManualOperationIds.filter((item) => eligible.has(item)), currentPreview: null }; }), applyStarted: () => set({ applyStatus: 'applying', lastError: null }),
  applyCompleted: (result, lastAppliedAt) => set((state) => { const history = unique([...(state.revisionsByProject[result.projectId] ?? []), result.previousRevision, result.revision]).slice(-LIMIT); return { activeProjectId: result.projectId, workingSnapshot: result.revision.snapshot, currentRevisionId: result.revision.id, revisionsByProject: { ...state.revisionsByProject, [result.projectId]: history }, redoByProject: { ...state.redoByProject, [result.projectId]: [] }, undoAvailable: history.length > 1, redoAvailable: false, applyStatus: 'completed', lastAppliedAt, approvedManualOperationIds: [], currentPreview: null }; }), applyFailed: (lastError) => set({ applyStatus: 'failed', lastError }), setWorkingSnapshot: (workingSnapshot) => set({ workingSnapshot, currentRevisionId: workingSnapshot.revisionId }),
  replaceWithFreshSnapshot: (snapshot) => set((state) => { const id = snapshot.projectId; const old = [...(state.revisionsByProject[id] ?? []), ...(state.redoByProject[id] ?? [])]; const first = revision(snapshot); return { activeProjectId: id, workingSnapshot: snapshot, currentRevisionId: snapshot.revisionId, revisionsByProject: { ...state.revisionsByProject, [id]: [first] }, staleRevisionsByProject: old.length ? { ...state.staleRevisionsByProject, [id]: [...(state.staleRevisionsByProject[id] ?? []), ...old].slice(-LIMIT) } : state.staleRevisionsByProject, redoByProject: { ...state.redoByProject, [id]: [] }, undoAvailable: false, redoAvailable: false, currentPlan: null, currentPreview: null, operations: [], conflicts: [], approvedManualOperationIds: [] }; }),
  getCurrentSnapshot: (id) => get().workingSnapshot?.projectId === id ? get().workingSnapshot : get().revisionsByProject[id]?.at(-1)?.snapshot ?? null,
  undo: () => moveRevision(get, set, false), redo: () => moveRevision(get, set, true),
  resetProject: (id) => set((state) => { const revisionsByProject = { ...state.revisionsByProject }; const redoByProject = { ...state.redoByProject }; delete revisionsByProject[id]; delete redoByProject[id]; return state.activeProjectId === id ? { ...base, revisionsByProject, redoByProject, staleRevisionsByProject: state.staleRevisionsByProject } : { revisionsByProject, redoByProject }; }),
}), { name: 'shortsflow-audio-production', version: 1, storage: createPersistentStorage<PersistedAudioState>(), skipHydration: true, partialize: (state) => ({ revisionsByProject: state.revisionsByProject, staleRevisionsByProject: state.staleRevisionsByProject, activeProjectId: state.activeProjectId }), migrate: normalize, merge: (persisted, current) => { const value = normalize(persisted); const active = value.activeProjectId; const workingSnapshot = active ? value.revisionsByProject[active]?.at(-1)?.snapshot ?? null : null; return { ...current, ...value, workingSnapshot, currentRevisionId: workingSnapshot?.revisionId ?? null, undoAvailable: active ? (value.revisionsByProject[active]?.length ?? 0) > 1 : false }; } }));

function moveRevision(get: () => AudioState, set: (value: Partial<AudioState>) => void, redo: boolean): TimelineSnapshot | null { const state = get(); const id = state.activeProjectId; if (!id) return null; const history = state.revisionsByProject[id] ?? []; const stack = state.redoByProject[id] ?? []; const target = redo ? stack.at(-1) : history.at(-2); if (!target) return null; if (!valid(target, id)) { set({ staleRevisionsByProject: { ...state.staleRevisionsByProject, [id]: [...(state.staleRevisionsByProject[id] ?? []), target].slice(-LIMIT) }, undoAvailable: redo ? state.undoAvailable : false, redoAvailable: redo ? stack.length > 1 : state.redoAvailable, lastError: 'Invalid audio revision was quarantined.' }); return null; } if (redo) { const nextHistory = [...history, target].slice(-LIMIT); set({ revisionsByProject: { ...state.revisionsByProject, [id]: nextHistory }, redoByProject: { ...state.redoByProject, [id]: stack.slice(0, -1) }, workingSnapshot: target.snapshot, currentRevisionId: target.id, approvedManualOperationIds: [], currentPreview: null, undoAvailable: nextHistory.length > 1, redoAvailable: stack.length > 1 }); } else { const removed = history.at(-1); if (!removed) return null; set({ revisionsByProject: { ...state.revisionsByProject, [id]: history.slice(0, -1) }, redoByProject: { ...state.redoByProject, [id]: [...stack, removed] }, workingSnapshot: target.snapshot, currentRevisionId: target.id, approvedManualOperationIds: [], currentPreview: null, undoAvailable: history.length > 2, redoAvailable: true }); } return target.snapshot; }
function normalize(value: unknown): PersistedAudioState { if (!record(value)) return { revisionsByProject: {}, staleRevisionsByProject: {}, activeProjectId: null }; return { revisionsByProject: map(value.revisionsByProject), staleRevisionsByProject: map(value.staleRevisionsByProject), activeProjectId: typeof value.activeProjectId === 'string' ? value.activeProjectId : null }; }
function map(value: unknown): Record<string, TimelineRevision[]> { if (!record(value)) return {}; return Object.fromEntries(Object.entries(value).flatMap(([id, entries]) => { if (!Array.isArray(entries)) return []; const validEntries = entries.filter((item): item is TimelineRevision => valid(item, id)).slice(-LIMIT); return validEntries.length ? [[id, validEntries]] : []; })); }
function valid(value: unknown, projectId: string): value is TimelineRevision { if (!record(value) || !record(value.snapshot)) return false; const snapshot = value.snapshot as unknown as TimelineSnapshot; return value.id === snapshot.revisionId && value.projectId === projectId && snapshot.projectId === projectId && snapshot.fingerprintVersion === MANIFEST_FINGERPRINT_VERSION && isTimelineSnapshotInternallyValid(snapshot); }
function record(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); } function revision(snapshot: TimelineSnapshot): TimelineRevision { return { id: snapshot.revisionId, projectId: snapshot.projectId, parentRevisionId: snapshot.parentRevisionId, createdAt: snapshot.createdAt, operationIds: [], snapshot }; } function unique(items: TimelineRevision[]): TimelineRevision[] { return items.filter((item, index) => items.findIndex((other) => other.id === item.id) === index); }
