import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import type { EditApplyResult, EditOperation, EditOperationConflict, EditPlan, EditPreview, TimelineRevision, TimelineSnapshot } from '@/core/editing';
import { deriveEffectiveEditPlan, isTimelineSnapshotInternallyValid, resolveEditPlanConflict } from '@/core/editing';
import { MANIFEST_FINGERPRINT_VERSION } from '@/core/editing';
import type { RenderManifest } from '@/core/media';
import { createPersistentStorage } from '@/persistence/storeStorage';

type ApplyStatus = 'idle' | 'planning' | 'preview' | 'applying' | 'completed' | 'failed';
interface PersistedEditingState { revisionsByProject: Record<string, TimelineRevision[]>; staleRevisionsByProject?: Record<string, TimelineRevision[]>; activeProjectId: string | null; }
interface EditingState extends PersistedEditingState { staleRevisionsByProject: Record<string, TimelineRevision[]>; currentPlan: EditPlan | null; currentPreview: EditPreview | null; workingSnapshot: TimelineSnapshot | null; applyStatus: ApplyStatus; operations: readonly EditOperation[]; conflicts: readonly EditOperationConflict[]; undoAvailable: boolean; redoAvailable: boolean; currentRevisionId: string | null; lastError: string | null; lastAppliedAt: string | null; redoByProject: Record<string, TimelineRevision[]>;
  planStarted(projectId: string): void; planCompleted(plan: EditPlan): void; planFailed(message: string): void; previewCreated(preview: EditPreview): void; operationEnabled(id: string, enabled: boolean): void; conflictResolved(id: string, selectedOperationId: string): void; applyStarted(): void; applyCompleted(result: EditApplyResult, completedAt?: string): void; applyFailed(message: string): void; setWorkingSnapshot(snapshot: TimelineSnapshot): void; replaceWithFreshSnapshot(snapshot: TimelineSnapshot): void; getCurrentSnapshot(projectId: string): TimelineSnapshot | null; undo(): TimelineSnapshot | null; redo(): TimelineSnapshot | null; resetProject(projectId: string): void; }
const HISTORY_LIMIT = 12;
const initial = { activeProjectId: null, currentPlan: null, currentPreview: null, workingSnapshot: null, applyStatus: 'idle' as ApplyStatus, operations: [], conflicts: [], revisionsByProject: {}, staleRevisionsByProject: {}, redoByProject: {}, undoAvailable: false, redoAvailable: false, currentRevisionId: null, lastError: null, lastAppliedAt: null };
export const useEditingStore = create<EditingState>()(persist((set, get) => ({ ...initial,
  planStarted: (activeProjectId) => set({ activeProjectId, currentPlan: null, currentPreview: null, applyStatus: 'planning', operations: [], conflicts: [], lastError: null }),
  planCompleted: (plan) => set(() => { const currentPlan = deriveEffectiveEditPlan(plan); return { currentPlan, operations: currentPlan.operations, conflicts: currentPlan.diagnostics.conflicts, applyStatus: 'idle' }; }),
  planFailed: (lastError) => set({ applyStatus: 'failed', lastError }), previewCreated: (currentPreview) => set({ currentPreview, applyStatus: 'preview' }),
  operationEnabled: (id, enabled) => set((state) => { if (!state.currentPlan) return state; const currentPlan = deriveEffectiveEditPlan({ ...state.currentPlan, operations: state.currentPlan.operations.map((item) => item.id === id ? { ...item, status: enabled ? 'proposed' as const : 'disabled' as const } : item) }); return { currentPlan, operations: currentPlan.operations, conflicts: currentPlan.diagnostics.conflicts, currentPreview: null }; }),
  conflictResolved: (id, selectedOperationId) => set((state) => { if (!state.currentPlan) return state; const currentPlan = resolveEditPlanConflict(state.currentPlan, id, selectedOperationId); return { currentPlan, operations: currentPlan.operations, conflicts: currentPlan.diagnostics.conflicts, currentPreview: null }; }),
  applyStarted: () => set({ applyStatus: 'applying', lastError: null }), applyCompleted: (result, completedAt = new Date().toISOString()) => set((state) => { const history = [...(state.revisionsByProject[result.projectId] ?? []), result.previousRevision, result.revision].filter((item, index, all) => all.findIndex((entry) => entry.id === item.id) === index).slice(-HISTORY_LIMIT); return { activeProjectId: result.projectId, workingSnapshot: result.revision.snapshot, currentRevisionId: result.revision.id, revisionsByProject: { ...state.revisionsByProject, [result.projectId]: history }, redoByProject: { ...state.redoByProject, [result.projectId]: [] }, undoAvailable: history.length > 1, redoAvailable: false, applyStatus: 'completed', lastAppliedAt: completedAt, currentPreview: null }; }),
  applyFailed: (lastError) => set({ applyStatus: 'failed', lastError }), setWorkingSnapshot: (workingSnapshot) => set({ workingSnapshot, currentRevisionId: workingSnapshot.revisionId }),
  getCurrentSnapshot: (projectId) => get().workingSnapshot?.projectId === projectId ? get().workingSnapshot : get().revisionsByProject[projectId]?.at(-1)?.snapshot ?? null,
  replaceWithFreshSnapshot: (snapshot) => set((state) => { const projectId = snapshot.projectId; const existing = [...(state.revisionsByProject[projectId] ?? []), ...(state.redoByProject[projectId] ?? [])]; const base: TimelineRevision = { id: snapshot.revisionId, projectId, parentRevisionId: null, createdAt: snapshot.createdAt, operationIds: [], snapshot }; return { activeProjectId: projectId, workingSnapshot: snapshot, currentRevisionId: snapshot.revisionId, revisionsByProject: { ...state.revisionsByProject, [projectId]: [base] }, staleRevisionsByProject: existing.length ? { ...state.staleRevisionsByProject, [projectId]: [...(state.staleRevisionsByProject[projectId] ?? []), ...existing].slice(-HISTORY_LIMIT) } : state.staleRevisionsByProject, redoByProject: { ...state.redoByProject, [projectId]: [] }, undoAvailable: false, redoAvailable: false, currentPlan: null, currentPreview: null, operations: [], conflicts: [] }; }),
  undo: () => { const state = get(); const id = state.activeProjectId; if (!id) return null; const history = state.revisionsByProject[id] ?? []; if (history.length < 2) return null; const removed = history.at(-1); const previous = history.at(-2); if (!removed || !previous) return null; if (!isTimelineSnapshotInternallyValid(previous.snapshot)) { set({ revisionsByProject: { ...state.revisionsByProject, [id]: removed ? [removed] : [] }, staleRevisionsByProject: { ...state.staleRevisionsByProject, [id]: [...(state.staleRevisionsByProject[id] ?? []), previous].slice(-HISTORY_LIMIT) }, undoAvailable: false, lastError: 'Undo history contained an invalid timeline revision and was quarantined.' }); return null; } set({ revisionsByProject: { ...state.revisionsByProject, [id]: history.slice(0, -1) }, redoByProject: { ...state.redoByProject, [id]: [...(state.redoByProject[id] ?? []), removed] }, workingSnapshot: previous.snapshot, currentRevisionId: previous.id, undoAvailable: history.length > 2, redoAvailable: true }); return previous.snapshot; },
  redo: () => { const state = get(); const id = state.activeProjectId; if (!id) return null; const stack = state.redoByProject[id] ?? []; const next = stack.at(-1); if (!next) return null; if (!isTimelineSnapshotInternallyValid(next.snapshot)) { const remaining = stack.slice(0, -1); set({ redoByProject: { ...state.redoByProject, [id]: remaining }, staleRevisionsByProject: { ...state.staleRevisionsByProject, [id]: [...(state.staleRevisionsByProject[id] ?? []), next].slice(-HISTORY_LIMIT) }, redoAvailable: remaining.length > 0, lastError: 'Redo history contained an invalid timeline revision and was quarantined.' }); return null; } const history = [...(state.revisionsByProject[id] ?? []), next].slice(-HISTORY_LIMIT); set({ revisionsByProject: { ...state.revisionsByProject, [id]: history }, redoByProject: { ...state.redoByProject, [id]: stack.slice(0, -1) }, workingSnapshot: next.snapshot, currentRevisionId: next.id, undoAvailable: history.length > 1, redoAvailable: stack.length > 1 }); return next.snapshot; },
  resetProject: (projectId) => set((state) => { const revisionsByProject = { ...state.revisionsByProject }; delete revisionsByProject[projectId]; const redoByProject = { ...state.redoByProject }; delete redoByProject[projectId]; return state.activeProjectId === projectId ? { ...initial, revisionsByProject, redoByProject, staleRevisionsByProject: state.staleRevisionsByProject } : { revisionsByProject, redoByProject }; }),
}), { name: 'shortsflow-editing', version: 3, storage: createPersistentStorage<PersistedEditingState>(), skipHydration: true, partialize: (state) => ({ revisionsByProject: state.revisionsByProject, staleRevisionsByProject: state.staleRevisionsByProject, activeProjectId: state.activeProjectId }),
  migrate: (persisted): PersistedEditingState => normalizePersistedEditingState(persisted),
  merge: (persisted, current) => { if (!persisted || typeof persisted !== 'object') return current; const value = normalizePersistedEditingState(persisted); const revisionsByProject = value.revisionsByProject; const staleRevisionsByProject = value.staleRevisionsByProject ?? {}; const activeProjectId = value.activeProjectId; const workingSnapshot = activeProjectId ? revisionsByProject[activeProjectId]?.at(-1)?.snapshot ?? null : null; return { ...current, revisionsByProject, staleRevisionsByProject, activeProjectId, workingSnapshot, currentRevisionId: workingSnapshot?.revisionId ?? null, undoAvailable: activeProjectId ? (revisionsByProject[activeProjectId]?.length ?? 0) > 1 : false }; } }));

function normalizePersistedEditingState(value: unknown): PersistedEditingState {
  if (!isRecord(value)) return { revisionsByProject: {}, staleRevisionsByProject: {}, activeProjectId: null };
  return { revisionsByProject: normalizeRevisionMap(value.revisionsByProject), staleRevisionsByProject: normalizeRevisionMap(value.staleRevisionsByProject),
    activeProjectId: typeof value.activeProjectId === 'string' ? value.activeProjectId : null };
}
function normalizeRevisionMap(value: unknown): Record<string, TimelineRevision[]> {
  if (!isRecord(value)) return {}; const result: Record<string, TimelineRevision[]> = {};
  for (const [projectId, entries] of Object.entries(value)) { if (!Array.isArray(entries)) continue; const revisions = entries.flatMap((entry) => normalizeRevision(entry, projectId)); if (revisions.length) result[projectId] = revisions.slice(-HISTORY_LIMIT); }
  return result;
}
function normalizeRevision(value: unknown, projectId: string): TimelineRevision[] {
  if (isTimelineRevision(value) && value.id === value.snapshot.revisionId && value.projectId === projectId && value.snapshot.projectId === projectId && value.snapshot.fingerprintVersion === MANIFEST_FINGERPRINT_VERSION && isTimelineSnapshotInternallyValid(value.snapshot)) return [value];
  return [];
}
function isTimelineRevision(value: unknown): value is TimelineRevision { return isRecord(value) && typeof value.id === 'string' && typeof value.projectId === 'string' &&
  (typeof value.parentRevisionId === 'string' || value.parentRevisionId === null) && typeof value.createdAt === 'string' && Array.isArray(value.operationIds) &&
  value.operationIds.every((id) => typeof id === 'string') && isRecord(value.snapshot) && typeof value.snapshot.projectId === 'string' &&
  typeof value.snapshot.revisionId === 'string' && typeof value.snapshot.manifestFingerprint === 'string' && typeof value.snapshot.fingerprintVersion === 'number' && isRenderManifest(value.snapshot.manifest); }
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
function isRenderManifest(value: unknown): value is RenderManifest { return isRecord(value) && value.schemaVersion === '1.4' && typeof value.projectId === 'string' && typeof value.durationMs === 'number' && isRecord(value.timeline) && Array.isArray(value.timeline.scenes) && isRecord(value.subtitles) && isRecord(value.audio); }
