import { create } from 'zustand';
import type { PlatformId, PlatformOptimizationPlan, PlatformOptimizationPreview, PlatformReadinessReport, PlatformVariantSnapshot } from '@/core/platform-optimization';

interface PlatformOptimizationState {
  activeProjectId: string | null; selectedPlatform: PlatformId; bindingFingerprint: string | null; bindingProfileVersion: string | null;
  currentPlan: PlatformOptimizationPlan | null; currentPreview: PlatformOptimizationPreview | null; readinessReports: Record<string, PlatformReadinessReport>;
  variantSnapshots: Record<string, PlatformVariantSnapshot>; revisionHistory: Record<string, PlatformVariantSnapshot[]>; redoStack: Record<string, PlatformVariantSnapshot[]>;
  approvedManualOperationIds: string[]; analysisStatus: 'idle' | 'analyzing' | 'ready' | 'error'; previewStatus: 'idle' | 'previewing' | 'ready' | 'error'; applyStatus: 'idle' | 'applying' | 'applied' | 'error'; lastError: string | null;
  setPlatform: (platform: PlatformId) => void; startAnalysis: (projectId: string, fingerprint?: string, profileVersion?: string) => void; setPlan: (plan: PlatformOptimizationPlan) => void; setPreview: (preview: PlatformOptimizationPreview) => void; setSnapshot: (snapshot: PlatformVariantSnapshot) => void; invalidateCurrentBinding: (message?: string) => void; undo: () => PlatformVariantSnapshot | null; redo: () => PlatformVariantSnapshot | null; setApproved: (ids: string[]) => void; fail: (message: string) => void; reset: () => void;
}

export const usePlatformOptimizationStore = create<PlatformOptimizationState>()((set, get) => ({
  activeProjectId: null, selectedPlatform: 'youtube-shorts', bindingFingerprint: null, bindingProfileVersion: null, currentPlan: null, currentPreview: null, readinessReports: {}, variantSnapshots: {}, revisionHistory: {}, redoStack: {}, approvedManualOperationIds: [], analysisStatus: 'idle', previewStatus: 'idle', applyStatus: 'idle', lastError: null,
  setPlatform: (selectedPlatform) => set({ selectedPlatform, currentPlan: null, currentPreview: null, approvedManualOperationIds: [], analysisStatus: 'idle', previewStatus: 'idle', lastError: null }),
  startAnalysis: (activeProjectId, bindingFingerprint, bindingProfileVersion) => set({ activeProjectId, bindingFingerprint: bindingFingerprint ?? null, bindingProfileVersion: bindingProfileVersion ?? null, analysisStatus: 'analyzing', lastError: null, currentPreview: null }),
  setPlan: (currentPlan) => set((state) => ({ activeProjectId: currentPlan.projectId, bindingFingerprint: currentPlan.sourceManifestFingerprint, bindingProfileVersion: currentPlan.profile.version, currentPlan, analysisStatus: 'ready', readinessReports: { ...state.readinessReports, [currentPlan.platformId]: currentPlan.readiness }, currentPreview: null, previewStatus: 'idle' })),
  setPreview: (currentPreview) => set({ currentPreview, previewStatus: 'ready' }),
  setSnapshot: (snapshot) => set((state) => { const key = `${snapshot.projectId}:${snapshot.platformId}`; if (snapshot.appliedOperationIds.length === 0) return { currentPreview: null, applyStatus: 'applied' }; const previous = state.revisionHistory[key] ?? []; const history = previous.some((item) => item.revisionId === snapshot.revisionId || item.manifest && JSON.stringify(item.manifest) === JSON.stringify(snapshot.manifest)) ? previous : [...previous, snapshot]; const bounded = history.slice(-12); return { currentPreview: null, variantSnapshots: { ...state.variantSnapshots, [key]: snapshot }, revisionHistory: { ...state.revisionHistory, [key]: bounded }, redoStack: { ...state.redoStack, [key]: [] }, applyStatus: 'applied' }; }),
  invalidateCurrentBinding: (lastError = 'Source manifest changed. Run platform analysis again.') => set({ currentPlan: null, currentPreview: null, approvedManualOperationIds: [], analysisStatus: 'idle', previewStatus: 'idle', applyStatus: 'idle', lastError }),
  undo: () => { const state = get(); const key = state.activeProjectId ? `${state.activeProjectId}:${state.selectedPlatform}` : ''; const history = [...(state.revisionHistory[key] ?? [])]; if (history.length < 2) return null; const current = history.pop()!; const target = history[history.length - 1]; set({ revisionHistory: { ...state.revisionHistory, [key]: history }, redoStack: { ...state.redoStack, [key]: [...(state.redoStack[key] ?? []), current] }, variantSnapshots: { ...state.variantSnapshots, [key]: target } }); return target; },
  redo: () => { const state = get(); const key = state.activeProjectId ? `${state.activeProjectId}:${state.selectedPlatform}` : ''; const stack = [...(state.redoStack[key] ?? [])]; const target = stack.pop(); if (!target) return null; set({ redoStack: { ...state.redoStack, [key]: stack }, revisionHistory: { ...state.revisionHistory, [key]: [...(state.revisionHistory[key] ?? []), target] }, variantSnapshots: { ...state.variantSnapshots, [key]: target } }); return target; },
  setApproved: (approvedManualOperationIds) => set({ approvedManualOperationIds, previewStatus: 'idle', currentPreview: null }),
  fail: (lastError) => set({ lastError, analysisStatus: 'error', previewStatus: 'error', applyStatus: 'error' }),
  reset: () => set({ currentPlan: null, currentPreview: null, approvedManualOperationIds: [], lastError: null, analysisStatus: 'idle', previewStatus: 'idle', applyStatus: 'idle' }),
}));
