import { describe, expect, it, vi } from 'vitest';
import { createExportJob, createExportPlan, createExportQueue, detectExportCapabilities, getExportPreset, listExportPresets, operationSignature, verifyArtifact } from '@/core/export-intelligence';
import { editingFixture } from '../editing/fixtures';
const capability = { ffmpeg: true, ffprobe: true, version: '6', encoders: ['libx264', 'libx265'], hardwareEncoders: ['h264_nvenc'], supports: { libx264: true, libx265: true }, raw: null, detectedAt: 'now' } as const;
async function manifest() { const result = await editingFixture(); result.manifest.validation = { ...(result.manifest.validation ?? {}), renderReady: true } as typeof result.manifest.validation; return result.manifest; }
describe('Epic 7.7 export intelligence', () => {
  it('exposes seven versioned presets', () => { expect(listExportPresets()).toHaveLength(7); expect(getExportPreset('tiktok').version).toBeTruthy(); });
  it.each(listExportPresets().map((preset) => preset.id))('plans preset %s deterministically', async (presetId) => { const source = await manifest(); const a = createExportPlan({ manifest: source, presetId, capabilities: capability, now: 'now' }); const b = createExportPlan({ manifest: source, presetId, capabilities: capability, now: 'now' }); expect(a).toEqual(b); expect(a.sourceManifestFingerprint).toBeTruthy(); });
  it.each(['libx264', 'libx265', 'h264_nvenc', 'h264_amf', 'h264_qsv', 'hevc_videotoolbox', 'libsvtav1', 'libvpx-vp9'])('planner keeps encoder capability decision for %s', async (encoder) => { const source = await manifest(); const plan = createExportPlan({ manifest: source, capabilities: { ...capability, encoders: [encoder], supports: { [encoder]: true } }, now: 'now' }); expect(plan.preset.encoder).toBeTruthy(); });
  it.each(Array.from({ length: 12 }, (_, index) => index))('verifies healthy artifact %s', async () => { const source = await manifest(); const plan = createExportPlan({ manifest: source, capabilities: capability }); const job = createExportJob(plan, source, 'out.mp4'); const result = verifyArtifact(job, { path: 'out.mp4', sizeBytes: 100, durationMs: source.durationMs, verified: false, diagnostics: { width: source.render.width, height: source.render.height, videoCodec: plan.preset.videoCodec, audioPresent: true }, createdAt: 'now' }); expect(result.valid).toBe(true); });
  it.each(['zero', 'duration', 'resolution', 'codec', 'audio', 'corruption'])('reports verification failure: %s', async (kind) => { const source = await manifest(); const plan = createExportPlan({ manifest: source, capabilities: capability }); const job = createExportJob(plan, source, 'out.mp4'); const diagnostics = kind === 'duration' ? { durationMs: 1 } : kind === 'resolution' ? { width: 1, height: 1 } : kind === 'codec' ? { videoCodec: 'vp9' } : kind === 'audio' ? { audioPresent: false } : kind === 'corruption' ? { corruption: true } : {}; const result = verifyArtifact(job, { path: 'out.mp4', sizeBytes: kind === 'zero' ? 0 : 100, durationMs: source.durationMs, verified: false, diagnostics, createdAt: 'now' }); expect(result.valid).toBe(false); });
  it('canonical operation signatures are order independent', () => { expect(operationSignature(['b', 'a'])).toBe(operationSignature(['a', 'b'])); });
  it('blocks unvalidated manifests', async () => { const source = await manifest(); source.validation = null; const plan = createExportPlan({ manifest: source, capabilities: capability }); expect(plan.blockingIssues).toHaveLength(1); });
  it('estimates size and render time from duration and preset', async () => { const source = await manifest(); const plan = createExportPlan({ manifest: source, presetId: 'archive', capabilities: capability }); expect(plan.estimatedSizeBytes).toBeGreaterThan(0); expect(plan.estimatedRenderMs).toBeGreaterThan(0); });
  it('queue executes jobs in insertion order and reports completion', async () => { const source = await manifest(); const plan = createExportPlan({ manifest: source, capabilities: capability }); const seen: string[] = []; const queue = createExportQueue({ async run(job) { seen.push(job.id); return { path: job.outputPath, sizeBytes: 10, durationMs: job.manifest.durationMs, verified: false, diagnostics: {}, createdAt: 'now' }; }, cancel: async () => true }); queue.enqueue(createExportJob(plan, source, 'a')); queue.enqueue(createExportJob({ ...plan, id: `${plan.id}-b` }, source, 'b')); await queue.start(); expect(seen).toHaveLength(2); expect(queue.list().every((job) => job.state === 'completed')).toBe(true); });
  it('queue retries a retryable job', async () => { const source = await manifest(); const plan = createExportPlan({ manifest: source, capabilities: capability }); let attempts = 0; const queue = createExportQueue({ async run(job) { attempts += 1; if (attempts === 1) throw new Error('temporary'); return { path: job.outputPath, sizeBytes: 1, durationMs: job.manifest.durationMs, verified: false, diagnostics: {}, createdAt: 'now' }; }, cancel: async () => true }); const job = createExportJob(plan, source, 'retry', 2); queue.enqueue(job); await queue.start(); expect(queue.get(job.id)?.state).toBe('failed'); await queue.retry(job.id); expect(attempts).toBe(2); });
  it('queue cancel delegates active cancellation', async () => { const source = await manifest(); const plan = createExportPlan({ manifest: source, capabilities: capability }); const cancel = vi.fn(async () => true); const queue = createExportQueue({ run: async (job) => new Promise((resolve) => setTimeout(() => resolve({ path: job.outputPath, sizeBytes: 1, durationMs: 1, verified: false, diagnostics: {}, createdAt: 'now' }), 20)), cancel }); const job = createExportJob(plan, source, 'cancel'); queue.enqueue(job); const running = queue.start(); await new Promise((resolve) => setTimeout(resolve, 1)); await queue.cancel(job.id); await running; expect(cancel).toHaveBeenCalledWith(job.id); });
  it('pause and resume preserve deterministic queue state', async () => { const source = await manifest(); const plan = createExportPlan({ manifest: source, capabilities: capability }); const queue = createExportQueue({ run: async (job) => ({ path: job.outputPath, sizeBytes: 1, durationMs: 1, verified: false, diagnostics: {}, createdAt: 'now' }), cancel: async () => true }); queue.pause(); await queue.start(); expect(queue.snapshot().paused).toBe(true); queue.resume(); await new Promise((resolve) => setTimeout(resolve, 5)); expect(queue.snapshot().jobs).toHaveLength(0); });
  it.each(['container', 'videoCodec', 'audioCodec', 'pixelFormat', 'bitrateKbps', 'audioBitrateKbps', 'sampleRate', 'frameRate', 'encoder', 'hardware', 'threads', 'gopFrames', 'quality', 'platformId', 'projectId', 'fingerprint', 'estimatedSize', 'estimatedDuration', 'estimatedRender', 'warnings'])('planner exposes deterministic %s contract', async (field) => { const source = await manifest(); const plan = createExportPlan({ manifest: source, platformId: 'tiktok', capabilities: capability, now: 'now' }); const values: Record<string, unknown> = { container: plan.preset.container, videoCodec: plan.preset.videoCodec, audioCodec: plan.preset.audioCodec, pixelFormat: plan.preset.pixelFormat, bitrateKbps: plan.preset.bitrateKbps, audioBitrateKbps: plan.preset.audioBitrateKbps, sampleRate: plan.preset.sampleRate, frameRate: plan.preset.frameRate, encoder: plan.preset.encoder, hardware: plan.preset.hardware, threads: plan.preset.threads, gopFrames: plan.preset.gopFrames, quality: plan.preset.quality, platformId: plan.platformId, projectId: plan.projectId, fingerprint: plan.sourceManifestFingerprint, estimatedSize: plan.estimatedSizeBytes, estimatedDuration: plan.estimatedDurationMs, estimatedRender: plan.estimatedRenderMs, warnings: plan.warnings }; expect(values[field]).toBeDefined(); });
});
