import { describe, expect, it } from 'vitest';
import { createExportJob, createExportPlan, createExportQueue, normalizeHydratedExportQueue, serializeExportQueue } from '@/core/export-intelligence';
import { editingFixture } from '../editing/fixtures';

async function setup() { const result = await editingFixture(); result.manifest.validation = { ...(result.manifest.validation ?? {}), renderReady: true } as typeof result.manifest.validation; const plan = createExportPlan({ manifest: result.manifest, capabilities: { ffmpeg: true, ffprobe: true, version: '6', encoders: ['libx264'], hardwareEncoders: [], supports: { libx264: true }, raw: null, detectedAt: 'now' } }); return { manifest: result.manifest, plan }; }

describe('export queue restart recovery', () => {
  it('normalizes in-flight jobs to interrupted without restoring active state', async () => { const { manifest, plan } = await setup(); const rendering = createExportJob(plan, manifest, 'rendering.mp4'); rendering.state = 'rendering'; const verifying = createExportJob({ ...plan, id: `${plan.id}-v` }, manifest, 'verifying.mp4'); verifying.state = 'verifying'; const snapshot = normalizeHydratedExportQueue(serializeExportQueue({ jobs: [rendering, verifying], activeJobId: rendering.id, paused: false })); expect(snapshot.activeJobId).toBeNull(); expect(snapshot.jobs.map((job) => job.state)).toEqual(['interrupted', 'interrupted']); });
  it('retries interrupted jobs in place and does not duplicate FIFO entries', async () => { const { manifest, plan } = await setup(); const job = createExportJob(plan, manifest, 'recover.mp4'); job.state = 'interrupted'; const queue = createExportQueue({ run: async (current) => ({ path: current.outputPath, sizeBytes: 10, durationMs: current.manifest.durationMs, verified: false, diagnostics: {}, createdAt: 'now' }), cancel: async () => true }); queue.hydrate({ jobs: [job], activeJobId: job.id, paused: false }); const retried = await queue.retry(job.id); expect(retried?.id).toBe(job.id); expect(queue.list()).toHaveLength(1); await new Promise((resolve) => setTimeout(resolve, 0)); expect(queue.get(job.id)?.state).toBe('completed'); });
  it('drops malformed and duplicate records without failing hydration', async () => { const { manifest, plan } = await setup(); const job = createExportJob(plan, manifest, 'valid.mp4'); const snapshot = normalizeHydratedExportQueue({ version: 1, savedAt: 'now', snapshot: { jobs: [job, job, { id: 'corrupt' } as never], activeJobId: 'corrupt', paused: false } }); expect(snapshot.jobs).toHaveLength(1); expect(normalizeHydratedExportQueue({ version: 99, savedAt: 'now', snapshot: snapshot } as never).jobs).toHaveLength(0); });
});
