import { canonicalSerialize } from '@/core/editing/manifestFingerprint';
import { createManifestRevisionId, createTimelineSnapshot, MANIFEST_FINGERPRINT_VERSION, type TimelineRevision, type TimelineSnapshot } from '@/core/editing';
import { deepClone, stableId } from '@/core/editing/utils';
import { calculateSubtitleMetrics, type RenderManifest, type SubtitleCue } from '@/core/media';
import { analyzeHighlights, analyzeSubtitleCues, planSubtitleOperations, subtitleScores } from './analyzers';
import { getSubtitleCapability, subtitleOperationSupport } from './capabilities';
import { resolveCaptionProfile } from './profiles';
import { evaluateSplitEligibility } from './splitEligibility';
import type { CaptionStyleProfile, SubtitleIntelligenceEngine, SubtitleIntelligencePlan, SubtitleIntelligencePreview, SubtitleIntelligenceResult, SubtitleOperation, SubtitleOperationResult } from './types';

export function createSubtitleIntelligenceEngine(): SubtitleIntelligenceEngine { return { analyze, preview, apply }; }

function analyze(input: { manifest: RenderManifest; snapshot: TimelineSnapshot; profile?: CaptionStyleProfile }, signal?: AbortSignal): SubtitleIntelligencePlan { assertNotAborted(signal); validateSnapshot(input.snapshot); if (input.snapshot.manifestFingerprint !== createManifestRevisionId(input.manifest)) throw new Error('Subtitle analysis source does not match the canonical manifest fingerprint.'); const profile = input.profile ?? 'shorts'; const cues = analyzeSubtitleCues(input.manifest); const highlights = analyzeHighlights(input.manifest); const animationSupported = subtitleOperationSupport('animation', { animation: input.manifest.subtitles.style.animation }) === 'implemented'; const scores = subtitleScores(cues, highlights, animationSupported); const createdAt = new Date().toISOString(); const operations = planSubtitleOperations(input.manifest, profile, cues, highlights); assertNotAborted(signal); return { id: stableId('subtitle-plan', `${input.snapshot.revisionId}|${profile}|${canonicalSerialize({ scores, operations })}`), version: '1.0', projectId: input.manifest.projectId, sourceRevisionId: input.snapshot.revisionId, sourceManifestFingerprint: input.snapshot.manifestFingerprint, createdAt, profile, scores, cues, highlights, operations }; }

function preview(plan: SubtitleIntelligencePlan, snapshot: TimelineSnapshot, approvedIds: readonly string[], signal?: AbortSignal): SubtitleIntelligencePreview { assertNotAborted(signal); validateSource(plan, snapshot); const approved = canonicalIds(approvedIds); const transformed = transform(plan, snapshot, approved); const applied = transformed.operationResults.filter((item) => item.status === 'applied'); const warnings = transformed.operationResults.filter((item) => item.status !== 'applied').map((item) => `${item.type}: ${item.diagnostic}`); const affectedCueIds = [...new Set(applied.flatMap((item) => item.affectedCueIds))].sort(); const rerenderSceneIds = [...new Set(affectedCueIds.map((id) => transformed.snapshot.manifest.subtitles.cues.find((cue) => cue.id === id)?.sceneId).filter((id): id is string => Boolean(id)))].sort(); const approvalSignature = signature(approved); const estimatedScore = Math.min(100, plan.scores.overall + applied.reduce((sum, item) => sum + (plan.operations.find((operation) => operation.id === item.operationId)?.expectedImpact ?? 0), 0)); assertNotAborted(signal); return { id: stableId('subtitle-preview', `${plan.id}|${snapshot.revisionId}|${approvalSignature}|${transformed.snapshot.revisionId}`), projectId: plan.projectId, planId: plan.id, sourceRevisionId: snapshot.revisionId, sourceManifestFingerprint: snapshot.manifestFingerprint, approvalSignature, approvedOperationIds: approved, operationResults: transformed.operationResults, estimatedScore, affectedCueIds, rerenderSceneIds, warnings, proposedSnapshot: transformed.snapshot }; }

function apply(plan: SubtitleIntelligencePlan, previewValue: SubtitleIntelligencePreview, snapshot: TimelineSnapshot, approvedIds: readonly string[]): SubtitleIntelligenceResult { validateSource(plan, snapshot); const approved = canonicalIds(approvedIds); if (previewValue.planId !== plan.id || previewValue.sourceRevisionId !== snapshot.revisionId || previewValue.sourceManifestFingerprint !== snapshot.manifestFingerprint || previewValue.approvalSignature !== signature(approved)) throw new Error('Subtitle selections changed; create a current preview before applying.'); const transformed = transform(plan, snapshot, approved); if (transformed.snapshot.manifestFingerprint !== previewValue.proposedSnapshot.manifestFingerprint || canonicalSerialize(transformed.operationResults) !== canonicalSerialize(previewValue.operationResults)) throw new Error('Subtitle preview no longer matches the deterministic transform.'); return { projectId: plan.projectId, appliedOperationIds: transformed.operationResults.filter((item) => item.status === 'applied').map((item) => item.operationId), skippedOperationIds: transformed.operationResults.filter((item) => item.status !== 'applied').map((item) => item.operationId), operationResults: transformed.operationResults, previousRevision: revision(snapshot, []), revision: revision(transformed.snapshot, transformed.operationResults.filter((item) => item.status === 'applied').map((item) => item.operationId)) }; }

function transform(plan: SubtitleIntelligencePlan, snapshot: TimelineSnapshot, approved: readonly string[]) { const manifest = deepClone(snapshot.manifest); const results: SubtitleOperationResult[] = []; const remap = new Map<string, string[]>(); const selected = plan.operations.filter((operation) => approved.includes(operation.id) && operation.status !== 'disabled').sort((left, right) => operationOrder(left.type) - operationOrder(right.type)); for (const operation of selected) { const capability = getSubtitleCapability(operation.type); const support = subtitleOperationSupport(operation.type, operation.parameters); if (support !== 'implemented' || capability.support !== 'implemented') { results.push(result(operation, 'planned-only', capability.diagnostic, [])); continue; } const applied = applyOperation(manifest, operation, remap); if (!applied.affected.length) { results.push(result(operation, 'rejected', 'Operation would not change the canonical subtitle timeline or style.', [])); continue; } for (const [sourceId, targetIds] of applied.remap) remap.set(sourceId, targetIds); results.push(result(operation, 'applied', capability.diagnostic, applied.affected)); }
  if (!results.some((item) => item.status === 'applied')) return { snapshot, operationResults: results };
  manifest.subtitles.metrics = calculateSubtitleMetrics(manifest.subtitles.words, manifest.subtitles.cues, manifest.subtitles.durationMs); manifest.validation = null; const fingerprint = createManifestRevisionId(manifest); const revisionId = stableId('revision', `${snapshot.revisionId}|subtitle|${results.filter((item) => item.status === 'applied').map((item) => item.operationId).join('|')}|${fingerprint}`); return { snapshot: createTimelineSnapshot(manifest, revisionId, snapshot.revisionId, plan.createdAt), operationResults: results };
}

function applyOperation(manifest: RenderManifest, operation: SubtitleOperation, remap: Map<string, string[]>): { affected: string[]; remap: Map<string, string[]> } { const targets = resolveCueTargets(manifest, operation, remap); const cue = targets[0]; if (operation.type === 'resize') return changed(updateStyle(manifest, 'fontSize', clamp(number(operation.parameters.fontSize), 36, 96))); if (operation.type === 'stroke') return changed(updateStyle(manifest, 'strokeWidth', clamp(number(operation.parameters.strokeWidth), 0, 8))); if (operation.type === 'shadow') return changed(updateStyle(manifest, 'shadowDepth', clamp(number(operation.parameters.shadowDepth), 0, 6))); if (operation.type === 'reposition') return changed(updateStyle(manifest, 'position', position(operation.parameters.position))); if (operation.type === 'animation') return changed(updateStyle(manifest, 'animation', String(operation.parameters.animation) as RenderManifest['subtitles']['style']['animation'])); if (operation.type === 'restyle') { const profile = resolveCaptionProfile(String(operation.parameters.profile) as CaptionStyleProfile); const before = canonicalSerialize(manifest.subtitles.style); manifest.subtitles.style = { ...manifest.subtitles.style, ...profile }; return changed(before === canonicalSerialize(manifest.subtitles.style) ? [] : manifest.subtitles.cues.map((item) => item.id)); } if (!cue) return changed([]);
  if (operation.type === 'highlight-keyword') { const wordId = String(operation.parameters.wordId); const target = targets.find((item) => item.wordIds.includes(wordId)); if (!target || target.emphasisWordIds.includes(wordId)) return changed([]); manifest.subtitles.cues = manifest.subtitles.cues.map((item) => item.id === target.id ? { ...item, emphasisWordIds: [...item.emphasisWordIds, wordId].sort() } : item); return changed([target.id]); }
  if (operation.type === 'timing-adjust') { const scene = manifest.timeline.scenes.find((item) => item.id === cue.sceneId); if (!scene) return changed([]); const minimum = clamp(number(operation.parameters.minimumDurationMs), 400, 1500); const maximum = clamp(number(operation.parameters.maximumDurationMs), 2500, 7000); const startMs = Math.max(scene.startMs, cue.startMs - clamp(number(operation.parameters.leadMs), 0, 250)); const desiredEnd = Math.max(cue.endMs + clamp(number(operation.parameters.tailMs), 0, 350), startMs + minimum); const endMs = Math.min(scene.endMs, startMs + maximum, desiredEnd); if (startMs === cue.startMs && endMs === cue.endMs) return changed([]); manifest.subtitles.cues = manifest.subtitles.cues.map((item) => item.id === cue.id ? { ...item, startMs, endMs, durationMs: endMs - startMs } : item); return changed([cue.id]); }
  if (operation.type === 'split-subtitle') { const split = splitCue(manifest, cue, number(operation.parameters.maxCharactersPerLine) || manifest.subtitles.style.maxCharactersPerLine); return { affected: split.affected, remap: new Map([[cue.id, split.ids]]) }; }
  if (operation.type === 'merge-subtitle') { const nextId = String(operation.parameters.nextCueId); const merged = mergeCue(manifest, cue, nextId); return { affected: merged.affected, remap: merged.ids.length ? new Map([[cue.id, merged.ids], [nextId, merged.ids]]) : new Map() }; }
  return changed([]);
}
function splitCue(manifest: RenderManifest, cue: SubtitleCue, maxCharactersPerLine: number): { ids: string[]; affected: string[] } { const eligibility = evaluateSplitEligibility(cue, manifest.subtitles.words, maxCharactersPerLine); if (!eligibility.eligible || eligibility.splitAt === null) return { ids: [], affected: [] }; const splitAt = eligibility.splitAt; const wordMap = new Map(manifest.subtitles.words.map((word) => [word.id, word])); const leftIds = cue.wordIds.slice(0, splitAt); const rightIds = cue.wordIds.slice(splitAt); const make = (ids: readonly string[], suffix: string): SubtitleCue => { const words = ids.map((id) => wordMap.get(id)!); return { ...cue, id: stableId('subtitle-cue', `${cue.id}|${suffix}`), text: words.map((word) => word.text).join(' '), startMs: words[0].startMs, endMs: words.at(-1)!.endMs, durationMs: words.at(-1)!.endMs - words[0].startMs, wordIds: [...ids], lineCount: 1, emphasisWordIds: cue.emphasisWordIds.filter((id) => ids.includes(id)) }; }; const replacements = [make(leftIds, 'a'), make(rightIds, 'b')]; manifest.subtitles.cues = manifest.subtitles.cues.flatMap((item) => item.id === cue.id ? replacements : [item]); return { ids: replacements.map((item) => item.id), affected: replacements.map((item) => item.id) }; }
function mergeCue(manifest: RenderManifest, cue: SubtitleCue, nextId: string): { ids: string[]; affected: string[] } { const ordered = [...manifest.subtitles.cues].sort((a, b) => a.startMs - b.startMs); const index = ordered.findIndex((item) => item.id === cue.id); const next = ordered[index + 1]?.id === nextId ? ordered[index + 1] : undefined; if (!next || next.sceneId !== cue.sceneId || next.startMs - cue.endMs > 250) return { ids: [], affected: [] }; const merged: SubtitleCue = { ...cue, id: stableId('subtitle-cue', `${cue.id}|${next.id}`), text: `${cue.text} ${next.text}`, endMs: next.endMs, durationMs: next.endMs - cue.startMs, wordIds: [...cue.wordIds, ...next.wordIds], lineCount: Math.min(2, cue.lineCount + next.lineCount), emphasisWordIds: [...new Set([...cue.emphasisWordIds, ...next.emphasisWordIds])].sort() }; manifest.subtitles.cues = manifest.subtitles.cues.filter((item) => item.id !== cue.id && item.id !== next.id).concat(merged).sort((a, b) => a.startMs - b.startMs); return { ids: [merged.id], affected: [merged.id] }; }
function resolveCueTargets(manifest: RenderManifest, operation: SubtitleOperation, remap: Map<string, string[]>): SubtitleCue[] { if (!operation.cueId) return []; const ids = remap.get(operation.cueId) ?? [operation.cueId]; const candidates = ids.map((id) => manifest.subtitles.cues.find((item) => item.id === id)).filter((item): item is SubtitleCue => Boolean(item)); if (operation.type !== 'highlight-keyword') return candidates.slice(0, 1); const wordId = String(operation.parameters.wordId); return candidates.filter((item) => item.wordIds.includes(wordId)); }
function changed(affected: string[]): { affected: string[]; remap: Map<string, string[]> } { return { affected, remap: new Map() }; }
function operationOrder(type: SubtitleOperation['type']): number { return type === 'split-subtitle' || type === 'merge-subtitle' ? 0 : type === 'highlight-keyword' ? 2 : 1; }
function updateStyle<K extends keyof RenderManifest['subtitles']['style']>(manifest: RenderManifest, key: K, value: RenderManifest['subtitles']['style'][K]): string[] { if (manifest.subtitles.style[key] === value) return []; manifest.subtitles.style = { ...manifest.subtitles.style, [key]: value }; return manifest.subtitles.cues.map((cue) => cue.id); }
function result(operation: SubtitleOperation, status: SubtitleOperationResult['status'], diagnostic: string, affectedCueIds: readonly string[]): SubtitleOperationResult { return { operationId: operation.id, type: operation.type, support: subtitleOperationSupport(operation.type, operation.parameters), status, diagnostic, affectedCueIds }; }
function validateSource(plan: SubtitleIntelligencePlan, snapshot: TimelineSnapshot) { validateSnapshot(snapshot); if (snapshot.projectId !== plan.projectId || snapshot.revisionId !== plan.sourceRevisionId || snapshot.manifestFingerprint !== plan.sourceManifestFingerprint) throw new Error('Stale subtitle intelligence plan; analyze the current manifest again.'); }
function validateSnapshot(snapshot: TimelineSnapshot) { if (snapshot.fingerprintVersion !== MANIFEST_FINGERPRINT_VERSION || createManifestRevisionId(snapshot.manifest) !== snapshot.manifestFingerprint) throw new Error('Subtitle intelligence requires a current canonical manifest fingerprint.'); }
function revision(snapshot: TimelineSnapshot, operationIds: readonly string[]): TimelineRevision { return { id: snapshot.revisionId, projectId: snapshot.projectId, parentRevisionId: snapshot.parentRevisionId, createdAt: snapshot.createdAt, operationIds, snapshot }; }
function canonicalIds(ids: readonly string[]): string[] { return [...new Set(ids)].sort(); } function signature(ids: readonly string[]): string { return stableId('subtitle-approval', canonicalSerialize(canonicalIds(ids))); }
function position(value: unknown): 'top' | 'center' | 'bottom' { return value === 'top' || value === 'center' ? value : 'bottom'; } function number(value: unknown): number { return typeof value === 'number' && Number.isFinite(value) ? value : 0; } function clamp(value: number, min: number, max: number): number { return Math.min(max, Math.max(min, value)); }
function assertNotAborted(signal?: AbortSignal) { if (!signal?.aborted) return; const error = new Error('Subtitle intelligence request was superseded.'); error.name = 'AbortError'; throw error; }
