import type { RenderManifest } from '@/core/media';
import type { TimelineRevision, TimelineSnapshot } from '@/core/editing';

export type VisualMetric = 'composition' | 'motion' | 'continuity' | 'quality' | 'hook' | 'readability';
export type VisualOperationType = 'crop' | 'reframe' | 'stabilize' | 'brightness' | 'contrast' | 'zoom' | 'slow-zoom' | 'color-grade' | 'overlay' | 'background-blur';
export type VisualOperationScope = 'scene' | 'asset-global';
export type VisualOperationSupport = 'implemented' | 'planned-only' | 'unsupported';
export type VisualOperationExecutionStatus = 'applied' | 'planned-only' | 'skipped' | 'rejected';
export interface VisualOperationCapability { readonly type: VisualOperationType; readonly support: VisualOperationSupport; readonly renderEffect: boolean; readonly label: string; readonly diagnostic: string; }
export interface VisualOperationResult { readonly operationId: string; readonly sceneId: string; readonly type: VisualOperationType; readonly scope: VisualOperationScope; readonly support: VisualOperationSupport; readonly status: VisualOperationExecutionStatus; readonly diagnostic: string; }
export type ColorGradeStyle = 'cinematic' | 'vibrant' | 'documentary' | 'social' | 'dramatic';
export interface VisualEvidence { readonly rule: string; readonly value: number | string | boolean; readonly threshold: string; readonly explanation: string; }
export interface VisualSceneAnalysis { readonly sceneId: string; readonly composition: number; readonly motion: number; readonly continuity: number; readonly quality: number; readonly hook: number; readonly readability: number; readonly risks: readonly string[]; readonly evidence: readonly VisualEvidence[]; }
export interface BrollOpportunity { readonly sceneId: string; readonly mode: 'insert' | 'overlay' | 'cutaway'; readonly score: number; readonly reason: string; }
export interface ColorGradePlan { readonly style: ColorGradeStyle; readonly intensity: number; readonly reason: string; readonly parameters: Readonly<{ brightness: number; saturation: number; contrast: number; gamma: number }>; }
export interface VisualRecommendation { readonly id: string; readonly sceneId: string; readonly metric: VisualMetric; readonly priority: 'low' | 'medium' | 'high' | 'critical'; readonly title: string; readonly explanation: string; readonly expectedImpact: number; }
export interface VisualOperation { readonly id: string; readonly sceneId: string; readonly type: VisualOperationType; readonly scope: VisualOperationScope; readonly support: VisualOperationSupport; readonly reason: string; readonly parameters: Readonly<Record<string, string | number | boolean>>; readonly expectedImpact: number; readonly automaticallyApplicable: boolean; readonly status: 'proposed' | 'disabled' | 'applied' | 'skipped'; }
export interface VisualScores { readonly overall: number; readonly composition: number; readonly motion: number; readonly continuity: number; readonly quality: number; readonly hook: number; readonly readability: number; }
export interface VisualProductionPlan { readonly id: string; readonly version: '1.0'; readonly projectId: string; readonly sourceRevisionId: string; readonly sourceManifestFingerprint: string; readonly createdAt: string; readonly platform: 'generic' | 'youtube-shorts' | 'tiktok' | 'instagram-reels'; readonly scores: VisualScores; readonly scenes: readonly VisualSceneAnalysis[]; readonly broll: readonly BrollOpportunity[]; readonly colorGrade: ColorGradePlan; readonly recommendations: readonly VisualRecommendation[]; readonly operations: readonly VisualOperation[]; }
export interface VisualExposureEstimate { readonly sceneId: string; readonly operationId: string; readonly before: number; readonly after: number; readonly delta: number; }
export interface VisualColorGradeEstimate { readonly sceneId: string; readonly operationId: string; readonly style: ColorGradeStyle; readonly intensity: number; readonly before: Readonly<{ brightness: 0; contrast: 1; saturation: 1; gamma: 1 }>; readonly after: Readonly<{ brightness: number; contrast: number; saturation: number; gamma: number }>; }
export interface VisualProductionPreview { readonly id: string; readonly projectId: string; readonly planId: string; readonly planSignature: string; readonly sourceRevisionId: string; readonly sourceManifestFingerprint: string; readonly approvalSignature: string; readonly approvedOperationIds: readonly string[]; readonly operationCount: number; readonly affectedScenes: readonly string[]; readonly estimatedScore: number; readonly rerenderSceneIds: readonly string[]; readonly reusableSceneIds: readonly string[]; readonly operationResults: readonly VisualOperationResult[]; readonly exposureEstimates: readonly VisualExposureEstimate[]; readonly colorGradeEstimates: readonly VisualColorGradeEstimate[]; readonly warnings: readonly string[]; readonly proposedSnapshot: TimelineSnapshot; }
export interface VisualProductionResult { readonly projectId: string; readonly appliedOperationIds: readonly string[]; readonly skippedOperationIds: readonly string[]; readonly operationResults: readonly VisualOperationResult[]; readonly previousRevision: TimelineRevision; readonly revision: TimelineRevision; }
export interface VisualProductionInput { readonly manifest: RenderManifest; readonly snapshot: TimelineSnapshot; readonly platform?: VisualProductionPlan['platform']; }
export interface VisualProductionEngine { analyze(input: VisualProductionInput, signal?: AbortSignal): VisualProductionPlan; preview(plan: VisualProductionPlan, snapshot: TimelineSnapshot, approvedOperationIds: readonly string[], signal?: AbortSignal): VisualProductionPreview; apply(plan: VisualProductionPlan, preview: VisualProductionPreview, snapshot: TimelineSnapshot, approvedOperationIds: readonly string[]): VisualProductionResult; }
