import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createManifestRevisionId, createTimelineSnapshot } from '@/core/editing';
import { createSceneFingerprint } from '@/core/render/sceneFingerprint';
import { buildSceneSegmentCommand } from '@/core/render/segmentCommandBuilder';
import { buildSceneSubtitleRenderPlan, subtitleVerticalMargin } from '@/core/render/subtitleRenderBuilder';
import { DEFAULT_RENDER_PRESET } from '@/core/render/types';
import { analyzeHighlights, breakSubtitleLines, createSubtitleIntelligenceEngine, evaluateSplitEligibility, getSubtitleCapability, normalizeSubtitleText, subtitleOperationSupport, type SubtitleOperation } from '@/core/subtitle-intelligence';
import { editingFixture } from '../editing/fixtures';

async function setup() { const fixture = await editingFixture(); const manifest = structuredClone(fixture.manifest); const snapshot = createTimelineSnapshot(manifest, createManifestRevisionId(manifest)); const engine = createSubtitleIntelligenceEngine(); const plan = engine.analyze({ manifest, snapshot, profile: 'shorts' }); return { ...fixture, manifest, snapshot, engine, plan }; }
describe('subtitle intelligence deterministic analysis', () => {
  it('normalizes Turkish text without corrupting English behavior', () => { expect(normalizeSubtitleText('İZLE, ÇÜNKÜ')).toBe('izle, çünkü'); expect(normalizeSubtitleText('IMPORTANT', 'en')).toBe('important'); });
  it('breaks cues by word, character, duration and punctuation without orphan lines', async () => { const { manifest } = await setup(); const result = breakSubtitleLines(manifest.subtitles.words, { maxCharactersPerLine: 18, maxWordsPerCue: 5, maxDurationMs: 2200 }); expect(result.cues.length).toBeGreaterThan(1); expect(result.cues.every((cue) => cue.wordIds.length <= 5 && cue.durationMs <= 2300 && cue.lineCount <= 2)).toBe(true); expect(result.cues.flatMap((cue) => cue.text.split('\n')).every((line) => line.trim().split(/\s+/).length !== 1 || !cueHasAlternative(line))).toBe(true); });
  it('treats Unicode ellipsis as a punctuation boundary', async () => { const { manifest } = await setup(); const words = manifest.subtitles.words.slice(0, 4).map((word, index) => ({ ...word, text: index === 1 ? 'devam…' : `kelime${index}`, normalizedText: index === 1 ? 'devam…' : `kelime${index}` })); const result = breakSubtitleLines(words, { maxCharactersPerLine: 80, maxWordsPerCue: 10, maxDurationMs: 5000 }); expect(result.cues).toHaveLength(2); expect(result.cues[0].text).toContain('devam…'); });
  it('uses the shared eligibility rule to apply an oversized three-word split', async () => { const state = await setup(); const scene = state.manifest.timeline.scenes[0]; const cue = state.manifest.subtitles.cues.find((item) => item.sceneId === scene.id)!; const words = state.manifest.subtitles.words.slice(0, 3); const texts = ['abcdefghijkl', 'mnopqrstuvw', 'abcdefghijklmnopqrstuvwx']; words.forEach((word, index) => { word.text = texts[index]; word.normalizedText = texts[index]; word.startMs = scene.startMs + index * 500; word.endMs = word.startMs + 400; word.durationMs = 400; }); cue.wordIds = words.map((word) => word.id); cue.text = texts.join(' '); cue.startMs = scene.startMs; cue.endMs = words.at(-1)!.endMs; cue.durationMs = cue.endMs - cue.startMs; cue.lineCount = 1; const eligibility = evaluateSplitEligibility(cue, state.manifest.subtitles.words, 24); expect(eligibility.eligible).toBe(true); expect([1, 2]).toContain(eligibility.splitAt); const snapshot = createTimelineSnapshot(state.manifest, createManifestRevisionId(state.manifest)); const plan = state.engine.analyze({ manifest: state.manifest, snapshot, profile: 'shorts' }); const split = plan.operations.find((operation) => operation.type === 'split-subtitle' && operation.cueId === cue.id)!; expect(split).toBeDefined(); const preview = state.engine.preview(plan, snapshot, [split.id]); expect(preview.operationResults[0].status).toBe('applied'); const applied = state.engine.apply(plan, preview, snapshot, [split.id]); expect(applied.operationResults[0].status).toBe('applied'); expect(applied.operationResults[0].affectedCueIds).toHaveLength(2); });
  it('produces explainable timing, typography, density, readability and safe-area scores', async () => { const { plan } = await setup(); expect(plan.scores.overall).toBeGreaterThanOrEqual(0); expect(plan.cues[0].evidence.map((item) => item.rule)).toEqual(expect.arrayContaining(['cue-duration', 'reading-speed', 'screen-coverage', 'safe-area-overlap'])); });
  it('detects numeric, percentage, money, date, question, exclamation and CTA highlights', async () => { const state = await setup(); const words = state.manifest.subtitles.words; const cue = state.manifest.subtitles.cues[0]; const samples = ['100', '25%', '₺500', '12/08/2026', 'hemen!', 'takip', 'neden?']; samples.forEach((text, index) => { words[index].text = text; words[index].normalizedText = text.replace(/[!?]/g, ''); }); cue.text = samples.join(' '); cue.wordIds = words.slice(0, samples.length).map((word) => word.id); const snapshot = createTimelineSnapshot(state.manifest, createManifestRevisionId(state.manifest)); const plan = state.engine.analyze({ manifest: state.manifest, snapshot }); expect(plan.highlights.map((item) => item.category)).toEqual(expect.arrayContaining(['number', 'percentage', 'money', 'date', 'exclamation', 'cta', 'question'])); });
  it('matches real Turkish CTA and Unicode currency literals without prefix false positives', async () => { const state = await setup(); const words = state.manifest.subtitles.words; const cue = state.manifest.subtitles.cues[0]; const samples = ['paylaş', 'PAYLAŞ', 'tıkla', 'TIKLA', 'paylaşım', '10₺', '₺10', '25', '€', '£', '…']; samples.forEach((text, index) => { words[index].text = text; words[index].normalizedText = normalizeSubtitleText(text); }); cue.text = samples.join(' '); cue.wordIds = words.slice(0, samples.length).map((word) => word.id); const highlights = analyzeHighlights(state.manifest); expect(highlights.filter((item) => item.category === 'cta').map((item) => item.text)).toEqual(expect.arrayContaining(['paylaş', 'PAYLAŞ', 'tıkla', 'TIKLA'])); expect(highlights.filter((item) => item.category === 'cta').map((item) => item.text)).not.toContain('paylaşım'); expect(highlights.filter((item) => item.category === 'money').map((item) => item.text)).toEqual(expect.arrayContaining(['10₺', '₺10', '€', '£'])); });
  it('validates subtitle analyzer source as UTF-8 without forbidden mojibake', () => { for (const file of ['src/core/subtitle-intelligence/analyzers.ts', 'src/core/subtitle-intelligence/lineBreaker.ts']) { const bytes = readFileSync(resolve(file)); const decoded = new TextDecoder('utf-8', { fatal: true }).decode(bytes); expect(Buffer.from(decoded, 'utf8'), file).toEqual(bytes); expect(decoded, file).not.toMatch(/Ã|Â|Ä|Å|â€|ï¿½|�/u); } });
});
describe('subtitle preview, apply and capability enforcement', () => {
  it('registers a lazy studio with revision-safe controls and persistence', () => { const registry = readFileSync(resolve('src/app/viewRegistry.tsx'), 'utf8'); const studio = readFileSync(resolve('src/views/AISubtitleStudio.tsx'), 'utf8'); const persistence = readFileSync(resolve('src/persistence/persistenceManager.ts'), 'utf8'); expect(registry).toContain("lazyNamed(() => import('@/views/AISubtitleStudio')"); expect(studio).toContain('explicit approval'); expect(studio).toContain('busy || previewBusy || revisionBusy'); expect(studio).toContain('mounted.current = true'); expect(studio).toContain('JSON Export'); expect(persistence).toContain("'subtitle-intelligence'"); });
  it('requires explicit approval and a matching preview', async () => { const state = await setup(); const operation = state.plan.operations.find((item) => item.support === 'implemented')!; const empty = state.engine.preview(state.plan, state.snapshot, []); expect(empty.operationResults).toHaveLength(0); const preview = state.engine.preview(state.plan, state.snapshot, [operation.id]); expect(() => state.engine.apply(state.plan, preview, state.snapshot, [])).toThrow(/selections changed/i); });
  it('applies style immutably and advances canonical fingerprint and revision', async () => { const state = await setup(); const operation = state.plan.operations.find((item) => item.type === 'restyle')!; const preview = state.engine.preview(state.plan, state.snapshot, [operation.id]); const result = state.engine.apply(state.plan, preview, state.snapshot, [operation.id]); expect(result.revision.snapshot).not.toBe(state.snapshot); expect(result.revision.snapshot.manifestFingerprint).not.toBe(state.snapshot.manifestFingerprint); expect(state.manifest.subtitles.style.fontSize).toBe(state.snapshot.manifest.subtitles.style.fontSize); });
  it('keeps unsupported animation planned-only without fingerprint or rerender changes', async () => { const state = await setup(); const base = state.plan.operations[0]; const animation: SubtitleOperation = { ...base, id: 'slide-animation', type: 'animation', support: 'planned-only', parameters: { animation: 'slide' } }; const plan = { ...state.plan, operations: [animation] }; const preview = state.engine.preview(plan, state.snapshot, [animation.id]); expect(preview.operationResults[0]).toMatchObject({ status: 'planned-only', support: 'planned-only' }); expect(preview.proposedSnapshot).toBe(state.snapshot); expect(preview.rerenderSceneIds).toEqual([]); expect(subtitleOperationSupport('animation', animation.parameters)).toBe('planned-only'); });
  it('reports renderer-backed and planned-only animation capabilities centrally', () => { expect(getSubtitleCapability('resize')).toMatchObject({ support: 'implemented', renderEffect: true }); expect(subtitleOperationSupport('animation', { animation: 'fade' })).toBe('implemented'); expect(subtitleOperationSupport('animation', { animation: 'bounce' })).toBe('planned-only'); });
  it('keeps vertical line spacing planned-only instead of misusing ASS character spacing', async () => { const { manifest } = await setup(); manifest.subtitles.style = { ...manifest.subtitles.style, fontFamily: 'Inter', fontSize: 72, lineSpacing: 1.22, strokeWidth: 6, shadowDepth: 3, position: 'center', animation: 'fade' }; const command = buildSceneSegmentCommand({ manifest, scene: manifest.timeline.scenes[0], preset: DEFAULT_RENDER_PRESET, outputPath: 'out.mp4' }); expect(command.subtitleContent).toContain('Style: Clean,Inter,72'); expect(command.subtitleContent).toContain(',100,100,0,0,1,6,3,5,'); expect(command.subtitleContent).not.toContain(',100,100,1.22,'); expect(command.args.join(' ')).toContain('subtitles={{SUBTITLE_FILE}}'); expect(command.args.join(' ')).not.toContain('force_style'); });
  it('remaps approved highlights from an original cue onto split children', async () => { const state = await setup(); const source = state.manifest.subtitles.cues.find((cue) => cue.wordIds.length >= 4)!; expect(source).toBeDefined(); const split: SubtitleOperation = { id: 'split-remap', cueId: source.id, sceneId: source.sceneId, type: 'split-subtitle', support: 'implemented', metric: 'density', parameters: {}, expectedImpact: 7, status: 'proposed', reason: 'Split for density.' }; const highlight: SubtitleOperation = { id: 'highlight-remap', cueId: source.id, sceneId: source.sceneId, type: 'highlight-keyword', support: 'implemented', metric: 'highlight', parameters: { wordId: source.wordIds[0] }, expectedImpact: 3, status: 'proposed', reason: 'Highlight keyword.' }; const plan = { ...state.plan, operations: [split, highlight] }; const preview = state.engine.preview(plan, state.snapshot, [split.id, highlight.id]); expect(preview.operationResults.map((item) => item.status)).toEqual(['applied', 'applied']); const child = preview.proposedSnapshot.manifest.subtitles.cues.find((cue) => cue.wordIds.includes(source.wordIds[0])); expect(child?.emphasisWordIds).toContain(source.wordIds[0]); });
  it.each([
    ['two lines', 'Hello,  world\nsecond line'],
    ['three lines', 'One\ntwo!\nthree?'],
    ['emoji and CJK', 'Hello 👋\n你好 世界'],
    ['RTL and mixed emphasis', 'Hello עולם\nمرحبا world'],
    ['leading and trailing line boundaries', '\nfirst  line\nlast\n'],
  ])('preserves %s while enriching highlighted and karaoke cues', async (_name, text) => {
    const { manifest } = await setup(); const scene = manifest.timeline.scenes[0]; const cue = manifest.subtitles.cues.find((item) => item.sceneId === scene.id)!;
    cue.text = text; cue.wordIds = Array.from({ length: Math.max(8, text.split(/\s+/u).filter(Boolean).length) }, (_, index) => `word-${index}`); cue.emphasisWordIds = [cue.wordIds[0], cue.wordIds.at(-1)!];
    for (const animation of ['none', 'karaoke'] as const) { manifest.subtitles.style.animation = animation; const ass = buildSceneSubtitleRenderPlan({ scene, cues: [cue], width: manifest.render.width, height: manifest.render.height, style: manifest.subtitles.style }).assContent!; const dialogue = ass.split('\n').find((line) => line.startsWith('Dialogue:'))!; const renderedText = dialogue.split(',,').at(-1)!.replace(/{\\[^}]+}/g, ''); expect(renderedText).toBe(escapeExpectedText(text)); }
  });
  it.each([[1080, 1920], [1920, 1080]])('uses symmetric safe-area margins for top and bottom at %sx%s', async (width, height) => { const { manifest } = await setup(); const scene = manifest.timeline.scenes[0]; const cue = manifest.subtitles.cues.find((item) => item.sceneId === scene.id)!; const render = (position: 'top' | 'bottom') => { const style = { ...manifest.subtitles.style, position }; return buildSceneSubtitleRenderPlan({ scene, cues: [cue], width, height, style }).assContent!; }; const expected = subtitleVerticalMargin('top', width, height); expect(expected).toBe(subtitleVerticalMargin('bottom', width, height)); expect(expected).toBeLessThan(height * .12); expect(render('top')).toContain(`,8,90,90,${expected},1`); expect(render('bottom')).toContain(`,2,90,90,${expected},1`); });
  it('invalidates scene cache for typography, line spacing and emphasis changes', async () => { const { manifest } = await setup(); const scene = manifest.timeline.scenes[0]; const before = await createSceneFingerprint(scene, manifest, DEFAULT_RENDER_PRESET); manifest.subtitles.style.fontSize += 1; const typography = await createSceneFingerprint(scene, manifest, DEFAULT_RENDER_PRESET); expect(typography).not.toBe(before); manifest.subtitles.style.lineSpacing += 0.1; const spacing = await createSceneFingerprint(scene, manifest, DEFAULT_RENDER_PRESET); expect(spacing).not.toBe(typography); manifest.subtitles.cues.find((cue) => cue.sceneId === scene.id)!.emphasisWordIds.push(manifest.subtitles.cues.find((cue) => cue.sceneId === scene.id)!.wordIds[0]); expect(await createSceneFingerprint(scene, manifest, DEFAULT_RENDER_PRESET)).not.toBe(spacing); });
  it('undo and redo payloads preserve exact profile parameters through revisions', async () => { const state = await setup(); const operation = state.plan.operations.find((item) => item.type === 'restyle')!; const preview = state.engine.preview(state.plan, state.snapshot, [operation.id]); const result = state.engine.apply(state.plan, preview, state.snapshot, [operation.id]); expect(result.previousRevision.snapshot.manifest.subtitles.style).toEqual(state.snapshot.manifest.subtitles.style); expect(result.revision.snapshot.manifest.subtitles.style).toEqual(expect.objectContaining({ fontSize: 70, lineSpacing: 1.05, strokeWidth: 5, animation: 'word-highlight' })); });
});
function cueHasAlternative(line: string): boolean { return line.trim().length > 18; }
function escapeExpectedText(text: string): string { return text.replace(/\\/g, '\\\\').replace(/{/g, '\\{').replace(/}/g, '\\}').replace(/\r\n?|\n/g, '\\N'); }
