import { afterEach, describe, expect, it } from 'vitest';
import { createManifestRevisionId, createTimelineSnapshot } from '@/core/editing';
import { createSubtitleIntelligenceEngine } from '@/core/subtitle-intelligence';
import { applyActiveSubtitlePlan, configureSubtitleIntelligenceController, refreshSubtitlePreview } from '@/services/subtitleIntelligenceController';
import type { SubtitleIntelligenceApplicationService } from '@/services/subtitleIntelligenceApplicationService';
import { acquireVisualOperation, getActiveVisualOperation, isPreviewOperation, releaseVisualOperation, resetVisualOperationCoordinator } from '@/services/visualOperationCoordinator';
import { useMediaStore } from '@/store/mediaStore';
import { useSubtitleIntelligenceStore } from '@/store/subtitleIntelligenceStore';
import { editingFixture } from '../editing/fixtures';

afterEach(() => { configureSubtitleIntelligenceController(null); resetVisualOperationCoordinator(); useMediaStore.setState(useMediaStore.getInitialState(), true); useSubtitleIntelligenceStore.setState(useSubtitleIntelligenceStore.getInitialState(), true); });
function deferred<T>() { let resolve!: (value: T) => void; let reject!: (reason: unknown) => void; const promise = new Promise<T>((yes, no) => { resolve = yes; reject = no; }); return { promise, resolve, reject }; }
async function ready() { const fixture = await editingFixture(); useMediaStore.getState().setBuildResult(fixture.project, fixture.manifest, fixture.renderReady, fixture.assetResolution, fixture.validation); const manifest = useMediaStore.getState().manifest!; const snapshot = createTimelineSnapshot(manifest, createManifestRevisionId(manifest)); const engine = createSubtitleIntelligenceEngine(); const plan = engine.analyze({ manifest, snapshot }); const operation = plan.operations.find((item) => item.support === 'implemented')!; const request = { requestId: 1, projectId: snapshot.projectId, revisionId: snapshot.revisionId, fingerprint: snapshot.manifestFingerprint }; useSubtitleIntelligenceStore.getState().replace(snapshot); useSubtitleIntelligenceStore.getState().start(request); useSubtitleIntelligenceStore.getState().complete(request, plan, snapshot); return { engine, plan, snapshot, operation }; }
function service(createPreview: SubtitleIntelligenceApplicationService['createPreview']): SubtitleIntelligenceApplicationService { return { async createPlan() { throw new Error('not used'); }, createPreview, async apply() { throw new Error('not used'); }, async revisionCompleted() {} }; }

describe('subtitle preview latest-request-wins lifecycle', () => {
  it('supersedes A with B and prevents A completion or release from disturbing B', async () => { const state = await ready(); const waits = [deferred<ReturnType<typeof state.engine.preview>>(), deferred<ReturnType<typeof state.engine.preview>>()]; const signals: AbortSignal[] = []; let call = 0; configureSubtitleIntelligenceController(service(async (_plan, _snapshot, _ids, signal) => { signals.push(signal!); return waits[call++].promise; })); const a = refreshSubtitlePreview(); const leaseA = getActiveVisualOperation(state.snapshot.projectId)!; useSubtitleIntelligenceStore.getState().approve(state.operation.id, true); const b = refreshSubtitlePreview(); const leaseB = getActiveVisualOperation(state.snapshot.projectId)!; expect(leaseB.token).not.toBe(leaseA.token); expect(signals[0].aborted).toBe(true); releaseVisualOperation(leaseA); expect(getActiveVisualOperation(state.snapshot.projectId)?.token).toBe(leaseB.token); waits[0].resolve(state.engine.preview(state.plan, state.snapshot, [])); await expect(a).resolves.toBe(false); expect(useSubtitleIntelligenceStore.getState().status).toBe('previewing'); waits[1].resolve(state.engine.preview(state.plan, state.snapshot, [state.operation.id])); await expect(b).resolves.toBe(true); expect(useSubtitleIntelligenceStore.getState().preview?.approvalSignature).toBe(state.engine.preview(state.plan, state.snapshot, [state.operation.id]).approvalSignature); });
  it('keeps only the third preview after three rapid approval changes', async () => { const state = await ready(); const waits = [deferred<ReturnType<typeof state.engine.preview>>(), deferred<ReturnType<typeof state.engine.preview>>(), deferred<ReturnType<typeof state.engine.preview>>()]; const signals: AbortSignal[] = []; let call = 0; configureSubtitleIntelligenceController(service(async (_plan, _snapshot, _ids, signal) => { signals.push(signal!); return waits[call++].promise; })); const a = refreshSubtitlePreview(); useSubtitleIntelligenceStore.getState().approve(state.operation.id, true); const b = refreshSubtitlePreview(); useSubtitleIntelligenceStore.getState().approve(state.operation.id, false); const c = refreshSubtitlePreview(); expect(signals.slice(0, 2).every((signal) => signal.aborted)).toBe(true); waits[1].reject(new Error('stale failure')); waits[0].resolve(state.engine.preview(state.plan, state.snapshot, [])); await expect(Promise.all([a, b])).resolves.toEqual([false, false]); expect(useSubtitleIntelligenceStore.getState().error).toBeNull(); expect(useSubtitleIntelligenceStore.getState().status).toBe('previewing'); waits[2].resolve(state.engine.preview(state.plan, state.snapshot, [])); await expect(c).resolves.toBe(true); expect(useSubtitleIntelligenceStore.getState().status).toBe('ready'); });
  it('does not let preview supersede apply or revision operations', async () => { const state = await ready(); configureSubtitleIntelligenceController(service(async () => state.engine.preview(state.plan, state.snapshot, []))); for (const operation of ['subtitle-applying', 'subtitle-undoing', 'subtitle-redoing'] as const) { const lease = acquireVisualOperation(state.snapshot.projectId, operation); await expect(refreshSubtitlePreview()).rejects.toThrow(new RegExp(operation)); releaseVisualOperation(lease); } });
  it('blocks apply while previewing and isolates projects', async () => { const state = await ready(); const wait = deferred<ReturnType<typeof state.engine.preview>>(); configureSubtitleIntelligenceController(service(async () => wait.promise)); const preview = refreshSubtitlePreview(); await expect(applyActiveSubtitlePlan()).rejects.toThrow(/subtitle-previewing/); const other = acquireVisualOperation('other-project', 'subtitle-previewing'); expect(getActiveVisualOperation('other-project')?.token).toBe(other.token); releaseVisualOperation(other); wait.resolve(state.engine.preview(state.plan, state.snapshot, [])); await preview; });
  it('classifies current and future preview operations centrally and makes release idempotent', () => { for (const operation of ['previewing', 'subtitle-previewing', 'audio-previewing', 'editing-previewing'] as const) expect(isPreviewOperation(operation)).toBe(true); const first = acquireVisualOperation('project', 'subtitle-previewing'); const second = acquireVisualOperation('project', 'subtitle-previewing'); releaseVisualOperation(first); releaseVisualOperation(first); expect(getActiveVisualOperation('project')?.token).toBe(second.token); releaseVisualOperation(second); });
});
