import { beforeEach, describe, expect, it } from 'vitest';
import { createManifestRevisionId, createTimelineSnapshot, MANIFEST_FINGERPRINT_VERSION, type TimelineRevision } from '@/core/editing';
import { createSubtitleIntelligenceEngine } from '@/core/subtitle-intelligence';
import { mergePersistedSubtitleState, normalizePersistedSubtitleState, useSubtitleIntelligenceStore } from '@/store/subtitleIntelligenceStore';
import { editingFixture } from '../editing/fixtures';

beforeEach(() => useSubtitleIntelligenceStore.setState(useSubtitleIntelligenceStore.getInitialState(), true));

async function revisions() {
  const fixture = await editingFixture(); const manifest = structuredClone(fixture.manifest); const first = createTimelineSnapshot(manifest, createManifestRevisionId(manifest)); const engine = createSubtitleIntelligenceEngine(); const plan = engine.analyze({ manifest, snapshot: first }); const operation = plan.operations.find((item) => item.support === 'implemented')!; const preview = engine.preview(plan, first, [operation.id]); const result = engine.apply(plan, preview, first, [operation.id]); return { first, second: result.revision.snapshot, history: [result.previousRevision, result.revision] as TimelineRevision[] };
}

describe('subtitle revision persistence', () => {
  it('hydrates the current snapshot and keeps restart undo/redo usable', async () => { const state = await revisions(); const persisted = normalizePersistedSubtitleState({ activeProjectId: state.first.projectId, snapshot: state.second, currentRevisionId: state.second.revisionId, fingerprintVersion: MANIFEST_FINGERPRINT_VERSION, snapshotFingerprint: state.second.manifestFingerprint, history: { [state.first.projectId]: state.history }, redoStack: {} }); useSubtitleIntelligenceStore.setState(mergePersistedSubtitleState(persisted, useSubtitleIntelligenceStore.getInitialState()), true); const undo = useSubtitleIntelligenceStore.getState().prepareRevisionMove('undo'); expect(undo?.target.id).toBe(state.first.revisionId); expect(useSubtitleIntelligenceStore.getState().commitRevisionMove(undo!)).toBe(true); const afterUndo = useSubtitleIntelligenceStore.getState(); const restarted = normalizePersistedSubtitleState({ activeProjectId: afterUndo.activeProjectId, snapshot: afterUndo.snapshot, currentRevisionId: afterUndo.currentRevisionId, fingerprintVersion: MANIFEST_FINGERPRINT_VERSION, snapshotFingerprint: afterUndo.snapshot?.manifestFingerprint, history: afterUndo.history, redoStack: afterUndo.redoStack }); useSubtitleIntelligenceStore.setState(mergePersistedSubtitleState(restarted, useSubtitleIntelligenceStore.getInitialState()), true); expect(useSubtitleIntelligenceStore.getState().prepareRevisionMove('redo')?.target.id).toBe(state.second.revisionId); });
  it('migrates legacy history without a snapshot instead of collapsing it', async () => { const state = await revisions(); const migrated = normalizePersistedSubtitleState({ activeProjectId: state.first.projectId, history: { [state.first.projectId]: state.history } }); expect(migrated.snapshot?.revisionId).toBe(state.second.revisionId); expect(migrated.currentRevisionId).toBe(state.second.revisionId); expect(migrated.history[state.first.projectId]).toHaveLength(2); });
  it('rejects stale snapshot metadata and clears malformed redo entries', async () => { const state = await revisions(); const stale = { ...state.second, manifestFingerprint: 'stale-fingerprint' }; const malformedRedo = { ...state.history[0], id: 'broken-redo' }; const normalized = normalizePersistedSubtitleState({ activeProjectId: state.first.projectId, snapshot: stale, currentRevisionId: stale.revisionId, snapshotFingerprint: stale.manifestFingerprint, history: { [state.first.projectId]: state.history }, redoStack: { [state.first.projectId]: [malformedRedo] } }); expect(normalized.snapshot?.revisionId).toBe(state.second.revisionId); expect(normalized.redoStack[state.first.projectId] ?? []).toHaveLength(0); expect(normalized.quarantinedHistory[state.first.projectId]).toBeDefined(); });
  it('quarantines fingerprint-version mismatches while preserving valid history integrity', async () => { const state = await revisions(); const staleRevision = { ...state.history[0], id: 'old', snapshot: { ...state.first, revisionId: 'old', fingerprintVersion: MANIFEST_FINGERPRINT_VERSION - 1 } }; const normalized = normalizePersistedSubtitleState({ activeProjectId: state.first.projectId, history: { [state.first.projectId]: [...state.history, staleRevision] }, redoStack: {} }); expect(normalized.history[state.first.projectId].map((item) => item.id)).toEqual(state.history.map((item) => item.id)); expect(normalized.quarantinedHistory[state.first.projectId]).toContainEqual(staleRevision); });
});
