import { afterEach, describe, expect, it } from 'vitest';
import { createManifestRevisionId, createTimelineSnapshot } from '@/core/editing';
import { createSubtitleIntelligenceEngine } from '@/core/subtitle-intelligence';
import { applyActiveSubtitlePlan, configureSubtitleIntelligenceController, createActiveSubtitlePlan, redoSubtitle, refreshSubtitlePreview, undoSubtitle } from '@/services/subtitleIntelligenceController';
import type { SubtitleIntelligenceApplicationService } from '@/services/subtitleIntelligenceApplicationService';
import { useMediaStore } from '@/store/mediaStore';
import { useSubtitleIntelligenceStore } from '@/store/subtitleIntelligenceStore';
import { editingFixture } from '../editing/fixtures';
afterEach(() => { configureSubtitleIntelligenceController(null); useMediaStore.setState(useMediaStore.getInitialState(), true); useSubtitleIntelligenceStore.setState(useSubtitleIntelligenceStore.getInitialState(), true); });
function deferred<T>() { let resolve!: (value: T) => void; let reject!: (reason: unknown) => void; const promise = new Promise<T>((yes, no) => { resolve = yes; reject = no; }); return { promise, resolve, reject }; }
async function setup() { const fixture = await editingFixture(); useMediaStore.getState().setBuildResult(fixture.project, fixture.manifest, fixture.renderReady, fixture.assetResolution, fixture.validation); const manifest = useMediaStore.getState().manifest!; const snapshot = createTimelineSnapshot(manifest, createManifestRevisionId(manifest)); const engine = createSubtitleIntelligenceEngine(); const plan = engine.analyze({ manifest, snapshot }); const operation = plan.operations.find((item) => item.support === 'implemented')!; const preview = engine.preview(plan, snapshot, [operation.id]); return { fixture, manifest, snapshot, engine, plan, operation, preview }; }
function service(overrides: Partial<SubtitleIntelligenceApplicationService> = {}): SubtitleIntelligenceApplicationService { return { async createPlan() { throw new Error('not used'); }, async createPreview() { throw new Error('not used'); }, async apply() { throw new Error('not used'); }, async revisionCompleted() {}, ...overrides }; }
describe('subtitle controller concurrency and revision transactions', () => {
  it('rejects duplicate analysis while the project operation lease is active', async () => { const state = await setup(); const wait = deferred<{ plan: typeof state.plan; snapshot: typeof state.snapshot }>(); configureSubtitleIntelligenceController(service({ createPlan: () => wait.promise })); const first = createActiveSubtitlePlan(); await expect(createActiveSubtitlePlan()).rejects.toThrow(/operation in progress.*subtitle-analyzing/i); wait.resolve({ plan: state.plan, snapshot: state.snapshot }); await expect(first).resolves.toBe(true); });
  it('rejects undo while analysis is active and releases the lock after failure', async () => { const state = await setup(); useSubtitleIntelligenceStore.getState().replace(state.snapshot); const wait = deferred<never>(); configureSubtitleIntelligenceController(service({ createPlan: () => wait.promise })); const analysis = createActiveSubtitlePlan(); await expect(undoSubtitle()).rejects.toThrow(/subtitle-analyzing/); wait.reject(new Error('analysis failed')); await expect(analysis).rejects.toThrow('analysis failed'); configureSubtitleIntelligenceController(service()); await expect(undoSubtitle()).resolves.toBeUndefined(); });
  it('applies only after current preview and installs matching manifest revision', async () => { const state = await setup(); configureSubtitleIntelligenceController(service({ createPlan: async () => ({ plan: state.plan, snapshot: state.snapshot }), createPreview: async () => state.preview, apply: async () => state.engine.apply(state.plan, state.preview, state.snapshot, [state.operation.id]) })); await createActiveSubtitlePlan(); useSubtitleIntelligenceStore.getState().approve(state.operation.id, true); await refreshSubtitlePreview(); await applyActiveSubtitlePlan(); expect(useMediaStore.getState().manifest && createManifestRevisionId(useMediaStore.getState().manifest!)).toBe(useSubtitleIntelligenceStore.getState().snapshot?.manifestFingerprint); });
  it('undoes and redoes manifest and subtitle revision state together', async () => { const state = await setup(); const result = state.engine.apply(state.plan, state.preview, state.snapshot, [state.operation.id]); useSubtitleIntelligenceStore.getState().replace(state.snapshot); useSubtitleIntelligenceStore.getState().applied(result); useMediaStore.getState().replaceEditedManifest(result.revision.snapshot.manifest); configureSubtitleIntelligenceController(service()); await undoSubtitle(); expect(createManifestRevisionId(useMediaStore.getState().manifest!)).toBe(state.snapshot.manifestFingerprint); await redoSubtitle(); expect(createManifestRevisionId(useMediaStore.getState().manifest!)).toBe(result.revision.snapshot.manifestFingerprint); });
  it('leaves store and manifest unchanged when revision event rejects', async () => { const state = await setup(); const result = state.engine.apply(state.plan, state.preview, state.snapshot, [state.operation.id]); useSubtitleIntelligenceStore.getState().replace(state.snapshot); useSubtitleIntelligenceStore.getState().applied(result); useMediaStore.getState().replaceEditedManifest(result.revision.snapshot.manifest); const before = createManifestRevisionId(useMediaStore.getState().manifest!); configureSubtitleIntelligenceController(service({ revisionCompleted: async () => { throw new Error('event failed'); } })); await expect(undoSubtitle()).rejects.toThrow('event failed'); expect(createManifestRevisionId(useMediaStore.getState().manifest!)).toBe(before); expect(useSubtitleIntelligenceStore.getState().snapshot?.revisionId).toBe(result.revision.id); });
});
