import { AlertTriangle, Download, Loader2, Play, Redo2, Undo2 } from 'lucide-react';
import { Button, Card } from '@/components/ui';
import { AudioOperationList } from '@/components/audio-production/AudioOperationList';
import { AudioPlanSummary } from '@/components/audio-production/AudioPlanSummary';
import { applyActiveAudioPlan, createActiveAudioPlan, redoActiveAudio, refreshActiveAudioPreview, undoActiveAudio } from '@/services/audioProductionController';
import { useAudioProductionStore } from '@/store/audioProductionStore';

export function AIAudioStudio() {
  const state = useAudioProductionStore(); const busy = state.analysisStatus === 'analyzing' || state.applyStatus === 'applying'; const plan = state.currentPlan; const preview = state.currentPreview; const historyCount = (state.activeProjectId ? state.revisionsByProject[state.activeProjectId]?.length : 0) ?? 0;
  const generate = async () => { try { await createActiveAudioPlan(); } catch (error) { useAudioProductionStore.getState().analysisFailed(error instanceof Error ? error.message : 'Audio analysis failed.'); } };
  const refresh = () => { void refreshActiveAudioPreview(); }; const toggle = (id: string, enabled: boolean) => { state.operationEnabled(id, enabled); refresh(); }; const approve = (id: string, approved: boolean) => { if (approved) state.approveManualOperation(id); else state.revokeManualOperationApproval(id); refresh(); }; const approveAll = () => { state.approveAllManualOperations(); refresh(); };
  const apply = async () => { if (!preview || !window.confirm('Apply automatic and explicitly approved manual audio operations?')) return; await applyActiveAudioPlan(); };
  const critical = state.conflicts.some((item) => item.severity === 'critical'); const conflictedOperationIds = state.conflicts.filter((item) => item.severity === 'critical').flatMap((item) => item.operationIds);
  if (!plan && !preview && !historyCount) return <Card className="mx-auto max-w-xl p-8 text-center"><h1 className="text-xl font-semibold">AI Audio Studio</h1><p className="mt-2 text-sm text-slate-500">Deterministic, heuristic voice and audio production. No TTS, media search, or audio render runs here.</p>{state.lastError && <p className="mt-3 text-sm text-rose-600">{state.lastError}</p>}<Button className="mt-5" disabled={busy} onClick={() => void generate()}>{busy ? <Loader2 className="animate-spin" size={16}/> : <Play size={16}/>} Create audio plan</Button></Card>;
  return <div className="space-y-5"><header className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">AI Audio Studio</h1><p className="text-sm text-slate-500">Heuristic production plan · revision {state.currentRevisionId ?? 'not applied'}</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={!state.undoAvailable} onClick={() => void undoActiveAudio()}><Undo2 size={16}/> Undo</Button><Button variant="secondary" disabled={!state.redoAvailable} onClick={() => void redoActiveAudio()}><Redo2 size={16}/> Redo</Button><Button variant="secondary" disabled={busy} onClick={() => void generate()}><Play size={16}/> New plan</Button>{plan && preview && <Button variant="secondary" onClick={() => exportJson({ plan, preview, approvedManualOperationIds: state.approvedManualOperationIds })}><Download size={16}/> JSON</Button>}{plan && preview && <Button disabled={busy || critical} onClick={() => void apply()}>Apply audio plan</Button>}</div></header>{state.lastError && <Card className="border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{state.lastError}</Card>}{critical && <Card className="border-amber-200 bg-amber-50 p-4"><p className="flex items-center gap-2"><AlertTriangle size={16}/> Resolve critical conflicts before apply.</p></Card>}{!preview && historyCount > 0 && <Card className="p-4"><h2 className="font-semibold">Applied audio revision</h2><p className="text-sm text-slate-500">History remains available without a preview.</p></Card>}{plan && preview && <><AudioPlanSummary plan={plan} preview={preview}/><div className="grid gap-5 xl:grid-cols-[2fr_1fr]"><AudioOperationList approvedManualIds={state.approvedManualOperationIds} conflictedOperationIds={conflictedOperationIds} operations={state.operations} onApprove={approve} onApproveAll={approveAll} onToggle={toggle}/><div className="space-y-4"><Card className="p-4"><h2 className="font-semibold">Silence map</h2>{plan.silenceRegions.map((item, index) => <p className="mt-2 text-sm" key={`${item.startMs}-${index}`}>{item.startMs}–{item.endMs} ms · {item.type} · {item.severity}</p>)}</Card><Card className="p-4"><h2 className="font-semibold">Music / SFX / ducking</h2><p className="text-sm text-slate-500">{plan.music.mood}, {plan.music.tempoRange.join('–')} BPM</p><p className="text-sm text-slate-500">{plan.sfx.length} SFX suggestions · {plan.ducking.length} ducking ranges</p></Card></div></div></>}</div>;
}
function exportJson(value: object): void { const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: 'application/json;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = 'ai-audio-production-plan.json'; link.click(); URL.revokeObjectURL(url); }
