import { useMemo, useState } from 'react';
import { Activity, AlertTriangle, BarChart3, Download, RefreshCw, ShieldCheck, Sparkles } from 'lucide-react';
import { Card } from '@/components/ui';
import { bindPublishedContent, bindingId, createAnalyticsAdapterRegistry, createAnalyticsReport, scorePerformance, type AnalyticsSnapshot, type ContentPerformance } from '@/core/analytics';
import { regenerateChannelLearning, refreshPublicationAnalytics } from '@/services/analyticsController';
import { useAnalyticsStore, usePublishingStore } from '@/store';
import type { Channel } from '@/lib/types';
import { insightsForSelectedPublication, snapshotForSelection } from './analyticsSelection';

interface AnalyticsProps { channels: Channel[]; }
const metricLabel = (name: string) => name.replace(/([A-Z])/g, ' $1').replace(/^./, (value) => value.toUpperCase());
const metricValue = (snapshot: AnalyticsSnapshot, name: string) => { const metric = snapshot.metrics.find((item) => item.name === name); if (!metric) return '—'; if (metric.availability !== 'available' || metric.value === null) return metric.availability.replace('-', ' '); return metric.unit === 'percentage' ? `${metric.value.toFixed(1)}%` : new Intl.NumberFormat().format(metric.value); };
export function Analytics({ channels }: AnalyticsProps) {
  const snapshots = useAnalyticsStore((state) => state.snapshots); const profiles = useAnalyticsStore((state) => state.profiles); const allInsights = useAnalyticsStore((state) => state.insights); const recommendations = useAnalyticsStore((state) => state.recommendations); const jobs = usePublishingStore((state) => state.queue.jobs); const [selected, setSelected] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const registry = useMemo(() => createAnalyticsAdapterRegistry(), []);
  const published = useMemo(() => jobs.filter((job) => job.state === 'published' && job.receipt?.verification.valid), [jobs]); const selectedSnapshot = snapshotForSelection(snapshots, selected);
  const performance: ContentPerformance | null = selectedSnapshot ? scorePerformance(selectedSnapshot, snapshots, selectedSnapshot.metrics[0]?.window ?? '24h') : null; const insights = selectedSnapshot ? insightsForSelectedPublication(allInsights, selectedSnapshot) : []; const selectedRecommendations = selectedSnapshot ? recommendations.filter((item) => item.channelBinding.platform === selectedSnapshot.binding.platform && item.channelBinding.accountId === selectedSnapshot.binding.accountId && item.channelBinding.channelRef === selectedSnapshot.binding.channelRef) : [];
  const exportReport = () => { const json = JSON.stringify(createAnalyticsReport({ version: 1, snapshots, attributions: useAnalyticsStore.getState().attributions, profiles, insights: allInsights, recommendations, refreshes: useAnalyticsStore.getState().refreshes }, performance ? [performance] : []), null, 2); const blob = new Blob([json], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'shortsflow-analytics-report.json'; anchor.click(); URL.revokeObjectURL(url); };
  const refresh = async (index: number) => { const job = published[index]; if (!job?.receipt) return; try { const binding = bindPublishedContent(job, job.receipt); setSelected(bindingId({ binding })); const result = await refreshPublicationAnalytics(binding, '24h', job.artifact.diagnostics); setNotice(result.diagnostics.map((item) => item.message).join(' ') || 'Analytics refreshed.'); } catch (error) { setNotice(error instanceof Error ? error.message : 'Analytics refresh failed.'); } };
  const learn = () => { const snapshot = selectedSnapshot; if (!snapshot) { setNotice('Select collected channel data before generating learning.'); return; } const profile = regenerateChannelLearning({ platform: snapshot.binding.platform, accountId: snapshot.binding.accountId, accountRef: snapshot.binding.accountRef, channelRef: snapshot.binding.channelRef }); setNotice(profile.profiles.at(-1)?.status === 'cold-start' ? 'Cold start: not enough comparable content for personalized learning.' : 'Learning profile regenerated.'); };
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold text-slate-900">AI Analytics Studio</h1><p className="text-sm text-slate-500">Canonical, publication-bound analytics. Associations are never presented as causation.</p></div><div className="flex gap-2"><button type="button" onClick={learn} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-medium text-slate-700"><Sparkles size={15}/> Generate learning</button><button type="button" onClick={exportReport} className="inline-flex items-center gap-2 rounded-lg bg-slate-900 px-3 py-2 text-sm font-medium text-white"><Download size={15}/> Export JSON</button></div></div>
  {notice && <div className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-900">{notice}</div>}
  <div className="grid gap-4 lg:grid-cols-3">{registry.list().slice(0, 3).map((adapter) => { const capability = adapter.capability(); return <Card key={capability.platform} className="p-4"><div className="flex items-center justify-between"><span className="font-semibold capitalize text-slate-800">{capability.platform}</span><span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-600">{capability.adapterStatus}</span></div><p className="mt-2 text-xs text-slate-500">{capability.reason}</p></Card>; })}</div>
  <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card className="p-5"><div className="mb-3 flex items-center gap-2"><BarChart3 size={18} className="text-emerald-600"/><h2 className="font-semibold text-slate-900">Published content</h2></div>{published.length ? <div className="space-y-2">{published.map((job, index) => <div key={job.id} className="flex flex-wrap items-center gap-3 rounded-lg border border-slate-100 p-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-slate-800">{job.metadata.title || job.id}</p><p className="text-xs text-slate-500">{job.target.platform} · {job.accountBinding.displayName} · {job.receipt?.publishedAt}</p></div><button type="button" onClick={() => void refresh(index)} className="inline-flex items-center gap-1 rounded-md border border-slate-200 px-2.5 py-1.5 text-xs font-medium"><RefreshCw size={13}/> Refresh</button></div>)}</div> : <Empty text="No verified published receipts are available. Analytics never binds to draft or ambiguous content."/>}</Card>
  <Card className="p-5"><div className="mb-3 flex items-center gap-2"><ShieldCheck size={18} className="text-emerald-600"/><h2 className="font-semibold text-slate-900">Data status</h2></div><p className="text-sm text-slate-600">{selectedSnapshot ? `${selectedSnapshot.freshness} · fetched ${new Date(selectedSnapshot.collectedAt).toLocaleString()}` : 'No canonical snapshots collected.'}</p><p className="mt-3 text-xs text-slate-500">A missing metric is explicitly unavailable; it is never treated as zero. Processing delays are diagnostics, not fabricated data.</p></Card></div>
  {selectedSnapshot ? <><div className="grid grid-cols-2 gap-4 md:grid-cols-4"><MetricCard label="Views" value={metricValue(selectedSnapshot, 'views')}/><MetricCard label="Likes" value={metricValue(selectedSnapshot, 'likes')}/><MetricCard label="Retention" value={metricValue(selectedSnapshot, 'averagePercentageViewed')}/><MetricCard label="Engagement" value={metricValue(selectedSnapshot, 'engagementRate')}/></div><div className="grid gap-5 xl:grid-cols-2"><Card className="p-5"><h2 className="font-semibold text-slate-900">Content detail & performance</h2><p className="mt-1 text-xs text-slate-500">Exact publication: {selectedSnapshot.binding.remotePublicationId}</p><div className="mt-4 space-y-2">{selectedSnapshot.metrics.map((metric) => <div key={`${metric.name}-${metric.window}`} className="flex justify-between border-b border-slate-100 py-2 text-sm"><span className="text-slate-600">{metricLabel(metric.name)} · {metric.window}</span><span className="font-medium text-slate-800">{metricValue(selectedSnapshot, metric.name)}</span></div>)}</div>{performance && <div className="mt-4 rounded-lg bg-slate-50 p-3 text-sm"><p className="font-medium">Performance score: {performance.score.overall === null ? 'insufficient data' : performance.score.overall.toFixed(0)}</p><p className="mt-1 text-xs text-slate-500">Confidence {Math.round(performance.score.confidence * 100)}% · score policy {performance.score.version}</p></div>}</Card><Card className="p-5"><div className="flex items-center gap-2"><Activity size={18} className="text-blue-600"/><h2 className="font-semibold text-slate-900">Insights & recommendations</h2></div><div className="mt-4 space-y-3">{insights.filter((item) => item.bindingId === bindingId(selectedSnapshot)).map((item) => <p key={item.id} className="rounded-lg bg-blue-50 p-3 text-sm text-blue-900">{item.message}</p>)}{selectedRecommendations.map((item) => <div key={item.id} className="rounded-lg border border-emerald-100 bg-emerald-50 p-3"><p className="text-sm font-medium text-emerald-900">{item.recommendation}</p><p className="mt-1 text-xs text-emerald-800">{item.reason} Sample: {item.evidence[0]?.sampleSize ?? 0}. Observational evidence only.</p></div>)}{!insights.length && !selectedRecommendations.length && <Empty text="No learned conclusion yet. Collect comparable channel observations before relying on personalized guidance."/>}</div></Card></div></> : <Card className="p-8"><div className="flex items-center gap-3"><AlertTriangle className="text-amber-500"/><div><h2 className="font-semibold text-slate-900">No production analytics is being invented</h2><p className="text-sm text-slate-500">Connect an official analytics adapter, then refresh a verified published receipt to build canonical observations.</p></div></div></Card>}
  <Card className="p-5"><h2 className="font-semibold text-slate-900">Channel learning</h2><div className="mt-3 grid gap-3 md:grid-cols-3"><LearningColumn title="What appears to work" items={profiles.flatMap((profile) => profile.strongestSignals.map((signal) => `${signal.cohort} (${signal.relation})`))}/><LearningColumn title="What appears weaker" items={profiles.flatMap((profile) => profile.weakSignals.map((signal) => `${signal.cohort} (${signal.relation})`))}/><LearningColumn title="Not enough evidence" items={profiles.flatMap((profile) => profile.unknowns)}/></div></Card></div>;
}
function MetricCard({ label, value }: { label: string; value: string }) { return <Card className="p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-bold text-slate-900">{value}</p></Card>; }
function Empty({ text }: { text: string }) { return <p className="rounded-lg border border-dashed border-slate-200 p-4 text-sm text-slate-500">{text}</p>; }
function LearningColumn({ title, items }: { title: string; items: readonly string[] }) { return <div className="rounded-lg bg-slate-50 p-3"><p className="text-sm font-medium text-slate-700">{title}</p>{items.length ? <ul className="mt-2 space-y-1 text-xs text-slate-600">{items.slice(0, 4).map((item) => <li key={item}>{item}</li>)}</ul> : <p className="mt-2 text-xs text-slate-400">No evidence yet.</p>}</div>; }
