import { useEffect, useState } from 'react';
import { Bell, Palette, Plug, Zap, Clock, Save, Check, Key, Youtube, Eye, EyeOff, ExternalLink, Loader2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import type { AppSetting, Channel, YoutubeToken } from '@/lib/types';
import { Card, Button, Toggle } from '@/components/ui';
import { classNames } from '@/lib/utils';
import { saveApiKey, getApiKeyKeys, getYouTubeAuthUrl } from '@/lib/api';
import { useI18n } from '@/lib/i18n';

export function Settings({ channels = [] }: { channels?: Channel[] }) {
  const { t } = useI18n();
  const [settings, setSettings] = useState<Record<string, AppSetting>>({});
  const [loading, setLoading] = useState(true);
  const [saved, setSaved] = useState(false);

  // API keys
  const [apiKeyStatus, setApiKeyStatus] = useState<Record<string, boolean>>({});
  const [openaiKey, setOpenaiKey] = useState('');
  const [elevenlabsKey, setElevenlabsKey] = useState('');
  const [pexelsKey, setPexelsKey] = useState('');
  const [ytClientId, setYtClientId] = useState('');
  const [ytClientSecret, setYtClientSecret] = useState('');
  const [showKeys, setShowKeys] = useState<Record<string, boolean>>({});
  const [savingKey, setSavingKey] = useState('');
  const [keySaved, setKeySaved] = useState('');

  // YouTube connections
  const [ytTokens, setYtTokens] = useState<YoutubeToken[]>([]);
  const [connecting, setConnecting] = useState('');

  useEffect(() => {
    (async () => {
      const [{ data: s }, { data: keys }, { data: tokens }] = await Promise.all([
        supabase.from('app_settings').select('*'),
        supabase.from('api_keys').select('key'),
        supabase.from('youtube_tokens').select('*'),
      ]);
      const map: Record<string, AppSetting> = {};
      s?.forEach((row) => { map[row.key] = row; });
      setSettings(map);
      const keyMap: Record<string, boolean> = {};
      keys?.forEach((row: { key: string }) => { keyMap[row.key] = true; });
      setApiKeyStatus(keyMap);
      setYtTokens(tokens ?? []);
      setLoading(false);
    })();
  }, []);

  async function updateSetting(key: string, value: Record<string, unknown>) {
    await supabase.from('app_settings').upsert({
      key,
      value,
      updated_at: new Date().toISOString(),
    });
    setSettings((prev) => ({ ...prev, [key]: { ...prev[key], value } }));
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  }

  async function handleSaveKey(key: string, value: string) {
    setSavingKey(key);
    try {
      await saveApiKey(key, value);
      setApiKeyStatus((prev) => ({ ...prev, [key]: true }));
      setKeySaved(key);
      setTimeout(() => setKeySaved(''), 2000);
      if (key === 'openai') setOpenaiKey('');
      if (key === 'elevenlabs') setElevenlabsKey('');
      if (key === 'youtube_client_id') setYtClientId('');
      if (key === 'youtube_client_secret') setYtClientSecret('');
    } finally {
      setSavingKey('');
    }
  }

  async function handleConnectYouTube(channelId: string) {
    setConnecting(channelId);
    try {
      const authUrl = await getYouTubeAuthUrl(channelId);
      window.open(authUrl, 'youtube-auth', 'width=600,height=700');
    } finally {
      setConnecting('');
    }
  }

  if (loading) return <div className="py-16 text-center text-slate-400">{t('common.loading')}</div>;

  const notifications = (settings.notifications?.value ?? {}) as Record<string, boolean>;
  const integrations = (settings.integrations?.value ?? {}) as Record<string, boolean>;
  const automation = (settings.automation?.value ?? {}) as Record<string, boolean>;
  const postingSchedule = (settings.posting_schedule?.value ?? {}) as Record<string, string[]>;

  const notificationList = [
    { key: 'emailAlerts', label: t('settings.emailAlerts'), desc: t('settings.emailAlertsDesc') },
    { key: 'pushAlerts', label: t('settings.pushAlerts'), desc: t('settings.pushAlertsDesc') },
    { key: 'autoReplyComments', label: t('settings.autoReplyComments'), desc: t('settings.autoReplyCommentsDesc') },
    { key: 'weeklyReport', label: t('settings.weeklyReport'), desc: t('settings.weeklyReportDesc') },
  ];

  const automationList = [
    { key: 'autoGenerate', label: t('settings.autoGenerate'), desc: t('settings.autoGenerateDesc') },
    { key: 'autoPublish', label: t('settings.autoPublish'), desc: t('settings.autoPublishDesc') },
    { key: 'autoThumbnail', label: t('settings.autoThumbnail'), desc: t('settings.autoThumbnailDesc') },
    { key: 'autoHashtags', label: t('settings.autoHashtags'), desc: t('settings.autoHashtagsDesc') },
    { key: 'autoReply', label: t('settings.autoReply'), desc: t('settings.autoReplyDesc') },
  ];

  const days = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">{t('settings.title')}</h1>
          <p className="text-sm text-slate-500">{t('settings.subtitle')}</p>
        </div>
        {saved && (
          <span className="flex items-center gap-1.5 rounded-lg bg-emerald-50 px-3 py-1.5 text-sm font-medium text-emerald-700">
            <Check size={16} /> {t('settings.saved')}
          </span>
        )}
      </div>

      {/* API Keys */}
      <Card className="p-5">
        <div className="mb-4 flex items-center gap-2">
          <Key size={18} className="text-slate-500" />
          <h3 className="font-semibold text-slate-900">{t('settings.apiKeys')}</h3>
        </div>
        <p className="mb-4 text-sm text-slate-500">
          {t('settings.apiKeysDesc')}
        </p>
        <div className="space-y-4">
          {/* OpenAI */}
          <ApiKeyRow
            label={t('settings.openaiKey')}
            desc={t('settings.openaiDesc')}
            placeholder="sk-..."
            value={openaiKey}
            onChange={setOpenaiKey}
            show={showKeys.openai}
            onToggleShow={() => setShowKeys((p) => ({ ...p, openai: !p.openai }))}
            configured={apiKeyStatus.openai}
            saving={savingKey === 'openai'}
            saved={keySaved === 'openai'}
            onSave={() => handleSaveKey('openai', openaiKey)}
            docsUrl="https://platform.openai.com/api-keys"
          />
          {/* ElevenLABS */}
          <ApiKeyRow
            label={t('settings.elevenlabsKey')}
            desc={t('settings.elevenlabsDesc')}
            placeholder="el-..."
            value={elevenlabsKey}
            onChange={setElevenlabsKey}
            show={showKeys.elevenlabs}
            onToggleShow={() => setShowKeys((p) => ({ ...p, elevenlabs: !p.elevenlabs }))}
            configured={apiKeyStatus.elevenlabs}
            saving={savingKey === 'elevenlabs'}
            saved={keySaved === 'elevenlabs'}
            onSave={() => handleSaveKey('elevenlabs', elevenlabsKey)}
            docsUrl="https://elevenlabs.io/app/settings/api-keys"
          />
          {/* Pexels */}
          <ApiKeyRow
            label={t('settings.pexelsKey')}
            desc={t('settings.pexelsDesc')}
            placeholder="Pexels API key..."
            value={pexelsKey}
            onChange={setPexelsKey}
            show={showKeys.pexels}
            onToggleShow={() => setShowKeys((p) => ({ ...p, pexels: !p.pexels }))}
            configured={apiKeyStatus.pexels}
            saving={savingKey === 'pexels'}
            saved={keySaved === 'pexels'}
            onSave={() => handleSaveKey('pexels', pexelsKey)}
            docsUrl="https://www.pexels.com/api/"
          />
        </div>
      </Card>

      {/* YouTube OAuth */}
      <Card className="p-5">
        <div className="mb-4 flex items-center gap-2">
          <Youtube size={18} className="text-red-500" />
          <h3 className="font-semibold text-slate-900">{t('settings.youtubeConnection')}</h3>
        </div>
        <p className="mb-4 text-sm text-slate-500">
          {t('settings.youtubeDesc')}
        </p>
        <div className="space-y-4">
          <div className="rounded-lg bg-amber-50 p-3 text-sm text-amber-700">
            <p className="font-medium">{t('settings.setupRequired')}</p>
            <p className="mt-1">
              {t('settings.setupDesc')}
            </p>
            <a href="https://console.cloud.google.com/apis/credentials" target="_blank" rel="noopener noreferrer"
              className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-amber-800 underline">
              {t('settings.openCloudConsole')} <ExternalLink size={12} />
            </a>
          </div>

          <ApiKeyRow
            label={t('settings.ytClientId')}
            desc={t('settings.fromCloudConsole')}
            placeholder="xxxx.apps.googleusercontent.com"
            value={ytClientId}
            onChange={setYtClientId}
            show={showKeys.ytClientId}
            onToggleShow={() => setShowKeys((p) => ({ ...p, ytClientId: !p.ytClientId }))}
            configured={apiKeyStatus.youtube_client_id}
            saving={savingKey === 'youtube_client_id'}
            saved={keySaved === 'youtube_client_id'}
            onSave={() => handleSaveKey('youtube_client_id', ytClientId)}
          />
          <ApiKeyRow
            label={t('settings.ytClientSecret')}
            desc={t('settings.fromCloudConsole')}
            placeholder="GOCSPX-..."
            value={ytClientSecret}
            onChange={setYtClientSecret}
            show={showKeys.ytClientSecret}
            onToggleShow={() => setShowKeys((p) => ({ ...p, ytClientSecret: !p.ytClientSecret }))}
            configured={apiKeyStatus.youtube_client_secret}
            saving={savingKey === 'youtube_client_secret'}
            saved={keySaved === 'youtube_client_secret'}
            onSave={() => handleSaveKey('youtube_client_secret', ytClientSecret)}
          />

          {channels.length > 0 && apiKeyStatus.youtube_client_id && apiKeyStatus.youtube_client_secret && (
            <div className="space-y-2 border-t border-slate-100 pt-4">
              <p className="text-sm font-medium text-slate-700">{t('settings.connectChannels')}</p>
              {channels.map((ch) => {
                const token = ytTokens.find((t) => t.channel_id === ch.id);
                return (
                  <div key={ch.id} className="flex items-center justify-between rounded-lg border border-slate-100 p-3">
                    <div className="flex items-center gap-2">
                      <div className="flex h-7 w-7 items-center justify-center rounded text-xs font-bold text-white"
                        style={{ backgroundColor: ch.avatar_color }}>
                        {ch.name.charAt(0)}
                      </div>
                      <div>
                        <p className="text-sm font-medium text-slate-800">{ch.name}</p>
                        {token?.youtube_channel_name && (
                          <p className="text-xs text-emerald-600">{t('settings.connected')}: {token.youtube_channel_name}</p>
                        )}
                      </div>
                    </div>
                    {token ? (
                      <span className="flex items-center gap-1 rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-medium text-emerald-700">
                        <Check size={12} /> {t('settings.connected')}
                      </span>
                    ) : (
                      <Button size="sm" variant="secondary" onClick={() => handleConnectYouTube(ch.id)}
                        disabled={connecting === ch.id}>
                        {connecting === ch.id ? <Loader2 size={14} className="animate-spin" /> : <Youtube size={14} />}
                        {t('settings.connect')}
                      </Button>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </Card>

      {/* Integrations */}
      <Card className="p-5">
        <div className="mb-4 flex items-center gap-2">
          <Plug size={18} className="text-slate-500" />
          <h3 className="font-semibold text-slate-900">{t('settings.integrations')}</h3>
        </div>
        <div className="space-y-3">
          {[
            { key: 'youtube', label: t('settings.ytDataApi'), desc: t('settings.ytDataApiDesc') },
            { key: 'openai', label: t('settings.openaiIntegration'), desc: t('settings.openaiIntegrationDesc') },
            { key: 'elevenlabs', label: t('settings.elevenlabsIntegration'), desc: t('settings.elevenlabsIntegrationDesc') },
            { key: 'canva', label: t('settings.canva'), desc: t('settings.canvaDesc') },
            { key: 'rss', label: t('settings.rss'), desc: t('settings.rssDesc') },
          ].map((item) => (
            <div key={item.key} className="flex items-center justify-between rounded-lg border border-slate-100 p-3">
              <div>
                <p className="text-sm font-medium text-slate-800">{item.label}</p>
                <p className="text-xs text-slate-500">{item.desc}</p>
              </div>
              <Toggle
                checked={integrations[item.key] ?? false}
                onChange={(checked) => updateSetting('integrations', { ...integrations, [item.key]: checked })}
              />
            </div>
          ))}
        </div>
      </Card>

      {/* Automation */}
      <Card className="p-5">
        <div className="mb-4 flex items-center gap-2">
          <Zap size={18} className="text-slate-500" />
          <h3 className="font-semibold text-slate-900">{t('settings.automationDefaults')}</h3>
        </div>
        <div className="space-y-3">
          {automationList.map((item) => (
            <div key={item.key} className="flex items-center justify-between rounded-lg border border-slate-100 p-3">
              <div>
                <p className="text-sm font-medium text-slate-800">{item.label}</p>
                <p className="text-xs text-slate-500">{item.desc}</p>
              </div>
              <Toggle
                checked={automation[item.key] ?? false}
                onChange={(checked) => updateSetting('automation', { ...automation, [item.key]: checked })}
              />
            </div>
          ))}
        </div>
      </Card>

      {/* Notifications */}
      <Card className="p-5">
        <div className="mb-4 flex items-center gap-2">
          <Bell size={18} className="text-slate-500" />
          <h3 className="font-semibold text-slate-900">{t('settings.notifications')}</h3>
        </div>
        <div className="space-y-3">
          {notificationList.map((item) => (
            <div key={item.key} className="flex items-center justify-between rounded-lg border border-slate-100 p-3">
              <div>
                <p className="text-sm font-medium text-slate-800">{item.label}</p>
                <p className="text-xs text-slate-500">{item.desc}</p>
              </div>
              <Toggle
                checked={notifications[item.key] ?? false}
                onChange={(checked) => updateSetting('notifications', { ...notifications, [item.key]: checked })}
              />
            </div>
          ))}
        </div>
      </Card>

      {/* Posting Schedule */}
      <Card className="p-5">
        <div className="mb-4 flex items-center gap-2">
          <Clock size={18} className="text-slate-500" />
          <h3 className="font-semibold text-slate-900">{t('settings.postingSchedule')}</h3>
        </div>
        <div className="space-y-2">
          {days.map((day) => (
            <div key={day} className="flex items-center gap-3">
              <span className="w-24 text-sm font-medium capitalize text-slate-700">{day}</span>
              <div className="flex flex-wrap gap-1.5">
                {(postingSchedule[day] ?? []).map((time, i) => (
                  <span key={i} className="rounded-lg bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-600">{time}</span>
                ))}
                {(postingSchedule[day] ?? []).length === 0 && (
                  <span className="text-xs text-slate-400">{t('settings.noPostsScheduled')}</span>
                )}
              </div>
            </div>
          ))}
        </div>
      </Card>

      {/* Brand */}
      <Card className="p-5">
        <div className="mb-4 flex items-center gap-2">
          <Palette size={18} className="text-slate-500" />
          <h3 className="font-semibold text-slate-900">{t('settings.brand')}</h3>
        </div>
        <div className="flex items-center gap-4">
          <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-emerald-500 to-teal-600 text-white shadow-sm">
            <svg viewBox="0 0 24 24" fill="currentColor" className="h-6 w-6">
              <path d="M8 5v14l11-7z" />
            </svg>
          </div>
          <div>
            <p className="text-sm font-semibold text-slate-900">ShortsFlow</p>
            <p className="text-xs text-slate-500">Automation Studio</p>
          </div>
        </div>
      </Card>
    </div>
  );
}

function ApiKeyRow({ label, desc, placeholder, value, onChange, show, onToggleShow, configured, saving, saved, onSave, docsUrl }: {
  label: string;
  desc: string;
  placeholder: string;
  value: string;
  onChange: (v: string) => void;
  show: boolean;
  onToggleShow: () => void;
  configured: boolean;
  saving: boolean;
  saved: boolean;
  onSave: () => void;
  docsUrl?: string;
}) {
  const { t } = useI18n();

  return (
    <div className="rounded-lg border border-slate-100 p-3">
      <div className="mb-2 flex items-center justify-between">
        <div>
          <p className="text-sm font-medium text-slate-800">{label}</p>
          <p className="text-xs text-slate-500">{desc}</p>
        </div>
        {configured && (
          <span className="flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-0.5 text-xs font-medium text-emerald-700">
            <Check size={10} /> {t('settings.configured')}
          </span>
        )}
      </div>
      <div className="flex gap-2">
        <div className="relative flex-1">
          <input
            type={show ? 'text' : 'password'}
            value={value}
            onChange={(e) => onChange(e.target.value)}
            placeholder={configured ? '•••••••• (enter new key to replace)' : placeholder}
            className="w-full rounded-lg border border-slate-200 px-3 py-2 pr-10 text-sm outline-none focus:border-slate-400"
          />
          <button onClick={onToggleShow} className="absolute right-2 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600">
            {show ? <EyeOff size={16} /> : <Eye size={16} />}
          </button>
        </div>
        <Button size="sm" onClick={onSave} disabled={!value.trim() || saving}>
          {saving ? <Loader2 size={14} className="animate-spin" /> : saved ? <Check size={14} /> : <Save size={14} />}
          {saved ? t('settings.saved') : t('settings.getApiKey').split(' ')[0]}
        </Button>
      </div>
      {docsUrl && (
        <a href={docsUrl} target="_blank" rel="noopener noreferrer"
          className="mt-1.5 inline-flex items-center gap-1 text-xs text-blue-600 hover:underline">
          {t('settings.getApiKey')} <ExternalLink size={10} />
        </a>
      )}
    </div>
  );
}
