import { describe, expect, it } from 'vitest';
import { bindPublishedContent, bindingId, buildBaseline, compareToBaseline, confidenceFor, createAnalyticsAdapterRegistry, createAnalyticsCollectionEngine, createAnalyticsReport, createDeterministicAnalyticsTestAdapter, freshnessOf, generateLearningProfile, insightsForPerformance, mergeObservations, normalizeAnalyticsPersistence, normalizeAnalyticsResponse, normalizeRawMetric, observationsFromSnapshot, recommendationsFromProfile, scorePerformance, type AnalyticsSnapshot, type PublishedContentBinding } from '@/core/analytics';
import type { PublishJob, PublishReceipt } from '@/core/publishing';

const binding = (remote = 'remote-1', accountId = 'account-1', channelRef: string | null = 'channel-1'): PublishedContentBinding => ({ projectId: 'project-1', variantId: 'variant-1', artifactFingerprint: 'artifact-1', publishJobId: 'job-1', publishReceiptId: `receipt-${remote}`, platform: 'youtube', accountId, accountRef: accountId, channelRef, remotePublicationId: remote, publishedAt: '2026-08-01T10:00:00.000Z' });
const snapshot = (remote: string, views: number | null, retention: number | null = 50, accountId = 'account-1', channelRef: string | null = 'channel-1', at = '2026-08-01T11:00:00.000Z'): AnalyticsSnapshot => normalizeAnalyticsResponse({ binding: binding(remote, accountId, channelRef), window: '24h', requestId: remote, adapterId: 'test', now: at, response: { metrics: [{ rawMetricId: 'views', value: views, observedAt: at, availability: views === null ? 'unavailable' : 'available' }, { rawMetricId: 'average_percentage_viewed', value: retention, observedAt: at, availability: retention === null ? 'unavailable' : 'available' }] } });

describe('Epic 7.9 analytics and learning engine', () => {
  it.each([
    ['views', 'views'], ['view_count', 'views'], ['impressions', 'impressions'], ['reach', 'reach'], ['likes', 'likes'], ['like_count', 'likes'], ['comments', 'comments'], ['comment_count', 'comments'], ['shares', 'shares'], ['saves', 'saves'], ['watch_time', 'watchTime'], ['average_watch_time', 'averageWatchTime'], ['average_percentage_viewed', 'averagePercentageViewed'], ['completion_rate', 'completionRate'], ['engagement_rate', 'engagementRate'], ['followers_gained', 'followersGained'], ['profile_visits', 'profileVisits'], ['clicks', 'clicks'],
  ])('maps canonical metric identity %s', (raw, expected) => expect(normalizeRawMetric(raw, 1).canonicalMetric).toBe(expected));
  it.each([undefined, null, '', 'NaN', Infinity, -Infinity, -0.1, {}, []])('rejects malformed external metric value %#', (value) => { const result = normalizeRawMetric('views', value); expect(result.availability).toBe('invalid'); expect(result.value).toBeNull(); });
  it.each([0, 0.01, 1, 50, 99.99, 100, 100.01, 1000])('bounds percentage metric safely: %s', (value) => { const result = normalizeRawMetric('completion_rate', value); expect(result.value).toBeGreaterThanOrEqual(0); expect(result.value).toBeLessThanOrEqual(100); });
  it.each(['views', 'likes', 'comments', 'shares', 'saves', 'watch_time', 'average_watch_time', 'average_percentage_viewed', 'completion_rate', 'engagement_rate', 'followers_gained', 'profile_visits', 'clicks'])('retains observed zero for %s', (raw) => { const result = normalizeRawMetric(raw, 0); expect(result.availability).toBe('available'); expect(result.value).toBe(0); });
  it.each([
    [0, 'fresh'], [1, 'fresh'], [60, 'fresh'], [360, 'fresh'], [361, 'delayed'], [720, 'delayed'], [1440, 'delayed'], [2880, 'delayed'], [2881, 'stale'], [10080, 'stale'],
  ])('classifies metric age at %s minutes', (ageMinutes, expected) => { const now = new Date('2026-08-06T12:00:00.000Z'); const observedAt = new Date(now.getTime() - Number(ageMinutes) * 60_000).toISOString(); expect(freshnessOf({ collectedAt: observedAt, observedAt }, now)).toBe(expected); });
  it.each([
    ['remote', 'account-1', 'channel-1', 'publication-1'], ['remote-2', 'account-1', 'channel-1', 'publication-2'], ['remote', 'account-2', 'channel-1', 'publication-3'], ['remote', 'account-1', 'channel-2', 'publication-4'], ['remote-3', 'account-3', 'channel-3', 'publication-5'], ['remote-4', 'account-4', null, 'publication-6'], ['remote-5', 'account-5', 'channel-5', 'publication-7'], ['remote-6', 'account-6', 'channel-6', 'publication-8'],
  ])('keeps publication identity account-scoped: %s/%s/%s', (remote, accountId, channelRef, expected) => { const id = bindingId({ binding: binding(remote, accountId, channelRef) }); expect(id).toMatch(/^publication-/); expect(id).not.toBe(expected); });
  it.each(['1h', '6h', '24h', '48h', '7d'] as const)('preserves observation window %s in canonical snapshots', (window) => { const item = normalizeAnalyticsResponse({ binding: binding(), window, requestId: window, adapterId: 'test', now: '2026-08-06T12:00:00.000Z', response: { metrics: [{ rawMetricId: 'views', value: 1 }] } }); expect(item.metrics[0].window).toBe(window); });
  it('keeps snapshot IDs distinct for different bindings with identical collection inputs', () => { const input = { window: '24h' as const, requestId: 'request', adapterId: 'test', now: '2026-08-06T12:00:00.000Z', response: { metrics: [{ rawMetricId: 'views', value: 1 }] } }; const first = normalizeAnalyticsResponse({ ...input, binding: binding('remote', 'account-a', 'channel-a') }); const second = normalizeAnalyticsResponse({ ...input, binding: binding('remote', 'account-b', 'channel-b') }); expect(first.id).not.toBe(second.id); });
  it.each([['views', 0, 'available', 0], ['views', '0', 'available', 0], ['average_percentage_viewed', 101, 'available', 100], ['views', -1, 'invalid', null], ['views', 'not-number', 'invalid', null], ['unknown_metric', 1, 'unsupported', null]])('normalizes %s safely', (raw, value, availability, expected) => { const normalized = normalizeRawMetric(raw, value); expect(normalized.availability).toBe(availability); expect(normalized.value).toBe(expected); });
  it('uses canonical units instead of mismatched adapter units', () => { const normalized = normalizeRawMetric('views', 100, 'percentage'); expect(normalized.unit).toBe('count'); expect(normalized.value).toBe(100); });
  it('drops malformed adapter timestamps without degrading freshness or confidence', () => { const now = new Date().toISOString(); const item = normalizeAnalyticsResponse({ binding: binding(), window: '24h', requestId: 'invalid-observed-at', adapterId: 'test', now, response: { metrics: [{ rawMetricId: 'views', value: 100, unit: 'percentage', observedAt: 'not-a-date' }] } }); expect(item.metrics[0]).toMatchObject({ unit: 'count', source: { observedAt: null } }); expect(item.observedAt).toBeNull(); expect(item.freshness).toBe('fresh'); expect(confidenceFor({ sampleSize: 5, availableDimensions: 1, freshness: item.freshness }).factors.freshness).toBe(1); });
  it('retains valid adapter timestamps', () => { const observedAt = '2026-08-01T10:00:00.000Z'; const item = normalizeAnalyticsResponse({ binding: binding(), window: '24h', requestId: 'valid-observed-at', adapterId: 'test', now: '2026-08-01T11:00:00.000Z', response: { metrics: [{ rawMetricId: 'views', value: 100, observedAt }] } }); expect(item.metrics[0].source.observedAt).toBe(observedAt); expect(item.observedAt).toBe(observedAt); });
  it.each(['unavailable', 'unsupported', 'not-ready', 'permission-missing'] as const)('preserves %s instead of making it zero', (availability) => { const metric = normalizeRawMetric('views', 10, undefined, availability); expect(metric.value).toBeNull(); expect(metric.availability).toBe(availability); });
  it('does not let an unknown adapter metric hide a later valid views metric', () => { const item = normalizeAnalyticsResponse({ binding: binding(), window: '24h', requestId: 'unknown-first', adapterId: 'test', now: '2026-08-01T11:00:00.000Z', response: { metrics: [{ rawMetricId: 'unmapped_metric', value: 999 }, { rawMetricId: 'views', value: 42 }] } }); expect(item.metrics).toHaveLength(1); expect(item.metrics.find((metric) => metric.name === 'views')?.value).toBe(42); });
  it('carries source provenance and detects missing retention', () => { const item = snapshot('one', 0, null); expect(item.metrics[0].source.platform).toBe('youtube'); expect(item.metrics[0].value).toBe(0); expect(item.diagnostics.some((diagnostic) => diagnostic.code === 'missing-retention')).toBe(true); });
  it.each([['2026-08-06T11:01:00.000Z', 'fresh'], ['2026-08-05T11:00:00.000Z', 'delayed'], ['2026-08-01T11:00:00.000Z', 'stale'], ['invalid', 'unknown']])('models freshness: %s', (at, expected) => expect(freshnessOf({ collectedAt: '2026-08-01T11:00:00.000Z', observedAt: at }, new Date('2026-08-06T12:00:00.000Z'))).toBe(expected));
  it('orders and deduplicates observations deterministically', () => { const early = snapshot('one', 2, 50, 'account-1', 'channel-1', '2026-08-01T10:00:00.000Z'); const later = snapshot('one', 3, 55, 'account-1', 'channel-1', '2026-08-01T12:00:00.000Z'); const merged = mergeObservations(observationsFromSnapshot(later), observationsFromSnapshot(early)); expect(merged).toHaveLength(4); expect(merged[0].observedAt <= merged.at(-1)!.observedAt).toBe(true); });
  it('isolates baselines by account and channel', () => { const history = [snapshot('a', 10), snapshot('b', 20), snapshot('c', 30), snapshot('d', 40), snapshot('e', 50), snapshot('other', 1000, 50, 'other-account')]; const baseline = buildBaseline(history, binding('current'), 'views', '24h'); expect(baseline.sampleSize).toBe(5); expect(baseline.median).toBe(30); });
  it('counts repeated refreshes as one comparable publication', () => { const history = [snapshot('a', 10), snapshot('a', 99, 50, 'account-1', 'channel-1', '2026-08-01T12:00:00.000Z'), snapshot('b', 20), snapshot('c', 30), snapshot('d', 40), snapshot('e', 50)]; const baseline = buildBaseline(history, binding('current'), 'views', '24h'); expect(baseline.sampleSize).toBe(5); expect(baseline.median).toBe(40); });
  it('keeps the latest matching window for each comparable publication', () => { const prior24h = ['a', 'b', 'c', 'd', 'e'].map((id, index) => snapshot(id, 10 + index * 10)); const newer1h = prior24h.map((item, index) => normalizeAnalyticsResponse({ binding: item.binding, window: '1h', requestId: `1h-${index}`, adapterId: 'test', now: '2026-08-01T12:00:00.000Z', response: { metrics: [{ rawMetricId: 'views', value: 100 + index }] } })); const baseline = buildBaseline([...prior24h, ...newer1h], binding('current'), 'views', '24h'); expect(baseline.sampleSize).toBe(5); expect(baseline.median).toBe(30); });
  it('keeps older requested-window snapshots in learning cohorts', () => { const prior24h = ['a', 'b', 'c', 'd', 'e'].map((id) => snapshot(id, 10)); const newer1h = prior24h.map((item, index) => normalizeAnalyticsResponse({ binding: item.binding, window: '1h', requestId: `1h-${index}`, adapterId: 'test', now: '2026-08-01T12:00:00.000Z', response: { metrics: [{ rawMetricId: 'views', value: 100 }, { rawMetricId: 'average_percentage_viewed', value: 90 }] } })); const profile = generateLearningProfile([...prior24h, ...newer1h], [], { platform: 'youtube', accountId: 'account-1', accountRef: 'account-1', channelRef: 'channel-1' }, '24h'); expect(profile.sampleSize).toBe(5); expect(profile.status).toBe('ready'); });
  it('does not let refreshes satisfy the learning minimum', () => { const refreshes = Array.from({ length: 5 }, (_, index) => snapshot('same-publication', 10 + index, 50, 'account-1', 'channel-1', `2026-08-01T${String(11 + index).padStart(2, '0')}:00:00.000Z`)); const profile = generateLearningProfile(refreshes, [], { platform: 'youtube', accountId: 'account-1', accountRef: 'account-1', channelRef: 'channel-1' }, '24h'); expect(profile.status).toBe('cold-start'); expect(profile.sampleSize).toBe(1); });
  it('requires comparable same-window evidence', () => { const current = snapshot('current', 20); const history = [snapshot('a', 10), snapshot('b', 20), snapshot('c', 30), snapshot('d', 40), snapshot('e', 50)]; expect(compareToBaseline(current, history, 'views', '1h').status).toBe('unavailable'); });
  it('does not divide by zero baseline', () => { const current = snapshot('current', 10); const history = ['a', 'b', 'c', 'd', 'e'].map((id) => snapshot(id, 0)); expect(compareToBaseline(current, history, 'views', '24h').deltaPercent).toBeNull(); });
  it('produces no score where dimensions are unavailable', () => { const current = snapshot('current', null, null); const score = scorePerformance(current, [], '24h'); expect(score.score.overall).toBeNull(); expect(Number.isFinite(score.score.confidence)).toBe(true); });
  it('lowers confidence for sparse, stale, outlier-heavy data', () => { const weak = confidenceFor({ sampleSize: 2, availableDimensions: 0, freshness: 'stale', outlierCount: 2 }); const strong = confidenceFor({ sampleSize: 20, availableDimensions: 5, freshness: 'fresh', outlierCount: 0 }); expect(weak.score).toBeLessThan(strong.score); expect(weak.level).toBe('low'); });
  it('marks mixed-age scoring metrics stale and lowers learning freshness confidence', () => { const now = new Date(); const freshAt = new Date(now.getTime() - 60_000).toISOString(); const staleAt = new Date(now.getTime() - 72 * 60 * 60_000).toISOString(); const mixed = (id: string) => normalizeAnalyticsResponse({ binding: binding(id), window: '24h', requestId: id, adapterId: 'test', now: now.toISOString(), response: { metrics: [{ rawMetricId: 'views', value: 100, observedAt: freshAt }, { rawMetricId: 'average_percentage_viewed', value: 50, observedAt: staleAt }] } }); const cohort = ['a', 'b', 'c', 'd', 'e'].map(mixed); const profile = generateLearningProfile(cohort, [], { platform: 'youtube', accountId: 'account-1', accountRef: 'account-1', channelRef: 'channel-1' }, '24h'); expect(cohort[0].freshness).toBe('stale'); expect(profile.confidence.factors.freshness).toBe(.45); });
  it('enters cold start before minimum comparable samples', () => { const profile = generateLearningProfile([snapshot('a', 10), snapshot('b', 11)], [], { platform: 'youtube', accountId: 'account-1', accountRef: 'account-1', channelRef: 'channel-1' }, '24h'); expect(profile.status).toBe('cold-start'); expect(recommendationsFromProfile(profile)).toEqual([]); });
  it('does not count other windows toward learning readiness', () => { const oneHourCohort = ['a', 'b', 'c', 'd', 'e'].map((id) => normalizeAnalyticsResponse({ binding: binding(id), window: '1h', requestId: id, adapterId: 'test', now: '2026-08-01T11:00:00.000Z', response: { metrics: [{ rawMetricId: 'views', value: 10 }, { rawMetricId: 'average_percentage_viewed', value: 50 }] } })); const profile = generateLearningProfile(oneHourCohort, [], { platform: 'youtube', accountId: 'account-1', accountRef: 'account-1', channelRef: 'channel-1' }, '24h'); expect(profile.status).toBe('cold-start'); expect(profile.sampleSize).toBe(0); expect(profile.observationWindow).toBe('24h'); });
  it('keeps learning channel-isolated', () => { const cohort = ['a', 'b', 'c', 'd', 'e'].map((id, index) => snapshot(id, 10 + index, 50, 'account-1', 'channel-1')); const profile = generateLearningProfile([...cohort, snapshot('other', 999, 99, 'account-2', 'channel-2')], [], { platform: 'youtube', accountId: 'account-1', accountRef: 'account-1', channelRef: 'channel-1' }, '24h'); expect(profile.sampleSize).toBe(5); });
  it('keeps persistence bounded and malformed snapshots isolated', () => { const many = Array.from({ length: 65 }, (_, index) => { const item = snapshot('same-publication', index, 50, 'account-1', 'channel-1', `2026-08-${String((index % 20) + 1).padStart(2, '0')}T11:00:00.000Z`); return { ...item, id: `snapshot-${index}`, requestId: `request-${index}` }; }); const state = normalizeAnalyticsPersistence({ snapshots: [{ bad: true }, ...many] }); expect(state.snapshots.length).toBeLessThanOrEqual(60); expect(state.snapshots.every((item) => item.binding.remotePublicationId)).toBe(true); });
  it('retains 60 complete multi-metric snapshots per publication', () => { const many = Array.from({ length: 65 }, (_, index) => { const at = new Date(Date.UTC(2026, 7, 1, 11, 0, index)).toISOString(); const item = snapshot('same-publication', index, 50, 'account-1', 'channel-1', at); return { ...item, metrics: Array.from({ length: 16 }, () => ({ ...item.metrics[0] })), requestId: `request-${index}` }; }); const state = normalizeAnalyticsPersistence({ snapshots: many }); expect(state.snapshots).toHaveLength(60); expect(state.snapshots.every((item) => item.metrics.length === 16)).toBe(true); expect(state.snapshots.map((item) => item.requestId)).not.toContain('request-0'); expect(state.snapshots.map((item) => item.requestId)).toContain('request-64'); });
  it('ignores malformed persisted bindings without dropping valid snapshots', () => { const valid = snapshot('valid', 10); const state = normalizeAnalyticsPersistence({ snapshots: [{ id: 'invalid', metrics: [], binding: null }, valid] }); expect(state.snapshots).toHaveLength(1); expect(state.snapshots[0].id).toBe(valid.id); });
  it('isolates malformed persisted learning records and metrics while retaining valid analytics', () => { const validSnapshot = snapshot('valid', 10); const cohort = ['a', 'b', 'c', 'd', 'e'].map((id, index) => snapshot(id, 10 + index)); const validProfile = generateLearningProfile(cohort, [], { platform: 'youtube', accountId: 'account-1', accountRef: 'account-1', channelRef: 'channel-1' }, '24h'); const validInsight = insightsForPerformance(scorePerformance(snapshot('current', 100), cohort, '24h'), snapshot('current', 100))[0]; const validRecommendation = { id: 'recommendation', channelBinding: validProfile.channelBinding, recommendation: 'Test this.', reason: 'Observed evidence.', expectedDirection: 'explore', confidence: validProfile.confidence, evidence: [{ signalId: 'signal', relation: 'associated-with', sampleSize: 5, effect: 1, limitations: [] }], limitations: [], autoApplyStatus: 'planned-only', generatedAt: '2026-08-01T11:00:00.000Z' }; const state = normalizeAnalyticsPersistence({ snapshots: [{ ...validSnapshot, metrics: [{ ...validSnapshot.metrics[0], availability: undefined }] }, validSnapshot], profiles: [{ ...validProfile, strongestSignals: undefined }, validProfile], insights: [{ ...validInsight, evidence: undefined }, validInsight], recommendations: [{ ...validRecommendation, evidence: undefined }, validRecommendation] }); expect(state.snapshots).toEqual([expect.objectContaining({ id: validSnapshot.id })]); expect(state.profiles).toEqual([expect.objectContaining({ id: validProfile.id })]); expect(state.insights).toEqual([expect.objectContaining({ id: validInsight.id })]); expect(state.recommendations).toEqual([expect.objectContaining({ id: validRecommendation.id })]); });
  it('exports canonical JSON without credentials', () => { const report = createAnalyticsReport({ version: 1, snapshots: [snapshot('a', 1)], attributions: [], profiles: [], insights: [], recommendations: [], refreshes: {} }); expect(JSON.stringify(report)).not.toMatch(/credential|oauth|token|secret/i); expect(report.bindings).toHaveLength(1); });
  it('honestly reports production platform capabilities', () => { const registry = createAnalyticsAdapterRegistry(); expect(registry.get('youtube').capability().adapterStatus).toBe('authentication-required'); expect(registry.get('tiktok').capability().adapterStatus).toBe('planned-only'); expect(registry.get('instagram').capability().supportedMetrics).toEqual([]); });
  it('does not expose a test adapter as the production registry', () => { const adapter = createDeterministicAnalyticsTestAdapter('youtube', async () => ({ metrics: [] })); expect(adapter.capability().version).toBe('test-only'); expect(createAnalyticsAdapterRegistry().get('youtube').capability().version).not.toBe('test-only'); });
  it('coalesces rate limited refreshes', async () => { const adapter = { platform: 'youtube' as const, capability: () => createAnalyticsAdapterRegistry().get('youtube').capability(), collect: async () => { throw Object.assign(new Error('429'), { status: 429, retryAfterMs: 20_000 }); } }; const engine = createAnalyticsCollectionEngine({ get: () => adapter, list: () => [adapter] }); const first = await engine.collect({ binding: binding(), window: '24h' }); const second = await engine.collect({ binding: binding(), window: '24h' }); expect(first.status).toBe('rate-limited'); expect(second.status).toBe('rate-limited'); expect(engine.getCooldown(binding())).not.toBeNull(); });
  it('restores a persisted account cooldown in a new collection engine', async () => { const adapter = { platform: 'youtube' as const, capability: () => createAnalyticsAdapterRegistry().get('youtube').capability(), collect: async () => ({ metrics: [{ rawMetricId: 'views', value: 1 }] }) }; const prior = createAnalyticsCollectionEngine({ get: () => adapter, list: () => [adapter] }); const cooldownUntil = new Date(Date.now() + 20_000).toISOString(); const restored = createAnalyticsCollectionEngine({ get: () => adapter, list: () => [adapter] }); restored.restoreCooldowns({ [prior.refreshKey(binding())]: { latestRequestId: 'limited-request', fetchedAt: new Date().toISOString(), cooldownUntil } }); const result = await restored.collect({ binding: binding(), window: '24h' }); expect(result.status).toBe('rate-limited'); expect(restored.getCooldown(binding())).toBe(cooldownUntil); });
  it('preserves a concurrent account cooldown after another publication succeeds', async () => { let resolveSuccess: (value: { metrics: { rawMetricId: string; value: number }[] }) => void = () => undefined; const adapter = { platform: 'youtube' as const, capability: () => createAnalyticsAdapterRegistry().get('youtube').capability(), collect: async (item: PublishedContentBinding) => item.remotePublicationId === 'success' ? new Promise<{ metrics: { rawMetricId: string; value: number }[] }>((resolve) => { resolveSuccess = resolve; }) : Promise.reject(Object.assign(new Error('429'), { status: 429, retryAfterMs: 20_000 })) }; const engine = createAnalyticsCollectionEngine({ get: () => adapter, list: () => [adapter] }); const pendingSuccess = engine.collect({ binding: binding('success'), window: '24h' }); const limited = await engine.collect({ binding: binding('limited'), window: '24h' }); resolveSuccess({ metrics: [{ rawMetricId: 'views', value: 1 }, { rawMetricId: 'average_percentage_viewed', value: 50 }] }); const success = await pendingSuccess; expect(limited.status).toBe('rate-limited'); expect(success.status).toBe('completed'); expect(engine.getCooldown(binding('success'))).not.toBeNull(); const cleanEngine = createAnalyticsCollectionEngine({ get: () => adapter, list: () => [adapter] }); const cleanSuccess = cleanEngine.collect({ binding: binding('success'), window: '24h' }); resolveSuccess({ metrics: [{ rawMetricId: 'views', value: 1 }, { rawMetricId: 'average_percentage_viewed', value: 50 }] }); await cleanSuccess; expect(cleanEngine.getCooldown(binding('success'))).toBeNull(); });
  it('ignores a superseded failure after a newer collection succeeds', async () => { let calls = 0; let rejectFirst: (reason?: unknown) => void = () => undefined; const adapter = { platform: 'youtube' as const, capability: () => createAnalyticsAdapterRegistry().get('youtube').capability(), collect: async () => { calls += 1; if (calls === 1) return new Promise<never>((_, reject) => { rejectFirst = reject; }); return { metrics: [{ rawMetricId: 'views', value: 1 }, { rawMetricId: 'average_percentage_viewed', value: 50 }] }; } }; const engine = createAnalyticsCollectionEngine({ get: () => adapter, list: () => [adapter] }); const first = engine.collect({ binding: binding(), window: '24h', requestId: 'first' }); const second = await engine.collect({ binding: binding(), window: '24h', requestId: 'second' }); rejectFirst(Object.assign(new Error('429'), { status: 429, retryAfterMs: 20_000 })); const stale = await first; expect(second.status).toBe('completed'); expect(stale.status).toBe('partial'); expect(engine.getCooldown(binding())).toBeNull(); });
  it('rejects mismatched receipt binding', () => { const job = { id: 'job', projectId: 'p', variantId: null, target: { platform: 'youtube', accountId: 'a', channelRef: 'c' }, accountBinding: { id: 'a', accountRef: 'account', platform: 'youtube', displayName: 'A', channelRef: 'c', credentialRef: null, authenticated: false, createdAt: 'now' }, artifact: { artifactFingerprint: 'fp' } } as PublishJob; const receipt = { jobId: 'other', remotePublishId: 'r', platform: 'youtube', accountRef: 'account', publishedAt: 'now', artifactFingerprint: 'fp' } as PublishReceipt; expect(() => bindPublishedContent(job, receipt)).toThrow(/receipt/); });
  it('rejects unverified and non-published receipts at the analytics binding boundary', () => { const job = { id: 'job', projectId: 'p', variantId: null, target: { platform: 'youtube', accountId: 'a', channelRef: 'c' }, accountBinding: { id: 'a', accountRef: 'account', platform: 'youtube', displayName: 'A', channelRef: 'c', credentialRef: null, authenticated: false, createdAt: 'now' }, artifact: { artifactFingerprint: 'fp' } } as PublishJob; const receipt = { jobId: 'job', remotePublishId: 'r', platform: 'youtube', accountRef: 'account', publishedAt: 'now', artifactFingerprint: 'fp', metadataFingerprint: 'metadata', scheduleIntent: { mode: 'now', scheduledAtUtc: null, timezone: 'UTC' }, remoteUrl: null, verification: { valid: false, remotePublishId: 'r', remoteState: 'processing', checkedAt: 'now', issues: [] } } as PublishReceipt; expect(() => bindPublishedContent(job, receipt)).toThrow(/verified/); expect(() => bindPublishedContent(job, { ...receipt, verification: { ...receipt.verification, valid: true } })).toThrow(/not published/); });
});
