import { describe, expect, it, vi } from 'vitest';
import { createPublishAdapterRegistry, createPublishQueue, evaluatePublishReadiness, idempotencyKey, isScheduleDue, normalizePublishQueue, validatePublishMetadata, type PublishJob } from '@/core/publishing';

const artifact = { path: 'C:/exports/video.mp4', sizeBytes: 100, durationMs: 1000, verified: true, diagnostics: {}, createdAt: 'now' };
const metadata = { title: 'A title', description: 'Description', hashtags: ['#shorts'], caption: 'Caption', visibility: 'private' as const, language: null, category: null, audienceFlags: {}, thumbnailPath: null, playlistRef: null, commentsEnabled: true };
const baseJob = (state: PublishJob['state'] = 'queued'): PublishJob => ({ id: 'job-1', projectId: 'p1', variantId: 'v1', target: { platform: 'youtube', accountId: 'a1', channelRef: 'c1' }, accountBinding: { id: 'a1', platform: 'youtube', accountRef: 'account-1', displayName: 'Account', channelRef: 'c1', credentialRef: 'credential-ref', authenticated: true, createdAt: 'now' }, artifact: { artifactPath: artifact.path, artifactFingerprint: 'artifact-1', projectId: 'p1', variantId: 'v1', exportJobId: 'e1', verified: true, sizeBytes: 100, durationMs: 1000, diagnostics: {}, sourceManifestFingerprint: 'source-1' }, metadata, schedule: { mode: 'now', scheduledAtUtc: null, timezone: 'UTC' }, state, progress: { state, percent: 0, message: '', remoteState: null, updatedAt: 'now' }, readiness: { ready: true, status: 'safe', issues: [], warnings: [], diagnostics: [] }, idempotencyKey: 'idem-1', approvalFingerprint: 'approval-1', approvedAt: 'now', attempts: [], maxAttempts: 3, failure: null, receipt: null, remotePublishId: null, createdAt: 'now', updatedAt: 'now' });

describe('Epic 7.8 publishing engine', () => {
  it.each(['youtube', 'tiktok', 'instagram'] as const)('reports honest capability for %s', (platform) => { const capability = createPublishAdapterRegistry().get(platform).capability(); expect(['authentication-required', 'planned-only']).toContain(capability.adapterStatus); });
  it('blocks unverified, zero-byte and pseudo artifacts', () => { const result = evaluatePublishReadiness({ artifact: { ...artifact, verified: false, sizeBytes: 0, path: 'render-plan://plan' }, target: { platform: 'youtube', accountId: 'a', channelRef: null }, metadata, projectId: 'p', sourceManifestFingerprint: 'f' }); expect(result.ready).toBe(false); expect(result.issues.length).toBeGreaterThan(2); });
  it.each(['', 'x'.repeat(101)])('validates title constraints', (title) => { const result = validatePublishMetadata({ ...metadata, title }, createPublishAdapterRegistry().get('youtube').capability()); expect(result.issues.some((item) => item.field === 'title')).toBe(true); });
  it('keeps idempotency stable and target-bound', () => { const input = { artifactFingerprint: 'a', target: { platform: 'youtube' as const, accountId: 'account', channelRef: 'channel' }, intent: 'revision-1' }; expect(idempotencyKey(input)).toBe(idempotencyKey(input)); expect(idempotencyKey({ ...input, target: { ...input.target, accountId: 'other' } })).not.toBe(idempotencyKey(input)); });
  it('normalizes in-flight jobs to interrupted and clears active state', () => { const snapshot = normalizePublishQueue({ jobs: [baseJob('uploading'), baseJob('processing')], activeJobId: 'job-1', paused: false }); expect(snapshot.activeJobId).toBeNull(); expect(snapshot.jobs.every((job) => job.state === 'interrupted')).toBe(true); expect(normalizePublishQueue(snapshot)).toEqual(snapshot); });
  it('does not run scheduled jobs before their UTC time', async () => { const run = vi.fn(async () => ({ jobId: 'job-1', remotePublishId: 'remote', platform: 'youtube' as const, accountRef: 'a', publishedAt: 'now', artifactFingerprint: 'a', metadataFingerprint: 'm', scheduleIntent: { mode: 'scheduled' as const, scheduledAtUtc: '2099-01-01T00:00:00.000Z', timezone: 'UTC' }, remoteUrl: null, verification: { valid: true, remotePublishId: 'remote', remoteState: 'published' as const, checkedAt: 'now', issues: [] } })); const queue = createPublishQueue({ run, reconcile: async (job) => job, cancel: async () => true }); queue.enqueue({ ...baseJob(), schedule: { mode: 'scheduled', scheduledAtUtc: '2099-01-01T00:00:00.000Z', timezone: 'UTC' }, state: 'scheduled' }); await queue.start(new Date('2026-01-01T00:00:00.000Z')); expect(run).not.toHaveBeenCalled(); expect(isScheduleDue(queue.list()[0].schedule, new Date('2026-01-01T00:00:00.000Z'))).toBe(false); });
  it('deduplicates enqueue by logical idempotency key', () => { const queue = createPublishQueue({ run: async () => { throw new Error('not called'); }, reconcile: async (job) => job, cancel: async () => true }); const first = baseJob(); expect(queue.enqueue(first)).toBe(first); expect(queue.enqueue({ ...first, id: 'different-id' })).toBe(first); expect(queue.list()).toHaveLength(1); });
  it('cancelled jobs cannot become published after late completion', async () => { let release!: (receipt: any) => void; const queue = createPublishQueue({ run: async () => new Promise((resolve) => { release = resolve; }), reconcile: async (job) => job, cancel: async () => true }); const job = baseJob(); queue.enqueue(job); const started = queue.start(); await new Promise((resolve) => setTimeout(resolve, 0)); await queue.cancel(job.id); release({ jobId: job.id, remotePublishId: 'remote', platform: 'youtube', accountRef: 'a', publishedAt: 'now', artifactFingerprint: 'a', metadataFingerprint: 'm', scheduleIntent: job.schedule, remoteUrl: null, verification: { valid: true, remotePublishId: 'remote', remoteState: 'published', checkedAt: 'now', issues: [] } }); await started; expect(queue.get(job.id)?.state).toBe('cancelled'); });
  it('does not mark an unverified remote response as published', async () => { const queue = createPublishQueue({ run: async (job) => ({ jobId: job.id, remotePublishId: 'remote', platform: 'youtube' as const, accountRef: 'a', publishedAt: 'now', artifactFingerprint: 'a', metadataFingerprint: 'm', scheduleIntent: job.schedule, remoteUrl: null, verification: { valid: false, remotePublishId: 'remote', remoteState: 'processing' as const, checkedAt: 'now', issues: ['processing'] } }), reconcile: async (job) => job, cancel: async () => true }); const job = baseJob(); queue.enqueue(job); await queue.start(); expect(queue.get(job.id)?.state).toBe('failed'); });
});
