import { createManifestRevisionId } from '@/core/editing/editPlanCompiler';
import type { RenderManifest } from '@/core/media';
import { getPlatformProfile } from './profiles';
import { platformCapability } from './capabilities';
import type { PlatformId, PlatformOperation, PlatformProfile, PlatformReadinessReport, PlatformScore } from './types';
const score = (value: number, evidence: string[], blockingIssues: string[] = [], warnings: string[] = [], quickWins: string[] = []): PlatformScore => ({ value: Math.max(0, Math.min(100, Math.round(value))), evidence, blockingIssues, warnings, quickWins });
function ratio(manifest: RenderManifest): number { return manifest.render.width / Math.max(1, manifest.render.height); }
function ratioValue(value: string): number { const [width, height] = value.split(':').map(Number); return height > 0 ? width / height : Number.NaN; }
function op(manifest: RenderManifest, platformId: PlatformId, type: PlatformOperation['type'], scope: PlatformOperation['scope'], reason: string, parameters: Record<string, string | number | boolean>, priority: number, confidence: number, now: string): PlatformOperation { const capability = platformCapability(type); return { id: `${type}-${manifest.projectId}-${platformId}`, projectId: manifest.projectId, targetPlatform: platformId, sourceManifestFingerprint: createManifestRevisionId(manifest), sourceManifestFingerprintVersion: 2, type, scope, priority, reason, evidence: [reason], parameters, expectedImpact: capability.status === 'implemented' ? 'Manifest/profile alignment' : 'Requires manual render or a future capability', confidence, automaticallyApplicable: capability.status === 'implemented', capability, dependencies: [], conflicts: [], status: capability.status === 'implemented' ? 'proposed' : 'planned-only', createdAt: now }; }
export function analyzeReadiness(manifest: RenderManifest, profile: PlatformProfile): PlatformReadinessReport { const r = ratio(manifest); const target = profile.preferredAspectRatio === '9:16' ? 9 / 16 : profile.preferredAspectRatio === '16:9' ? 16 / 9 : 1; const format = Math.abs(r - target) < .02 ? 100 : Math.max(30, 100 - Math.abs(r - target) * 80); const duration = manifest.durationMs >= profile.durationPolicy.minMs && manifest.durationMs <= profile.durationPolicy.maxMs ? 100 : 65; const subtitleCount = manifest.subtitles.cues.length; const subtitle = subtitleCount ? 85 : 25; const audio = manifest.audio.voice.length ? 90 : 35; const scenes = manifest.timeline.scenes.length; const pacing = scenes ? 85 : 30; const sections = { formatFit: score(format, [`Source ratio ${r.toFixed(3)}, target ${profile.preferredAspectRatio}.`]), durationFit: score(duration, [`Duration ${manifest.durationMs}ms checked against versioned policy.`]), safeAreaFit: score(85, ['Normalized safe-area profile is available.']), subtitleFit: score(subtitle, [`${subtitleCount} subtitle cues evaluated.`]), audioFit: score(audio, ['Voice and audio profile binding evaluated.']), visualFit: score(scenes ? 85 : 25, [`${scenes} scenes evaluated.`]), hookFit: score(manifest.durationMs <= profile.hookGuidance.maxMs * 10 ? 80 : 55, ['Hook guidance is heuristic and deterministic.']), pacingFit: score(pacing, ['Scene count and duration are used; no semantic timeline rewrite is performed.']), exportCompatibility: score(90, ['MP4/H.264/AAC baseline is supported by the existing render path.']) }; const overall = Math.round(Object.values(sections).reduce((sum, value) => sum + value.value, 0) / Object.keys(sections).length); return { platformId: profile.id, profileVersion: profile.version, ...sections, overall }; }
export function createOperations(manifest: RenderManifest, platformId: PlatformId, profile: PlatformProfile, now: string): PlatformOperation[] { const result: PlatformOperation[] = []; const ratioMatches = Math.abs(ratio(manifest) - ratioValue(profile.preferredAspectRatio)) < .01; if (manifest.render.width !== profile.preferredResolution.width || manifest.render.height !== profile.preferredResolution.height) { const resolution = op(manifest, platformId, 'change-resolution', 'manifest', ratioMatches ? 'Preferred platform resolution differs from source.' : 'Resolution is blocked until an aspect-ratio or pad capability is available.', { width: profile.preferredResolution.width, height: profile.preferredResolution.height }, 90, ratioMatches ? .98 : .8, now); if (!ratioMatches) { resolution.automaticallyApplicable = false; resolution.status = 'planned-only'; resolution.capability = { type: 'change-resolution', status: 'planned-only', reason: 'Geometry must remain atomic when source and target aspect ratios differ.' }; resolution.dependencies = [`change-aspect-ratio-${manifest.projectId}-${platformId}`]; } result.push(resolution); } if (!ratioMatches) result.push(op(manifest, platformId, 'change-aspect-ratio', 'manifest', 'Target aspect ratio requires crop, pad, or reframe capability.', { aspectRatio: profile.preferredAspectRatio, scalingMode: 'crop' }, 95, .82, now)); result.push(op(manifest, platformId, 'adjust-safe-area', 'manifest', 'Apply versioned normalized platform safe-area metadata.', { ...profile.safeAreaInsets }, 80, .9, now)); result.push(op(manifest, platformId, 'change-caption-profile', 'subtitle', `Use ${profile.subtitleProfile.style} caption guidance.`, { ...profile.subtitleProfile }, 70, .9, now)); result.push(op(manifest, platformId, 'normalize-audio-profile', 'audio', `Use ${profile.loudnessProfile.integratedLufs} LUFS configurable profile guidance.`, { ...profile.loudnessProfile }, 60, .88, now)); result.push(op(manifest, platformId, 'change-video-codec', 'export', 'Codec compatibility is planned for export orchestration.', { codec: 'h264' }, 40, .8, now)); return result; }
