import { createManifestRevisionId } from '@/core/editing/editPlanCompiler';
import { deepClone, stableId } from '@/core/editing/utils';
import type { RenderManifest } from '@/core/media';
import { getPlatformProfile } from './profiles';
import { analyzeReadiness, createOperations } from './analyzers';
import type { PlatformOperation, PlatformOptimizationEngine, PlatformOptimizationInput, PlatformOptimizationPlan, PlatformOptimizationPreview, PlatformVariantSnapshot } from './types';
const FINGERPRINT_VERSION = 2;
export function canonicalApprovedOperationIds(plan: PlatformOptimizationPlan, ids: readonly string[]): string[] { const known = new Set(plan.operations.map((item) => item.id)); return [...new Set(ids)].filter((id) => known.has(id)).sort(); }
export function operationSignature(ids: readonly string[]): string { return stableId('platform-ops', [...ids].sort().join('|')); }
function effectiveOperations(plan: PlatformOptimizationPlan, approved: readonly string[]): PlatformOperation[] { const selected = new Set(canonicalApprovedOperationIds(plan, approved)); return plan.operations.filter((item) => item.capability.status === 'implemented' && (item.automaticallyApplicable || selected.has(item.id))); }
function planFingerprint(plan: PlatformOptimizationPlan): string { return stableId('platform-plan', `${plan.sourceManifestFingerprint}:${plan.platformId}:${plan.profile.version}:${plan.operations.map((item) => `${item.id}:${item.capability.status}:${item.automaticallyApplicable}`).join('|')}`); }
function abort(signal?: AbortSignal): void { if (signal?.aborted) { const error = new Error('Platform optimization aborted.'); error.name = 'AbortError'; throw error; } }
export function createPlatformOptimizationEngine(): PlatformOptimizationEngine {
  const consumedPreviewIds = new Set<string>();
  return {
    analyze(input, signal) { abort(signal); const now = input.now ?? new Date().toISOString(); const profile = getPlatformProfile(input.platformId, input.profileOverride); const fingerprint = createManifestRevisionId(input.manifest); const operations = createOperations(input.manifest, profile.id, profile, now); const plan = { id: '', projectId: input.manifest.projectId, platformId: profile.id, profile, sourceManifestFingerprint: fingerprint, sourceManifestFingerprintVersion: FINGERPRINT_VERSION, operations, readiness: analyzeReadiness(input.manifest, profile), variant: { targetWidth: profile.preferredResolution.width, targetHeight: profile.preferredResolution.height, targetAspectRatio: profile.preferredAspectRatio, scalingMode: 'scale' as const, safeAreaInsets: profile.safeAreaInsets, manualReviewRequired: true }, warnings: [...profile.warnings], createdAt: now }; return { ...plan, id: planFingerprint(plan) }; },
    preview(plan, manifest, approvedOperationIds = [], signal) { abort(signal); if (plan.sourceManifestFingerprint !== createManifestRevisionId(manifest)) throw new Error('Platform plan is stale; analyze the current manifest again.'); const canonical = canonicalApprovedOperationIds(plan, approvedOperationIds); const applied = effectiveOperations(plan, canonical); const planned = plan.operations.filter((item) => !applied.some((candidate) => candidate.id === item.id)); return { id: stableId('platform-preview', `${plan.id}:${operationSignature(canonical)}`), planId: plan.id, planFingerprint: planFingerprint(plan), projectId: plan.projectId, platformId: plan.platformId, profileVersion: plan.profile.version, sourceManifestFingerprint: plan.sourceManifestFingerprint, sourceManifestFingerprintVersion: FINGERPRINT_VERSION, canonicalApprovedOperationIds: canonical, approvalSignature: operationSignature(canonical), effectiveOperationSignature: operationSignature(applied.map((item) => item.id)), plan, before: plan.readiness, after: analyzeReadiness(manifest, plan.profile), appliedOperationIds: applied.map((item) => item.id), plannedOperationIds: planned.map((item) => item.id), affectedScenes: manifest.timeline.scenes.map((scene) => scene.id), reusableScenes: manifest.timeline.scenes.map((scene) => scene.id), cacheReuseEstimate: 100, manualApprovalRequired: plan.operations.filter((item) => !item.automaticallyApplicable).map((item) => item.id), createdAt: new Date().toISOString() }; },
    apply(plan, preview, manifest, approvedOperationIds = []) { if (consumedPreviewIds.has(preview.id)) throw new Error('Platform preview was already consumed; create a new preview.'); const canonical = canonicalApprovedOperationIds(plan, approvedOperationIds); const currentApproval = operationSignature(canonical); if (preview.planId !== plan.id || preview.planFingerprint !== planFingerprint(plan) || preview.sourceManifestFingerprint !== createManifestRevisionId(manifest) || preview.sourceManifestFingerprintVersion !== FINGERPRINT_VERSION || preview.platformId !== plan.platformId || preview.profileVersion !== plan.profile.version || preview.approvalSignature !== currentApproval || preview.canonicalApprovedOperationIds.join('|') !== canonical.join('|')) throw new Error('Platform plan or approval selection changed; create a new preview.'); const applied = effectiveOperations(plan, canonical); if (preview.effectiveOperationSignature !== operationSignature(applied.map((item) => item.id)) || preview.appliedOperationIds.join('|') !== applied.map((item) => item.id).join('|')) throw new Error('Platform preview effective operations are stale; create a new preview.'); const skipped = plan.operations.filter((item) => !applied.some((candidate) => candidate.id === item.id)); const variantManifest = deepClone(manifest); const resolution = applied.find((item) => item.type === 'change-resolution'); if (resolution) { variantManifest.render.width = Number(resolution.parameters.width); variantManifest.render.height = Number(resolution.parameters.height); variantManifest.validation = null; } const aspect = applied.find((item) => item.type === 'change-aspect-ratio'); if (aspect) { variantManifest.render.aspectRatio = String(aspect.parameters.aspectRatio); variantManifest.validation = null; } if (applied.some((item) => item.scope === 'manifest')) variantManifest.validation = null; variantManifest.metadata = { ...variantManifest.metadata, platformVariant: { platformId: plan.platformId, profileVersion: plan.profile.version, sourceManifestFingerprint: plan.sourceManifestFingerprint, appliedOperationIds: applied.map((item) => item.id), safeAreaInsets: plan.profile.safeAreaInsets, subtitleProfile: plan.profile.subtitleProfile, audioProfile: plan.profile.loudnessProfile } } as unknown as typeof variantManifest.metadata; const snapshot: PlatformVariantSnapshot = { variantId: stableId('variant', `${manifest.projectId}:${plan.platformId}`), projectId: manifest.projectId, platformId: plan.platformId, profileVersion: plan.profile.version, sourceManifestFingerprint: plan.sourceManifestFingerprint, manifest: variantManifest, appliedOperationIds: applied.map((item) => item.id), revisionId: stableId('platform-revision', `${plan.platformId}:${createManifestRevisionId(variantManifest)}`), createdAt: new Date().toISOString() }; consumedPreviewIds.add(preview.id); return { snapshot, appliedOperations: applied, skippedOperations: skipped }; },
  };
}
