import type { PlatformId, PlatformProfile } from './types';
const base = { frameRateRange: { min: 24, max: 60 }, preferredFrameRates: [30, 60], durationPolicy: { minMs: 1000, maxMs: 180000, preferredMaxMs: 60000 }, safeAreaInsets: { top: .08, right: .06, bottom: .14, left: .06 }, subtitleSafeArea: { top: .12, right: .06, bottom: .2, left: .06 }, subtitleProfile: { maxLines: 2, maxCharsPerLine: 32, position: 'bottom' as const, fontScale: 1, style: 'shorts' }, hookGuidance: { maxMs: 3000, minDensity: .7 }, pacingGuidance: { minSceneMs: 500, maxSceneMs: 5000 }, ctaGuidance: { preferredStartRatio: .7, preferredEndRatio: .95 }, loudnessProfile: { integratedLufs: -14, truePeakDbtp: -1, channels: 2 as const, sampleRate: 48000 }, bitrateProfile: { videoKbps: 8000, audioKbps: 192, gopFrames: 60 }, codecCapabilities: ['h264', 'hevc'], containerCapabilities: ['mp4'], colorSpaceCapabilities: ['yuv420p', 'bt709'], thumbnailFrameGuidance: { preferredRatio: 9 / 16 }, metadataGuidance: { required: ['title'] }, warnings: ['Profile rules are configurable guidance, not platform guarantees.'] };
const profiles: Record<PlatformId, PlatformProfile> = {
  'youtube-shorts': { ...base, id: 'youtube-shorts', displayName: 'YouTube Shorts', version: '2026.1', sourcePolicyVersion: 'short-video-guidance-1', updatedAt: '2026-01-01', aspectRatios: ['9:16'], preferredAspectRatio: '9:16', supportedResolutions: [{ width: 1080, height: 1920 }, { width: 720, height: 1280 }], preferredResolution: { width: 1080, height: 1920 } },
  tiktok: { ...base, id: 'tiktok', displayName: 'TikTok', version: '2026.1', sourcePolicyVersion: 'short-video-guidance-1', updatedAt: '2026-01-01', aspectRatios: ['9:16', '1:1'], preferredAspectRatio: '9:16', supportedResolutions: [{ width: 1080, height: 1920 }, { width: 720, height: 1280 }], preferredResolution: { width: 1080, height: 1920 }, subtitleProfile: { ...base.subtitleProfile, style: 'tiktok', fontScale: 1.05 } },
  'instagram-reels': { ...base, id: 'instagram-reels', displayName: 'Instagram Reels', version: '2026.1', sourcePolicyVersion: 'short-video-guidance-1', updatedAt: '2026-01-01', aspectRatios: ['9:16', '4:5'], preferredAspectRatio: '9:16', supportedResolutions: [{ width: 1080, height: 1920 }, { width: 1080, height: 1350 }], preferredResolution: { width: 1080, height: 1920 }, safeAreaInsets: { top: .1, right: .06, bottom: .18, left: .06 } },
  'generic-short-video': { ...base, id: 'generic-short-video', displayName: 'Generic short video', version: '2026.1', sourcePolicyVersion: 'short-video-guidance-1', updatedAt: '2026-01-01', aspectRatios: ['9:16', '1:1', '16:9'], preferredAspectRatio: '9:16', supportedResolutions: [{ width: 1080, height: 1920 }, { width: 1920, height: 1080 }], preferredResolution: { width: 1080, height: 1920 } },
};
export function getPlatformProfile(id: PlatformId | string, override?: Partial<PlatformProfile>): PlatformProfile { const selected = profiles[id as PlatformId] ?? profiles['generic-short-video']; return { ...selected, ...override, safeAreaInsets: { ...selected.safeAreaInsets, ...(override?.safeAreaInsets ?? {}) }, subtitleSafeArea: { ...selected.subtitleSafeArea, ...(override?.subtitleSafeArea ?? {}) }, subtitleProfile: { ...selected.subtitleProfile, ...(override?.subtitleProfile ?? {}) } }; }
export function listPlatformProfiles(): readonly PlatformProfile[] { return Object.values(profiles); }
