import { stableId } from '@/core/editing/utils';
import { verifyArtifact } from './verification';
import type { ExportArtifactVerifier, ExportExecutor, ExportJob, ExportProgress, ExportQueue, ExportQueueSnapshot } from './types';
export function canRetryExportJob(job: ExportJob): boolean { return (job.state === 'failed' && Boolean(job.failure?.retryable)) || job.state === 'interrupted'; }
export function createExportQueue(executor: ExportExecutor, onUpdate?: (job: ExportJob) => void, verifier: ExportArtifactVerifier = (job, artifact) => verifyArtifact(job, artifact)): ExportQueue {
  const jobs = new Map<string, ExportJob>(); const order: string[] = []; let activeJobId: string | null = null; let paused = false; let running = false;
  const update = (job: ExportJob) => { jobs.set(job.id, structuredClone(job)); onUpdate?.(structuredClone(job)); };
  const fail = (job: ExportJob, error: unknown, code = 'EXPORT_FAILED', diagnostics: Readonly<Record<string, unknown>> = {}) => { job.attempts += 1; job.state = 'failed'; job.stage = 'completed'; job.failure = { code, message: error instanceof Error ? error.message : String(error), retryable: job.attempts < job.maxAttempts, attempt: job.attempts, maxAttempts: job.maxAttempts, nextRetryAt: null, stderrTail: Object.values(diagnostics).map(String) }; update(job); };
  const start = async () => { if (running) return; running = true; try { while (!paused) { const id = order.find((candidate) => jobs.get(candidate)?.state === 'queued'); if (!id) break; const job = jobs.get(id)!; activeJobId = id; job.state = 'rendering'; job.stage = 'rendering'; job.startedAt = new Date().toISOString(); update(job); try { const artifact = await executor.run(job, (progress: ExportProgress) => { const current = jobs.get(id); if (current && current.state === 'rendering') { current.progress = progress; update(current); } }); const current = jobs.get(id); if (!current || current.state === 'cancelled') continue; current.artifact = artifact; current.state = 'verifying'; current.stage = 'verifying'; current.progress = { ...current.progress, state: 'verifying', stage: 'verifying', message: 'Verifying export artifact.', updatedAt: new Date().toISOString() }; update(current); const verification = await verifier(current, artifact); if (!verification.valid) { fail(current, verification.issues.join(' '), 'ARTIFACT_VERIFICATION_FAILED', verification.diagnostics); continue; } current.artifact = { ...artifact, verified: true, diagnostics: verification.diagnostics }; current.state = 'completed'; current.stage = 'completed'; current.progress = { ...current.progress, state: 'completed', stage: 'completed', percent: 100, updatedAt: new Date().toISOString() }; current.completedAt = new Date().toISOString(); current.failure = null; update(current); } catch (error) { const current = jobs.get(id); if (current && current.state !== 'cancelled') fail(current, error); } finally { if (activeJobId === id) activeJobId = null; } } } finally { running = false; } };
  return { enqueue(job) { if (jobs.has(job.id)) return structuredClone(jobs.get(job.id)!); order.push(job.id); update(job); return structuredClone(job); }, hydrate(snapshot) { jobs.clear(); order.length = 0; for (const job of snapshot.jobs) { if (!jobs.has(job.id)) { jobs.set(job.id, structuredClone(job)); order.push(job.id); } } activeJobId = null; paused = snapshot.paused; }, start, pause() { paused = true; }, resume() { paused = false; void start(); }, async cancel(jobId) { const job = jobs.get(jobId); if (!job || ['completed', 'failed', 'cancelled'].includes(job.state)) return false; if (job.state === 'rendering' || job.state === 'verifying') await executor.cancel(jobId); job.state = 'cancelled'; job.stage = 'completed'; job.progress = { ...job.progress, state: 'cancelled', updatedAt: new Date().toISOString() }; update(job); return true; }, async retry(jobId) { const job = jobs.get(jobId); if (!job || !['failed', 'interrupted'].includes(job.state) || (job.state === 'failed' && !job.failure?.retryable)) return null; job.state = 'queued'; job.stage = 'queued'; job.failure = null; job.artifact = null; job.startedAt = null; job.completedAt = null; job.progress = { ...job.progress, state: 'queued', stage: 'queued', percent: 0, updatedAt: new Date().toISOString() }; update(job); void start(); return structuredClone(job); }, get(jobId) { const job = jobs.get(jobId); return job ? structuredClone(job) : null; }, list() { return order.map((id) => jobs.get(id)).filter((job): job is ExportJob => Boolean(job)).map((job) => structuredClone(job)); }, snapshot(): ExportQueueSnapshot { return { jobs: this.list(), activeJobId, paused }; } };
}
export function serializeExportQueue(snapshot: ExportQueueSnapshot, savedAt = new Date().toISOString()): import('./types').ExportQueuePersistence { return { version: 1, snapshot: structuredClone(snapshot), savedAt }; }
export function normalizeHydratedExportState(snapshot: ExportQueueSnapshot): ExportQueueSnapshot { const seen = new Set<string>(); const jobs = (snapshot?.jobs ?? []).filter((job): job is import('./types').ExportJob => Boolean(job && typeof job.id === 'string' && typeof job.state === 'string' && job.plan && job.manifest && job.progress && !seen.has(job.id) && (seen.add(job.id), true))).slice(0, 500).map((job) => job.state === 'rendering' || job.state === 'planning' || job.state === 'verifying' ? { ...job, state: 'interrupted' as const, stage: 'completed' as const, artifact: job.artifact?.verified ? job.artifact : null, failure: { code: 'INTERRUPTED', message: 'Export process was interrupted before application restart.', retryable: true, attempt: job.attempts, maxAttempts: job.maxAttempts, nextRetryAt: null, stderrTail: [] } } : job); return { jobs, activeJobId: null, paused: Boolean(snapshot?.paused) }; }
export function normalizeHydratedExportQueue(persistence: import('./types').ExportQueuePersistence): ExportQueueSnapshot { if (!persistence || persistence.version !== 1 || !persistence.snapshot || !Array.isArray(persistence.snapshot.jobs)) return { jobs: [], activeJobId: null, paused: false }; return normalizeHydratedExportState(persistence.snapshot); }
export function createExportJob(plan: import('./types').ExportPlan, manifest: import('@/core/media').RenderManifest, outputPath: string, maxAttempts = 3): ExportJob { const now = new Date().toISOString(); return { id: stableId('export-job', `${plan.id}:${outputPath}`), projectId: manifest.projectId, platformId: plan.platformId, sourceManifestFingerprint: plan.sourceManifestFingerprint, sourceManifestFingerprintVersion: plan.sourceManifestFingerprintVersion, manifest, plan, outputPath, state: 'queued', stage: 'queued', progress: { jobId: stableId('export-job', `${plan.id}:${outputPath}`), stage: 'queued', state: 'queued', percent: 0, etaMs: null, fps: null, speed: null, frame: null, bitrateKbps: null, message: 'Queued', updatedAt: now }, attempts: 0, maxAttempts, artifact: null, failure: null, queuedAt: now, startedAt: null, completedAt: null }; }
