import type { FFmpegCapabilities } from '@/core/render';
import type { RenderManifest } from '@/core/media';
export type ExportState = 'queued' | 'planning' | 'rendering' | 'verifying' | 'completed' | 'failed' | 'cancelled' | 'paused' | 'interrupted';
export type ExportStage = 'queued' | 'capability' | 'planning' | 'rendering' | 'verifying' | 'completed';
export type ExportHardware = 'cpu' | 'gpu' | 'mixed';
export interface ExportBenchmark { hardware: ExportHardware; encoder: string; estimatedFps: number; cpuPercent: number; gpuPercent: number | null; measuredAt: string; confidence: 'capability' | 'measured'; }
export interface ExportCapability { ffmpeg: boolean; ffprobe: boolean; version: string | null; encoders: readonly string[]; hardwareEncoders: readonly string[]; supports: Readonly<Record<string, boolean>>; raw: FFmpegCapabilities | null; detectedAt: string; }
export interface ExportPreset { id: string; version: string; name: string; platformId: string | null; container: 'mp4' | 'webm'; videoCodec: 'h264' | 'hevc' | 'av1' | 'vp9'; audioCodec: 'aac' | 'opus'; pixelFormat: 'yuv420p' | 'yuv444p'; bitrateKbps: number; maxBitrateKbps?: number; bufferSizeKbps?: number; audioBitrateKbps: number; sampleRate: number; audioChannels?: number; frameRate: number; encoder: string; encoderPreset?: string; crf?: number; hardware: ExportHardware; threads: number; gopFrames: number; keyframeInterval?: number; colorSpace?: string; profile?: string; quality: 'preview' | 'standard' | 'high' | 'archive'; }
export interface ExportPlan { id: string; projectId: string; sourceManifestFingerprint: string; sourceManifestFingerprintVersion: number; platformId: string | null; preset: ExportPreset; estimatedSizeBytes: number; estimatedDurationMs: number; estimatedRenderMs: number; warnings: readonly string[]; blockingIssues: readonly string[]; cacheReusePercent: number; hardwareReason: string; createdAt: string; }
export interface ExportProgress { jobId: string; stage: ExportStage; state: ExportState; percent: number; etaMs: number | null; fps: number | null; speed: number | null; frame: number | null; bitrateKbps: number | null; message: string; updatedAt: string; }
export interface ExportArtifact { path: string; sizeBytes: number; durationMs: number; verified: boolean; contentDigest?: string | null; diagnostics: Readonly<Record<string, unknown>>; createdAt: string; }
export interface ExportFailure { code: string; message: string; retryable: boolean; attempt: number; maxAttempts: number; nextRetryAt: string | null; stderrTail: readonly string[]; }
export interface ExportJob { id: string; projectId: string; platformId: string | null; sourceManifestFingerprint: string; sourceManifestFingerprintVersion: number; manifest: RenderManifest; plan: ExportPlan; outputPath: string; state: ExportState; stage: ExportStage; progress: ExportProgress; attempts: number; maxAttempts: number; artifact: ExportArtifact | null; failure: ExportFailure | null; queuedAt: string; startedAt: string | null; completedAt: string | null; }
export interface ExportResult { job: ExportJob; artifact: ExportArtifact | null; failure: ExportFailure | null; }
export interface ExportRevision { id: string; jobId: string; projectId: string; platformId: string | null; sourceManifestFingerprint: string; artifactFingerprint: string | null; createdAt: string; }
export interface ExportVerification { valid: boolean; zeroByte: boolean; durationMatch: boolean; resolutionMatch: boolean; codecMatch: boolean; audioPresent: boolean; subtitlesPresent: boolean; corruption: boolean; contentDigest?: string | null; sizeBytes?: number; issues: readonly string[]; diagnostics: Readonly<Record<string, unknown>>; }
export interface ExportPlannerInput { manifest: RenderManifest; platformId?: string | null; presetId?: string; capabilities: ExportCapability; now?: string; }
export interface ExportExecutor { run(job: ExportJob, onProgress: (progress: ExportProgress) => void): Promise<ExportArtifact>; cancel(jobId: string): Promise<boolean>; }
export interface ExportQueueSnapshot { jobs: readonly ExportJob[]; activeJobId: string | null; paused: boolean; }
export interface ExportQueuePersistence { version: 1; snapshot: ExportQueueSnapshot; savedAt: string; }
export type ExportArtifactVerifier = (job: ExportJob, artifact: ExportArtifact) => Promise<ExportVerification> | ExportVerification;
export interface ExportQueue { enqueue(job: ExportJob): ExportJob; hydrate(snapshot: ExportQueueSnapshot): void; start(): Promise<void>; pause(): void; resume(): void; cancel(jobId: string): Promise<boolean>; retry(jobId: string): Promise<ExportJob | null>; get(jobId: string): ExportJob | null; list(): readonly ExportJob[]; snapshot(): ExportQueueSnapshot; }
export interface ExportIntelligenceEngine { detectCapabilities(forceRefresh?: boolean): Promise<ExportCapability>; plan(input: ExportPlannerInput): ExportPlan; preview(input: ExportPlannerInput): Promise<ExportPlan>; verify(job: ExportJob, artifact: ExportArtifact): Promise<ExportVerification>; createQueue(executor?: ExportExecutor): ExportQueue; }
