import { describe, expect, it } from 'vitest';
import { createPlatformOptimizationEngine, getPlatformProfile, listPlatformProfiles, platformCapability, type PlatformId } from '@/core/platform-optimization';
import { createManifestRevisionId } from '@/core/editing';
import { editingFixture } from '../editing/fixtures';

async function source() { return (await editingFixture()).manifest; }
describe('Epic 7.6 platform optimization engine', () => {
  it('registers all versioned platforms and falls back safely', () => { expect(listPlatformProfiles()).toHaveLength(4); expect(getPlatformProfile('unknown').id).toBe('generic-short-video'); expect(getPlatformProfile('tiktok').version).toBeTruthy(); });
  it('keeps profile overrides type-safe and scoped', () => { const profile = getPlatformProfile('youtube-shorts', { version: 'test', subtitleProfile: { ...getPlatformProfile('youtube-shorts').subtitleProfile, maxLines: 3 } }); expect(profile.version).toBe('test'); expect(profile.subtitleProfile.maxLines).toBe(3); expect(getPlatformProfile('youtube-shorts').version).not.toBe('test'); });
  it('creates deterministic readiness and operations from one fingerprint', async () => { const manifest = await source(); const engine = createPlatformOptimizationEngine(); const a = engine.analyze({ manifest, platformId: 'tiktok', now: '2026-01-01T00:00:00.000Z' }); const b = engine.analyze({ manifest, platformId: 'tiktok', now: '2026-01-01T00:00:00.000Z' }); expect(a).toEqual(b); expect(a.sourceManifestFingerprint).toBe(createManifestRevisionId(manifest)); expect(a.readiness.overall).toBeGreaterThanOrEqual(0); });
  it('marks structural and export work planned-only', () => { expect(platformCapability('change-aspect-ratio').status).toBe('planned-only'); expect(platformCapability('change-video-codec').status).toBe('planned-only'); expect(platformCapability('change-resolution').status).toBe('implemented'); });
  it('previews only supported operations and never invents score gains', async () => { const manifest = await source(); const engine = createPlatformOptimizationEngine(); const plan = engine.analyze({ manifest, platformId: 'youtube-shorts', now: '2026-01-01T00:00:00.000Z' }); const preview = engine.preview(plan, manifest); expect(preview.sourceManifestFingerprint).toBe(plan.sourceManifestFingerprint); expect(preview.plannedOperationIds.every((id) => plan.operations.some((op) => op.id === id))).toBe(true); expect(preview.after.overall).toBe(plan.readiness.overall); });
  it('applies a supported resolution immutably and isolates variant metadata', async () => { const manifest = await source(); const engine = createPlatformOptimizationEngine(); const plan = engine.analyze({ manifest, platformId: 'youtube-shorts', now: '2026-01-01T00:00:00.000Z' }); const preview = engine.preview(plan, manifest); const result = engine.apply(plan, preview, manifest); expect(result.snapshot.manifest).not.toBe(manifest); expect(result.snapshot.platformId).toBe('youtube-shorts'); expect(result.snapshot.manifest.metadata).toHaveProperty('platformVariant'); expect(manifest.metadata).not.toHaveProperty('platformVariant'); });
  it('rejects stale source manifests before apply', async () => { const manifest = await source(); const engine = createPlatformOptimizationEngine(); const plan = engine.analyze({ manifest, platformId: 'tiktok', now: '2026-01-01T00:00:00.000Z' }); const preview = engine.preview(plan, manifest); const stale = structuredClone(manifest); stale.durationMs += 100; expect(() => engine.apply(plan, preview, stale)).toThrow(/stale|changed/i); });
  it('keeps geometry unchanged when aspect conversion is planned-only', async () => { const manifest = await source(); manifest.render.width = 1920; manifest.render.height = 1080; manifest.render.aspectRatio = '16:9'; const before = structuredClone(manifest.render); const engine = createPlatformOptimizationEngine(); const plan = engine.analyze({ manifest, platformId: 'youtube-shorts', now: '2026-01-01T00:00:00.000Z' }); const preview = engine.preview(plan, manifest); const result = engine.apply(plan, preview, manifest); expect(result.snapshot.manifest.render).toEqual(before); expect(result.skippedOperations.map((item) => item.type)).toContain('change-resolution'); expect(result.skippedOperations.map((item) => item.type)).toContain('change-aspect-ratio'); });
  it('rejects a preview from another plan or approval signature', async () => { const manifest = await source(); const engine = createPlatformOptimizationEngine(); const plan = engine.analyze({ manifest, platformId: 'youtube-shorts', now: '2026-01-01T00:00:00.000Z' }); const other = engine.analyze({ manifest, platformId: 'tiktok', now: '2026-01-01T00:00:00.000Z' }); const preview = engine.preview(other, manifest); expect(() => engine.apply(plan, preview, manifest)).toThrow(/plan or approval/i); const valid = engine.preview(plan, manifest); const changedApproval = plan.operations.find((item) => !item.automaticallyApplicable)?.id; if (changedApproval) expect(() => engine.apply(plan, valid, manifest, [changedApproval])).toThrow(/plan or approval/i); });
  it('invalidates source validation when a supported geometry operation changes the variant', async () => { const manifest = await source(); manifest.validation = { ...(manifest.validation ?? {}), renderReady: true } as typeof manifest.validation; const engine = createPlatformOptimizationEngine(); const plan = engine.analyze({ manifest, platformId: 'youtube-shorts', now: '2026-01-01T00:00:00.000Z' }); const preview = engine.preview(plan, manifest); const result = engine.apply(plan, preview, manifest); if (result.appliedOperations.some((item) => item.type === 'change-resolution')) expect(result.snapshot.manifest.validation).toBeNull(); });
  it('consumes a preview after successful apply', async () => { const manifest = await source(); const engine = createPlatformOptimizationEngine(); const plan = engine.analyze({ manifest, platformId: 'youtube-shorts', now: '2026-01-01T00:00:00.000Z' }); const preview = engine.preview(plan, manifest); engine.apply(plan, preview, manifest); expect(() => engine.apply(plan, preview, manifest)).toThrow(/consumed/i); });
  it.each(['youtube-shorts', 'tiktok', 'instagram-reels', 'generic-short-video'] as PlatformId[])('produces an isolated %s variant', async (platformId) => { const manifest = await source(); const engine = createPlatformOptimizationEngine(); const plan = engine.analyze({ manifest, platformId, now: '2026-01-01T00:00:00.000Z' }); const preview = engine.preview(plan, manifest); const result = engine.apply(plan, preview, manifest); expect(result.snapshot.platformId).toBe(platformId); expect(result.snapshot.sourceManifestFingerprint).toBe(createManifestRevisionId(manifest)); });
});
