import { stableId } from '@/core/editing/utils';
import { freshnessOf } from './series';
import { normalizeAnalyticsResponse } from './normalization';
import type { AnalyticsCollectionResult, AnalyticsDiagnostic, AnalyticsPersistenceState, AnalyticsPlatformAdapterRegistry, AnalyticsSnapshot, AnalyticsWindow, PublishedContentBinding } from './types';

export interface AnalyticsCollectionEngine { collect(input: { binding: PublishedContentBinding; window: AnalyticsWindow; requestId?: string; signal?: AbortSignal }): Promise<AnalyticsCollectionResult>; getCooldown(binding: PublishedContentBinding): string | null; refreshKey(binding: PublishedContentBinding): string; restoreCooldowns(refreshes: AnalyticsPersistenceState['refreshes']): void; }
interface Budget { attempts: number; cooldownUntil: number; }
export function createAnalyticsCollectionEngine(registry: AnalyticsPlatformAdapterRegistry, onEvent?: (name: string, payload: Record<string, unknown>) => void): AnalyticsCollectionEngine {
  const budgets = new Map<string, Budget>(); const latest = new Map<string, string>(); const keyFor = (binding: PublishedContentBinding) => `${binding.platform}:${binding.accountId}`;
  return { async collect(input) { const collectionId = input.requestId ?? stableId('analytics-collection', `${input.binding.remotePublicationId}:${Date.now()}`); const key = keyFor(input.binding); latest.set(`${key}:${input.binding.remotePublicationId}`, collectionId); const now = Date.now(); const budget = budgets.get(key) ?? { attempts: 0, cooldownUntil: 0 };
      if (budget.cooldownUntil > now) { const diagnostic: AnalyticsDiagnostic = { code: 'rate-limited', severity: 'warning', message: `Analytics refresh is cooling down until ${new Date(budget.cooldownUntil).toISOString()}.` }; onEvent?.('analytics.collection.partial', { collectionId, projectId: input.binding.projectId, publicationId: input.binding.remotePublicationId, platform: input.binding.platform, accountRef: input.binding.accountRef }); return { collectionId, snapshots: [], status: 'rate-limited', diagnostics: [diagnostic] }; }
      onEvent?.('analytics.collection.started', { collectionId, projectId: input.binding.projectId, publicationId: input.binding.remotePublicationId, platform: input.binding.platform, accountRef: input.binding.accountRef });
      try { const adapter = registry.get(input.binding.platform); const response = await adapter.collect(input.binding, { window: input.window, signal: input.signal ?? new AbortController().signal });
        if (latest.get(`${key}:${input.binding.remotePublicationId}`) !== collectionId) return { collectionId, snapshots: [], status: 'partial', diagnostics: [{ code: 'platform-discrepancy', severity: 'info', message: 'Ignored a superseded analytics response.' }] };
        const normalized = normalizeAnalyticsResponse({ binding: input.binding, response, window: input.window, requestId: collectionId, adapterId: adapter.platform }); const snapshot: AnalyticsSnapshot = { ...normalized, freshness: freshnessOf(normalized) }; const currentBudget = budgets.get(key) ?? budget; budgets.set(key, { attempts: 0, cooldownUntil: currentBudget.cooldownUntil > budget.cooldownUntil ? currentBudget.cooldownUntil : 0 }); onEvent?.('analytics.snapshot.updated', { collectionId, projectId: input.binding.projectId, publicationId: input.binding.remotePublicationId, platform: input.binding.platform, accountRef: input.binding.accountRef }); onEvent?.(normalized.diagnostics.length ? 'analytics.collection.partial' : 'analytics.collection.completed', { collectionId, projectId: input.binding.projectId, publicationId: input.binding.remotePublicationId, platform: input.binding.platform, accountRef: input.binding.accountRef }); return { collectionId, snapshots: [snapshot], status: normalized.diagnostics.length ? 'partial' : 'completed', diagnostics: normalized.diagnostics };
      } catch (error) { if (latest.get(`${key}:${input.binding.remotePublicationId}`) !== collectionId) return { collectionId, snapshots: [], status: 'partial', diagnostics: [{ code: 'platform-discrepancy', severity: 'info', message: 'Ignored a superseded analytics failure.' }] }; const retryAfter = Number((error as { retryAfterMs?: number }).retryAfterMs); const rateLimited = (error as { status?: number }).status === 429 || Number.isFinite(retryAfter); const attempts = budget.attempts + 1; const cooldown = rateLimited ? Math.max(1_000, Number.isFinite(retryAfter) ? retryAfter : 30_000) : Math.min(300_000, 1_000 * 2 ** Math.min(attempts, 8) + Math.floor(Math.random() * 250)); budgets.set(key, { attempts, cooldownUntil: Date.now() + cooldown }); const diagnostic: AnalyticsDiagnostic = { code: rateLimited ? 'rate-limited' : 'permission-limited', severity: 'warning', message: error instanceof Error ? error.message : 'Analytics collection failed.' }; onEvent?.(rateLimited ? 'analytics.rate_limited' : 'analytics.collection.failed', { collectionId, projectId: input.binding.projectId, publicationId: input.binding.remotePublicationId, platform: input.binding.platform, accountRef: input.binding.accountRef }); return { collectionId, snapshots: [], status: rateLimited ? 'rate-limited' : 'failed', diagnostics: [diagnostic] }; }
    }, getCooldown(binding) { const until = budgets.get(keyFor(binding))?.cooldownUntil ?? 0; return until > Date.now() ? new Date(until).toISOString() : null; }, refreshKey: keyFor, restoreCooldowns(refreshes) { const now = Date.now(); for (const [key, refresh] of Object.entries(refreshes)) { const cooldownUntil = refresh.cooldownUntil === null ? NaN : Date.parse(refresh.cooldownUntil); if (!Number.isFinite(cooldownUntil) || cooldownUntil <= now) continue; const existing = budgets.get(key); if (!existing || cooldownUntil > existing.cooldownUntil) budgets.set(key, { attempts: existing?.attempts ?? 0, cooldownUntil }); } } };
}
