import { freshnessOf } from './series';
import type { AnalyticsAttribution, AnalyticsMetric, AnalyticsPersistenceState, AnalyticsSnapshot, LearningConfidence, LearningProfile, LearningSignal, PerformanceInsight, Recommendation } from './types';

export const EMPTY_ANALYTICS_PERSISTENCE: AnalyticsPersistenceState = { version: 1, snapshots: [], attributions: [], profiles: [], insights: [], recommendations: [], refreshes: {} };
const MAX_SNAPSHOTS = 500; const MAX_PER_PUBLICATION = 60;
const metricNames = new Set(['views', 'impressions', 'reach', 'likes', 'comments', 'shares', 'saves', 'watchTime', 'averageWatchTime', 'averagePercentageViewed', 'completionRate', 'engagementRate', 'followersGained', 'profileVisits', 'clicks']);
const windows = new Set(['1h', '6h', '24h', '48h', '7d', '30d', 'lifetime']); const units = new Set(['count', 'seconds', 'percentage', 'ratio']); const availability = new Set(['available', 'unavailable', 'unsupported', 'not-ready', 'permission-missing', 'invalid']); const freshness = new Set(['fresh', 'stale', 'delayed', 'unknown']); const levels = new Set(['low', 'medium', 'high']);
const record = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === 'object' && !Array.isArray(value);
const string = (value: unknown): value is string => typeof value === 'string'; const finite = (value: unknown): value is number => typeof value === 'number' && Number.isFinite(value);
const stringArray = (value: unknown): value is string[] => Array.isArray(value) && value.every(string);
function binding(value: unknown): boolean { return record(value) && string(value.projectId) && (string(value.variantId) || value.variantId === null) && string(value.artifactFingerprint) && string(value.publishJobId) && string(value.publishReceiptId) && string(value.platform) && string(value.accountId) && string(value.accountRef) && (string(value.channelRef) || value.channelRef === null) && string(value.remotePublicationId) && string(value.publishedAt); }
function channelBinding(value: unknown): boolean { return record(value) && string(value.platform) && string(value.accountId) && string(value.accountRef) && (string(value.channelRef) || value.channelRef === null); }
function confidence(value: unknown): value is LearningConfidence { return record(value) && levels.has(value.level as string) && finite(value.score) && string(value.policyVersion) && record(value.factors) && Object.values(value.factors).every(finite); }
function evidence(value: unknown): boolean { return record(value) && metricNames.has(value.metric as string) && (finite(value.value) || value.value === null) && (finite(value.baselineValue) || value.baselineValue === null) && finite(value.sampleSize) && windows.has(value.window as string) && stringArray(value.sourceSnapshotIds); }
function signal(value: unknown): value is LearningSignal { return record(value) && string(value.id) && string(value.feature) && string(value.cohort) && finite(value.sampleSize) && finite(value.effect) && ['associated-with', 'correlated-with', 'outperformed-in-observed-sample'].includes(value.relation as string) && confidence(value.confidence) && Array.isArray(value.evidence) && value.evidence.every(evidence) && windows.has(value.window as string) && stringArray(value.limitations) && finite(value.outlierCount); }
function metric(value: unknown): value is AnalyticsMetric { if (!record(value) || !metricNames.has(value.name as string) || !windows.has(value.window as string) || !units.has(value.unit as string) || !availability.has(value.availability as string) || !record(value.source)) return false; const source = value.source; if (!string(source.platform) || !string(source.adapterId) || !string(source.fetchedAt) || !(string(source.observedAt) || source.observedAt === null) || !(string(source.rawMetricId) || source.rawMetricId === null) || !metricNames.has(source.normalizedMetric as string) || typeof source.estimated !== 'boolean' || !levels.has(source.quality as string)) return false; return value.availability === 'available' ? finite(value.value) && value.value >= 0 : value.value === null; }
function isPersistedSnapshot(value: unknown): value is AnalyticsSnapshot { if (!record(value) || !string(value.id) || !string(value.collectedAt) || !string(value.requestId) || !(string(value.observedAt) || value.observedAt === null) || !freshness.has(value.freshness as string) || !binding(value.binding) || !Array.isArray(value.metrics) || !value.metrics.every(metric) || !Array.isArray(value.diagnostics) || !record(value.revision)) return false; const revision = value.revision; return revision.version === 1 && string(revision.normalizationPolicy) && string(revision.scoringPolicy) && string(revision.confidencePolicy) && string(revision.retentionPolicy) && string(revision.createdAt); }
function attribution(value: unknown): value is AnalyticsAttribution { return record(value) && string(value.bindingId) && string(value.extractedAt) && string(value.sourceFingerprint) && record(value.features) && Object.values(value.features).every((feature) => string(feature) || finite(feature) || typeof feature === 'boolean' || feature === null); }
function profile(value: unknown): value is LearningProfile { return record(value) && string(value.id) && channelBinding(value.channelBinding) && finite(value.sampleSize) && windows.has(value.observationWindow as string) && ['ready', 'cold-start'].includes(value.status as string) && Array.isArray(value.strongestSignals) && value.strongestSignals.every(signal) && Array.isArray(value.weakSignals) && value.weakSignals.every(signal) && stringArray(value.unknowns) && confidence(value.confidence) && string(value.version) && string(value.generatedAt); }
function insight(value: unknown): value is PerformanceInsight { return record(value) && string(value.id) && string(value.bindingId) && ['associated-with', 'correlated-with', 'outperformed-in-observed-sample'].includes(value.relation as string) && string(value.message) && Array.isArray(value.evidence) && value.evidence.every(evidence) && confidence(value.confidence) && stringArray(value.limitations) && string(value.generatedAt); }
function recommendation(value: unknown): value is Recommendation { return record(value) && string(value.id) && channelBinding(value.channelBinding) && string(value.recommendation) && string(value.reason) && ['test-for-improvement', 'test-for-reduction', 'explore'].includes(value.expectedDirection as string) && confidence(value.confidence) && Array.isArray(value.evidence) && value.evidence.every((item) => record(item) && string(item.signalId) && ['associated-with', 'correlated-with', 'outperformed-in-observed-sample'].includes(item.relation as string) && finite(item.sampleSize) && finite(item.effect) && stringArray(item.limitations)) && stringArray(value.limitations) && value.autoApplyStatus === 'planned-only' && string(value.generatedAt); }
function refreshes(value: unknown): AnalyticsPersistenceState['refreshes'] { if (!record(value)) return {}; return Object.fromEntries(Object.entries(value).filter(([, item]) => record(item) && string(item.latestRequestId) && string(item.fetchedAt) && (string(item.cooldownUntil) || item.cooldownUntil === null))) as AnalyticsPersistenceState['refreshes']; }

export function normalizeAnalyticsPersistence(value: unknown): AnalyticsPersistenceState { if (!record(value)) return EMPTY_ANALYTICS_PERSISTENCE; const snapshots = Array.isArray(value.snapshots) ? value.snapshots.filter(isPersistedSnapshot).map((snapshot) => ({ ...snapshot, freshness: freshnessOf(snapshot) })) : []; const byPublication = new Map<string, AnalyticsSnapshot[]>(); for (const snapshot of snapshots) { const key = `${snapshot.binding.platform}:${snapshot.binding.accountId}:${snapshot.binding.remotePublicationId}`; byPublication.set(key, [...(byPublication.get(key) ?? []), snapshot]); } const compacted = [...byPublication.values()].flatMap((group) => { const latestById = new Map<string, AnalyticsSnapshot>(); for (const snapshot of group) { const prior = latestById.get(snapshot.id); if (!prior || snapshot.collectedAt >= prior.collectedAt) latestById.set(snapshot.id, snapshot); } return [...latestById.values()].sort((a, b) => a.collectedAt.localeCompare(b.collectedAt)).slice(-MAX_PER_PUBLICATION); }).sort((a, b) => a.collectedAt.localeCompare(b.collectedAt)).slice(-MAX_SNAPSHOTS); return { version: 1, snapshots: compacted, attributions: Array.isArray(value.attributions) ? value.attributions.filter(attribution).slice(-MAX_SNAPSHOTS) : [], profiles: Array.isArray(value.profiles) ? value.profiles.filter(profile).slice(-100) : [], insights: Array.isArray(value.insights) ? value.insights.filter(insight).slice(-500) : [], recommendations: Array.isArray(value.recommendations) ? value.recommendations.filter(recommendation).slice(-200) : [], refreshes: refreshes(value.refreshes) }; }
export function mergeSnapshot(state: AnalyticsPersistenceState, snapshot: AnalyticsSnapshot): AnalyticsPersistenceState { const existing = state.snapshots.find((item) => item.id === snapshot.id); if (existing && Date.parse(existing.collectedAt) > Date.parse(snapshot.collectedAt)) return state; return normalizeAnalyticsPersistence({ ...state, snapshots: [...state.snapshots.filter((item) => item.id !== snapshot.id), snapshot] }); }
