import { stableId } from '@/core/editing/utils';
import type { AnalyticsFreshness, AnalyticsMetricName, AnalyticsMetricSeries, AnalyticsObservation, AnalyticsSnapshot, AnalyticsWindow } from './types';

export function bindingId(snapshot: Pick<AnalyticsSnapshot, 'binding'> | { binding: { platform: string; accountId: string; remotePublicationId: string } }): string { const b = snapshot.binding; return stableId('publication', `${b.platform}:${b.accountId}:${b.remotePublicationId}`); }
export function freshnessOf(snapshot: Pick<AnalyticsSnapshot, 'collectedAt' | 'observedAt'>, now = new Date()): AnalyticsFreshness { const at = Date.parse(snapshot.observedAt ?? snapshot.collectedAt); if (!Number.isFinite(at)) return 'unknown'; const age = now.getTime() - at; if (age < 0) return 'unknown'; if (age <= 6 * 60 * 60_000) return 'fresh'; if (age <= 48 * 60 * 60_000) return 'delayed'; return 'stale'; }
export function observationId(binding: string, metric: AnalyticsMetricName, window: AnalyticsWindow, observedAt: string): string { return stableId('analytics-observation', `${binding}:${metric}:${window}:${observedAt}`); }
export function observationsFromSnapshot(snapshot: AnalyticsSnapshot): AnalyticsObservation[] { const id = bindingId(snapshot); return snapshot.metrics.map((metric) => ({ id: observationId(id, metric.name, metric.window, metric.source.observedAt ?? snapshot.collectedAt), bindingId: id, metric, observedAt: metric.source.observedAt ?? snapshot.collectedAt, fetchedAt: snapshot.collectedAt, requestId: snapshot.requestId })); }
export function mergeObservations(existing: readonly AnalyticsObservation[], incoming: readonly AnalyticsObservation[]): AnalyticsObservation[] { const byId = new Map<string, AnalyticsObservation>(); for (const observation of [...existing, ...incoming]) { const prior = byId.get(observation.id); if (!prior || Date.parse(observation.fetchedAt) >= Date.parse(prior.fetchedAt)) byId.set(observation.id, observation); } return [...byId.values()].sort((a, b) => Date.parse(a.observedAt) - Date.parse(b.observedAt) || a.id.localeCompare(b.id)); }
export function seriesFor(binding: string, metric: AnalyticsMetricName, window: AnalyticsWindow, observations: readonly AnalyticsObservation[]): AnalyticsMetricSeries { const values = observations.filter((item) => item.bindingId === binding && item.metric.name === metric && item.metric.window === window && item.metric.availability === 'available' && item.metric.value !== null); const trajectory = values.length < 2 ? 'unknown' : (values.at(-1)!.metric.value! - values.at(-2)!.metric.value!) > 0 ? 'rising' : (values.at(-1)!.metric.value! - values.at(-2)!.metric.value!) < 0 ? 'slowing' : 'stable'; return { bindingId: binding, metric, window, observations: values, trajectory }; }
