import { describe, expect, it } from 'vitest';
import { compileAudioProductionPlan, createAudioPreview, createAudioProductionEngine, detectAudioConflicts, transformAudio, validateAudioManifest, type AudioOperation } from '@/core/audio-production';
import { createManifestRevisionId, createTimelineSnapshot } from '@/core/editing';
import { editingFixture } from '../editing/fixtures';

describe('audio plan compiler', () => {
  it('is deterministic for the same input', async () => { const fixture = await setup(); expect(fixture.plan).toEqual(compileAudioProductionPlan(fixture.input)); });
  it('binds the complete manifest fingerprint', async () => { const fixture = await setup(); expect(fixture.plan.sourceManifestFingerprint).toBe(createManifestRevisionId(fixture.manifest)); });
  it('rejects a stale Director report', async () => { const fixture = await setup(); fixture.manifest.audio.settings.musicGain += 0.01; expect(() => compileAudioProductionPlan(fixture.input)).toThrow(/Manifest changed/); });
  it('deduplicates scene operation types', async () => { const { plan } = await setup(); const keys = plan.operations.map((item) => `${item.sceneId}|${item.type}`); expect(new Set(keys).size).toBe(keys.length); });
  it('separates automatic and manual operations', async () => { const { plan } = await setup(); expect(plan.automaticOperations.every((id) => plan.operations.find((item) => item.id === id)?.automaticallyApplicable)).toBe(true); expect(plan.manualOperations.every((id) => !plan.operations.find((item) => item.id === id)?.automaticallyApplicable)).toBe(true); });
  it('detects silence removal conflict', async () => { const { plan } = await setup(); const base = plan.operations[0]; const operations = [{ ...base, id: 'trim', type: 'trim-silence' as const }, { ...base, id: 'extend', type: 'extend-silence' as const }]; expect(detectAudioConflicts(operations, 10000)[0].severity).toBe('critical'); });
  it('detects out-of-bounds placement', async () => { const { plan } = await setup(); const item = { ...plan.operations[0], parameters: { startMs: 999999 } }; expect(detectAudioConflicts([item], 1000).some((conflict) => conflict.type === 'segment-out-of-bounds')).toBe(true); });
  it('supports abort', async () => { const fixture = await setup(); const controller = new AbortController(); controller.abort(); expect(() => compileAudioProductionPlan(fixture.input, {}, controller.signal)).toThrow(/aborted/); });
});

describe('audio preview and immutable manifest transform', () => {
  it('does not mutate input manifest', async () => { const fixture = await setup(); const before = structuredClone(fixture.manifest); transformAudio(fixture.snapshot, fixture.plan); expect(fixture.manifest).toEqual(before); });
  it('invalidates validation', async () => { const fixture = await setup(); expect(transformAudio(fixture.snapshot, fixture.plan).snapshot.manifest.validation).toBeNull(); });
  it('recomputes audio metrics', async () => { const fixture = await setup(); const after = transformAudio(fixture.snapshot, fixture.plan).snapshot.manifest; expect(after.audio.metrics.sfxCount).toBe(after.audio.sfx.length); expect(after.audio.metrics.durationMs).toBe(after.durationMs); });
  it('clamps global music to timeline', async () => { const fixture = await setup(); fixture.snapshot.manifest.audio.music[0].endMs = fixture.manifest.durationMs + 5000; fixture.snapshot.manifest.audio.music[0].durationMs += 5000; fixture.snapshot = createTimelineSnapshot(fixture.snapshot.manifest, createManifestRevisionId(fixture.snapshot.manifest)); fixture.plan = compileAudioProductionPlan({ ...fixture.input, manifest: fixture.snapshot.manifest, directorReport: { ...fixture.report, analyzedManifestFingerprint: createManifestRevisionId(fixture.snapshot.manifest) } }); const after = transformAudio(fixture.snapshot, fixture.plan).snapshot.manifest; expect(after.audio.music[0].endMs).toBe(after.durationMs); });
  it('inserts deterministic SFX without duplicate IDs', async () => { const fixture = await setup(); const operation = audioOperation(fixture, 'insert-sfx', fixture.manifest.timeline.scenes[0].id, { startMs: 100, durationMs: 180, gainDb: -12, intent: 'impact' }); const plan = { ...fixture.plan, operations: [operation], conflicts: [] }; const after = transformAudio(fixture.snapshot, plan, [operation.id]).snapshot.manifest; expect(after.audio.sfx.map((item) => item.id).filter((id, index, all) => all.indexOf(id) !== index)).toEqual([]); });
  it('synchronizes audio tracks and segment timing', async () => { const fixture = await setup(); const operation = audioOperation(fixture, 'normalize-voice-gain', null, { maxGain: 0.8 }); const after = transformAudio(fixture.snapshot, { ...fixture.plan, operations: [operation], conflicts: [] }, [operation.id]).snapshot.manifest; const clip = after.timeline.tracks.find((item) => item.type === 'voice')?.clips[0]; expect(clip?.metadata.gain).toBe(after.audio.voice[0].gain); expect(clip?.startMs).toBe(after.audio.voice[0].startMs); });
  it('updates ducking automation without replacing unrelated points', async () => { const fixture = await setup(); const unrelatedIds = fixture.manifest.audio.automation.map((item) => item.id); const operation = audioOperation(fixture, 'adjust-ducking', null, {}); const after = transformAudio(fixture.snapshot, { ...fixture.plan, operations: [operation], conflicts: [] }, [operation.id]).snapshot.manifest; expect(after.audio.automation.filter((item) => unrelatedIds.includes(item.id)).map((item) => item.id).sort()).toEqual([...unrelatedIds].sort()); expect(after.audio.automation.filter((item) => item.metadata.sourceOperationId === operation.id)).toHaveLength(fixture.plan.ducking.length * 4); });
  it('keeps all segments in bounds', async () => { const fixture = await setup(); const after = transformAudio(fixture.snapshot, fixture.plan).snapshot.manifest; expect(() => validateAudioManifest(after)).not.toThrow(); });
  it('produces result-fingerprint revision IDs', async () => { const fixture = await setup(); const left = transformAudio(fixture.snapshot, fixture.plan); const modified = { ...fixture.plan, operations: fixture.plan.operations.map((item) => ({ ...item, status: 'disabled' as const })) }; const right = transformAudio(fixture.snapshot, modified); expect(left.snapshot.revisionId).not.toBe(right.snapshot.revisionId); });
  it('preview carries transformed snapshot and consistent rerender IDs', async () => { const fixture = await setup(); const preview = createAudioPreview(fixture.plan, fixture.snapshot); expect(preview.proposedSnapshot.manifest.validation).toBeNull(); expect(preview.rerenderSceneIds).toEqual(preview.affectedScenes); expect(preview.reusableSceneIds.filter((id) => preview.rerenderSceneIds.includes(id))).toEqual([]); });
  it('rejects previewless apply', async () => { const fixture = await setup(); const engine = createAudioProductionEngine(); const preview = engine.preview(fixture.plan, fixture.snapshot); await expect(() => engine.apply(fixture.plan, { ...preview, id: 'stale' }, fixture.snapshot)).toThrow(/current audio preview/); });
  it('requires explicit approval for manual SFX insertion at the engine boundary', async () => { const fixture = await setup(); const engine = createAudioProductionEngine(); const operation = { ...audioOperation(fixture, 'insert-sfx', fixture.manifest.timeline.scenes[0].id, { startMs: 100, durationMs: 180, gainDb: -12, intent: 'impact' }), automaticallyApplicable: false }; const plan = { ...fixture.plan, operations: [operation], conflicts: [] }; const unapproved = engine.preview(plan, fixture.snapshot); const withoutSfx = engine.apply(plan, unapproved, fixture.snapshot); expect(withoutSfx.appliedOperationIds).toEqual([]); expect(withoutSfx.revision.snapshot.manifest.audio.sfx).toEqual(fixture.manifest.audio.sfx); const approved = engine.preview(plan, fixture.snapshot, [operation.id]); const withSfx = engine.apply(plan, approved, fixture.snapshot, [operation.id]); expect(withSfx.appliedOperationIds).toEqual([operation.id]); expect(withSfx.revision.snapshot.manifest.audio.sfx.length).toBe(fixture.manifest.audio.sfx.length + 1); });
  it('binds preview freshness and exported metrics to the manual approval set', async () => { const fixture = await setup(); const engine = createAudioProductionEngine(); const operation = { ...audioOperation(fixture, 'insert-sfx', fixture.manifest.timeline.scenes[0].id, { startMs: 100, durationMs: 180, gainDb: -12, intent: 'impact' }), automaticallyApplicable: false }; const plan = { ...fixture.plan, operations: [operation], conflicts: [] }; const unapproved = engine.preview(plan, fixture.snapshot); const approved = engine.preview(plan, fixture.snapshot, [operation.id]); expect(unapproved.id).not.toBe(approved.id); expect(unapproved.operationCount).toBe(0); expect(unapproved.unapprovedManualOperationIds).toEqual([operation.id]); expect(approved.operationCount).toBe(1); expect(approved.approvedManualOperationIds).toEqual([operation.id]); expect(JSON.parse(JSON.stringify(approved)).approvedManualOperationIds).toEqual([operation.id]); expect(() => engine.apply(plan, unapproved, fixture.snapshot, [operation.id])).toThrow(/current audio preview/); });
  it('ignores invalid, disabled and critically conflicted manual approvals with diagnostics', async () => { const fixture = await setup(); const engine = createAudioProductionEngine(); const operation = { ...audioOperation(fixture, 'insert-sfx', fixture.manifest.timeline.scenes[0].id, { startMs: 100, durationMs: 180 }), automaticallyApplicable: false, status: 'disabled' as const }; const plan = { ...fixture.plan, operations: [operation], conflicts: [] }; const preview = engine.preview(plan, fixture.snapshot, [operation.id, 'missing-operation']); expect(preview.approvedManualOperationIds).toEqual([]); expect(preview.operationCount).toBe(0); expect(preview.warnings.filter((item) => item.includes('Ignored invalid manual operation approval'))).toHaveLength(2); });
  it('rejects stale snapshot transform', async () => { const fixture = await setup(); const stale = structuredClone(fixture.snapshot); stale.manifest.audio.settings.musicGain += 0.1; expect(() => transformAudio(stale, fixture.plan)).toThrow(/Stale audio plan/); });
  it('retimes the full timeline when trimming a trailing region', async () => { const fixture = await trailingSetup(); const scene = fixture.manifest.timeline.scenes[0]; const next = fixture.manifest.timeline.scenes[1]; const voice = fixture.manifest.audio.voice.find((item) => item.sceneId === scene.id)!; const nextVoice = fixture.manifest.audio.voice.find((item) => item.sceneId === next.id)!; const music = structuredClone(fixture.manifest.audio.music); const visual = fixture.manifest.timeline.tracks.flatMap((item) => item.clips).find((item) => item.sceneId === scene.id && item.endMs === scene.endMs)!; const nextClip = fixture.manifest.timeline.tracks.flatMap((item) => item.clips).find((item) => item.sceneId === next.id)!; const operation = audioOperation(fixture, 'trim-silence', scene.id, { startMs: voice.endMs, endMs: scene.endMs, preserveMs: 180 }); const plan = { ...fixture.plan, operations: [operation], conflicts: [] }; const result = transformAudio(fixture.snapshot, plan); const after = result.snapshot.manifest; const delta = result.removedSilenceMs; const afterScene = after.timeline.scenes[0]; const afterNext = after.timeline.scenes[1]; expect(after.audio.voice.find((item) => item.id === voice.id)?.startMs).toBe(voice.startMs); expect(afterScene.durationMs).toBeCloseTo(scene.durationMs - delta); expect(afterNext.startMs).toBeCloseTo(next.startMs - delta); expect(after.audio.voice.find((item) => item.id === nextVoice.id)?.startMs).toBeCloseTo(nextVoice.startMs - delta); expect(after.timeline.tracks.flatMap((item) => item.clips).find((item) => item.id === visual.id)?.endMs).toBe(afterScene.endMs); expect(after.timeline.tracks.flatMap((item) => item.clips).find((item) => item.id === nextClip.id)?.startMs).toBeCloseTo(nextClip.startMs - delta); expect(after.durationMs).toBeCloseTo(fixture.manifest.durationMs - delta); expect(after.timeline.durationMs).toBe(after.durationMs); expect(after.audio.durationMs).toBe(after.durationMs); expect(after.subtitles.durationMs).toBe(after.durationMs); expect(after.audio.music[0].startMs).toBe(music[0].startMs); expect(after.audio.music[0].endMs).toBeLessThanOrEqual(after.durationMs); expect(after.timeline.markers.every((item) => item.timeMs >= 0 && item.timeMs <= after.durationMs)).toBe(true); expect(after.timeline.markers.find((item) => item.sceneId === scene.id && item.type === 'scene-end')?.timeMs).toBe(afterScene.endMs); expect(after.timeline.scenes.every((item, index, scenes) => index === 0 || item.startMs <= scenes[index - 1].endMs)).toBe(true); const preview = createAudioPreview(plan, fixture.snapshot); expect(preview.durationDeltaMs).toBeCloseTo(-delta); expect(preview.removedSilenceMs).toBe(delta); expect(preview.rerenderSceneIds).toEqual(after.timeline.scenes.map((item) => item.id).sort()); });
  it('trims leading silence and keeps subtitles synchronized', async () => { const fixture = await setup(); const scene = fixture.manifest.timeline.scenes[0]; const voice = fixture.manifest.audio.voice.find((item) => item.sceneId === scene.id)!; const cue = fixture.manifest.subtitles.cues.find((item) => item.sceneId === scene.id)!; const operation = audioOperation(fixture, 'trim-silence', scene.id, { startMs: scene.startMs, endMs: voice.startMs, preserveMs: 50 }); const result = transformAudio(fixture.snapshot, { ...fixture.plan, operations: [operation], conflicts: [] }); const afterVoice = result.snapshot.manifest.audio.voice.find((item) => item.id === voice.id)!; const afterCue = result.snapshot.manifest.subtitles.cues.find((item) => item.id === cue.id)!; expect(voice.startMs - afterVoice.startMs).toBe(result.removedSilenceMs); expect(cue.startMs - afterCue.startMs).toBe(result.removedSilenceMs); expect(afterVoice.startMs).toBeGreaterThanOrEqual(scene.startMs); });
  it('trims internal dead-air only after the targeted gap', async () => { const fixture = await setup(); const scene = fixture.manifest.timeline.scenes[1]; const original = fixture.manifest.audio.voice.find((item) => item.sceneId === scene.id)!; const first = { ...original, id: 'voice-before', endMs: original.startMs + 300, durationMs: 300 }; const second = { ...original, id: 'voice-after', startMs: original.startMs + 1000, endMs: original.startMs + 1400, durationMs: 400 }; const manifest = structuredClone(fixture.manifest); manifest.audio.voice = manifest.audio.voice.filter((item) => item.sceneId !== scene.id).concat(first, second); const fingerprint = createManifestRevisionId(manifest); const snapshot = createTimelineSnapshot(manifest, fingerprint); const operation = { ...audioOperation(fixture, 'trim-silence', scene.id, { startMs: first.endMs, endMs: second.startMs, preserveMs: 100 }), projectId: manifest.projectId }; const plan = { ...fixture.plan, sourceManifestFingerprint: fingerprint, operations: [operation], conflicts: [] }; const result = transformAudio(snapshot, plan); const voices = result.snapshot.manifest.audio.voice; expect(voices.find((item) => item.id === first.id)).toEqual(first); expect(voices.find((item) => item.id === second.id)?.startMs).toBe(second.startMs - 600); expect(result.removedSilenceMs).toBe(600); });
  it('derives preview metrics only from enabled operations', async () => { const fixture = await trailingSetup(); const scene = fixture.manifest.timeline.scenes[0]; const voice = fixture.manifest.audio.voice.find((item) => item.sceneId === scene.id)!; const trim = audioOperation(fixture, 'trim-silence', scene.id, { startMs: voice.endMs, endMs: scene.endMs, preserveMs: 180 }); const active = createAudioPreview({ ...fixture.plan, operations: [trim], conflicts: [] }, fixture.snapshot); const disabled = createAudioPreview({ ...fixture.plan, operations: [{ ...trim, status: 'disabled' }], conflicts: [] }, fixture.snapshot); expect(active.removedSilenceMs).toBeGreaterThan(0); expect(active.operationCount).toBe(1); expect(active.affectedScenes).toContain(scene.id); expect(active.affectedScenes).toEqual(active.rerenderSceneIds); expect(disabled.removedSilenceMs).toBe(0); expect(disabled.operationCount).toBe(0); expect(disabled.affectedScenes).toEqual([]); expect(disabled.rerenderSceneIds).toEqual([]); });
  it('flags overlapping silence trims as a conflict', async () => { const fixture = await setup(); const scene = fixture.manifest.timeline.scenes[0]; const left = audioOperation(fixture, 'trim-silence', scene.id, { startMs: 100, endMs: 900 }); const right = { ...audioOperation(fixture, 'trim-silence', scene.id, { startMs: 800, endMs: 1200 }), id: 'trim-right' }; expect(detectAudioConflicts([right, left], fixture.manifest.durationMs).some((item) => item.type === 'silence-removal-conflict')).toBe(true); });
  it('preserves voice, SFX, music and manual ducking automation', async () => { const fixture = await automationSetup(); const operation = audioOperation(fixture, 'add-ducking', null, {}); const before = structuredClone(fixture.manifest.audio.automation); const result = transformAudio(fixture.snapshot, { ...fixture.plan, operations: [operation], conflicts: [] }); expect(result.snapshot.manifest.audio.automation).toEqual(expect.arrayContaining(before)); expect(fixture.snapshot.manifest.audio.automation).toEqual(before); });
  it('replaces generated ducking owned by the same operation across plan IDs', async () => { const fixture = await setup(); const operation = audioOperation(fixture, 'adjust-ducking', null, {}); const owned = { ...fixture.manifest.audio.automation[0], id: 'old-owned', type: 'ducking' as const, metadata: { sourceOperationId: operation.id, sourcePlanId: 'earlier-plan', kind: 'ducking', source: 'audio-production' } }; const legacyOwned = { ...owned, id: 'legacy-owned', metadata: { sourceOperationId: operation.id, sourcePlanId: 'legacy-plan', kind: 'ducking' } }; const other = { ...owned, id: 'other-owned', metadata: { ...owned.metadata, sourceOperationId: 'another-operation' } }; const manual = { ...owned, id: 'manual-owned', metadata: { ...owned.metadata, source: 'manual' } }; const manifest = structuredClone(fixture.manifest); manifest.audio.automation.push(owned, legacyOwned, other, manual); const fingerprint = createManifestRevisionId(manifest); const nextPlan = { ...fixture.plan, id: 'new-plan', sourceManifestFingerprint: fingerprint, operations: [operation], conflicts: [] }; const result = transformAudio(createTimelineSnapshot(manifest, fingerprint), nextPlan); const after = result.snapshot.manifest.audio.automation; expect(after.some((item) => item.id === owned.id || item.id === legacyOwned.id)).toBe(false); expect(after).toContainEqual(other); expect(after).toContainEqual(manual); expect(after.filter((item) => item.metadata.sourceOperationId === operation.id && item.metadata.source === 'audio-production')).toHaveLength(nextPlan.ducking.length * 4); expect(after.filter((item) => item.metadata.sourceOperationId === operation.id && item.metadata.source === 'audio-production').every((item) => item.metadata.sourcePlanId === nextPlan.id)).toBe(true); expect(new Set(after.map((item) => item.id)).size).toBe(after.length); });
  it('does not accumulate a ducking envelope on a repeated production run', async () => { const fixture = await setup(); const operation = audioOperation(fixture, 'adjust-ducking', null, {}); const firstPlan = { ...fixture.plan, id: 'ducking-plan-one', operations: [operation], conflicts: [] }; const first = transformAudio(fixture.snapshot, firstPlan).snapshot.manifest; const firstFingerprint = createManifestRevisionId(first); const secondPlan = { ...firstPlan, id: 'ducking-plan-two', sourceManifestFingerprint: firstFingerprint, ducking: firstPlan.ducking.map((item) => ({ ...item, reductionDb: item.reductionDb - 2 })) }; const second = transformAudio(createTimelineSnapshot(first, firstFingerprint), secondPlan).snapshot.manifest; const generated = second.audio.automation.filter((item) => item.metadata.sourceOperationId === operation.id && item.metadata.source === 'audio-production'); expect(generated).toHaveLength(secondPlan.ducking.length * 4); expect(generated.every((item) => item.metadata.sourcePlanId === secondPlan.id)).toBe(true); expect(generated.some((item) => item.metadata.phase === 'active' && item.gain < first.audio.automation.find((point) => point.metadata.sourceOperationId === operation.id && point.metadata.phase === 'active')!.gain)).toBe(true); });
  it('is idempotent for the same manifest and effective ducking plan', async () => { const fixture = await setup(); const operation = audioOperation(fixture, 'adjust-ducking', null, {}); const plan = { ...fixture.plan, operations: [operation], conflicts: [] }; const left = transformAudio(fixture.snapshot, plan); const right = transformAudio(fixture.snapshot, plan); expect(left.snapshot.manifest.audio.automation).toEqual(right.snapshot.manifest.audio.automation); expect(left.snapshot.revisionId).toBe(right.snapshot.revisionId); });
  it('produces deterministic ducking IDs and ordering', async () => { const fixture = await setup(); const operation = audioOperation(fixture, 'adjust-ducking', null, {}); const plan = { ...fixture.plan, operations: [operation], conflicts: [] }; const left = transformAudio(fixture.snapshot, plan).snapshot.manifest.audio.automation; const right = transformAudio(fixture.snapshot, plan).snapshot.manifest.audio.automation; expect(left).toEqual(right); expect(left).toEqual([...left].sort((a, b) => Number(a.metadata.startMs ?? a.timeMs) - Number(b.metadata.startMs ?? b.timeMs) || Number(a.metadata.endMs ?? a.timeMs) - Number(b.metadata.endMs ?? b.timeMs) || a.trackType.localeCompare(b.trackType) || a.id.localeCompare(b.id))); });
  it('invalidates all scenes for global ducking and none when disabled', async () => { const fixture = await setup(); const operation = audioOperation(fixture, 'add-ducking', null, {}); const active = createAudioPreview({ ...fixture.plan, operations: [operation], conflicts: [] }, fixture.snapshot); const disabled = createAudioPreview({ ...fixture.plan, operations: [{ ...operation, status: 'disabled' }], conflicts: [] }, fixture.snapshot); expect(active.rerenderSceneIds).toEqual(fixture.manifest.timeline.scenes.map((item) => item.id).sort()); expect(active.reusableSceneIds).toEqual([]); expect(disabled.rerenderSceneIds).toEqual([]); });
  it('invalidates only scenes intersecting a normalized track', async () => { const fixture = await setup(); const operation = audioOperation(fixture, 'normalize-voice-gain', null, { maxGain: 0.8 }); const preview = createAudioPreview({ ...fixture.plan, operations: [operation], conflicts: [] }, fixture.snapshot); const expected = fixture.manifest.timeline.scenes.filter((scene) => fixture.manifest.audio.voice.some((item) => item.endMs > scene.startMs && item.startMs < scene.endMs)).map((item) => item.id); expect(preview.rerenderSceneIds).toEqual(expected.sort()); });
  it('does not invalidate for critical conflicted global operations', async () => { const fixture = await setup(); const left = audioOperation(fixture, 'normalize-music-gain', null, { gain: 0.2 }); const right = { ...audioOperation(fixture, 'reduce-masking', null, { gain: 0.2 }), id: 'masking' }; const preview = createAudioPreview({ ...fixture.plan, operations: [left, right], conflicts: [] }, fixture.snapshot); expect(preview.operationCount).toBe(0); expect(preview.rerenderSceneIds).toEqual([]); });
});

async function setup() { const fixture = await editingFixture(); const input = { projectId: fixture.manifest.projectId, manifest: fixture.manifest, directorReport: fixture.report, scenes: fixture.manifest.timeline.scenes.map((scene) => ({ scene, voice: fixture.manifest.audio.voice.filter((item) => item.sceneId === scene.id) })) }; const plan = compileAudioProductionPlan(input); const snapshot = createTimelineSnapshot(fixture.manifest, createManifestRevisionId(fixture.manifest)); return { ...fixture, input, plan, snapshot }; }
async function trailingSetup() { const fixture = await setup(); const manifest = structuredClone(fixture.manifest); const scene = manifest.timeline.scenes[0]; manifest.audio.voice = manifest.audio.voice.map((item) => item.sceneId === scene.id ? { ...item, endMs: item.endMs - 600, durationMs: item.durationMs - 600 } : item); const fingerprint = createManifestRevisionId(manifest); return { ...fixture, manifest, snapshot: createTimelineSnapshot(manifest, fingerprint), plan: { ...fixture.plan, sourceManifestFingerprint: fingerprint } }; }
async function automationSetup() { const fixture = await setup(); const manifest = structuredClone(fixture.manifest); const base = manifest.audio.automation[0]; manifest.audio.automation = [{ ...base, id: 'voice-gain', type: 'gain', trackType: 'voice', metadata: { kind: 'manual-gain' } }, { ...base, id: 'sfx-gain', type: 'gain', trackType: 'sfx', metadata: { kind: 'manual-gain' } }, { ...base, id: 'music-fade', type: 'gain', trackType: 'music', metadata: { kind: 'manual-fade' } }, { ...base, id: 'manual-duck', type: 'ducking', trackType: 'music', metadata: { kind: 'ducking', source: 'manual' } }]; const fingerprint = createManifestRevisionId(manifest); return { ...fixture, manifest, snapshot: createTimelineSnapshot(manifest, fingerprint), plan: { ...fixture.plan, sourceManifestFingerprint: fingerprint } }; }
function audioOperation(fixture: Awaited<ReturnType<typeof setup>>, type: AudioOperation['type'], sceneId: string | null, parameters: AudioOperation['parameters']): AudioOperation { return { id: `test-${type}`, projectId: fixture.manifest.projectId, sceneId, sourceRecommendationId: null, type, priority: 'high', reason: type, evidence: [], parameters, expectedImpact: 5, confidence: 90, automaticallyApplicable: true, dependencies: [], conflicts: [], status: 'proposed', createdAt: fixture.report.generatedAt }; }
