import { beforeEach, describe, expect, it } from 'vitest';
import { createAudioProductionEngine } from '@/core/audio-production';
import { createManifestRevisionId, createTimelineSnapshot } from '@/core/editing';
import { TypedEventBus, type ApplicationEventMap } from '@/core/events';
import { createAudioProductionApplicationService } from '@/services/audioProductionApplicationService';
import { createAudioProductionMonitor } from '@/services/audioProductionMonitor';
import { applyActiveAudioPlan, configureAudioProductionController, createActiveAudioPlan, redoActiveAudio, undoActiveAudio } from '@/services/audioProductionController';
import { useAudioProductionStore } from '@/store/audioProductionStore';
import { useDirectorReportStore } from '@/store/directorReportStore';
import { useMediaStore } from '@/store/mediaStore';
import { editingFixture } from '../editing/fixtures';

describe('audio service lifecycle and revision safety', () => {
  it('publishes analysis, plan and preview lifecycle', async () => { const fixture = await prepare(); await createActiveAudioPlan(); const state = useAudioProductionStore.getState(); expect(state.analysisStatus).toBe('ready'); expect(state.currentPlan).not.toBeNull(); expect(state.currentPreview).not.toBeNull(); });
  it('rejects stale Director reports', async () => { const fixture = await prepare(); const changed = structuredClone(fixture.manifest); changed.audio.settings.musicGain += 0.1; useMediaStore.setState({ manifest: changed }); await expect(createActiveAudioPlan()).rejects.toThrow(/Manifest changed/); });
  it('rejects apply after concurrent manifest change', async () => { const fixture = await prepare(); await createActiveAudioPlan(); const changed = structuredClone(fixture.manifest); changed.audio.settings.sfxGain += 0.1; useMediaStore.setState({ manifest: changed }); await expect(applyActiveAudioPlan(useAudioProductionStore.getState().operations.map((item) => item.id))).rejects.toThrow(/Stale audio revision/); expect(useMediaStore.getState().manifest?.audio.settings.sfxGain).toBe(changed.audio.settings.sfxGain); });
  it('validates a successful apply and restores render readiness', async () => { await prepare(); await createActiveAudioPlan(); await applyActiveAudioPlan(); expect(useMediaStore.getState().validation).not.toBeNull(); expect(useMediaStore.getState().validationRequired).toBe(false); });
  it('keeps apply history after preview is cleared', async () => { await prepare(); await createActiveAudioPlan(); await applyActiveAudioPlan(); const state = useAudioProductionStore.getState(); expect(state.currentPreview).toBeNull(); expect(state.undoAvailable).toBe(true); });
  it('undo and redo work without creating a new plan', async () => { await prepare(); await createActiveAudioPlan(); await applyActiveAudioPlan(); const applied = useMediaStore.getState().manifest; expect(applied).not.toBeNull(); const appliedFingerprint = createManifestRevisionId(applied!); await undoActiveAudio(); expect(useAudioProductionStore.getState().redoAvailable).toBe(true); await redoActiveAudio(); expect(createManifestRevisionId(useMediaStore.getState().manifest!)).toBe(appliedFingerprint); expect(useAudioProductionStore.getState().approvedManualOperationIds).toEqual([]); });
  it('isolates histories by project', async () => { const fixture = await prepare(); const snapshot = createTimelineSnapshot(fixture.manifest, createManifestRevisionId(fixture.manifest)); useAudioProductionStore.getState().replaceWithFreshSnapshot(snapshot); useAudioProductionStore.setState({ revisionsByProject: { ...useAudioProductionStore.getState().revisionsByProject, other: [{ id: 'other', projectId: 'other', parentRevisionId: null, createdAt: '', operationIds: [], snapshot: { ...snapshot, projectId: 'other', revisionId: 'other', manifest: { ...snapshot.manifest, projectId: 'other' } } }] } }); useAudioProductionStore.getState().resetProject(fixture.manifest.projectId); expect(useAudioProductionStore.getState().revisionsByProject.other).toHaveLength(1); });
  it('invalidates preview when an operation is disabled', async () => { await prepare(); await createActiveAudioPlan(); const operation = useAudioProductionStore.getState().operations[0]; useAudioProductionStore.getState().operationEnabled(operation.id, false); expect(useAudioProductionStore.getState().currentPreview).toBeNull(); });
  it('keeps manual enablement separate from explicit approval', async () => { await prepare(); await createActiveAudioPlan(); const manual = useAudioProductionStore.getState().operations.find((item) => !item.automaticallyApplicable); expect(manual).toBeDefined(); expect(useAudioProductionStore.getState().approvedManualOperationIds).toEqual([]); useAudioProductionStore.getState().approveManualOperation(manual!.id); expect(useAudioProductionStore.getState().approvedManualOperationIds).toEqual([manual!.id]); expect(useAudioProductionStore.getState().currentPreview).toBeNull(); useAudioProductionStore.getState().operationEnabled(manual!.id, false); expect(useAudioProductionStore.getState().approvedManualOperationIds).toEqual([]); useAudioProductionStore.getState().operationEnabled(manual!.id, true); expect(useAudioProductionStore.getState().approvedManualOperationIds).toEqual([]); });
  it('resets manual approvals when a new project plan starts', async () => { const fixture = await prepare(); await createActiveAudioPlan(); const manual = useAudioProductionStore.getState().operations.find((item) => !item.automaticallyApplicable)!; useAudioProductionStore.getState().approveManualOperation(manual.id); expect(useAudioProductionStore.getState().approvedManualOperationIds).toEqual([manual.id]); useAudioProductionStore.getState().analysisStarted(`${fixture.manifest.projectId}-other`); expect(useAudioProductionStore.getState().approvedManualOperationIds).toEqual([]); });
  it('prevents duplicate monitor listeners', async () => { const fixture = await editingFixture(); const bus = new TypedEventBus<ApplicationEventMap>(); const monitor = createAudioProductionMonitor(bus); monitor.start(); monitor.start(); await bus.emit('audio-production:analysis-started', { projectId: fixture.manifest.projectId, revisionId: 'r', startedAt: '' }); expect(useAudioProductionStore.getState().activeProjectId).toBe(fixture.manifest.projectId); monitor.stop(); });
  it('supports abort through the application service', async () => { const fixture = await editingFixture(); const bus = new TypedEventBus<ApplicationEventMap>(); const service = createAudioProductionApplicationService(createAudioProductionEngine(), bus); const controller = new AbortController(); controller.abort(); await expect(service.createPlan(fixture.report, fixture.manifest, undefined, controller.signal)).rejects.toMatchObject({ name: 'AbortError' }); });
});

beforeEach(() => { useAudioProductionStore.setState({ activeProjectId: null, currentPlan: null, currentPreview: null, workingSnapshot: null, analysisStatus: 'idle', applyStatus: 'idle', conflicts: [], operations: [], approvedManualOperationIds: [], currentRevisionId: null, revisionsByProject: {}, staleRevisionsByProject: {}, redoByProject: {}, undoAvailable: false, redoAvailable: false, lastError: null, lastAnalyzedAt: null, lastAppliedAt: null }); useDirectorReportStore.getState().reset(); useMediaStore.getState().clearMediaProject(); });
async function prepare() { const fixture = await editingFixture(); const bus = new TypedEventBus<ApplicationEventMap>(); const monitor = createAudioProductionMonitor(bus); monitor.start(); configureAudioProductionController(createAudioProductionApplicationService(createAudioProductionEngine(), bus)); useMediaStore.getState().setBuildResult(fixture.project, fixture.manifest, fixture.renderReady, fixture.assetResolution, fixture.validation); useDirectorReportStore.getState().analysisCompleted(fixture.report); return fixture; }
