import { afterEach, describe, expect, it, vi } from 'vitest';
import { createManifestRevisionId, createTimelineSnapshot } from '@/core/editing';
import { createVisualAnalysisRequestIdentity, createVisualPreviewRequestIdentity, createVisualProductionEngine } from '@/core/visual-production';
import { applyActiveVisualPlan, configureVisualProductionController, createActiveVisualPlan, redoVisual, undoVisual } from '@/services/visualProductionController';
import type { VisualProductionApplicationService } from '@/services/visualProductionApplicationService';
import { acquireVisualOperation, releaseVisualOperation } from '@/services/visualOperationCoordinator';
import { useMediaStore } from '@/store/mediaStore';
import { useVisualProductionStore } from '@/store/visualProductionStore';
import { editingFixture } from '../editing/fixtures';

afterEach(() => { configureVisualProductionController(null); useMediaStore.setState(useMediaStore.getInitialState(), true); useVisualProductionStore.setState(useVisualProductionStore.getInitialState(), true); });

it('isolates mutable visual operation locks by project', () => { const first = acquireVisualOperation('project-a', 'analyzing'); const second = acquireVisualOperation('project-b', 'undoing'); expect(() => acquireVisualOperation('project-a', 'applying')).toThrow(/Visual operation in progress \(analyzing\)/); releaseVisualOperation(second); releaseVisualOperation(first); });

async function preparedApply() { const base = await editingFixture(); const manifest = structuredClone(base.manifest); manifest.assets.push({ id: 'controller-asset', type: 'video', source: 'controller.mp4', metadata: { brightness: .1 } }); const scene = manifest.timeline.scenes[0]; scene.assetIds = ['controller-asset']; manifest.timeline.tracks.find((track) => track.type === 'video')!.clips.push({ id: 'controller-clip', sceneId: scene.id, assetId: 'controller-asset', startMs: scene.startMs, endMs: scene.endMs, durationMs: scene.durationMs, offsetMs: 0, metadata: {} }); useMediaStore.getState().setBuildResult(base.project, manifest, base.renderReady, base.assetResolution, base.validation); const installed = useMediaStore.getState().manifest!; const snapshot = createTimelineSnapshot(installed, createManifestRevisionId(installed)); const engine = createVisualProductionEngine(); const plan = engine.analyze({ manifest: installed, snapshot }); const operation = plan.operations.find((item) => item.type === 'brightness')!; const preview = engine.preview(plan, snapshot, [operation.id]); const result = engine.apply(plan, preview, snapshot, [operation.id]); const store = useVisualProductionStore.getState(); store.replace(snapshot); const analysisRequest = createVisualAnalysisRequestIdentity(snapshot, 1); store.start(analysisRequest); store.complete(analysisRequest, plan, snapshot); store.approve(operation.id, true); const request = createVisualPreviewRequestIdentity(plan, snapshot, [operation.id], 1); store.previewStarted(request); store.previewCompleted(request, preview); return { base, engine, manifest: installed, snapshot, plan, preview, operation, result }; }
function service(overrides: Partial<VisualProductionApplicationService> = {}): VisualProductionApplicationService { return { async createPlan() { throw new Error('not used'); }, async createPreview() { throw new Error('not used'); }, async apply() { throw new Error('not used'); }, async revisionCompleted() {}, ...overrides }; }
function changed(manifest: Awaited<ReturnType<typeof preparedApply>>['manifest'], suffix = ' concurrent') { const value = structuredClone(manifest); value.timeline.scenes[0].text += suffix; return value; }
function deferred<T>() { let resolve!: (value: T) => void; let reject!: (reason: unknown) => void; const promise = new Promise<T>((done, fail) => { resolve = done; reject = fail; }); return { promise, resolve, reject }; }

describe('visual controller optimistic apply concurrency', () => {
  it('installs and records apply when the source manifest remains current', async () => { const state = await preparedApply(); configureVisualProductionController(service({ apply: vi.fn(async () => state.result) })); await applyActiveVisualPlan(); expect(useMediaStore.getState().manifest?.timeline.tracks.flatMap((track) => track.clips).some((clip) => Array.isArray(clip.metadata.visualProduction))).toBe(true); expect(useVisualProductionStore.getState().history[state.manifest.projectId]).toHaveLength(2); });
  it('rejects an apply changed during await without overwriting media or history', async () => { const state = await preparedApply(); const wait = deferred<typeof state.result>(); configureVisualProductionController(service({ apply: vi.fn(() => wait.promise) })); const applying = applyActiveVisualPlan(); const concurrent = changed(state.manifest); useMediaStore.getState().replaceEditedManifest(concurrent); wait.resolve(state.result); await expect(applying).rejects.toThrow(/changed by another operation/); expect(useMediaStore.getState().manifest?.timeline.scenes[0].text).toBe(concurrent.timeline.scenes[0].text); expect(useVisualProductionStore.getState().history[state.manifest.projectId]).toHaveLength(1); expect(useVisualProductionStore.getState().snapshot?.manifestFingerprint).toBe(createManifestRevisionId(concurrent)); });
  it('rejects the same project with a different fingerprint before apply', async () => { const state = await preparedApply(); useMediaStore.getState().replaceEditedManifest(changed(state.manifest)); const apply = vi.fn(async () => state.result); configureVisualProductionController(service({ apply })); await expect(applyActiveVisualPlan()).rejects.toThrow(/Stale visual revision/); expect(apply).not.toHaveBeenCalled(); });
  it('continues rejecting a different active project identity', async () => { const state = await preparedApply(); const other = changed(state.manifest); other.projectId = 'other-project'; useMediaStore.setState({ manifest: other }); const apply = vi.fn(async () => state.result); configureVisualProductionController(service({ apply })); await expect(applyActiveVisualPlan()).rejects.toThrow(/Stale visual revision/); expect(apply).not.toHaveBeenCalled(); });
  it('does not install validation derived from the stale source', async () => { const state = await preparedApply(); const wait = deferred<typeof state.result>(); configureVisualProductionController(service({ apply: () => wait.promise })); const applying = applyActiveVisualPlan(); const concurrent = changed(state.manifest); concurrent.validation = null; useMediaStore.getState().replaceEditedManifest(concurrent); wait.resolve(state.result); await expect(applying).rejects.toThrow(); expect(useMediaStore.getState().manifest?.validation).toBeNull(); expect(useMediaStore.getState().manifest?.timeline.scenes[0].text).toBe(concurrent.timeline.scenes[0].text); });
  it('starts a retry plan from the quarantined current manifest', async () => { const state = await preparedApply(); const wait = deferred<typeof state.result>(); configureVisualProductionController(service({ apply: () => wait.promise })); const applying = applyActiveVisualPlan(); const concurrent = changed(state.manifest); useMediaStore.getState().replaceEditedManifest(concurrent); wait.resolve(state.result); await expect(applying).rejects.toThrow(); const createPlan = vi.fn(async (_manifest, snapshot) => ({ plan: state.engine.analyze({ manifest: concurrent, snapshot: snapshot! }), snapshot: snapshot! })); const createPreview = vi.fn(async (plan, snapshot) => state.engine.preview(plan, snapshot, [])); configureVisualProductionController(service({ createPlan, createPreview })); await createActiveVisualPlan(); expect(createPlan.mock.calls[0][1]?.manifestFingerprint).toBe(createManifestRevisionId(concurrent)); });
});

describe('visual controller stale undo and redo protection', () => {
  async function appliedState() { const state = await preparedApply(); useMediaStore.getState().replaceEditedManifest(state.result.revision.snapshot.manifest); useVisualProductionStore.getState().applied(state.result); return state; }
  it('undoes and redoes a current visual revision', async () => { const state = await appliedState(); configureVisualProductionController(service()); await undoVisual(); expect(createManifestRevisionId(useMediaStore.getState().manifest!)).toBe(state.snapshot.manifestFingerprint); await redoVisual(); expect(createManifestRevisionId(useMediaStore.getState().manifest!)).toBe(state.result.revision.snapshot.manifestFingerprint); });
  it('rejects stale undo and preserves concurrent subsystem edits', async () => { const state = await appliedState(); const concurrent = changed(state.result.revision.snapshot.manifest, ' audio edit'); useMediaStore.getState().replaceEditedManifest(concurrent); configureVisualProductionController(service()); await expect(undoVisual()).rejects.toThrow(/visual revision history is no longer current/); expect(useMediaStore.getState().manifest?.timeline.scenes[0].text).toBe(concurrent.timeline.scenes[0].text); expect(useVisualProductionStore.getState().history[state.manifest.projectId]).toHaveLength(1); });
  it('rejects stale redo and preserves concurrent subsystem edits', async () => { const state = await appliedState(); configureVisualProductionController(service()); await undoVisual(); const concurrent = changed(state.snapshot.manifest, ' editing change'); useMediaStore.getState().replaceEditedManifest(concurrent); await expect(redoVisual()).rejects.toThrow(/visual revision history is no longer current/); expect(useMediaStore.getState().manifest?.timeline.scenes[0].text).toBe(concurrent.timeline.scenes[0].text); expect(useVisualProductionStore.getState().history[state.manifest.projectId]).toHaveLength(1); });
  it.each(['undo', 'redo'] as const)('rechecks current manifest after delayed %s event handlers', async (kind) => { const state = await appliedState(); configureVisualProductionController(service()); if (kind === 'redo') await undoVisual(); const wait = deferred<void>(); configureVisualProductionController(service({ revisionCompleted: () => wait.promise })); const moving = kind === 'undo' ? undoVisual() : redoVisual(); const concurrent = changed(useMediaStore.getState().manifest!, ` ${kind} race`); useMediaStore.getState().replaceEditedManifest(concurrent); wait.resolve(); await expect(moving).rejects.toThrow(/visual revision history is no longer current/); expect(useMediaStore.getState().manifest?.timeline.scenes[0].text).toBe(concurrent.timeline.scenes[0].text); });
  it.each(['undo', 'redo'] as const)('keeps revision and media state unchanged when the %s event rejects', async (kind) => {
    const state = await appliedState();
    configureVisualProductionController(service());
    if (kind === 'redo') await undoVisual();
    const beforeStore = useVisualProductionStore.getState();
    const beforeHistory = beforeStore.history[state.manifest.projectId];
    const beforeRedo = beforeStore.redoStack[state.manifest.projectId];
    const beforeFingerprint = createManifestRevisionId(useMediaStore.getState().manifest!);
    configureVisualProductionController(service({ revisionCompleted: vi.fn(async () => { throw new Error(`${kind} listener failed`); }) }));
    const action = kind === 'undo' ? undoVisual : redoVisual;
    await expect(action()).rejects.toThrow(`${kind} listener failed`);
    const after = useVisualProductionStore.getState();
    expect(after.history[state.manifest.projectId]).toEqual(beforeHistory);
    expect(after.redoStack[state.manifest.projectId]).toEqual(beforeRedo);
    expect(after.snapshot?.revisionId).toBe(beforeStore.snapshot?.revisionId);
    expect(createManifestRevisionId(useMediaStore.getState().manifest!)).toBe(beforeFingerprint);
    configureVisualProductionController(service());
    await expect(action()).resolves.toBeUndefined();
  });
  it('does not commit undo history when manifest installation fails', async () => {
    const state = await appliedState();
    const before = useVisualProductionStore.getState();
    const replace = vi.spyOn(useMediaStore.getState(), 'replaceValidatedManifest').mockImplementation(() => { throw new Error('install failed'); });
    configureVisualProductionController(service());
    await expect(undoVisual()).rejects.toThrow('install failed');
    expect(useVisualProductionStore.getState().history[state.manifest.projectId]).toEqual(before.history[state.manifest.projectId]);
    expect(useVisualProductionStore.getState().snapshot?.revisionId).toBe(before.snapshot?.revisionId);
    replace.mockRestore();
  });
  it.each(['undo', 'redo'] as const)('rejects analysis and apply while delayed %s owns the project transaction', async (kind) => { const state = await appliedState(); configureVisualProductionController(service()); if (kind === 'redo') await undoVisual(); const wait = deferred<void>(); configureVisualProductionController(service({ revisionCompleted: () => wait.promise })); const moving = kind === 'undo' ? undoVisual() : redoVisual(); await expect(createActiveVisualPlan()).rejects.toThrow(new RegExp(`Visual operation in progress \\(${kind}ing\\)`)); await expect(applyActiveVisualPlan()).rejects.toThrow(new RegExp(`Visual operation in progress \\(${kind}ing\\)`)); const beforeManifest = createManifestRevisionId(useMediaStore.getState().manifest!); wait.resolve(); await expect(moving).resolves.toBeUndefined(); expect(createManifestRevisionId(useMediaStore.getState().manifest!)).not.toBe(beforeManifest); expect(useVisualProductionStore.getState().snapshot?.revisionId).toBe(kind === 'undo' ? state.snapshot.revisionId : state.result.revision.snapshot.revisionId); });
  it('rejects duplicate and opposite revision moves while one event is pending, then releases the lock', async () => { await appliedState(); const wait = deferred<void>(); configureVisualProductionController(service({ revisionCompleted: () => wait.promise })); const moving = undoVisual(); await expect(undoVisual()).rejects.toThrow(/Visual operation in progress \(undoing\)/); await expect(redoVisual()).rejects.toThrow(/Visual operation in progress \(undoing\)/); wait.reject(new Error('event failed')); await expect(moving).rejects.toThrow('event failed'); configureVisualProductionController(service()); await expect(undoVisual()).resolves.toBeUndefined(); });
  it('rejects undo while analysis owns the project and permits retry after analysis failure', async () => { await appliedState(); const wait = deferred<never>(); configureVisualProductionController(service({ createPlan: () => wait.promise })); const analyzing = createActiveVisualPlan(); await expect(undoVisual()).rejects.toThrow(/Visual operation in progress \(analyzing\)/); wait.reject(new Error('analysis failed')); await expect(analyzing).rejects.toThrow('analysis failed'); configureVisualProductionController(service()); await expect(undoVisual()).resolves.toBeUndefined(); });
  it('rejects redo while apply owns the project and releases the lock after completion', async () => { const state = await appliedState(); configureVisualProductionController(service()); await undoVisual(); const current = useMediaStore.getState().manifest!; const snapshot = useVisualProductionStore.getState().snapshot!; const plan = state.engine.analyze({ manifest: current, snapshot }); const preview = state.engine.preview(plan, snapshot, []); configureVisualProductionController(service({ createPlan: async () => ({ plan, snapshot }), createPreview: async () => preview })); await createActiveVisualPlan(); const result = state.engine.apply(plan, preview, snapshot, []); const wait = deferred<typeof result>(); configureVisualProductionController(service({ apply: () => wait.promise })); const applying = applyActiveVisualPlan(); await expect(redoVisual()).rejects.toThrow(/Visual operation in progress \(applying\)/); wait.resolve(result); await expect(applying).resolves.toBeUndefined(); configureVisualProductionController(service()); await expect(redoVisual()).resolves.toBeUndefined(); });
  it('does not install the target when the store binding changes before commit', async () => { const state = await appliedState(); const wait = deferred<void>(); configureVisualProductionController(service({ revisionCompleted: () => wait.promise })); const moving = undoVisual(); useVisualProductionStore.setState({ snapshot: state.snapshot }); const replaceEdited = vi.spyOn(useMediaStore.getState(), 'replaceEditedManifest'); wait.resolve(); await expect(moving).rejects.toThrow(/visual revision history is no longer current/); expect(replaceEdited).not.toHaveBeenCalled(); expect(createManifestRevisionId(useMediaStore.getState().manifest!)).toBe(state.result.revision.snapshot.manifestFingerprint); replaceEdited.mockRestore(); });
  it('does not install the target when commitRevisionMove rejects the candidate', async () => { const state = await appliedState(); configureVisualProductionController(service()); const commit = vi.spyOn(useVisualProductionStore.getState(), 'commitRevisionMove').mockReturnValue(false); const replaceEdited = vi.spyOn(useMediaStore.getState(), 'replaceEditedManifest'); await expect(undoVisual()).rejects.toThrow(/visual revision history is no longer current/); expect(replaceEdited).not.toHaveBeenCalled(); expect(createManifestRevisionId(useMediaStore.getState().manifest!)).toBe(state.result.revision.snapshot.manifestFingerprint); commit.mockRestore(); replaceEdited.mockRestore(); });
  it('rejects restored history without a current working snapshot and allows a fresh plan', async () => { const state = await appliedState(); useVisualProductionStore.setState({ snapshot: null }); configureVisualProductionController(service()); await expect(undoVisual()).rejects.toThrow(/visual revision history is no longer current/); expect(useVisualProductionStore.getState().history[state.manifest.projectId]).toHaveLength(1); });
});

describe('visual analysis latest-request-wins ordering', () => {
  async function analysisState() { const base = await editingFixture(); useMediaStore.getState().setBuildResult(base.project, base.manifest, base.renderReady, base.assetResolution, base.validation); const manifest = useMediaStore.getState().manifest!; const snapshot = createTimelineSnapshot(manifest, createManifestRevisionId(manifest)); const engine = createVisualProductionEngine(); const plan = engine.analyze({ manifest, snapshot }); return { manifest, snapshot, engine, plan }; }
  it('rejects a duplicate active analysis without disturbing the effective request', async () => { const state = await analysisState(); const wait = deferred<{ plan: typeof state.plan; snapshot: typeof state.snapshot }>(); const createPlan = vi.fn(() => wait.promise); configureVisualProductionController(service({ createPlan, createPreview: async (plan, snapshot) => state.engine.preview(plan, snapshot, []) })); const first = createActiveVisualPlan(); await expect(createActiveVisualPlan()).rejects.toThrow(/Visual operation in progress \(analyzing\)/); expect(createPlan).toHaveBeenCalledTimes(1); wait.resolve({ plan: state.plan, snapshot: state.snapshot }); await expect(first).resolves.toBe(true); expect(useVisualProductionStore.getState()).toMatchObject({ plan: state.plan, status: 'ready' }); });
  it.each(['fingerprint', 'project'] as const)('rejects completion after the active %s binding changes', async (binding) => { const state = await analysisState(); const wait = deferred<{ plan: typeof state.plan; snapshot: typeof state.snapshot }>(); configureVisualProductionController(service({ createPlan: () => wait.promise, createPreview: async (plan, snapshot) => state.engine.preview(plan, snapshot, []) })); const creating = createActiveVisualPlan(); const changedManifest = structuredClone(state.manifest); if (binding === 'project') changedManifest.projectId = 'new-project'; else changedManifest.timeline.scenes[0].text += ' changed'; useMediaStore.setState({ manifest: changedManifest }); wait.resolve({ plan: state.plan, snapshot: state.snapshot }); await expect(creating).resolves.toBe(false); expect(useVisualProductionStore.getState().plan).toBeNull(); expect(useVisualProductionStore.getState().status).toBe('idle'); });
});
