import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { createManifestRevisionId, createTimelineSnapshot } from '@/core/editing';
import { colorGradeFilter, createVisualProductionEngine, exposureDelta, getSceneVisualOperations, getVisualOperationCapability, matchesAbstractVisualKeyword, normalizeVisualAnalyzerText, resolveColorGrade, type VisualOperation, type VisualOperationType, type VisualProductionPlan } from '@/core/visual-production';
import { buildSceneVisualEffectPlan } from '@/core/render/visualEffectBuilder';
import { editingFixture } from '../editing/fixtures';

async function fixture(brightness = .12) { const base = await editingFixture(); const manifest = structuredClone(base.manifest); manifest.timeline.scenes[1].text = `How ${manifest.timeline.scenes[1].text}`; manifest.timeline.scenes[1].cameraMotion = 'none'; manifest.assets.push({ id: 'visual-asset', type: 'video', source: 'visual.mp4', metadata: { faceX: .92, faceY: .08, brightness, contrast: .18, sharpness: .2, shake: .7, compressionArtifacts: .8, textContrast: .3, visualNovelty: .2, lumaClipping: true } }); manifest.timeline.scenes[0].assetIds = ['visual-asset']; manifest.timeline.tracks.find((item) => item.type === 'video')?.clips.splice(0, 0, { id: 'visual-clip', sceneId: manifest.timeline.scenes[0].id, assetId: 'visual-asset', startMs: manifest.timeline.scenes[0].startMs, endMs: manifest.timeline.scenes[0].endMs, durationMs: manifest.timeline.scenes[0].durationMs, offsetMs: 0, metadata: {} }); return manifest; }
async function setup(brightness = .12) { const manifest = await fixture(brightness); const snapshot = createTimelineSnapshot(manifest, createManifestRevisionId(manifest)); const engine = createVisualProductionEngine(); const plan = engine.analyze({ manifest, snapshot }); return { manifest, snapshot, engine, plan }; }
function operation(plan: VisualProductionPlan, type: VisualOperationType): VisualOperation { const found = plan.operations.find((item) => item.type === type); if (!found) throw new Error(`Missing ${type} operation in fixture.`); return found; }
function withReframe(plan: VisualProductionPlan): { plan: VisualProductionPlan; reframe: VisualOperation } { const base = operation(plan, 'brightness'); const reframe = { ...base, id: `${base.id}-reframe`, type: 'reframe' as const, support: 'planned-only' as const, parameters: { anchorX: .5, anchorY: .38 } }; return { plan: { ...plan, operations: [reframe] }, reframe }; }
function epicVisualProductionFiles(): string[] { const roots = ['src/core/visual-production', 'src/components/visual-production']; const recursive = (directory: string): string[] => existsSync(resolve(directory)) ? readdirSync(resolve(directory)).flatMap((name) => { const path = resolve(directory, name); return statSync(path).isDirectory() ? recursive(path) : path.endsWith('.ts') || path.endsWith('.tsx') ? [path] : []; }) : []; return [...roots.flatMap(recursive), resolve('src/core/render/visualEffectBuilder.ts'), resolve('src/services/visualProductionApplicationService.ts'), resolve('src/services/visualProductionController.ts'), resolve('src/store/visualProductionStore.ts'), resolve('src/views/AIVisualStudio.tsx')].sort(); }

describe('visual operation capability enforcement', () => {
  it('keeps unsupported reframe out of applied operations, score impact, rerender and fingerprint changes', async () => { const state = await setup(); const { plan, reframe } = withReframe(state.plan); const { engine, snapshot } = state; const preview = engine.preview(plan, snapshot, [reframe.id]); expect(reframe.support).toBe('planned-only'); expect(preview.operationCount).toBe(0); expect(preview.estimatedScore).toBe(plan.scores.overall); expect(preview.rerenderSceneIds).toEqual([]); expect(preview.proposedSnapshot).toBe(snapshot); expect(preview.proposedSnapshot.manifestFingerprint).toBe(snapshot.manifestFingerprint); expect(preview.operationResults.find((item) => item.operationId === reframe.id)).toMatchObject({ support: 'planned-only', status: 'planned-only' }); const result = engine.apply(plan, preview, snapshot, [reframe.id]); expect(result.appliedOperationIds).toEqual([]); expect(result.skippedOperationIds).toContain(reframe.id); expect(result.revision.snapshot).toBe(snapshot); });
  it('retains B-roll as a plan but never inserts or applies its overlay', async () => { const { engine, plan, snapshot } = await setup(); expect(plan.broll.length).toBeGreaterThan(0); const overlay = operation(plan, 'overlay'); const before = JSON.stringify(snapshot.manifest); const preview = engine.preview(plan, snapshot, [overlay.id]); const result = engine.apply(plan, preview, snapshot, [overlay.id]); expect(preview.operationResults.find((item) => item.operationId === overlay.id)).toMatchObject({ support: 'planned-only', status: 'planned-only' }); expect(preview.operationCount).toBe(0); expect(preview.rerenderSceneIds).toEqual([]); expect(result.appliedOperationIds).not.toContain(overlay.id); expect(JSON.stringify(result.revision.snapshot.manifest)).toBe(before); expect(result.operationResults).toEqual(preview.operationResults); });
  it('cannot force a planned-only operation through manual approval and emits understandable diagnostics', async () => { const state = await setup(); const { plan, reframe: planned } = withReframe(state.plan); const { engine, snapshot } = state; const preview = engine.preview(plan, snapshot, [planned.id]); expect(preview.warnings.join(' ')).toContain('Reframe is retained as composition guidance'); expect(engine.apply(plan, preview, snapshot, [planned.id]).operationResults).toEqual(preview.operationResults); });
  it('uses one central registry for implemented and plan-only behavior', () => { expect(getVisualOperationCapability('reframe')).toMatchObject({ support: 'planned-only', renderEffect: false }); expect(getVisualOperationCapability('overlay')).toMatchObject({ support: 'planned-only', renderEffect: false }); for (const type of ['brightness', 'contrast', 'color-grade'] as const) expect(getVisualOperationCapability(type)).toMatchObject({ support: 'implemented', renderEffect: true }); expect(getVisualOperationCapability('background-blur')).toMatchObject({ support: 'planned-only', renderEffect: false }); });
  it('shows the plan-only capability label in UI and exports matching operation results', () => { const source = readFileSync(resolve('src/views/AIVisualStudio.tsx'), 'utf8'); expect(source).toContain('{capability.label}'); expect(source).toContain('disabled={!implemented || busy || previewBusy || revisionBusy}'); expect(source).toContain('operationResults: preview.operationResults'); expect(getVisualOperationCapability('overlay').label).toBe('Plan only in this version'); });
  it('handles revision action failures and StrictMode lifecycle without leaving controls busy', () => { const source = readFileSync(resolve('src/views/AIVisualStudio.tsx'), 'utf8'); expect(source).toContain('mounted.current = true'); expect(source).toContain('mountCycle.current === cycle'); expect(source).toContain('revisionInFlight.current = false'); expect(source).toContain('setRevisionBusy(false)'); expect(source).toContain('cancelActiveVisualAnalysis()'); expect(source).toContain('disabled={revisionBusy || busy || previewBusy'); expect(source).toContain('disabled={busy || previewBusy || revisionBusy}'); expect(source).toContain('!preview || !preview.operationCount || busy || previewBusy || revisionBusy'); expect(source).toContain('Visual revision operation is in progress.'); expect(source).toContain("moveRevision('undo')"); expect(source).toContain("moveRevision('redo')"); });
  it('continues applying implemented brightness, contrast and color-grade operations', async () => { const { engine, plan, snapshot } = await setup(); const base = operation(plan, 'brightness'); for (const type of ['brightness', 'contrast', 'color-grade'] as const) { const candidate = { ...base, id: `${base.id}-${type}`, type, support: 'implemented' as const, parameters: type === 'brightness' ? base.parameters : type === 'contrast' ? { factor: 1.08 } : { style: 'cinematic', intensity: .25 } }; const custom = { ...plan, operations: [candidate] }; const preview = engine.preview(custom, snapshot, [candidate.id]); expect(preview.operationCount).toBe(1); expect(engine.apply(custom, preview, snapshot, [candidate.id]).appliedOperationIds).toEqual([candidate.id]); } });
});

describe('exposure direction and render semantics', () => {
  it('generates a positive under-exposure delta with directional evidence', async () => { const { plan } = await setup(.12); const brightness = operation(plan, 'brightness'); expect(brightness.parameters.delta).toBeGreaterThan(0); expect(brightness.reason).toContain('positive'); });
  it('generates a negative over-exposure delta and no conflicting exposure operation', async () => { const { plan } = await setup(.96); const brightness = operation(plan, 'brightness'); expect(brightness.parameters.delta).toBeLessThan(0); expect(brightness.reason).toContain('negative'); expect(plan.operations.filter((item) => item.sceneId === brightness.sceneId && item.type === 'brightness')).toHaveLength(1); });
  it('clamps deltas safely while preserving direction and severity', () => { expect(exposureDelta(-10)).toBeGreaterThan(0); expect(exposureDelta(-10)).toBeLessThanOrEqual(.15); expect(exposureDelta(10)).toBeLessThan(0); expect(exposureDelta(10)).toBeGreaterThanOrEqual(-.15); expect(exposureDelta(.01)).toBeGreaterThan(exposureDelta(.2)); expect(Math.abs(exposureDelta(.99))).toBeGreaterThan(Math.abs(exposureDelta(.88))); expect(exposureDelta(.5)).toBe(0); });
  it.each([{ before: .12, direction: 'increase' }, { before: .96, direction: 'decrease' }])('$direction brightness in preview and apply using the same delta', async ({ before, direction }) => { const { engine, plan, snapshot } = await setup(before); const brightness = operation(plan, 'brightness'); const preview = engine.preview(plan, snapshot, [brightness.id]); const estimate = preview.exposureEstimates[0]; expect(direction === 'increase' ? estimate.after > estimate.before : estimate.after < estimate.before).toBe(true); expect(estimate.delta).toBe(brightness.parameters.delta); const result = engine.apply(plan, preview, snapshot, [brightness.id]); expect(result.revision.snapshot.manifest.assets.find((item) => item.id === 'visual-asset')?.metadata.brightness).toBe(before); expect(getSceneVisualOperations(result.revision.snapshot.manifest, brightness.sceneId).some((item) => item.operationId === brightness.id)).toBe(true); expect(result.operationResults).toEqual(preview.operationResults); });
  it('passes the exact signed domain delta to FFmpeg', async () => { for (const before of [.12, .96]) { const { engine, plan, snapshot } = await setup(before); const brightness = operation(plan, 'brightness'); const preview = engine.preview(plan, snapshot, [brightness.id]); const render = buildSceneVisualEffectPlan({ scene: snapshot.manifest.timeline.scenes[0], width: 1080, height: 1920, fps: 30, durationSeconds: 3, visualProduction: getSceneVisualOperations(preview.proposedSnapshot.manifest, brightness.sceneId) }); expect(render.filters).toContain(`eq=brightness=${Number(brightness.parameters.delta).toFixed(3)}`); } });
  it('preserves an exact previous revision for brightness undo/redo round trips', async () => { const { engine, plan, snapshot } = await setup(.12); const brightness = operation(plan, 'brightness'); const result = engine.apply(plan, engine.preview(plan, snapshot, [brightness.id]), snapshot, [brightness.id]); expect(result.previousRevision.snapshot).toBe(snapshot); expect(getSceneVisualOperations(result.previousRevision.snapshot.manifest, brightness.sceneId)).toEqual([]); expect(getSceneVisualOperations(result.revision.snapshot.manifest, brightness.sceneId).some((item) => item.operationId === brightness.id)).toBe(true); expect(createManifestRevisionId(result.previousRevision.snapshot.manifest)).toBe(snapshot.manifestFingerprint); });
});

describe('visual regression safety', () => {
  it('is deterministic, immutable and rejects stale canonical fingerprints', async () => { const { engine, manifest, plan, snapshot } = await setup(); expect(engine.analyze({ manifest, snapshot })).toEqual(plan); const stale = structuredClone(snapshot); stale.manifest.timeline.scenes[0].text += ' changed'; expect(() => engine.preview(plan, stale, [])).toThrow(/Stale visual production plan/); expect(snapshot.manifest).toEqual(manifest); });
});

describe('Turkish visual keyword matching', () => {
  it.each(['nasıl', 'NASIL', 'çünkü', 'ÇÜNKÜ', 'sonuç', 'SONUÇ'])('matches the normalized whole-word keyword %s', (word) => { expect(matchesAbstractVisualKeyword(`Bu ${word} çalışıyor?`)).toBe(true); });
  it('normalizes composed Unicode and Turkish dotted/dotless casing', () => { expect(normalizeVisualAnalyzerText('Iİ ÇU\u0308NKÜ')).toBe('ıi çünkü'); expect(matchesAbstractVisualKeyword('NASİL')).toBe(false); });
  it('preserves English matching and avoids substring false positives', () => { expect(matchesAbstractVisualKeyword('HOW does this work?')).toBe(true); expect(matchesAbstractVisualKeyword('somehow resultant')).toBe(false); });
  it('adds the abstract +45 contribution and produces a Turkish cutaway opportunity', async () => { const manifest = await fixture(); const scene = manifest.timeline.scenes[1]; scene.text = 'Bu sonuç neden önemli?'; scene.visualPrompt = ''; scene.cameraMotion = 'none'; const snapshot = createTimelineSnapshot(manifest, createManifestRevisionId(manifest)); const plan = createVisualProductionEngine().analyze({ manifest, snapshot }); expect(plan.broll.find((item) => item.sceneId === scene.id)).toMatchObject({ mode: 'cutaway', score: 85 }); });
  it('keeps every Epic 7.4 production source valid UTF-8 without forbidden mojibake', () => { const files = epicVisualProductionFiles(); expect(files).toHaveLength(14); for (const file of files) { const bytes = readFileSync(file); const decoded = new TextDecoder('utf-8', { fatal: true }).decode(bytes); expect(Buffer.from(decoded, 'utf8'), file).toEqual(bytes); expect(decoded, file).not.toMatch(/Ã|Â|Ä|Å|â€|ï¿½|�/u); } });
  it('preserves exact Turkish keywords and UI punctuation code points', () => { const analyzer = readFileSync(resolve('src/core/visual-production/analyzers.ts'), 'utf8'); const studio = readFileSync(resolve('src/views/AIVisualStudio.tsx'), 'utf8'); for (const keyword of ['nasıl', 'çünkü', 'sonuç']) expect(analyzer).toContain(`'${keyword}'`); expect(studio).toContain(' · '); expect(studio).toContain(' — '); expect(studio).not.toContain('Â·'); expect(studio).not.toContain('â€”'); expect([...studio].some((character) => character.codePointAt(0) === 0x00b7)).toBe(true); expect([...studio].some((character) => character.codePointAt(0) === 0x2014)).toBe(true); });
});

describe('motion recommendation eligibility', () => {
  it('treats a static scene as stable and never recommends stabilization', async () => { const manifest = await fixture(); manifest.timeline.scenes.forEach((scene) => { scene.cameraMotion = 'none'; }); const snapshot = createTimelineSnapshot(manifest, createManifestRevisionId(manifest)); const plan = createVisualProductionEngine().analyze({ manifest, snapshot }); expect(plan.scenes.every((scene) => scene.motion >= 72)).toBe(true); expect(plan.operations.filter((item) => item.type === 'stabilize')).toEqual([]); });
  it('recommends evidence-bound stabilization for real moving shake and applies it consistently', async () => { const manifest = await fixture(); manifest.timeline.scenes[0].cameraMotion = 'pan_left'; const snapshot = createTimelineSnapshot(manifest, createManifestRevisionId(manifest)); const engine = createVisualProductionEngine(); const plan = engine.analyze({ manifest, snapshot }); const stabilize = operation(plan, 'stabilize'); expect(stabilize.parameters.instabilitySignal).toBe(.7); expect(stabilize.reason).toContain('Declared shake 0.7'); const preview = engine.preview(plan, snapshot, [stabilize.id]); expect(preview.operationResults.find((item) => item.operationId === stabilize.id)?.status).toBe('applied'); expect(engine.apply(plan, preview, snapshot, [stabilize.id]).appliedOperationIds).toEqual([stabilize.id]); });
});

describe('color-grade render contract', () => {
  const scene = { id: 'grade-scene', cameraMotion: 'none', transition: { type: 'cut', durationMs: 0 } } as Parameters<typeof buildSceneVisualEffectPlan>[0]['scene'];
  function rendered(style: string, intensity: number) { return buildSceneVisualEffectPlan({ scene, width: 1080, height: 1920, fps: 30, durationSeconds: 3, visualProduction: [{ operationId: `grade-${style}-${intensity}`, type: 'color-grade', scope: 'scene', parameters: { style, intensity } }] }); }
  it.each(['social', 'documentary', 'cinematic'] as const)('renders the central %s profile from stored operation parameters', (style) => { const grade = resolveColorGrade(style, .5)!; expect(rendered(style, .5).filters).toContain(colorGradeFilter(grade)); });
  it('scales profile intensity from neutral and clamps it safely', () => { const low = resolveColorGrade('vibrant', .1)!; const high = resolveColorGrade('vibrant', 2)!; expect(low.saturation).toBeLessThan(high.saturation); expect(high.intensity).toBe(1); expect(rendered('vibrant', .1).filters).not.toEqual(rendered('vibrant', 1).filters); });
  it('diagnoses an invalid profile without producing a fabricated filter', () => { const result = rendered('unknown', .5); expect(result.effectNames).not.toContain('visual-production:color-grade'); expect(result.filters.some((item) => item.startsWith('eq=brightness='))).toBe(false); expect(result.diagnostics.join(' ')).toContain('unknown color-grade profile'); });
  it('stores the planner profile and intensity on generated color-grade operations', async () => { const state = await setup(); const grade = state.plan.operations.find((item) => item.type === 'color-grade'); if (grade) expect(grade.parameters).toMatchObject({ style: state.plan.colorGrade.style, intensity: state.plan.colorGrade.intensity }); const resolved = resolveColorGrade(state.plan.colorGrade.style, state.plan.colorGrade.intensity)!; expect(state.plan.colorGrade.parameters).toEqual({ brightness: resolved.brightness, contrast: resolved.contrast, saturation: resolved.saturation, gamma: resolved.gamma }); });
  it('uses the same resolved values in preview, JSON payload and renderer and rejects invalid profiles', async () => { const state = await setup(); const base = operation(state.plan, 'brightness'); const grade: VisualOperation = { ...base, id: 'grade-social', type: 'color-grade', parameters: { style: 'social', intensity: .6 } }; const plan = { ...state.plan, operations: [grade] }; const preview = state.engine.preview(plan, state.snapshot, [grade.id]); const resolved = resolveColorGrade('social', .6)!; expect(preview.colorGradeEstimates[0]).toMatchObject({ style: 'social', intensity: .6, after: { brightness: resolved.brightness, contrast: resolved.contrast, saturation: resolved.saturation, gamma: resolved.gamma } }); const stored = getSceneVisualOperations(preview.proposedSnapshot.manifest, grade.sceneId); const render = buildSceneVisualEffectPlan({ scene: preview.proposedSnapshot.manifest.timeline.scenes.find((item) => item.id === grade.sceneId)!, width: 1080, height: 1920, fps: 30, durationSeconds: 3, visualProduction: stored }); expect(render.filters).toContain(colorGradeFilter(resolved)); expect(JSON.parse(JSON.stringify({ plan, preview })).preview.colorGradeEstimates[0].after).toEqual(preview.colorGradeEstimates[0].after); const invalid = { ...grade, id: 'grade-invalid', parameters: { style: 'invalid', intensity: .5 } }; const invalidPreview = state.engine.preview({ ...plan, operations: [invalid] }, state.snapshot, [invalid.id]); expect(invalidPreview.operationResults[0].status).toBe('rejected'); expect(invalidPreview.operationCount).toBe(0); });
});

describe('background blur capability safety', () => {
  it('keeps background blur plan-only without score, fingerprint, rerender or full-frame blur effects', async () => { const state = await setup(); const base = operation(state.plan, 'brightness'); const blur: VisualOperation = { ...base, id: 'planned-background-blur', type: 'background-blur', support: 'planned-only', parameters: { radius: 8 } }; const plan = { ...state.plan, operations: [blur] }; const preview = state.engine.preview(plan, state.snapshot, [blur.id]); expect(preview.operationResults[0]).toMatchObject({ support: 'planned-only', status: 'planned-only' }); expect(preview.operationCount).toBe(0); expect(preview.estimatedScore).toBe(plan.scores.overall); expect(preview.rerenderSceneIds).toEqual([]); expect(preview.proposedSnapshot.manifestFingerprint).toBe(state.snapshot.manifestFingerprint); expect(state.engine.apply(plan, preview, state.snapshot, [blur.id]).appliedOperationIds).toEqual([]); const render = buildSceneVisualEffectPlan({ scene: state.snapshot.manifest.timeline.scenes[0], width: 1080, height: 1920, fps: 30, durationSeconds: 3, visualProduction: [{ operationId: blur.id, type: blur.type, scope: blur.scope, parameters: blur.parameters }] }); expect(render.filters.some((item) => item.startsWith('gblur='))).toBe(false); expect(render.diagnostics.join(' ')).toContain('requires foreground segmentation'); });
});
