import { beforeEach, describe, expect, it } from 'vitest';
import { compileEditPlan, createEditingEngine, createManifestRevisionId, createTimelineSnapshot, deriveEffectiveEditPlan, transformTimeline, validateTimelineTrackConsistency, type EditOperation, type EditPlan } from '@/core/editing';
import { isRenderManifestReady } from '@/core/media';
import { useEditingStore } from '@/store/editingStore';
import { useMediaStore } from '@/store/mediaStore';
import { editingFixture } from './fixtures';

describe('timeline track and clip synchronization', () => {
  it('removes every clip linked to a removed scene', async () => { const fixture = await transform('remove'); const removed = fixture.original.timeline.scenes[1].id; expect(fixture.output.timeline.tracks.flatMap((track) => track.clips).some((clip) => clip.sceneId === removed)).toBe(false); });
  it('clamps shortened scene clips to the new boundary', async () => { const fixture = await transform('shorten'); const scene = fixture.output.timeline.scenes[1]; const clips = fixture.output.timeline.tracks.flatMap((track) => track.clips).filter((clip) => clip.sceneId === scene.id); expect(clips.every((clip) => clip.startMs >= scene.startMs && clip.endMs <= scene.endMs)).toBe(true); });
  it('shifts later clips after shortening', async () => { const fixture = await transform('shorten'); const lastId = fixture.original.timeline.scenes[2].id; const before = fixture.original.timeline.tracks.flatMap((track) => track.clips).find((clip) => clip.sceneId === lastId); const after = fixture.output.timeline.tracks.flatMap((track) => track.clips).find((clip) => clip.sceneId === lastId); expect(after?.startMs).toBeLessThan(before?.startMs ?? 0); });
  it('replaces old split scene clips with deterministic child clips', async () => { const source = await editingFixture(); const left = await transform('split', source); const right = await transform('split', source); const oldId = left.original.timeline.scenes[1].id; const leftClips = left.output.timeline.tracks.flatMap((track) => track.clips); expect(leftClips.some((clip) => clip.sceneId === oldId)).toBe(false); expect(new Set(leftClips.map((clip) => clip.sceneId)).has('split-left')).toBe(true); expect(new Set(leftClips.map((clip) => clip.sceneId)).has('split-right')).toBe(true); expect(leftClips.map((clip) => clip.id)).toEqual(right.output.timeline.tracks.flatMap((track) => track.clips).map((clip) => clip.id)); });
  it('keeps split clip durations within child scene durations', async () => { const fixture = await transform('split'); const scenes = new Map(fixture.output.timeline.scenes.map((scene) => [scene.id, scene])); expect(fixture.output.timeline.tracks.flatMap((track) => track.clips).every((clip) => clip.sceneId === 'global' || clip.durationMs <= (scenes.get(clip.sceneId)?.durationMs ?? -1))).toBe(true); });
  it('aligns reordered clip timing and ordering with scenes', async () => { const fixture = await transform('reorder'); const index = new Map(fixture.output.timeline.scenes.map((scene) => [scene.id, scene.index])); const video = fixture.output.timeline.tracks.find((track) => track.type === 'video'); expect(video?.clips.map((clip) => index.get(clip.sceneId))).toEqual([0, 1, 2]); expect(video?.clips.every((clip) => clip.startMs === fixture.output.timeline.scenes[index.get(clip.sceneId) ?? -1]?.startMs)).toBe(true); });
  it('keeps subtitle and audio track clips scene-consistent', async () => { const fixture = await transform('split'); for (const type of ['subtitle', 'voice', 'effects'] as const) { const track = fixture.output.timeline.tracks.find((item) => item.type === type); expect(() => validateTimelineTrackConsistency({ ...fixture.output, timeline: { ...fixture.output.timeline, tracks: track ? [track] : [] } })).not.toThrow(); } });
  it('preserves and clamps global background music', async () => { const fixture = await editingFixture(); const music = fixture.manifest.timeline.tracks.find((track) => track.type === 'music'); if (!music) throw new Error('Music track missing.'); music.clips.push({ id: 'global-music', sceneId: 'global', startMs: 0, endMs: fixture.manifest.durationMs, durationMs: fixture.manifest.durationMs, offsetMs: 0, metadata: {} }); const result = await transform('shorten', fixture); const clip = result.output.timeline.tracks.find((track) => track.type === 'music')?.clips.find((item) => item.id === 'global-music'); expect(clip).toMatchObject({ startMs: 0, endMs: result.output.durationMs, durationMs: result.output.durationMs }); });
  it('throws for orphan scene-linked clips', async () => { const { manifest } = await editingFixture(); manifest.timeline.tracks[0].clips[0].sceneId = 'missing-scene'; expect(() => validateTimelineTrackConsistency(manifest)).toThrow(/orphan/); });
  it('passes full internal track consistency after transform', async () => { const fixture = await transform('split'); expect(() => validateTimelineTrackConsistency(fixture.output)).not.toThrow(); });
  it('does not mutate input tracks', async () => { const fixture = await editingFixture(); const before = JSON.stringify(fixture.manifest.timeline.tracks); await transform('split', fixture); expect(JSON.stringify(fixture.manifest.timeline.tracks)).toBe(before); });
  it('restores exact track structures through undo and redo revisions', async () => { const fixture = await operationFixture('shorten'); const engine = createEditingEngine(); const preview = engine.preview(fixture.plan, fixture.snapshot); const result = engine.apply(fixture.plan, preview, fixture.snapshot, [fixture.operation.id]); useEditingStore.getState().applyCompleted(result); expect(useEditingStore.getState().undo()?.manifest.timeline.tracks).toEqual(fixture.snapshot.manifest.timeline.tracks); expect(useEditingStore.getState().redo()?.manifest.timeline.tracks).toEqual(result.revision.snapshot.manifest.timeline.tracks); });
});

describe('edited manifest validation invalidation', () => {
  it('marks an edited manifest not render-ready', async () => { const fixture = await readyStore(); useMediaStore.getState().replaceEditedManifest(fixture.manifest); expect(useMediaStore.getState().renderReady).toBe(false); expect(useMediaStore.getState().validationRequired).toBe(true); });
  it('resets validation, quality score and issue count', async () => { const fixture = await readyStore(); useMediaStore.getState().replaceEditedManifest(fixture.manifest); expect(useMediaStore.getState()).toMatchObject({ validation: null, qualityScore: 0, validationIssueCount: 0 }); });
  it('clears validation inside the replacement manifest', async () => { const fixture = await readyStore(); useMediaStore.getState().replaceEditedManifest({ ...fixture.manifest, validation: fixture.validation }); expect(useMediaStore.getState().manifest?.validation).toBeNull(); });
  it('requires validation after an undo replacement', async () => { const fixture = await readyStore(); useMediaStore.getState().replaceEditedManifest(fixture.manifest); expect(useMediaStore.getState().validationRequired).toBe(true); });
  it('requires validation after a redo replacement', async () => { const fixture = await readyStore(); useMediaStore.getState().replaceEditedManifest(structuredClone(fixture.manifest)); expect(useMediaStore.getState()).toMatchObject({ renderReady: false, validationRequired: true }); });
  it('can become render-ready only through validated replacement', async () => { const fixture = await readyStore(); const validation = { ...fixture.validation, valid: true, renderReady: true }; useMediaStore.getState().replaceEditedManifest(fixture.manifest); useMediaStore.getState().replaceValidatedManifest(fixture.manifest, validation); expect(useMediaStore.getState()).toMatchObject({ renderReady: true, validationRequired: false, validation }); });
  it('keeps normal validated build results working', async () => { const fixture = await editingFixture(); useMediaStore.getState().setBuildResult(fixture.project, fixture.manifest, fixture.renderReady, undefined, fixture.validation); expect(useMediaStore.getState().validation).toEqual(fixture.validation); expect(useMediaStore.getState().validatedManifestFingerprint).not.toBeNull(); });
  it('does not carry an old quality score into edited state', async () => { const fixture = await readyStore(); expect(useMediaStore.getState().qualityScore).toBe(fixture.validation.score); useMediaStore.getState().replaceEditedManifest(fixture.manifest); expect(useMediaStore.getState().qualityScore).toBe(0); });
  it('serializes edited revisions as unvalidated', async () => { const fixture = await operationFixture('shorten'); const transformed = transformTimeline(fixture.snapshot, fixture.plan, [fixture.operation.id]); expect(JSON.parse(JSON.stringify(transformed.snapshot)).manifest.validation).toBeNull(); });
  it('fails the existing render-ready quality gate for edited manifests', async () => { const fixture = await operationFixture('shorten'); const transformed = transformTimeline(fixture.snapshot, fixture.plan, [fixture.operation.id]); expect(isRenderManifestReady(transformed.snapshot.manifest)).toBe(false); });
});

beforeEach(() => { useEditingStore.setState({ activeProjectId: null, currentPlan: null, currentPreview: null, workingSnapshot: null, applyStatus: 'idle', operations: [], conflicts: [], revisionsByProject: {}, staleRevisionsByProject: {}, redoByProject: {}, undoAvailable: false, redoAvailable: false, currentRevisionId: null, lastError: null, lastAppliedAt: null }); useMediaStore.getState().clearMediaProject(); });

async function readyStore() { const fixture = await editingFixture(); useMediaStore.getState().setBuildResult(fixture.project, fixture.manifest, fixture.renderReady, undefined, fixture.validation); return fixture; }
async function transform(type: 'remove' | 'shorten' | 'split' | 'reorder', provided?: Awaited<ReturnType<typeof editingFixture>>) { const fixture = provided ?? await editingFixture(); const setup = await operationFixture(type, fixture); return { original: fixture.manifest, output: transformTimeline(setup.snapshot, setup.plan, [setup.operation.id]).snapshot.manifest }; }
async function operationFixture(type: 'remove' | 'shorten' | 'split' | 'reorder', provided?: Awaited<ReturnType<typeof editingFixture>>) { const fixture = provided ?? await editingFixture(); const revision = createManifestRevisionId(fixture.manifest); const snapshot = createTimelineSnapshot(fixture.manifest, revision); const compiled = compileEditPlan({ projectId: fixture.manifest.projectId, manifest: fixture.manifest, directorReport: fixture.report, revisionId: revision }); const scene = fixture.manifest.timeline.scenes[1]; let parameters: EditOperation['parameters'] = {}; if (type === 'shorten') parameters = { proposedEndMs: scene.endMs - 1_000 }; if (type === 'split') parameters = { splitAtMs: scene.startMs + scene.durationMs / 2, childSceneIds: ['split-left', 'split-right'] }; if (type === 'reorder') parameters = { order: [...fixture.manifest.timeline.scenes].reverse().map((item) => item.id) }; const operation: EditOperation = { id: `test-${type}`, sourceDecisionId: null, projectId: fixture.manifest.projectId, sceneId: type === 'reorder' ? null : scene.id, type, priority: 'high', reason: type, evidence: [], expectedImpact: 1, confidence: 90, automaticallyApplicable: true, requestedBy: 'user', parameters, dependencies: [], conflicts: [], status: 'proposed', createdAt: fixture.report.generatedAt }; const plan: EditPlan = deriveEffectiveEditPlan({ ...compiled, operations: [operation] }); return { operation, plan, snapshot }; }
