import { describe, expect, it } from 'vitest';
import { optimizeAudioSegments, optimizeSubtitleCues, planAutoTrim, planBroll, planMotion, planReorder, planSceneSplit, planTransitions } from '@/core/editing';
import { editingFixture } from './fixtures';
describe('editing planners', () => {
  it('does not trim before subtitle/voice tails', async () => { const { manifest } = await editingFixture(); const scene = manifest.timeline.scenes[1]; const result = planAutoTrim(scene, manifest); expect(result.proposedEndMs).toBeGreaterThanOrEqual(Math.max(...manifest.subtitles.cues.filter((cue) => cue.sceneId === scene.id).map((cue) => cue.endMs))); });
  it('limits hook trimming to a safe duration', async () => { const { manifest } = await editingFixture(); const result = planAutoTrim(manifest.timeline.scenes[0], manifest, 0.9); expect(result.proposedEndMs - result.proposedStartMs).toBeGreaterThanOrEqual(1_800); });
  it('includes a transition safety margin', async () => { const { manifest } = await editingFixture(); expect(planAutoTrim(manifest.timeline.scenes[1], manifest).safetyMarginMs).toBeGreaterThanOrEqual(180); });
  it('selects a deterministic split boundary and IDs', async () => { const { manifest } = await editingFixture(); const left = planSceneSplit(manifest.timeline.scenes[1], manifest); const right = planSceneSplit(manifest.timeline.scenes[1], manifest); expect(left).toEqual(right); expect(left.childSceneIds).toHaveLength(2); });
  it('does not create short split fragments', async () => { const { manifest } = await editingFixture(); const scene = manifest.timeline.scenes[1]; const split = planSceneSplit(scene, manifest); expect((split.splitAtMs ?? scene.startMs) - scene.startMs).toBeGreaterThanOrEqual(1_000); expect(scene.endMs - (split.splitAtMs ?? scene.endMs)).toBeGreaterThanOrEqual(1_000); });
  it('builds a deterministic B-roll query without external search', async () => { const { manifest } = await editingFixture(); const plan = planBroll(manifest.timeline.scenes[1]); expect(plan.searchQuery).toContain('açıklama'); expect(plan.preferredAssetTypes).toContain('broll'); });
  it('uses a strong safe hook motion', async () => { const { manifest } = await editingFixture(); expect(['punch-in', 'text-emphasis']).toContain(planMotion(manifest.timeline.scenes[0])); });
  it('avoids complex motion on very short scenes', async () => { const { manifest } = await editingFixture(); manifest.timeline.scenes[0].durationMs = 900; expect(planMotion(manifest.timeline.scenes[0])).toBe('quick-cut'); });
  it('only emits supported transitions', async () => { const { manifest } = await editingFixture(); expect(planTransitions(manifest.timeline.scenes).every((item) => ['cut', 'fade', 'crossfade', 'slide', 'zoom', 'blur'].includes(item.type))).toBe(true); });
  it('keeps hook first and CTA last when reordering', async () => { const { manifest, report } = await editingFixture(); const order = planReorder(report, manifest.timeline.scenes); expect(order[0]).toBe(manifest.timeline.scenes[0].id); expect(order.at(-1)).toBe(manifest.timeline.scenes.at(-1)?.id); });
  it('clamps subtitle cues to scene boundaries', async () => { const { manifest } = await editingFixture(); const cue = manifest.subtitles.cues[0]; cue.startMs = -50; expect(optimizeSubtitleCues(manifest)[0].startMs).toBe(0); });
  it('clamps scene-specific audio but preserves global music', async () => { const { manifest } = await editingFixture(); const global = { ...manifest.audio.music[0], id: 'global', sceneId: undefined, startMs: 0 }; manifest.audio.music = [global]; const optimized = optimizeAudioSegments(manifest); expect(optimized.find((item) => item.id === 'global')?.startMs).toBe(0); });
});
