import { beforeEach, describe, expect, it } from 'vitest';
import { compileEditPlan, createEditingEngine, createManifestRevisionId, createTimelineSnapshot, deriveEffectiveEditPlan, isTimelineSnapshotCurrent, resolveEditPlanConflict, type EditOperation, type EditPlan } from '@/core/editing';
import { TypedEventBus, type ApplicationEventMap } from '@/core/events';
import { applyActiveEditPlan, configureEditingController, resolveCurrentEditingSnapshot, undoActiveEdit } from '@/services/editingController';
import { createEditingApplicationService } from '@/services/editingApplicationService';
import { createEditingMonitor } from '@/services/editingMonitor';
import { useEditingStore } from '@/store/editingStore';
import { useMediaStore } from '@/store/mediaStore';
import { editingFixture } from './fixtures';

describe('stale editing snapshot protection', () => {
  it('rejects the same project with a different manifest fingerprint', async () => { const { manifest } = await editingFixture(); const snapshot = createTimelineSnapshot(manifest, createManifestRevisionId(manifest)); const changed = structuredClone(manifest); changed.timeline.scenes[0].text += ' changed'; expect(isTimelineSnapshotCurrent(snapshot, changed)).toBe(false); });
  it('reuses a snapshot when project and fingerprint match', async () => { const { manifest } = await editingFixture(); const snapshot = createTimelineSnapshot(manifest, createManifestRevisionId(manifest)); expect(resolveCurrentEditingSnapshot(structuredClone(manifest), snapshot)).toBe(snapshot); });
  it('marks changed scene order as stale', async () => { const { manifest } = await editingFixture(); const snapshot = createTimelineSnapshot(manifest, createManifestRevisionId(manifest)); const changed = structuredClone(manifest); changed.timeline.scenes.reverse(); expect(isTimelineSnapshotCurrent(snapshot, changed)).toBe(false); });
  it('marks changed duration as stale', async () => { const { manifest } = await editingFixture(); const snapshot = createTimelineSnapshot(manifest, createManifestRevisionId(manifest)); const changed = structuredClone(manifest); changed.timeline.scenes[1].durationMs += 500; expect(isTimelineSnapshotCurrent(snapshot, changed)).toBe(false); });
  it('creates a fresh snapshot that preserves the rebuilt manifest', async () => { const { manifest } = await editingFixture(); const old = createTimelineSnapshot(manifest, createManifestRevisionId(manifest)); const rebuilt = structuredClone(manifest); rebuilt.timeline.scenes[0].text = 'Rebuilt source'; const fresh = resolveCurrentEditingSnapshot(rebuilt, old); expect(fresh).not.toBe(old); expect(fresh.manifest.timeline.scenes[0].text).toBe('Rebuilt source'); expect(isTimelineSnapshotCurrent(fresh, rebuilt)).toBe(true); });
  it('quarantines old undo/redo history when a fresh snapshot starts', async () => { const { manifest } = await editingFixture(); const old = createTimelineSnapshot(manifest, createManifestRevisionId(manifest)); const revision = { id: old.revisionId, projectId: manifest.projectId, parentRevisionId: null, createdAt: old.createdAt, operationIds: [], snapshot: old }; useEditingStore.setState({ activeProjectId: manifest.projectId, revisionsByProject: { [manifest.projectId]: [revision] }, redoByProject: { [manifest.projectId]: [revision] } }); const changed = structuredClone(manifest); changed.timeline.scenes[0].text = 'new'; const fresh = resolveCurrentEditingSnapshot(changed, old); useEditingStore.getState().replaceWithFreshSnapshot(fresh); expect(useEditingStore.getState().revisionsByProject[manifest.projectId]).toHaveLength(1); expect(useEditingStore.getState().redoAvailable).toBe(false); expect(useEditingStore.getState().staleRevisionsByProject[manifest.projectId]).toHaveLength(2); });
  it('rejects apply when the manifest changes after preview', async () => { const fixture = await prepareController(); const changed = structuredClone(fixture.manifest); changed.timeline.scenes[0].text += ' rebuilt'; useMediaStore.setState({ manifest: changed }); await expect(applyActiveEditPlan(fixture.plan.operations.map((item) => item.id))).rejects.toThrow(/Stale timeline revision/); });
  it('writes only the verified applied snapshot to media store', async () => { const fixture = await prepareController(); await applyActiveEditPlan(fixture.plan.operations.filter((item) => item.status !== 'disabled').map((item) => item.id)); const stored = useMediaStore.getState().manifest; expect(stored?.projectId).toBe(fixture.manifest.projectId); expect(stored?.timeline.scenes[0].text).toBe(fixture.manifest.timeline.scenes[0].text); expect(stored?.timeline.scenes[0].text).not.toBe('stale content'); });
  it('does not apply old undo history over a rebuilt manifest', async () => { const fixture = await prepareController(); const changed = structuredClone(fixture.manifest); changed.timeline.scenes[0].text = 'rebuilt'; useMediaStore.setState({ manifest: changed }); expect(() => undoActiveEdit()).toThrow(/history is stale/); expect(useMediaStore.getState().manifest?.timeline.scenes[0].text).toBe('rebuilt'); expect(useEditingStore.getState().redoAvailable).toBe(false); });
});

describe('effective edit conflict graph', () => {
  it('blocks apply while two critical operations conflict', async () => { const { engine, plan, preview, snapshot } = await conflictFixture(); expect(() => engine.apply(plan, preview, snapshot, plan.operations.map((item) => item.id))).toThrow(/Critical/); });
  it('removes the conflict when one operation is disabled', async () => { const { plan } = await conflictFixture(); const updated = deriveEffectiveEditPlan({ ...plan, operations: plan.operations.map((item, index) => index === 0 ? { ...item, status: 'disabled' as const } : item) }); expect(updated.diagnostics.conflicts).toHaveLength(0); });
  it('recalculates preview conflicts from the effective operations', async () => { const { engine, plan, snapshot } = await conflictFixture(); const updated = deriveEffectiveEditPlan({ ...plan, operations: plan.operations.map((item, index) => index === 0 ? { ...item, status: 'disabled' as const } : item) }); expect(engine.preview(updated, snapshot).conflicts).toHaveLength(0); });
  it('manual resolution records the rejected operation in the plan', async () => { const { plan } = await conflictFixture(); const conflict = plan.diagnostics.conflicts[0]; const selected = conflict.operationIds[0]; const updated = resolveEditPlanConflict(plan, conflict.id, selected); expect(updated.operations.find((item) => item.id !== selected)?.status).toBe('disabled'); expect(updated.diagnostics.conflicts).toHaveLength(0); });
  it('keeps store conflicts identical to current plan diagnostics', async () => { const { plan } = await conflictFixture(); useEditingStore.getState().planCompleted(plan); const conflict = useEditingStore.getState().conflicts[0]; useEditingStore.getState().conflictResolved(conflict.id, conflict.operationIds[0]); expect(useEditingStore.getState().conflicts).toEqual(useEditingStore.getState().currentPlan?.diagnostics.conflicts); });
  it('allows apply after a real conflict resolution and fresh preview', async () => { const { engine, plan, snapshot } = await conflictFixture(); const conflict = plan.diagnostics.conflicts[0]; const updated = resolveEditPlanConflict(plan, conflict.id, conflict.operationIds[0]); const preview = engine.preview(updated, snapshot); expect(() => engine.apply(updated, preview, snapshot, [conflict.operationIds[0]])).not.toThrow(); });
  it('still blocks apply if the conflict continues', async () => { const { engine, plan, snapshot } = await conflictFixture(); const preview = engine.preview(plan, snapshot); expect(() => engine.apply(plan, preview, snapshot, plan.operations.map((item) => item.id))).toThrow(/Critical/); });
  it('re-enabling a rejected operation recreates the conflict', async () => { const { plan } = await conflictFixture(); useEditingStore.getState().planCompleted(plan); const conflict = useEditingStore.getState().conflicts[0]; useEditingStore.getState().conflictResolved(conflict.id, conflict.operationIds[0]); const rejected = useEditingStore.getState().operations.find((item) => item.status === 'disabled'); if (!rejected) throw new Error('Expected rejected operation.'); useEditingStore.getState().operationEnabled(rejected.id, true); expect(useEditingStore.getState().conflicts).toHaveLength(1); });
  it('deduplicates the derived conflict graph', async () => { const { plan } = await conflictFixture(); const duplicated = deriveEffectiveEditPlan({ ...plan, diagnostics: { ...plan.diagnostics, conflicts: [...plan.diagnostics.conflicts, ...plan.diagnostics.conflicts] } }); expect(new Set(duplicated.diagnostics.conflicts.map((item) => item.id)).size).toBe(duplicated.diagnostics.conflicts.length); });
  it('undo and redo do not retain a stale conflict resolution plan', async () => { const fixture = await conflictFixture(); useEditingStore.getState().planCompleted(fixture.plan); const conflict = useEditingStore.getState().conflicts[0]; useEditingStore.getState().conflictResolved(conflict.id, conflict.operationIds[0]); const resolvedPlan = useEditingStore.getState().currentPlan; useEditingStore.getState().setWorkingSnapshot(fixture.snapshot); expect(resolvedPlan?.diagnostics.conflicts).toHaveLength(0); expect(useEditingStore.getState().workingSnapshot?.revisionId).toBe(fixture.snapshot.revisionId); });
});

beforeEach(() => { useEditingStore.setState({ activeProjectId: null, currentPlan: null, currentPreview: null, workingSnapshot: null, applyStatus: 'idle', operations: [], conflicts: [], revisionsByProject: {}, staleRevisionsByProject: {}, redoByProject: {}, undoAvailable: false, redoAvailable: false, currentRevisionId: null, lastError: null, lastAppliedAt: null }); useMediaStore.getState().clearMediaProject(); });

async function prepareController() { const fixture = await editingFixture(); const bus = new TypedEventBus<ApplicationEventMap>(); const service = createEditingApplicationService(createEditingEngine(), bus); const monitor = createEditingMonitor(bus); monitor.start(); configureEditingController(service); useMediaStore.getState().setBuildResult(fixture.project, fixture.manifest, true); const snapshot = createTimelineSnapshot(fixture.manifest, createManifestRevisionId(fixture.manifest)); const { plan } = await service.createPlan(fixture.report, fixture.manifest, snapshot); useEditingStore.getState().setWorkingSnapshot(snapshot); const preview = await service.createPreview(plan, snapshot); useEditingStore.getState().planCompleted(plan); useEditingStore.getState().previewCreated(preview); monitor.stop(); return { ...fixture, plan }; }

async function conflictFixture() { const fixture = await editingFixture(); const revision = createManifestRevisionId(fixture.manifest); const snapshot = createTimelineSnapshot(fixture.manifest, revision); const compiled = compileEditPlan({ projectId: fixture.manifest.projectId, manifest: fixture.manifest, directorReport: fixture.report, revisionId: revision }); const scene = fixture.manifest.timeline.scenes[1]; const base: EditOperation = { id: 'remove', sourceDecisionId: null, projectId: fixture.manifest.projectId, sceneId: scene.id, type: 'remove', priority: 'critical', reason: 'Remove', evidence: [], expectedImpact: 1, confidence: 90, automaticallyApplicable: false, requestedBy: 'user', parameters: {}, dependencies: [], conflicts: [], status: 'proposed', createdAt: fixture.report.generatedAt }; const shorten: EditOperation = { ...base, id: 'shorten', type: 'shorten', reason: 'Shorten', parameters: { proposedEndMs: scene.endMs - 500 } }; const plan: EditPlan = deriveEffectiveEditPlan({ ...compiled, operations: [base, shorten] }); const engine = createEditingEngine(); return { engine, plan, preview: engine.preview(plan, snapshot), snapshot }; }
