import { beforeEach, describe, expect, it, vi } from 'vitest';
import { compileEditPlan, createEditingEngine, createManifestRevisionId, createTimelineSnapshot, deriveEffectiveEditPlan, transformTimeline, type EditOperation, type EditOperationType } from '@/core/editing';
import { isRenderManifestReady } from '@/core/media';
import { TypedEventBus, type ApplicationEventMap } from '@/core/events';
import { applyActiveEditPlan, configureEditingController } from '@/services/editingController';
import { createEditingApplicationService } from '@/services/editingApplicationService';
import { createEditingMonitor } from '@/services/editingMonitor';
import { useEditingStore } from '@/store/editingStore';
import { useMediaStore } from '@/store/mediaStore';
import { editingFixture } from './fixtures';

describe('post-edit media validation', () => {
  it('runs validation after apply', async () => { await prepareApply('shorten'); await applyActiveEditPlan(['operation-shorten']); expect(useMediaStore.getState().validation?.validatedAt).toBeTruthy(); });
  it('makes a valid edited manifest render-ready', async () => { await prepareApply('shorten'); await applyActiveEditPlan(['operation-shorten']); expect(useMediaStore.getState().renderReady).toBe(true); });
  it('preserves an edit when validation reports errors', async () => { const fixture = await prepareApply('shorten', true); await applyActiveEditPlan(['operation-shorten']); const stored = useMediaStore.getState(); expect(stored.manifest?.timeline.scenes[1].durationMs).toBeLessThan(fixture.manifest.timeline.scenes[1].durationMs); expect(stored.validation?.valid).toBe(false); expect(stored.renderReady).toBe(false); });
  it('publishes the result through replaceValidatedManifest', async () => { await prepareApply('shorten'); const spy = vi.spyOn(useMediaStore.getState(), 'replaceValidatedManifest'); await applyActiveEditPlan(['operation-shorten']); expect(spy).toHaveBeenCalledOnce(); spy.mockRestore(); });
  it('binds validation to the current edited fingerprint', async () => { await prepareApply('shorten'); await applyActiveEditPlan(['operation-shorten']); const state = useMediaStore.getState(); expect(state.validatedManifestFingerprint).toBe(createManifestRevisionId(requireManifest())); });
  it('passes the existing render-ready manifest gate after successful validation', async () => { await prepareApply('shorten'); await applyActiveEditPlan(['operation-shorten']); expect(isRenderManifestReady(requireManifest())).toBe(true); });
});

describe('derived metrics after timeline transforms', () => {
  it('recomputes duration after remove', async () => { const { before, after } = await transformed('remove'); expect(after.timeline.metrics.durationMs).toBe(after.durationMs); expect(after.durationMs).toBeLessThan(before.durationMs); });
  it('updates scene count after split', async () => { const { before, after } = await transformed('split'); expect(after.timeline.scenes).toHaveLength(before.timeline.scenes.length + 1); });
  it('recomputes pacing after reorder instead of retaining stale input', async () => { const fixture = await editingFixture(); fixture.manifest.timeline.metrics.pacingScore = -1; const { after } = await transformed('reorder', fixture); expect(after.timeline.metrics.pacingScore).toBeGreaterThanOrEqual(0); });
  it('recomputes subtitle cue and word counts', async () => { const { after } = await transformed('remove'); expect(after.subtitles.metrics.cueCount).toBe(after.subtitles.cues.length); expect(after.subtitles.metrics.wordCount).toBe(after.subtitles.words.length); });
  it('recomputes audio coverage and segment metrics', async () => { const fixture = await editingFixture(); fixture.manifest.audio.metrics.voiceCoverage = 0.123; const { after } = await transformed('shorten', fixture); const voiceDuration = after.audio.voice.reduce((sum, segment) => sum + segment.durationMs, 0); expect(after.audio.metrics.voiceCoverage).toBeCloseTo(Math.min(1, voiceDuration / after.durationMs), 3); expect(after.audio.metrics.sfxCount).toBe(after.audio.sfx.length); });
  it('recomputes average scene duration', async () => { const { after } = await transformed('shorten'); const expected = Math.round(after.timeline.scenes.reduce((sum, scene) => sum + scene.durationMs, 0) / after.timeline.scenes.length); expect(after.timeline.metrics.averageSceneDurationMs).toBe(expected); });
  it('puts current metrics in the preview snapshot', async () => { const fixture = await operationFixture('remove'); const preview = createEditingEngine().preview(fixture.plan, fixture.snapshot); expect(preview.proposedSnapshot.manifest.timeline.metrics.durationMs).toBe(preview.proposedDurationMs); expect(preview.proposedSnapshot.manifest.subtitles.metrics.cueCount).toBe(preview.proposedSnapshot.manifest.subtitles.cues.length); });
  it('publishes current metrics to the media store', async () => { await prepareApply('shorten'); await applyActiveEditPlan(['operation-shorten']); const state = useMediaStore.getState(); expect(state.timelineMetrics).toEqual(state.manifest?.timeline.metrics); expect(state.subtitleMetrics).toEqual(state.manifest?.subtitles.metrics); expect(state.audioMetrics).toEqual(state.manifest?.audio.metrics); });
  it('does not alter recalculated metrics while attaching validation', async () => { await prepareApply('shorten'); await applyActiveEditPlan(['operation-shorten']); const manifest = requireManifest(); expect(useMediaStore.getState().project?.timeline.metrics).toEqual(manifest.timeline.metrics); expect(useMediaStore.getState().project?.subtitles.metrics).toEqual(manifest.subtitles.metrics); expect(useMediaStore.getState().project?.audio.metrics).toEqual(manifest.audio.metrics); });
});

beforeEach(() => { useEditingStore.setState({ activeProjectId: null, currentPlan: null, currentPreview: null, workingSnapshot: null, applyStatus: 'idle', operations: [], conflicts: [], revisionsByProject: {}, staleRevisionsByProject: {}, redoByProject: {}, undoAvailable: false, redoAvailable: false, currentRevisionId: null, lastError: null, lastAppliedAt: null }); useMediaStore.getState().clearMediaProject(); });

async function prepareApply(type: EditOperationType, invalidRender = false) { const fixture = await editingFixture(); if (invalidRender) fixture.manifest.render = { ...fixture.manifest.render, width: 1920, height: 1080 }; const setup = await operationFixture(type, fixture); const bus = new TypedEventBus<ApplicationEventMap>(); const monitor = createEditingMonitor(bus); monitor.start(); configureEditingController(createEditingApplicationService(createEditingEngine(), bus)); useMediaStore.getState().setBuildResult(fixture.project, fixture.manifest, fixture.renderReady, fixture.assetResolution, fixture.validation); useEditingStore.getState().setWorkingSnapshot(setup.snapshot); useEditingStore.getState().planCompleted(setup.plan); useEditingStore.getState().previewCreated(createEditingEngine().preview(setup.plan, setup.snapshot)); return fixture; }
async function transformed(type: EditOperationType, provided?: Awaited<ReturnType<typeof editingFixture>>) { const fixture = provided ?? await editingFixture(); const setup = await operationFixture(type, fixture); return { before: fixture.manifest, after: transformTimeline(setup.snapshot, setup.plan, [setup.operation.id]).snapshot.manifest }; }
async function operationFixture(type: EditOperationType, provided?: Awaited<ReturnType<typeof editingFixture>>) { const fixture = provided ?? await editingFixture(); const revision = createManifestRevisionId(fixture.manifest); const snapshot = createTimelineSnapshot(fixture.manifest, revision); const compiled = compileEditPlan({ projectId: fixture.manifest.projectId, manifest: fixture.manifest, directorReport: fixture.report, revisionId: revision }); const scene = fixture.manifest.timeline.scenes[1]; let parameters: EditOperation['parameters'] = {}; if (type === 'shorten') parameters = { proposedEndMs: scene.endMs - 1_000 }; if (type === 'split') parameters = { splitAtMs: scene.startMs + scene.durationMs / 2, childSceneIds: ['metrics-left', 'metrics-right'] }; if (type === 'reorder') parameters = { order: [...fixture.manifest.timeline.scenes].reverse().map((item) => item.id) }; const operation: EditOperation = { id: `operation-${type}`, sourceDecisionId: null, projectId: fixture.manifest.projectId, sceneId: type === 'reorder' ? null : scene.id, type, priority: 'high', reason: type, evidence: [], expectedImpact: 1, confidence: 90, automaticallyApplicable: true, requestedBy: 'user', parameters, dependencies: [], conflicts: [], status: 'proposed', createdAt: fixture.report.generatedAt }; return { operation, snapshot, plan: deriveEffectiveEditPlan({ ...compiled, operations: [operation] }) }; }
function requireManifest() { const manifest = useMediaStore.getState().manifest; if (!manifest) throw new Error('Expected media manifest.'); return manifest; }
