import { describe, expect, it } from 'vitest';
import { compileEditPlan, createEditingEngine, createEditPreview, createManifestRevisionId, createTimelineSnapshot, detectConflicts, transformTimeline, type EditOperation } from '@/core/editing';
import { editingFixture } from './fixtures';
describe('AI Editing Engine', () => {
  it('maps supported Director decisions and reports unsupported decisions', async () => { const { manifest, report } = await editingFixture(); const plan = compileEditPlan({ projectId: manifest.projectId, manifest, directorReport: report }); expect(plan.operations.length).toBeGreaterThan(0); expect(plan.diagnostics.unsupportedDecisionIds.every((id) => report.editDecisionPlan.decisions.some((item) => item.id === id))).toBe(true); });
  it('is deterministic for the same input', async () => { const fixture = await editingFixture(); const input = { projectId: fixture.manifest.projectId, manifest: fixture.manifest, directorReport: fixture.report }; expect(compileEditPlan(input)).toEqual(compileEditPlan(input)); });
  it('sorts operations by priority', async () => { const { manifest, report } = await editingFixture(); const plan = compileEditPlan({ projectId: manifest.projectId, manifest, directorReport: report }); const rank = { critical: 4, high: 3, medium: 2, low: 1 }; expect(plan.operations.every((item, index) => index === 0 || rank[plan.operations[index - 1].priority] >= rank[item.priority])).toBe(true); });
  it('rejects mismatched project identity', async () => { const { manifest, report } = await editingFixture(); expect(() => compileEditPlan({ projectId: 'wrong', manifest, directorReport: report })).toThrow(/identities/); });
  it('detects remove/shorten conflicts', () => { const base = { id: 'a', projectId: 'p', sceneId: 's', sourceDecisionId: null, priority: 'high', reason: '', evidence: [], expectedImpact: 1, confidence: 80, automaticallyApplicable: false, requestedBy: 'user', parameters: {}, dependencies: [], conflicts: [], status: 'proposed', createdAt: '' } satisfies Omit<EditOperation, 'type'>; expect(detectConflicts([{ ...base, type: 'remove' }, { ...base, id: 'b', type: 'shorten' }])[0].severity).toBe('critical'); });
  it('does not mutate the source manifest during preview', async () => { const { manifest, report } = await editingFixture(); const original = JSON.stringify(manifest); const revision = createManifestRevisionId(manifest); const plan = compileEditPlan({ projectId: manifest.projectId, manifest, directorReport: report, revisionId: revision }); createEditPreview(plan, createTimelineSnapshot(manifest, revision)); expect(JSON.stringify(manifest)).toBe(original); });
  it('creates a preview with cache invalidation estimates', async () => { const { manifest, report } = await editingFixture(); const revision = createManifestRevisionId(manifest); const plan = compileEditPlan({ projectId: manifest.projectId, manifest, directorReport: report, revisionId: revision }); const preview = createEditPreview(plan, createTimelineSnapshot(manifest, revision)); expect(preview.rerenderSceneIds.length).toBe(preview.affectedSceneCount); expect(preview.reusableSegmentCountEstimate).toBeGreaterThanOrEqual(0); });
  it('rejects a stale revision', async () => { const { manifest, report } = await editingFixture(); const plan = compileEditPlan({ projectId: manifest.projectId, manifest, directorReport: report, revisionId: 'expected' }); expect(() => transformTimeline(createTimelineSnapshot(manifest, 'stale'), plan)).toThrow(/Stale/); });
  it('never creates negative timestamps', async () => { const { manifest, report } = await editingFixture(); const revision = createManifestRevisionId(manifest); const result = transformTimeline(createTimelineSnapshot(manifest, revision), compileEditPlan({ projectId: manifest.projectId, manifest, directorReport: report, revisionId: revision })); expect(result.snapshot.manifest.timeline.scenes.every((scene) => scene.startMs >= 0 && scene.endMs > scene.startMs)).toBe(true); });
  it('maintains unique scene IDs', async () => { const { manifest, report } = await editingFixture(); const revision = createManifestRevisionId(manifest); const result = transformTimeline(createTimelineSnapshot(manifest, revision), compileEditPlan({ projectId: manifest.projectId, manifest, directorReport: report, revisionId: revision })); const ids = result.snapshot.manifest.timeline.scenes.map((scene) => scene.id); expect(new Set(ids).size).toBe(ids.length); });
  it('requires a matching preview before apply', async () => { const { manifest, report } = await editingFixture(); const engine = createEditingEngine(); const revision = createManifestRevisionId(manifest); const snapshot = createTimelineSnapshot(manifest, revision); const plan = engine.compile({ projectId: manifest.projectId, manifest, directorReport: report, revisionId: revision }); const preview = engine.preview(plan, snapshot); expect(() => engine.apply(plan, { ...preview, sourceRevisionId: 'stale' }, snapshot)).toThrow(/preview/); });
  it('supports abort during compile', async () => { const { manifest, report } = await editingFixture(); const controller = new AbortController(); controller.abort(); expect(() => compileEditPlan({ projectId: manifest.projectId, manifest, directorReport: report }, undefined, controller.signal)).toThrowError(expect.objectContaining({ name: 'AbortError' })); });
});
