import { beforeEach, describe, expect, it, vi } from 'vitest';
import { createEditingEngine, createManifestRevisionId, createTimelineSnapshot, type EditApplyResult } from '@/core/editing';
import { TypedEventBus, type ApplicationEventMap } from '@/core/events';
import { createEditingApplicationService } from '@/services/editingApplicationService';
import { createEditingMonitor } from '@/services/editingMonitor';
import { useEditingStore } from '@/store/editingStore';
import { editingFixture } from './fixtures';

describe('Editing service, store and monitor', () => {
  beforeEach(() => useEditingStore.setState({ activeProjectId: null, currentPlan: null, currentPreview: null, workingSnapshot: null, applyStatus: 'idle', operations: [], conflicts: [], revisionsByProject: {}, redoByProject: {}, undoAvailable: false, redoAvailable: false, currentRevisionId: null, lastError: null, lastAppliedAt: null }));
  it('publishes plan and preview lifecycle events', async () => { const bus = new TypedEventBus<ApplicationEventMap>(); const completed = vi.fn(); const previewed = vi.fn(); bus.on('editing:plan-completed', completed); bus.on('editing:preview-created', previewed); const service = createEditingApplicationService(createEditingEngine(), bus); const { manifest, report } = await editingFixture(); const result = await service.createPlan(report, manifest); await service.createPreview(result.plan, result.snapshot); expect(completed).toHaveBeenCalledOnce(); expect(previewed).toHaveBeenCalledOnce(); });
  it('monitor transfers lifecycle state without duplicate listeners', async () => { const bus = new TypedEventBus<ApplicationEventMap>(); const monitor = createEditingMonitor(bus); monitor.start(); monitor.start(); await bus.emit('editing:plan-started', { projectId: 'p', revisionId: 'r', startedAt: 'now' }); expect(useEditingStore.getState()).toMatchObject({ activeProjectId: 'p', applyStatus: 'planning' }); monitor.stop(); });
  it('rejects a report from another project', async () => { const bus = new TypedEventBus<ApplicationEventMap>(); const service = createEditingApplicationService(createEditingEngine(), bus); const { manifest, report } = await editingFixture(); await expect(service.createPlan({ ...report, projectId: 'other' }, manifest)).rejects.toThrow(/another project/); });
  it('emits an error lifecycle event when planning fails', async () => { const bus = new TypedEventBus<ApplicationEventMap>(); const failed = vi.fn(); bus.on('editing:apply-failed', failed); const service = createEditingApplicationService(createEditingEngine(), bus); const { manifest, report } = await editingFixture(); await expect(service.createPlan({ ...report, projectId: 'other' }, manifest)).rejects.toThrow(); expect(failed).toHaveBeenCalledWith(expect.objectContaining({ stage: 'plan' })); });
  it('enables and disables operations and invalidates preview', async () => { const { plan, preview } = await build(); useEditingStore.getState().planCompleted(plan); useEditingStore.getState().previewCreated(preview); useEditingStore.getState().operationEnabled(plan.operations[0].id, false); expect(useEditingStore.getState().operations[0].status).toBe('disabled'); expect(useEditingStore.getState().currentPreview).toBeNull(); });
  it('keeps revision history isolated by project', async () => { const { result } = await build(); useEditingStore.getState().applyCompleted(result); expect(useEditingStore.getState().revisionsByProject[result.projectId]).toHaveLength(2); expect(useEditingStore.getState().revisionsByProject.other).toBeUndefined(); });
  it('undo restores the previous snapshot', async () => { const { result } = await build(); useEditingStore.getState().applyCompleted(result); const snapshot = useEditingStore.getState().undo(); expect(snapshot?.revisionId).toBe(result.previousRevision.id); expect(useEditingStore.getState().redoAvailable).toBe(true); });
  it('redo restores the applied revision', async () => { const { result } = await build(); useEditingStore.getState().applyCompleted(result); useEditingStore.getState().undo(); expect(useEditingStore.getState().redo()?.revisionId).toBe(result.revision.id); });
  it('a new apply clears redo history', async () => { const first = await build(); useEditingStore.getState().applyCompleted(first.result); useEditingStore.getState().undo(); expect(useEditingStore.getState().redoAvailable).toBe(true); useEditingStore.getState().applyCompleted(first.result); expect(useEditingStore.getState().redoAvailable).toBe(false); });
  it('resetProject does not remove another project history', async () => { const { result } = await build(); useEditingStore.getState().applyCompleted(result); const other = { ...result.previousRevision, id: 'other-r', projectId: 'other', snapshot: { ...result.previousRevision.snapshot, projectId: 'other' } }; useEditingStore.setState((state) => ({ revisionsByProject: { ...state.revisionsByProject, other: [other] } })); useEditingStore.getState().resetProject(result.projectId); expect(useEditingStore.getState().revisionsByProject.other).toHaveLength(1); });
  it('records apply errors in store state', () => { useEditingStore.getState().applyFailed('stale revision'); expect(useEditingStore.getState()).toMatchObject({ applyStatus: 'failed', lastError: 'stale revision' }); });
  it('updates the current snapshot after successful apply', async () => { const { result } = await build(); useEditingStore.getState().applyCompleted(result, '2026-08-03T10:00:00.000Z'); expect(useEditingStore.getState().currentRevisionId).toBe(result.revision.id); expect(useEditingStore.getState().lastAppliedAt).toBe('2026-08-03T10:00:00.000Z'); });
});

async function build(): Promise<{ plan: Awaited<ReturnType<ReturnType<typeof createEditingApplicationService>['createPlan']>>['plan']; preview: Awaited<ReturnType<ReturnType<typeof createEditingApplicationService>['createPreview']>>; result: EditApplyResult }> { const bus = new TypedEventBus<ApplicationEventMap>(); const service = createEditingApplicationService(createEditingEngine(), bus); const { manifest, report } = await editingFixture(); const revision = createManifestRevisionId(manifest); const snapshot = createTimelineSnapshot(manifest, revision); const { plan } = await service.createPlan(report, manifest, snapshot); const preview = await service.createPreview(plan, snapshot); const result = await service.apply(plan, preview, snapshot, plan.operations.map((item) => item.id)); return { plan, preview, result }; }
