import { beforeEach, describe, expect, it } from 'vitest';
import { compileEditPlan, createEditingEngine, createManifestRevisionId, createTimelineSnapshot, deriveEffectiveEditPlan, transformTimeline, validateTimelineMarkerConsistency, type EditOperation, type EditOperationType } from '@/core/editing';
import { buildIntelligentTimeline } from '@/core/media';
import { useEditingStore } from '@/store/editingStore';
import { editingFixture } from './fixtures';

describe('transition-aware editing retime', () => {
  it('starts the second crossfade scene by its overlap', async () => { const { after } = await transformed('keep'); expect(after.timeline.scenes[1].startMs).toBe(after.timeline.scenes[0].endMs - after.timeline.scenes[1].overlapBeforeMs); });
  it('reduces total duration by transition overlaps', async () => { const { after } = await transformed('keep'); const raw = after.timeline.scenes.reduce((sum, scene) => sum + scene.durationMs, 0); const overlaps = after.timeline.scenes.reduce((sum, scene) => sum + scene.overlapBeforeMs, 0); expect(after.durationMs).toBe(raw - overlaps); });
  it('recalculates neighboring overlap after remove', async () => { const { after } = await transformed('remove'); expect(after.timeline.scenes[1].startMs).toBe(after.timeline.scenes[0].endMs - after.timeline.scenes[1].overlapBeforeMs); expect(after.timeline.scenes[0].overlapAfterMs).toBe(after.timeline.scenes[1].overlapBeforeMs); });
  it('never lets overlap exceed a shortened scene', async () => { const fixture = await overlapFixture(); fixture.manifest.timeline.scenes[1].overlapBeforeMs = 50_000; const { after } = await transformed('shorten', fixture); expect(after.timeline.scenes[1].overlapBeforeMs).toBeLessThanOrEqual(after.timeline.scenes[1].durationMs); });
  it('uses a cut between deterministic split children', async () => { const { after } = await transformed('split'); const right = after.timeline.scenes.find((scene) => scene.id === 'overlap-right'); expect(right).toMatchObject({ overlapBeforeMs: 0, transition: { type: 'cut', durationMs: 0 } }); });
  it('recalculates overlap for reordered neighbors', async () => { const { after } = await transformed('reorder'); after.timeline.scenes.slice(1).forEach((scene, index) => expect(scene.startMs).toBe(after.timeline.scenes[index].endMs - scene.overlapBeforeMs)); });
  it('falls back to zero for invalid transition metadata', async () => { const fixture = await overlapFixture(); Reflect.set(fixture.manifest.timeline.scenes[1].transition, 'type', 'invalid'); const { after } = await transformed('keep', fixture); expect(after.timeline.scenes[1].overlapBeforeMs).toBe(0); });
  it('keeps the first scene at zero', async () => { const { after } = await transformed('reorder'); expect(after.timeline.scenes[0].startMs).toBe(0); expect(after.timeline.scenes[0].overlapBeforeMs).toBe(0); });
  it('never creates negative scene timestamps', async () => { const { after } = await transformed('shorten'); expect(after.timeline.scenes.every((scene) => scene.startMs >= 0 && scene.endMs > scene.startMs)).toBe(true); });
  it('aligns scene, clips and metrics to the final duration', async () => { const { after } = await transformed('shorten'); expect(after.timeline.metrics.durationMs).toBe(after.durationMs); expect(after.timeline.scenes.at(-1)?.endMs).toBe(after.durationMs); expect(after.timeline.tracks.flatMap((track) => track.clips).every((clip) => clip.endMs <= after.durationMs)).toBe(true); });
  it('restores overlap metadata exactly through undo and redo', async () => { const setup = await operationFixture('shorten'); const engine = createEditingEngine(); const result = engine.apply(setup.plan, engine.preview(setup.plan, setup.snapshot), setup.snapshot, [setup.operation.id]); useEditingStore.getState().applyCompleted(result); expect(useEditingStore.getState().undo()?.manifest.timeline.scenes).toEqual(setup.snapshot.manifest.timeline.scenes); expect(useEditingStore.getState().redo()?.manifest.timeline.scenes).toEqual(result.revision.snapshot.manifest.timeline.scenes); });
  it('matches buildIntelligentTimeline overlap semantics', async () => { const fixture = await overlapFixture(); const built = buildIntelligentTimeline(structuredClone(fixture.manifest.timeline.scenes), fixture.project.settings); fixture.manifest.timeline.scenes = built.scenes; fixture.manifest.durationMs = built.durationMs; fixture.manifest.timeline.durationMs = built.durationMs; const { after } = await transformed('keep', fixture); expect(after.timeline.scenes.map(({ startMs, endMs, overlapBeforeMs }) => ({ startMs, endMs, overlapBeforeMs }))).toEqual(built.scenes.map(({ startMs, endMs, overlapBeforeMs }) => ({ startMs, endMs, overlapBeforeMs }))); });
});

describe('timeline marker synchronization', () => {
  it('removes markers linked to a removed scene', async () => { const { before, after } = await transformed('remove'); const removed = before.timeline.scenes[1].id; expect(after.timeline.markers.some((marker) => marker.sceneId === removed)).toBe(false); });
  it('clamps markers to a trimmed scene boundary', async () => { const fixture = await overlapFixture(); const scene = fixture.manifest.timeline.scenes[1]; fixture.manifest.timeline.markers.push({ id: 'late-marker', type: 'emphasis', timeMs: scene.endMs, sceneId: scene.id, label: 'late', metadata: {} }); const { after } = await transformed('shorten', fixture); const marker = after.timeline.markers.find((item) => item.id === 'late-marker'); const edited = after.timeline.scenes.find((item) => item.id === scene.id); expect(marker?.timeMs).toBe(edited?.endMs); });
  it('moves split markers to the correct child', async () => { const fixture = await overlapFixture(); const parent = fixture.manifest.timeline.scenes[1]; fixture.manifest.timeline.markers.push({ id: 'after-split', type: 'emphasis', timeMs: parent.startMs + parent.durationMs * 0.75, sceneId: parent.id, label: 'after', metadata: {} }); const { after } = await transformed('split', fixture); expect(after.timeline.markers.find((marker) => marker.id === 'after-split')?.sceneId).toBe('overlap-right'); });
  it('leaves no parent scene IDs after split', async () => { const { before, after } = await transformed('split'); expect(after.timeline.markers.some((marker) => marker.sceneId === before.timeline.scenes[1].id)).toBe(false); });
  it('moves scene markers with reordered scenes', async () => { const fixture = await overlapFixture(); const marker = fixture.manifest.timeline.markers.find((item) => item.sceneId === fixture.manifest.timeline.scenes[0].id); if (!marker) throw new Error('Expected scene marker.'); const oldTime = marker.timeMs; const { after } = await transformed('reorder', fixture); expect(after.timeline.markers.find((item) => item.id === marker.id)?.timeMs).not.toBe(oldTime); });
  it('sorts markers deterministically by timestamp and ID', async () => { const fixture = await overlapFixture(); const left = await transformed('reorder', fixture); const right = await transformed('reorder', fixture); expect(left.after.timeline.markers).toEqual(right.after.timeline.markers); expect(left.after.timeline.markers).toEqual([...left.after.timeline.markers].sort((a, b) => a.timeMs - b.timeMs || a.id.localeCompare(b.id))); });
  it('clamps global markers to timeline duration', async () => { const fixture = await overlapFixture(); fixture.manifest.timeline.markers.push({ id: 'global-late', type: 'beat', timeMs: 999_999, label: 'late', metadata: {} }); const { after } = await transformed('remove', fixture); expect(after.timeline.markers.find((marker) => marker.id === 'global-late')?.timeMs).toBe(after.durationMs); });
  it('rejects duplicate marker IDs', async () => { const { after } = await transformed('keep'); after.timeline.markers.push({ ...after.timeline.markers[0] }); expect(() => validateTimelineMarkerConsistency(after)).toThrow(/unique/); });
  it('rejects markers referencing invalid scenes', async () => { const { after } = await transformed('keep'); after.timeline.markers.push({ id: 'orphan-marker', type: 'emphasis', timeMs: 0, sceneId: 'missing', label: 'orphan', metadata: {} }); expect(() => validateTimelineMarkerConsistency(after)).toThrow(/invalid scene/); });
  it('restores marker snapshots through undo and redo', async () => { const setup = await operationFixture('remove'); const engine = createEditingEngine(); const result = engine.apply(setup.plan, engine.preview(setup.plan, setup.snapshot), setup.snapshot, [setup.operation.id]); useEditingStore.getState().applyCompleted(result); expect(useEditingStore.getState().undo()?.manifest.timeline.markers).toEqual(setup.snapshot.manifest.timeline.markers); expect(useEditingStore.getState().redo()?.manifest.timeline.markers).toEqual(result.revision.snapshot.manifest.timeline.markers); });
  it('keeps every marker within the final duration', async () => { const { after } = await transformed('shorten'); expect(after.timeline.markers.every((marker) => marker.timeMs >= 0 && marker.timeMs <= after.durationMs)).toBe(true); });
  it('aligns transition markers with current overlap starts', async () => { const { after } = await transformed('reorder'); for (const marker of after.timeline.markers.filter((item) => item.type === 'transition')) { const scene = after.timeline.scenes.find((item) => item.id === marker.sceneId); expect(marker.timeMs).toBe(scene?.startMs); expect(marker.metadata.overlapMs).toBe(scene?.overlapBeforeMs); } });
});

beforeEach(() => useEditingStore.setState({ activeProjectId: null, currentPlan: null, currentPreview: null, workingSnapshot: null, applyStatus: 'idle', operations: [], conflicts: [], revisionsByProject: {}, staleRevisionsByProject: {}, redoByProject: {}, undoAvailable: false, redoAvailable: false, currentRevisionId: null, lastError: null, lastAppliedAt: null }));

async function overlapFixture() { const fixture = await editingFixture(); const scenes = fixture.manifest.timeline.scenes; scenes[0].transition = { type: 'cut', durationMs: 0 }; scenes[0].overlapBeforeMs = 0; scenes[1].transition = { type: 'crossfade', durationMs: 1_000 }; scenes[1].overlapBeforeMs = 500; scenes[2].transition = { type: 'fade', durationMs: 600 }; scenes[2].overlapBeforeMs = 300; return fixture; }
async function transformed(type: EditOperationType, provided?: Awaited<ReturnType<typeof editingFixture>>) { const fixture = provided ?? await overlapFixture(); const setup = await operationFixture(type, fixture); return { before: fixture.manifest, after: transformTimeline(setup.snapshot, setup.plan, [setup.operation.id]).snapshot.manifest }; }
async function operationFixture(type: EditOperationType, provided?: Awaited<ReturnType<typeof editingFixture>>) { const fixture = provided ?? await overlapFixture(); const revision = createManifestRevisionId(fixture.manifest); const snapshot = createTimelineSnapshot(fixture.manifest, revision); const compiled = compileEditPlan({ projectId: fixture.manifest.projectId, manifest: fixture.manifest, directorReport: fixture.report, revisionId: revision }); const scene = fixture.manifest.timeline.scenes[1]; let parameters: EditOperation['parameters'] = {}; if (type === 'shorten') parameters = { proposedEndMs: scene.endMs - 1_000 }; if (type === 'split') parameters = { splitAtMs: scene.startMs + scene.durationMs / 2, childSceneIds: ['overlap-left', 'overlap-right'] }; if (type === 'reorder') parameters = { order: [...fixture.manifest.timeline.scenes].reverse().map((item) => item.id) }; const operation: EditOperation = { id: `overlap-${type}`, sourceDecisionId: null, projectId: fixture.manifest.projectId, sceneId: type === 'reorder' || type === 'keep' ? null : scene.id, type, priority: 'high', reason: type, evidence: [], expectedImpact: 1, confidence: 90, automaticallyApplicable: true, requestedBy: 'user', parameters, dependencies: [], conflicts: [], status: 'proposed', createdAt: fixture.report.generatedAt }; return { operation, snapshot, plan: deriveEffectiveEditPlan({ ...compiled, operations: [operation] }) }; }
